### ISSUE TITLE
ONNX: support .ngf extension

### ISSUE THREAD

**Issue by chaoyujiang** [lutzroeder/netron#1002]
Our company build the inference model named "*.ngf" which is based on onnx. But the Netron can not load the file named "xx.ngf". Everytime, we have to change the file name from "xx.ngf" to "xx.onnx" by manual. Pls support to load the file which suffix is ".ngf". Thanks.

**Comment by lutzroeder** [comment]
@chaoyujiang why are you using a different file extension? If the file is in ONNX format the right file extension would be `.onnx`?

**Comment by chaoyujiang** [comment]
> 

@lutzroeder  hi， thank you for your reply. 
Our engine file is format by onnx's protobuf, and we extend the protobuf for our inference needs. Actually, there are some differences from standard onnx file.

**Comment by lutzroeder** [comment]
@chaoyujiang can you work with the folks on the ONNX repository to find a solution that doesn't require forking the `.proto` definition. Forking was done for Caffe and resulted in lots of conflicting incompatible formats causing load errors in tools. Is there a way to accomplish the same goal by for example adding data to [metadata_props](https://github.com/onnx/onnx/blob/main/docs/MetadataProps.md) or requesting changes to ONNX to make it extensibly for your needs?

cc @prasanthpul
