### ISSUE TITLE
Text output feature

### ISSUE THREAD

**Issue by ycchung0516** [lutzroeder/netron#1003]
Hi, 

Is there any possibility that Netron outputs the NN description text for the user?
Similar to CAFFE's prototxt format, with the layer details &  dependency (input layer name) shown in Netron's block.

For example:
```
INPUT {
  output_size: {3, 224, 224}
}
Layer0 {
   Type: CONV2D
   Input_name: INPUT
   kernel: (64,3,3,3)
   stride: 1   
   output_size: (64,222,222)
}

Layer1 {
   Type: CONV2D
   Input_name: Layer0
   kernel: (64,64,3,3)
   stride: 1   
   output_size: (64,220,220)
}

...

```

Thank you.

**Comment by lutzroeder** [comment]
@ycchung0516 can you explain what specific problem you are trying to solve, why you need this feature? What would a mockup look like?

**Comment by ycchung0516** [comment]
@lutzroeder I am working on the AI accelerator hardware design for parallel multi-DNN execution. 
To determine the hardware architecture, I want to profile and analyze different domains' DNN workloads in the early design stage.
Also, at the compile time, I can convert these DNN description files to generate the instructions/configs to operate the AI accelerator.

The DNN description file can be a text file that includes all the information in the Netron GUI block. With these description files, I can build the DAG for the analysis with the inputs' and outputs' names.

The mockup is referenced from SqueezeNet in the repo:
The format can be changed for your convenience, I used CAFFE's prototxt format here for the example.

CONV block example
![image](https://user-images.githubusercontent.com/108042975/200182195-fcc2e42e-0f6e-47c0-917d-efd679120df1.png)
```
Layer {
    NODE_PROPERTIES {
        type: Conv
   }
    ATTRIBUTES {
       kernel_shape: 3, 3
       pads: 0, 0, 0, 0
       strides: 2, 2
   }
    INPUTS {
          X:  data_0
         W: conv1_w_0
         B: conv1_b_0
    }
    OUTPUTS {
        Y: conv1_1
   }
}
```

**Comment by lutzroeder** [comment]
How would this work, copy and paste the description for each node manually? Can this be done more efficiently via a CLI Python script using the actual Caffe framework? Is the challenge more that in Caffe the nodes don't show identifiers or a location index?

**Comment by ycchung0516** [comment]
CAFFE doesn't support other kinds of frameworks like Netron.
I am sorry that the expression is not clear.
Netron draws the block diagram of DNN with each layer's information, it must generate the information with the defined data structure before drawing.
Can Netron add a feature to output this information of each block (layer) as a text file? The CAFFE format above is an example for you to look at.

**Comment by lutzroeder** [comment]
@ycchung0516 Netron is not a framework. Caffe is a framework. You can use Caffe to open Caffe models, process them or output text information about the model. Why would it help to copy random text in a random format from a tool like Netron. For example, below is "text" and it's a better compact representation. A representation that makes sense for Caffe likely does not work for other formats like ONNX and would not be efficient to render in a large graph.

![image](https://user-images.githubusercontent.com/438516/200231666-1960baef-b351-4ea3-bcd0-0e815ea7aa91.png)
