### ISSUE TITLE
Netron uses wrong home directory when installed via snap

### ISSUE THREAD

**Issue by josh-gleason** [lutzroeder/netron#1004]
- Netron app and version: 6.1.7
- OS and browser version: Ubuntu 18.04

Steps to Reproduce:

1. Install netron via snap `snap install netron`
2. Open netron
3. File->Open puts us at the wrong home directory making it very inconvenient to navigate to the proper directory in the dialog window.

![Screenshot from 2022-11-17 17-46-15](https://user-images.githubusercontent.com/194276/202576885-50abfad2-7143-42b9-bf33-db0d8915fdcc.png)

I'm guessing this is a result of the `HOME` environment variable being set when snap builds an environment. For the purpose of opening files however it makes more sense to use the `SNAP_REAL_HOME` environment variable which is available since snapd 2.46.

([link to similar issue in inkscape project](https://gitlab.com/inkscape/inkscape/-/issues/1507))

**Comment by lutzroeder** [comment]
@josh-gleason if this is a common problem, should it be addressed in Snap or Electron? Can you investigate, drive the correct fix and submit a pull request if needed?
