### ISSUE TITLE
oneDNN support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#1006]
[sample-graph-100001.json.zip](https://github.com/lutzroeder/netron/files/10037438/sample-graph-100001.json.zip)
[resnet50-sample-graph.json.zip](https://github.com/lutzroeder/netron/files/10065168/resnet50-sample-graph.json.zip)

@xinyu-intel

**Comment by TaoLv** [comment]
Upload the test case for PR #1218 :

[f8_matmul.json.zip](https://github.com/lutzroeder/netron/files/14018737/f8_matmul.json.zip)

**Comment by TaoLv** [comment]
Upload the test case for PR #1341 

[int4-matmul.json.zip](https://github.com/user-attachments/files/16884596/int4-matmul.json.zip)
