### ISSUE TITLE
Passing a model to browser app via data URL in URL fragment

### ISSUE THREAD

**Issue by FranklinWhale** [lutzroeder/netron#1007]
I would like to share a number of model to students and let them visualize it with Netron. Although there is a `url` parameter, it will be sent to the hosting server and the length may be limited. I hope the model can be passed to the browser application via URL fragment.

Example:
https://netron.app/#url=data%3Aapplication%2Foctet-stream%3Bbase64%2CCAYSBk1MLk5FVBoBMCIWbWFjaGluZWxlYXJuaW5nLmRvdG5ldDqTFAqgAQoNU2VwYWxMZW5ndGhDbQoMU2VwYWxXaWR0aENtCg1QZXRhbExlbmd0aENtCgxQZXRhbFdpZHRoQ20SFlZlY3RvckZlYXR1cml6ZXJPdXRwdXQaEUZlYXR1cmVWZWN0b3JpemVyIhFGZWF0dXJlVmVjdG9yaXplcioaCg9pbnB1dGRpbWVuc2lvbnNCBAEBAQGgAQc6CmFpLm9ubngubWwKOQoWVmVjdG9yRmVhdHVyaXplck91dHB1dBIIRmVhdHVyZXMaBENhc3QiBENhc3QqCQoCdG8YAaABAgo%2BCghGZWF0dXJlcxICWDIaD1JlZHVjZVN1bVNxdWFyZSIPUmVkdWNlU3VtU3F1YXJlKgwKBGF4ZXNCAQGgAQcKRAoIRmVhdHVyZXMKAUMKBHplcm8SA1hDMhoER2VtbSIER2VtbSoPCgVhbHBoYRUAAADAoAEBKg0KBnRyYW5zQhgBoAECChYKAlgyCgNYQzISAVoaA0FkZCIDQWRkChkKAVoKAkMyEgVTY29yZRoEQWRkMCIDQWRkCkIKBVNjb3JlEgtBcmdNaW5JbnQ2NBoGQXJnTWluIgZBcmdNaW4qCwoEYXhpcxgBoAECKg8KCGtlZXBkaW1zGAGgAQIKNQoLQXJnTWluSW50NjQSDlByZWRpY3RlZExhYmVsGgVDYXN0MCIEQ2FzdCoJCgJ0bxgMoAECCjMKDVNlcGFsTGVuZ3RoQ20SDlNlcGFsTGVuZ3RoQ20wGghJZGVudGl0eSIISWRlbnRpdHkKMgoMU2VwYWxXaWR0aENtEg1TZXBhbFdpZHRoQ20wGglJZGVudGl0eTAiCElkZW50aXR5CjQKDVBldGFsTGVuZ3RoQ20SDlBldGFsTGVuZ3RoQ20wGglJZGVudGl0eTEiCElkZW50aXR5CjIKDFBldGFsV2lkdGhDbRINUGV0YWxXaWR0aENtMBoJSWRlbnRpdHkyIghJZGVudGl0eQo2Cg5QcmVkaWN0ZWRMYWJlbBIPUHJlZGljdGVkTGFiZWwwGglJZGVudGl0eTMiCElkZW50aXR5CiQKBVNjb3JlEgZTY29yZTAaCUlkZW50aXR5NCIISWRlbnRpdHkKOwoOU2VwYWxMZW5ndGhDbTASFFNlcGFsTGVuZ3RoQ20ub3V0cHV0GglJZGVudGl0eTUiCElkZW50aXR5CjkKDVNlcGFsV2lkdGhDbTASE1NlcGFsV2lkdGhDbS5vdXRwdXQaCUlkZW50aXR5NiIISWRlbnRpdHkKOwoOUGV0YWxMZW5ndGhDbTASFFBldGFsTGVuZ3RoQ20ub3V0cHV0GglJZGVudGl0eTciCElkZW50aXR5CjkKDVBldGFsV2lkdGhDbTASE1BldGFsV2lkdGhDbS5vdXRwdXQaCUlkZW50aXR5OCIISWRlbnRpdHkKPQoPUHJlZGljdGVkTGFiZWwwEhVQcmVkaWN0ZWRMYWJlbC5vdXRwdXQaCUlkZW50aXR5OSIISWRlbnRpdHkKLAoGU2NvcmUwEgxTY29yZS5vdXRwdXQaCklkZW50aXR5MTAiCElkZW50aXR5EgVtb2RlbCpbCgIFBBABIlAvM91AZ2ZGQJkZu0BnZghAQtGWQJTKR0AVbbU%2FSeVDPrjysEB%2B0idAGDV8QGv4mz8aksdAQ%2FI2QIvVmUAanM8%2FhS2oQFrnakBeecA%2FO%2BmTPkIBQyofCgEFEAEiFNk9wEK6AwhCRt5ZQlCdkUKRvy1CQgJDMioRCgEBEAEiBAAAAABCBHplcm9aKAoNU2VwYWxMZW5ndGhDbRIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFaJwoMU2VwYWxXaWR0aENtEhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAVooCg1QZXRhbExlbmd0aENtEhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAVonCgxQZXRhbFdpZHRoQ20SFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggBYi8KFFNlcGFsTGVuZ3RoQ20ub3V0cHV0EhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWIuChNTZXBhbFdpZHRoQ20ub3V0cHV0EhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWIvChRQZXRhbExlbmd0aENtLm91dHB1dBIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFiLgoTUGV0YWxXaWR0aENtLm91dHB1dBIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFiMAoVUHJlZGljdGVkTGFiZWwub3V0cHV0EhcKFQgMEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWInCgxTY29yZS5vdXRwdXQSFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggFajEKFlZlY3RvckZlYXR1cml6ZXJPdXRwdXQSFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggEaiMKCEZlYXR1cmVzEhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIBGopCg5QcmVkaWN0ZWRMYWJlbBIXChUIDBIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFqIAoFU2NvcmUSFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggFah0KAlgyEhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWoeCgNYQzISFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggFahwKAVoSFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggFaikKDlNlcGFsTGVuZ3RoQ20wEhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWooCg1TZXBhbFdpZHRoQ20wEhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWopCg5QZXRhbExlbmd0aENtMBIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFqKAoNUGV0YWxXaWR0aENtMBIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFqKgoPUHJlZGljdGVkTGFiZWwwEhcKFQgMEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWohCgZTY29yZTASFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggFai8KFFNlcGFsTGVuZ3RoQ20ub3V0cHV0EhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWouChNTZXBhbFdpZHRoQ20ub3V0cHV0EhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWovChRQZXRhbExlbmd0aENtLm91dHB1dBIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFqLgoTUGV0YWxXaWR0aENtLm91dHB1dBIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFqMAoVUHJlZGljdGVkTGFiZWwub3V0cHV0EhcKFQgMEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWonCgxTY29yZS5vdXRwdXQSFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggFQg4KCmFpLm9ubngubWwQAkICEAw%3D

**Comment by lutzroeder** [comment]
The URL needs to include a file identifier. For many ML files the format can not be derived from content.

For example: [http://netron.app?identifier=x.onnx&url=data:...](https://netron.app/?identifier=x.onnx&url=data%3Aapplication%2Foctet-stream%3Bbase64%2CCAYSBk1MLk5FVBoBMCIWbWFjaGluZWxlYXJuaW5nLmRvdG5ldDqTFAqgAQoNU2VwYWxMZW5ndGhDbQoMU2VwYWxXaWR0aENtCg1QZXRhbExlbmd0aENtCgxQZXRhbFdpZHRoQ20SFlZlY3RvckZlYXR1cml6ZXJPdXRwdXQaEUZlYXR1cmVWZWN0b3JpemVyIhFGZWF0dXJlVmVjdG9yaXplcioaCg9pbnB1dGRpbWVuc2lvbnNCBAEBAQGgAQc6CmFpLm9ubngubWwKOQoWVmVjdG9yRmVhdHVyaXplck91dHB1dBIIRmVhdHVyZXMaBENhc3QiBENhc3QqCQoCdG8YAaABAgo%2BCghGZWF0dXJlcxICWDIaD1JlZHVjZVN1bVNxdWFyZSIPUmVkdWNlU3VtU3F1YXJlKgwKBGF4ZXNCAQGgAQcKRAoIRmVhdHVyZXMKAUMKBHplcm8SA1hDMhoER2VtbSIER2VtbSoPCgVhbHBoYRUAAADAoAEBKg0KBnRyYW5zQhgBoAECChYKAlgyCgNYQzISAVoaA0FkZCIDQWRkChkKAVoKAkMyEgVTY29yZRoEQWRkMCIDQWRkCkIKBVNjb3JlEgtBcmdNaW5JbnQ2NBoGQXJnTWluIgZBcmdNaW4qCwoEYXhpcxgBoAECKg8KCGtlZXBkaW1zGAGgAQIKNQoLQXJnTWluSW50NjQSDlByZWRpY3RlZExhYmVsGgVDYXN0MCIEQ2FzdCoJCgJ0bxgMoAECCjMKDVNlcGFsTGVuZ3RoQ20SDlNlcGFsTGVuZ3RoQ20wGghJZGVudGl0eSIISWRlbnRpdHkKMgoMU2VwYWxXaWR0aENtEg1TZXBhbFdpZHRoQ20wGglJZGVudGl0eTAiCElkZW50aXR5CjQKDVBldGFsTGVuZ3RoQ20SDlBldGFsTGVuZ3RoQ20wGglJZGVudGl0eTEiCElkZW50aXR5CjIKDFBldGFsV2lkdGhDbRINUGV0YWxXaWR0aENtMBoJSWRlbnRpdHkyIghJZGVudGl0eQo2Cg5QcmVkaWN0ZWRMYWJlbBIPUHJlZGljdGVkTGFiZWwwGglJZGVudGl0eTMiCElkZW50aXR5CiQKBVNjb3JlEgZTY29yZTAaCUlkZW50aXR5NCIISWRlbnRpdHkKOwoOU2VwYWxMZW5ndGhDbTASFFNlcGFsTGVuZ3RoQ20ub3V0cHV0GglJZGVudGl0eTUiCElkZW50aXR5CjkKDVNlcGFsV2lkdGhDbTASE1NlcGFsV2lkdGhDbS5vdXRwdXQaCUlkZW50aXR5NiIISWRlbnRpdHkKOwoOUGV0YWxMZW5ndGhDbTASFFBldGFsTGVuZ3RoQ20ub3V0cHV0GglJZGVudGl0eTciCElkZW50aXR5CjkKDVBldGFsV2lkdGhDbTASE1BldGFsV2lkdGhDbS5vdXRwdXQaCUlkZW50aXR5OCIISWRlbnRpdHkKPQoPUHJlZGljdGVkTGFiZWwwEhVQcmVkaWN0ZWRMYWJlbC5vdXRwdXQaCUlkZW50aXR5OSIISWRlbnRpdHkKLAoGU2NvcmUwEgxTY29yZS5vdXRwdXQaCklkZW50aXR5MTAiCElkZW50aXR5EgVtb2RlbCpbCgIFBBABIlAvM91AZ2ZGQJkZu0BnZghAQtGWQJTKR0AVbbU%2FSeVDPrjysEB%2B0idAGDV8QGv4mz8aksdAQ%2FI2QIvVmUAanM8%2FhS2oQFrnakBeecA%2FO%2BmTPkIBQyofCgEFEAEiFNk9wEK6AwhCRt5ZQlCdkUKRvy1CQgJDMioRCgEBEAEiBAAAAABCBHplcm9aKAoNU2VwYWxMZW5ndGhDbRIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFaJwoMU2VwYWxXaWR0aENtEhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAVooCg1QZXRhbExlbmd0aENtEhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAVonCgxQZXRhbFdpZHRoQ20SFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggBYi8KFFNlcGFsTGVuZ3RoQ20ub3V0cHV0EhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWIuChNTZXBhbFdpZHRoQ20ub3V0cHV0EhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWIvChRQZXRhbExlbmd0aENtLm91dHB1dBIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFiLgoTUGV0YWxXaWR0aENtLm91dHB1dBIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFiMAoVUHJlZGljdGVkTGFiZWwub3V0cHV0EhcKFQgMEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWInCgxTY29yZS5vdXRwdXQSFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggFajEKFlZlY3RvckZlYXR1cml6ZXJPdXRwdXQSFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggEaiMKCEZlYXR1cmVzEhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIBGopCg5QcmVkaWN0ZWRMYWJlbBIXChUIDBIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFqIAoFU2NvcmUSFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggFah0KAlgyEhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWoeCgNYQzISFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggFahwKAVoSFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggFaikKDlNlcGFsTGVuZ3RoQ20wEhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWooCg1TZXBhbFdpZHRoQ20wEhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWopCg5QZXRhbExlbmd0aENtMBIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFqKAoNUGV0YWxXaWR0aENtMBIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFqKgoPUHJlZGljdGVkTGFiZWwwEhcKFQgMEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWohCgZTY29yZTASFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggFai8KFFNlcGFsTGVuZ3RoQ20ub3V0cHV0EhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWouChNTZXBhbFdpZHRoQ20ub3V0cHV0EhcKFQgBEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWovChRQZXRhbExlbmd0aENtLm91dHB1dBIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFqLgoTUGV0YWxXaWR0aENtLm91dHB1dBIXChUIARIRCgsI%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FAQoCCAFqMAoVUHJlZGljdGVkTGFiZWwub3V0cHV0EhcKFQgMEhEKCwj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BCgIIAWonCgxTY29yZS5vdXRwdXQSFwoVCAESEQoLCP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEKAggFQg4KCmFpLm9ubngubWwQAkICEAw%3D)

**Comment by FranklinWhale** [comment]
The model is passed through query (after `?`) rather than fragment (after `#`) in URL, which will be sent to server and probably logged. Is it okay?

**Comment by FranklinWhale** [comment]
Commit 2010f2616fd4f0ee80665ea238f6b1222a892be7 looks good. Thanks!

By the way, where may the list of file identifiers be found? The `type` inside `test/models.json` seems not the same as file identifiers, as `onnx` is `x.onnx`.

**Comment by FranklinWhale** [comment]
> Commit [2010f26](https://github.com/lutzroeder/netron/commit/2010f2616fd4f0ee80665ea238f6b1222a892be7) looks good. Thanks!
> 
> By the way, where may the list of file identifiers be found? The `type` inside `test/models.json` seems not the same as file identifiers, as `onnx` is `x.onnx`.

Found that `file identifier` is actually just file name, I think this issue is resolved :D
