### ISSUE TITLE
Data type documentation

### ISSUE THREAD

**Issue by triandco** [lutzroeder/netron#1008]
I'm following [a guide from MS website](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-use-automl-onnx-model-dotnet) using netron to inspect an onnx model in order to use it in production. I'm having difficulty understand the data type of the input and output. They look like python type but not quite.

From their example, I understand that something like ```int32[n,1]``` could be translated to a single int32 value in C#. However, in my model I have something with the type ```float32[batch,sequence,768]```. Does this mean an array of float32 array with a maximum length of 768?

Would you be able to document the data types or point us to its documentation?

Thank you very much. 🙇‍♂️

**Comment by lutzroeder** [comment]
@triandco please open an issue in [MicrosoftDocs/azure-docs](https://github.com/https://github.com/MicrosoftDocs/azure-docs/issues).

cc @luisquintanilla
