### ISSUE TITLE
TorchScript: unknown function torch.get in torchvision mask R-CNN model

### ISSUE THREAD

**Issue by fader111** [lutzroeder/netron#1009]
- Netron app and version: 6.2.0 Desktop 
- OS and browser version: Win 10 Pro, Chrome 107.0.5304.108

Steps to Reproduce:

1. Generate model Mask R-CNN https://github.com/facebookresearch/detectron2/tree/main/tools/deploy with export_model.py
2. Try to open It with Netron

**Comment by lutzroeder** [comment]
@fader111 can you please share the model file or detailed steps to create the model file.
