### ISSUE TITLE
bad interpreter issue when running on linux

### ISSUE THREAD

**Issue by ahmedhosny** [lutzroeder/Netron#101]
Great effort!
Any chance this was developed on a windows machine?
I am getting this running on ubuntu

```
$ netron
bash: /usr/local/bin/netron: /usr/local/opt/python@2/bin/python2.7: bad interpreter: No such file or directory
```

The problem is described [here](https://stackoverflow.com/questions/16757349/bad-interpreter-no-such-file-or-directory-in-python). I just replaced the first line in the bash file from 
`#!/usr/bin/env python` to `#!/usr/bin/python` 
and you can do this programatically using 
`sed -i '1s:.*:#!/usr/bin/python:' /usr/local/bin/netron`

Anyway, thought there might be a better solution instead of this workaround.

**Comment by lutzroeder** [comment]
Issue seems to be that `distutil` is overwriting the shebang when building the package: https://stackoverflow.com/questions/1530702/dont-touch-my-shebang

**Comment by ahmedhosny** [comment]
Hello Lutz- tried to get your email but failed miserably, sorry to comment here.

@michaelschwier and I have been working on a project where we implement netron. He has also been active with issues: #102.

**We would like to quickly introduce [modelhub.ai](http://modelhub.ai/), as we have recently published our flagship model running on squeezenet.**

Modelhub is a purely academic effort providing "Plug and Predict" solutions for medical AI research - with hopes of extending to other domains. As medical ML researchers, we are often unable to re-implement prior work due to unpublished code and sensitivity to training variables - as I am sure you are well aware. Benchmarking performance is not feasible and instead we must rely on authors' pseudocode loosely describing architectures & hyperparameters. Almost all libraries host their own "model zoos" and while valuable, they often lack running instructions, pre- & post-processing pipelines, sample input, and are focused only on natural images. 

We want to lower the barriers to consuming published AI models by developing a generalizable "sharing" template for AI researchers. AI model containers built using this template will be open-source, run out of self-contained portable dockers, use standard formats through ONNX & are inherently linked to specific research studies. *Contributors* are AI researchers & will be guided through the template. *Users* interaction with the model containers: 
A. Users with little or no technical skill set through a simple web interface (where **netron** is served)
B. Researchers through jupyter notebooks and 
C. Developers through API calls to get model info & predictions. 
The focus will be on AI applications in radiology to start, as well as inference only, with provisions for end-to-end training and fine-tuning.

We are currently packaging other models in a similar fashion to squeezenet. We are running this lean operation in parallel with optimizing and refining the contribution process - with the hopes of a fully automated contribution process once we understand the general needs and requirements.

**Please test drive the model directly in the browser and come back to us with comments and suggestions. We would be grateful for any input, and if we could be featured with a link as a community adoption on your github readme page. Also any help in spreading the word would be much appreciated.**

We hope to continue testing netron and bring up issues here. 
And as always, keep opening source.

Ahmed & Michael.
