### ISSUE TITLE
Python Server fails to load model when the file is a symbolic link

### ISSUE THREAD

**Issue by fefe982** [lutzroeder/netron#1010]
- Netron app and version: 6.1.2 python command line server

Steps to Reproduce:

1. In path `/foo` ,there is a symbolic link `/foo/bar.onnx`, which links to `/foobar/bar.onnx`
2. In `/foo`, use `netron bar.onnx` to start a server
3. In the webbrowser, connect to the server. And there would be the prompt of `Model load request failed. The web request failed with status code 404 at 'http://localhost:8081/data/bar.onnx?cb=1xxxxxxxxxx'.`

**Comment by fefe982** [comment]
This seems to be caused by the check [here](https://github.com/lutzroeder/netron/blob/b3862c1268fa51e5db4e3bb83f50fb21ea1230fb/source/server.py#L37):

```python
        base_dir = os.path.realpath(self.dir)
        filename = os.path.normpath(os.path.realpath(base_dir + '/' + path))
        if os.path.commonprefix([ base_dir, filename ]) == base_dir: # <--- here
            if os.path.exists(filename) and not os.path.isdir(filename):
                with open(filename, 'rb') as file:
                    return file.read()
```

`os.path.realpath` would resolve symbolic links, which makes the check to failed.

**Comment by lutzroeder** [comment]
@fefe982 can you investigate this further, maybe add which OS and script to reproduce?

**Comment by fefe982** [comment]
I tested on a cloud Linux environment, which seems to be based on RHEL or CentOS
