### ISSUE TITLE
Visualizing reverse order of inputs for some Concat modules in YOLOV5s

### ISSUE THREAD

**Issue by NKSagarReddy** [lutzroeder/netron#1012]
- Netron app (website) : https://netron.app/ 
- OS and browser version: macOS 12.5 (21G72) + Chrome Version 106.0.5249.119

Steps to Reproduce:

1. Upload yolov5s.onnx in netron.app
2. Concat Modules - [12, 16, 19, 22] are being given inputs in reverse order. (Correct order(Tensorboard) is in [https://medium.com/analytics-vidhya/object-detection-algorithm-yolo-v5-architecture-89e0a35472ef](url))

**Comment by lutzroeder** [comment]
@NKSagarReddy can you please share the specific ONNX file and a screenshot or example?

**Comment by NKSagarReddy** [comment]
@lutzroeder 
Yolov5s.onnx - https://drive.google.com/file/d/1-99xFLF2v3jz_PgS5mJI5rI9k4pkjf3i/view?usp=sharing
![yolov5s in netron](https://user-images.githubusercontent.com/108252538/205024154-894d2dcd-9401-4166-9890-bd3c28ea5679.jpg)
The Concat after model.18.conv is model.19
For the model.19 concat layer, the model.18.conv output should be the first argument, not the second.
Expected representation:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/108252538/205024605-0103950d-11e1-459c-9af7-83f04ca72a11.png">

**Comment by lutzroeder** [comment]
The order is listed in properties. The graph layout library does not support edge ordering. dagrejs/dagre#112

<img width="813" alt="screenshot" src="https://user-images.githubusercontent.com/438516/205210809-abc0530a-0eca-4319-ad30-42031a0b6edf.png">
