### ISSUE TITLE
Browser: cannot open model on browser from remote server

### ISSUE THREAD

**Issue by wangmingzhiJohn** [lutzroeder/netron#1016]
I setup a process in machine A with `netron xxx.pb -p 8081`. Then i open the browser on machine B and type in `http://{A's ip}:8081`. But i can only see ERR_CONNECTION_REFUSED. I have tried it on chrome and firefox browser.

**Comment by lutzroeder** [comment]
@wangmingzhiJohn can you investigate and create a pull request with a fix? Is the `netron --host` option of any help?

**Comment by wangmingzhiJohn** [comment]
@lutzroeder yep, that is the key, I missed the `--host` option so it actually works when the request from local browser. After I add `--host` and specify the ip, everything is ok now. Thank you a lot

**Comment by wangmingzhiJohn** [comment]
@lutzroeder yep, that is the key, I missed the `--host` option so it actually works when the request from local browser. After I add `--host` and specify the ip, everything is ok now. Thank you a lot
