### ISSUE TITLE
gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported

### ISSUE THREAD

**Issue by wutheringcoo** [lutzroeder/netron#1018]
when i run netron in terminal, it occurs an error:
(netron:157206): Gtk-WARNING **: 17:28:15.578: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name
[157348:1213/172832.677694:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
how can i solve this problem, thanks!

**Comment by lutzroeder** [comment]
@wutheringcoo can you investigate and submit a solution. This is likely a graphics driver, Electron or Chrome issue, see results when you search for the error message. What version are you using and in which environment?
