### ISSUE TITLE
Integrate Netron into other web service (scaling issues)

### ISSUE THREAD

**Issue by michaelschwier** [lutzroeder/Netron#102]
What is the best/most stable way to integrate Netron into an existing service?

We were trying to integrate Netron into an existing webservice, running Netron in a separate process and integrating the Netron output page into the main page. Unfortunately this caused trouble. Usually the Netron server would not respond, even if only run locally with one user.

I believe the main trouble is that Netron uses the build-in python HTTP Server which does not handle multiple/parallel requests very well (or at all). This seems to be a problem even running locally, since e.g. [Chrome might send multiple requests](https://stackoverflow.com/questions/4460661/what-to-do-with-chrome-sending-extra-requests) for one user (Firefox was more stable in our case). This problem can be easily reproduced by accessing the Netron output directly in Chrome and repeatedly clicking reload. The reloading will get stuck.

Any hints how to work around this with the current implementation of Netron? I currently only see the solution to change the Server Netron uses, but I'm hoping I missed smth :/

**Comment by lutzroeder** [comment]
Would be great if you can dig into this and come up with a fix. Which OS does this happen with? Clicking reload in Chrome doesn't seem to repro the issue.

**Comment by michaelschwier** [comment]
Thx, it seems the ThredingMixIn fixed the issue! (was happening on ubuntu 16.04 with Chrome 65.0.3325.181)
