### ISSUE TITLE
color of layers and 3d shapes

### ISSUE THREAD

**Issue by mohammadjavad-izadi** [lutzroeder/netron#1027]
hello, thank you for your app.
could you please add a feature for changing the colors of the layers?
the app selects colors automatically.
also if you add 3d shapes for layers, it would be great.
thank you again.

**Comment by lutzroeder** [comment]
@mohammadjavad-izadi can you provide some context why customization is needed and how it is expected to work. Please create a separate issue to track the shape issue and provide some detail how this is expected to work as well.
