### ISSUE TITLE
ONNX: Unsupported data type 'XXX' when loading file with custom attribute

### ISSUE THREAD

**Issue by xuzijian629** [lutzroeder/netron#1029]
# Problem
When loading ONNX with custom attributes, netron may raise error like
```
Error loading ONNX model. Unsupported data type '["a"]'.
```

### Reproduce
```python3
import onnx

cast_node = onnx.helper.make_node(
    name="Cast1",
    op_type="Cast",
    inputs=["x"],
    outputs=["y"],
    to=onnx.TensorProto.DOUBLE,
    custom_attribute=["a"]
)

graph = onnx.helper.make_graph(
    nodes=[cast_node],
    name="custom_cast",
    inputs=[onnx.helper.make_tensor_value_info("x", onnx.TensorProto.FLOAT, [1])],
    outputs=[onnx.helper.make_tensor_value_info("y", onnx.TensorProto.DOUBLE, [1])],
)

model = onnx.helper.make_model(graph, producer_name="debug")

onnx.save(model, "model.onnx")
```

### Versions
master, 6.3.8
Python 3.9

**Comment by xuzijian629** [comment]
In above example, 

https://github.com/lutzroeder/netron/blob/f78fc13e0714506db3cf5e94b0efcacba7bf07f4/source/onnx.js#L699

returns the metadata of ":cast:to" even when the arguments are for ":cast:custom_attribute".

For ":cast:to", we can do
https://github.com/lutzroeder/netron/blob/f78fc13e0714506db3cf5e94b0efcacba7bf07f4/source/onnx.js#L704-L706

, but since it is now ":cast:custom_attribute" and we cannot convert its value `["a"]` to any of `onnx.DataType`

**Comment by xuzijian629** [comment]
I'll submit a PR modifying this soon

**Comment by lutzroeder** [comment]
[issue_1029.onnx.zip](https://github.com/lutzroeder/netron/files/10344328/issue_1029.onnx.zip)
