### ISSUE TITLE
More informative error descriptions

### ISSUE THREAD

**Issue by BenPYeh** [lutzroeder/Netron#103]
Any way to be more descriptive with the errors? I tried loading a model and a pop up says "ONNX Error: invalid wire type 7 at offset 569841". But I don't know what operator(s) this corresponds to, or what else is wrong with the model.

**Comment by lutzroeder** [comment]
This is a low level error in protobuf deserializer. If the file extension `.pb` or `.onnx`? Does changing the extension to `.onnx` fix the issue? If so, can you share the file?
