### ISSUE TITLE
Export full size image

### ISSUE THREAD

**Issue by adrianodac** [lutzroeder/netron#1032]
I have onnx file successfully exported from mmsegmentation (swin-transformer), huge model (975.4) MB, I managed to open it in netron, however when I try to export it and preview in full size its blured. 

Any way I can fix it ? 
Thanks

**Comment by lutzroeder** [comment]
Export as SVG using a different app to convert to bitmap. The code [here](https://github.com/lutzroeder/netron/blob/b5dae3c361cee2b97d425c1bac8823b2333361a7/source/view.js#L1055) scales very large bitmaps to work around browser size limits and is another option to experiment with.
