### ISSUE TITLE
Keras: Invalid inbound connection '_CONSTANT_VALUE'

### ISSUE THREAD

**Issue by NikolasMarkou** [lutzroeder/netron#1035]
- Netron app and version: 6.4.0 desktop
- OS and browser version: linux mint

Steps to Reproduce:

1. open file
[model_hydra.h5.zip](https://github.com/lutzroeder/netron/files/10390050/model_hydra.h5.zip)

Please attach or link model files to reproduce the issue if necessary.
![image](https://user-images.githubusercontent.com/1175820/211752284-c4e0b76b-9b03-47b0-a3fc-947ba527c8b8.png)

**Comment by lutzroeder** [comment]
[model_hydra.h5.zip](https://github.com/lutzroeder/netron/files/10398337/model_hydra.h5.zip)
