### ISSUE TITLE
DLC: File format is not dlc.NetDef

### ISSUE THREAD

**Issue by Travis-Lee** [lutzroeder/netron#1037]
- Netron app and version: 
- OS and browser version: 

Steps to Reproduce:

1,Error loading DLC model. File format is not dlc.NetDef (File contains undocumented '' data).
2, DLC Version Is snpe-2.5.0.4052

Please attach or link model files to reproduce the issue if necessary.

**Comment by lutzroeder** [comment]
@Travis-Lee can you share a model file to reproduce the issue.

**Comment by itskyf** [comment]
SNPE v2 [changed the format of DLC file](https://developer.qualcomm.com/sites/default/files/docs/snpe/snpe2_migration_guidelines.html)

**Comment by lutzroeder** [comment]
@Travis-Lee can you share a model file.

**Comment by itskyf** [comment]
I have generated these model ([YOLOv8](https://github.com/ultralytics/ultralytics) -> ONNX -> DLC) using SNPE 1.68 and 2.05 [YOLOv8DLC.zip](https://github.com/lutzroeder/netron/files/10498535/YOLOv8DLC.zip)

**Comment by lutzroeder** [comment]
[yolov8n_op11.zip](https://github.com/lutzroeder/netron/files/10527007/yolov8n_op11.zip)

**Comment by Travis-Lee** [comment]
I was used DLC Version 2.05 With Netron 6.5.8. There is on  error  with "Error loading DLC Model. File contains undocumented DL v4 Data". So, how to solve this problem?

**Comment by lutzroeder** [comment]
@Travis-Lee the format is not documented. Either share documentation or move to an open format like ONNX instead.
