### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by Hyprnx** [lutzroeder/netron#1038]
Hi, i have search all of the issue, but none mentioned what i need.

So, i have a model, pretty lightweight one, consists of 3 linear layers, combined with Batchnorm and Dropout, etc. So when i export the graph, there are only 2 options, verticle and horizontal. Both are really hard to look when i insert them to my report since the font size is pretty small.

Im opening this issue to ask for the change font/scale or even re-arrange the model graph if possible.

Thanks in advanced!

Here is my graph, which looks pretty small if insert to my reports.
![classifier](https://user-images.githubusercontent.com/13253140/214034223-5675ca02-7a44-455f-8baf-d8b6b87b5fd7.png)

**Comment by lutzroeder** [comment]
@Hyprnx can you submit a pull request implementing this change or share examples what the result should look like.
