### ISSUE TITLE
TorchScript: new version failed to visualize model correctly

### ISSUE THREAD

**Issue by shuokay** [lutzroeder/netron#1045]
- Netron app and version: 6.4.5 Python Server
- OS and browser version: centos + edge

Steps to Reproduce:

1. start netron python server
2. open the attatched torchscript file

Please attach or link model files to reproduce the issue if necessary.

[test.pt.zip](https://github.com/lutzroeder/netron/files/10672579/test.pt.zip)

visualize the model with netron 6.4.5:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/5029591/217179729-dbbdb449-f746-4125-9c5a-0b3a6f9ec8ff.png">

Netron 6.0.2 visualize the model correctly, but netron 6.0.2 was deleted from pypi.

**Comment by lutzroeder** [comment]
@shuokay what difference in the current version that was not present in the old version?

Can you revert to `git log --grep "Update to 6.0.2"` and follow [DEVELOPMENT.md](https://github.com/lutzroeder/netron/blob/main/.github/DEVELOPMENT.md) and show the comparison.

**Comment by shuokay** [comment]
@lutzroeder 
The result of 6.0.2 is:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/5029591/217737069-ab1578a8-e5fc-4f41-aaec-9e33c297650f.png">

**Comment by lutzroeder** [comment]
@shuokay I'm seeing below when reverting to 6.0.2. Are you using the same model file uploaded in this issue?

1. `git log --grep "Update to 6.0.2"`
2. `git reset --hard df5f35a853ae90c2b3f4f5cb96e578cf39094e4d`
3. `npm install`
4. `npm start`

<img width="434" alt="screenshot" src="https://user-images.githubusercontent.com/438516/217741346-d79b3596-e979-4d7e-8a46-ccf9fc7d87fb.png">

**Comment by shuokay** [comment]
@lutzroeder 
Should patch the following function signature to `pytorch_metadata.json`
```json
{
    "name": "ops.horizon.bpu_scale_quantization",
    "inputs": [
      {
        "name": "data",
        "type": "Tensor"
      },
      {
        "name": "scale",
        "type": "Tensor"
      },
      {
        "name": "zero_point",
        "type": "Tensor"
      },
      {
        "name": "vector_dim",
        "type": "int64"
      },
      {
        "name": "quant_min",
        "type": "int64"
      },
      {
        "name": "quant_max",
        "type": "int64"
      },
      {
        "name": "qtype",
        "type": "string"
      },
      {
        "name": "march_str",
        "type": "string"
      }
    ],
    "outputs": [
      {
        "name": "output",
        "type": "Tensor"
      }
    ]
  },
```
