### ISSUE TITLE
color for custom onnx operators 

### ISSUE THREAD

**Issue by AllenFind** [lutzroeder/netron#1046]
Hi,

Thanks for your Netron! It's very useful!

Now I am converting my dataset into ONNX format and then using Netron to do visualization.

Can we assign a color to the custom operator? Or could you give me some guidance about how to modify it?

**Comment by lutzroeder** [comment]
The colors are determined by the `category` of the `type` of a `node`. The actual colors are defined via `.node-item-type-<category>` in [grapher.css](https://github.com/lutzroeder/netron/blob/main/source/grapher.css). Categories for known operators are encoded in [onnx-metadata.json](https://github.com/lutzroeder/netron/blob/main/source/onnx-metadata.json). #742 for more  discussion how custom colors could be implemented.
