### ISSUE TITLE
Add feature map sizes

### ISSUE THREAD

**Issue by ogvalt** [lutzroeder/Netron#105]
It would be great if you'll add input and output feature map size

**Comment by lutzroeder** [comment]
Can you provide a sample file? Which file format and what do you expect to see?

**Comment by ogvalt** [comment]
For example, there is a function in keras that builds graph representation of model and saves it as image. Here an example of such image:
![model](https://user-images.githubusercontent.com/10532355/40297901-0548e3d4-5cea-11e8-9d01-98df48e6df3e.png)
And I think it would be great to add such explicit size representation into your tool.
i.e.
![export](https://user-images.githubusercontent.com/10532355/40298341-81d6a250-5ceb-11e8-89df-4e0f8b4ba8a5.png)

**Comment by lutzroeder** [comment]
Got it. This will require #71.
