### ISSUE TITLE
Mobile Safari does not support input file accept

### ISSUE THREAD

**Issue by FantasticStevenLuan** [lutzroeder/netron#1051]
I have my onnx in the ios app “file”, but when I clicked the “open module” button, i can go into the folder, but i cannot select the onnx file.
![89E137C5-892C-45CC-9490-4B2AB6E3E195](https://user-images.githubusercontent.com/64406506/220060151-7f8e1468-e6d8-42f6-900c-8b9c2531387c.png)

**Comment by lutzroeder** [comment]
https://openradar.appspot.com/36726477
