### ISSUE TITLE
ONNX: subgraph support of top-level initializers

### ISSUE THREAD

**Issue by fxmarty** [lutzroeder/netron#1052]
Hi,

In some cases, it can be interesting to register ONNX initializers in the topmost level, while using theses initializers only in subgraphs. This is especially useful when initializers need to be shared between subgraphs, for example to save memory and avoid duplicates.

Unfortunately, netron does not permit to inspect such initializers.

Here is an example: https://netron.app/?url=https://huggingface.co/fxmarty/netron-inspect-topmost-initializers/blob/main/decoder_model_merged.onnx

The initializer `transformer.h.0.attn.c_proj.weight_merged` is used the two `If` subgraphs in the node `/transformer/h.0/attn/c_proj/Gemm`, but the initializer itself is registered at the top level. Unfortunately with netron, this initializer can neither be inspected on the level graph or in the `If` subgraphs.

Corresponding file: https://huggingface.co/fxmarty/netron-inspect-topmost-initializers/tree/main

Netron version: 6.5.9

**Comment by lutzroeder** [comment]
[decoder_model_merged.onnx.zip](https://github.com/lutzroeder/netron/files/10830273/decoder_model_merged.onnx.zip)

**Comment by fxmarty** [comment]
@lutzroeder thank you for adding the support!
