### ISSUE TITLE
Caffe: different data type for Convolution between caffemodel and prototxt

### ISSUE THREAD

**Issue by lbq779660843** [lutzroeder/netron#1053]
Hello, I found that when I opened my caffemodel using Netron, the numerical values of all convolutional layers were displayed as '?'. However, when I opened any caffemodel downloaded(such as bvlc_googlenet.caffemodel) from the official Caffe website using Netron, the numerical values of all convolutional layers were normally displayed as float32.
![1](https://user-images.githubusercontent.com/27773249/222323639-588c66bb-634a-463d-8d62-51b587559f0c.jpg)

So I compared the corresponding information of the convolutional layers in the prototxt file of these two models and found that the bias_term parameter in my prototxt was set to false, but in the official prototxt file, the bias_term parameter was set to true and the bias_filler parameter had a value.
![2](https://user-images.githubusercontent.com/27773249/222323670-85dbb5b2-f03d-4ab7-b9e4-7b8bbf054d22.jpg)

Is this the specific reason for this issue?

**Comment by lutzroeder** [comment]
@lbq779660843 please share sample files to reproduce the issue.
