### ISSUE TITLE
window does not follow Windows theme

### ISSUE THREAD

**Issue by xwin** [lutzroeder/netron#1059]
I am using native Netron on windows. I guess it runs using electron or some other engine. My theme is set to have no shadows and use accent color for window border. The Netron window does not have accent border so the window is completely lost on top of another window. I am attaching example of how it looks.<br>
![netron-example](https://user-images.githubusercontent.com/1545682/225068370-1b3ce5f1-1542-4e57-887a-a9bdb4583ae6.png) <br>
This is how notepad looks. Notice the title bar with accent color and window borders are visible. <br>
![notepad-example](https://user-images.githubusercontent.com/1545682/225069019-136e1080-8ece-47d3-bfa4-6c7cf5512f2c.png)

**Comment by xwin** [comment]
I am using windows 10 22H2. There is no special steps to reproduce this issue. If I just run netron, its window is lost against the white window behind it. As shown in the attached image. The title bar of the window stays white, regardless if the window is selected or not. I dont know why netron does not follow windows theme.

**Comment by lutzroeder** [comment]
Electron apps like MarkText or Visual Studio Code have the same behavior. Does not repro on Windows 11. This needs to get fixed upstream: electron/electron#7172
