### ISSUE TITLE
TorchScript: Unknown function 'torch.resize_'

### ISSUE THREAD

**Issue by Jonxjdong** [lutzroeder/netron#1060]
- Netron app and version: 6.6.8
- OS and browser version: Ubuntu 18.04
- torch version  1.12.1+cu102

It seems the torchscript model converted from pytorch model inserted with observers for quantization fails to open. It reports error with something like "unknown function: torch.item" or "unknown function: torch.resize_". 

Steps to Generate target model:

import torch
from torchvision.models import resnet18
from torch.ao.quantization import get_default_qconfig
from torch.ao.quantization.quantize_fx import prepare_fx, convert_fx
model = resnet18(pretrained=True, num_classes=1000)
model.eval()

qconfig = get_default_qconfig('fbgemm')
qconfig_dict = {"": qconfig}  

prepared_model = prepare_fx(model, qconfig_dict)
model_scripted = torch.jit.script(prepared_model)
torch.jit.save(model_scripted, 'r18_scripted.pt')

**Comment by lutzroeder** [comment]
[r18_scripted.pt.zip](https://github.com/lutzroeder/netron/files/10988051/r18_scripted.pt.zip)

**Comment by Jonxjdong** [comment]
Got another error on min/max attribute. 

![无标题](https://user-images.githubusercontent.com/6297023/225583407-fe616a71-1796-4223-a7cf-a02545e680f2.png)

**Comment by lutzroeder** [comment]
TorchScript support is experimental. The code tries to trace the file guessing input sizes (pytorch/pytorch#48525). A possible workaround is to save a trace instead of script. Supporting script blocks without tracing is tracked by #1061.
