### ISSUE TITLE
(feature) Geometry visualization of inputs/outputs

### ISSUE THREAD

**Issue by enricoros** [lutzroeder/Netron#108]
Many papers show visually how an image input gets progressively shrunk but deepened by strided convolutions or expanded by deconvolutions.

Would be nice to have an isometric representation of the W*H*C input and output, in case of 3-dimensional geometries (batch=1).

The 2 isometric parallelepipeds could be drawn in the Node/Net panel.

**Comment by lutzroeder** [comment]
Yes, great idea. This would require #71 or is there another way to do this?

**Comment by enricoros** [comment]
Yep, #71 is a milestone here. When I take a look at some TF models (mobilenets) I see Input and output dimensions correctly specified in the right panel - is it the case in which the model well specifies the tensor shapes?
