### ISSUE TITLE
Win7 ,  netron 6.8.2 and 6.8.1 release versions , " can't locate DiscardVirtualMemory function on kernel32.dll"

### ISSUE THREAD

**Issue by wuyuanmm** [lutzroeder/netron#1080]
how to solve this ? thanks.

**Comment by lutzroeder** [comment]
Windows 7 is no longer supported by Electron. See [Farewell, Windows 7/8/8.1](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice).

The [browser](https://netron.app) app still works on Windows 7.
