### ISSUE TITLE
Enable toggling Full Screen

### ISSUE THREAD

**Issue by beru** [lutzroeder/netron#1085]
Enable toggling Full Screen would be handy. On Windows, pressing F11 key toggles fullscreen in web browsers, VSCode. So I expect Netron to be the same.

**Comment by lutzroeder** [comment]
<kbd>Ctrl</kbd>+<kbd>Cmd</kbd>+<kbd>F</kbd> on macOS or <kbd>F11</kbd> on Windows and Linux to enter and leave full screen.
