### ISSUE TITLE
Instructions how to install from source?

### ISSUE THREAD

**Issue by yurivict** [lutzroeder/netron#1093]
- Netron app and version: 6.8.8
- OS and browser version: FreeBSD 13.2

I am trying to update the netron FreeBSD port.

There used to be the setup.py in the root directory. Now it is in the publish directory. It refers to the 'netron' subdirectory that doesn't exist.

Are there instructions how to install netron from source?

**Comment by lutzroeder** [comment]
Do you have more context? Why is there a need for a FreeBSD port that is not being maintained?

**Comment by yurivict** [comment]
> Do you have more context? Why is there a need for a FreeBSD port that is not being maintained?

I maintain the port.

>  For the Python version, wouldn't users just install Python and run pip install netron?

We create ports/packages for all popular Python packages, because some other, non-Pythonic  software might then depend on Python packages, and 'pip install' wouldn't work in such situation.

**Comment by lutzroeder** [comment]
The `setup.py` change happened a while ago so sounds like this is a port that was not updated for a while? Is there an example of a broadly used "non-Pythonic" software requiring this or more a hypothetical scenario that for practical purposes results in outdated packages and users left on older versions? Would downloading the latest `.whl` from PyPi by an option?
