### ISSUE TITLE
DaVinci OM: dynamic model visualization

### ISSUE THREAD

**Issue by xiangyun-hz** [lutzroeder/netron#1098]
- Netron app and version:  3.8.2 Desktop app
- OS and browser version:  macos
10.15
Steps to Reproduce:

1. convert onnx to dynamic om model
2. visiual model using netron app
3. the result is as follows
<img width="245" alt="resnet18_1248" src="https://github.com/lutzroeder/netron/assets/30768593/a3e69da1-e58f-4a13-a7f6-99e33e11c7c0">

[resnet18_1248.om.zip](https://github.com/lutzroeder/netron/files/11475936/resnet18_1248.om.zip)
the attach model file is converted and it can be opened by netron app directly.
Please attach or link model files to reproduce the issue if necessary.

**Comment by lutzroeder** [comment]
@xiangyun-hz please investigate and submit a pull request.
