### ISSUE TITLE
Add support to visualize the DLC model format

### ISSUE THREAD

**Issue by MeghnaNatraj** [lutzroeder/netron#1101]
The DLC file extension is a ML model format that is currently not supported by Netron. 

Reference:

- [SNPE tool to convert Caffe / TensorFlow models to DLC format](https://developer.qualcomm.com/sites/default/files/docs/snpe/overview.html)

**Comment by lutzroeder** [comment]
Duplicate of #1101

**Comment by lutzroeder** [comment]
@MeghnaNatraj please share a model file, the format specification as some formats are undocumented and a pull request adding support.

**Comment by lutzroeder** [comment]
Duplicate of #640
