### ISSUE TITLE
Can't open Hailo *.har files if the filename different to the model name

### ISSUE THREAD

**Issue by RapidEdgeAI** [lutzroeder/netron#1104]
- Netron app and version: 6.9.2 Desktop app
- OS and browser version: Windows 10

Steps to Reproduce:

1. Parse an ONNX model with the Hailo ClientRunner
2. Save the *.har file with a different name than the model name

I parsed an ONNX model using `runner.translate_onnx_model`. For the `net_name` parameter i used "yolov5". Then I saved the HAR as "model.har" file using `runner.save_har`.  
If you try to view the HAR file with netron an error occures:
![image](https://github.com/lutzroeder/netron/assets/111732409/667bd868-24df-47b5-b101-028e1e04300b)

If I rename the file to "yolov5.har" it works.

**Comment by lutzroeder** [comment]
@RapidEdgeAI please report this to the [hailo-ai](https://github.com/hailo-ai) team.

cc: @mkhsanov
