### ISSUE TITLE
ONNX: FP8 data type support

### ISSUE THREAD

**Issue by zhenhuaw-me** [lutzroeder/netron#1107]
Firstly, thank you for this great tool! It closes so many barriers in DL.

I can see that the latest ONNX spec of FP8 definitions has been included in the source tree: https://github.com/lutzroeder/netron/blob/main/source/onnx-proto.js#L859

But my local try of the latest release (9.4.2) still reports unsupported data type.

![image](https://github.com/lutzroeder/netron/assets/4936589/7f372bd7-c210-4d20-b8e1-7d9787963809)

If any path needs to be enabled? Thanks!

**Comment by lutzroeder** [comment]
@zhenhuaw-me please share a model file to reproduce the issue.

**Comment by zhenhuaw-me** [comment]
Hi @lutzroeder, thank you for the quick update!

Attaching an ONNX FP8 sample that containing FP8 weights. It contains a `QuantizeLinear` operation of which the zero point is in FP8 data type.
[qf8.zip](https://github.com/lutzroeder/netron/files/11699457/qf8.zip)
The scripts that generates it and the log of text format of the model are included too.

You might want to refer to [the ONNX Quantize operation spec](https://github.com/onnx/onnx/blob/main/docs/Operators.md#QuantizeLinear). 

I think the main work is interpretting the FP8 buffer with the semantic described in this paper: https://arxiv.org/abs/2209.05433 . To be specific, the table below shows the semantic. The details can be found in the section "FP8 Binary Interchange Format".

![image](https://github.com/lutzroeder/netron/assets/4936589/fa716080-e7de-457c-a428-197477afefbb)

FP8 is a key feature of Nvidia Hopper GPUs which will are being widely deploied in the industry.

I'd like help to contribute, but I am not familiar with JS related dev.

**Comment by zhenhuaw-me** [comment]
Attaching more FP8 models that has different formats. FP8 has 4 representations:
```
    FLOAT8E4M3FN = 17;    // float 8, mostly used for coefficients, supports nan, not inf 
    FLOAT8E4M3FNUZ = 18;  // float 8, mostly used for coefficients, supports nan, not inf, no negative zero 
    FLOAT8E5M2 = 19;      // follows IEEE 754, supports nan, inf, mostly used for gradients
    FLOAT8E5M2FNUZ = 20;  // follows IEEE 754, supports nan, inf, mostly used for gradients, no negative zero
```

The one attached above is `FLOAT8E4M3FN`. This zip includes other three types.

[more-fp8-models.zip](https://github.com/lutzroeder/netron/files/11699545/more-fp8-models.zip)

**Comment by lutzroeder** [comment]
@zhenhuaw-me @xadupre can you help validate the fix at TIP?

**Comment by zhenhuaw-me** [comment]
@lutzroeder Awesome! What does TIP means?

**Comment by lutzroeder** [comment]
Latest commit in main. It is not included in a release yet.

**Comment by zhenhuaw-me** [comment]
@lutzroeder If any build that I can try with or I need to setup locally? I have only used the app before.

**Comment by xadupre** [comment]
zero_point is not used, only its type to determine the quantization type. onnxruntime considers it should be a scalar. onnx.checker does not check that. Here is the code I used to validate your model.

```python
import numpy as np
from onnx import load, TensorProto
from onnx.helper import (
    make_tensor_value_info,
    make_graph,
    make_node,
    make_model,
    make_tensor,
    make_opsetid,
)
from onnx.checker import check_model
from onnx.numpy_helper import to_array
from onnx.reference import ReferenceEvaluator
from onnx.reference.op_run import to_array_extended


def create_model(use_constant=True):
    X = make_tensor_value_info("A", TensorProto.FLOAT, [8, 16])
    Y = make_tensor_value_info("Y", TensorProto.FLOAT8E4M3FN, [8, 16])
    if use_constant:
        model = make_model(
            make_graph(
                [
                    make_node(
                        "Constant",
                        [],
                        ["scale"],
                        value=make_tensor("scale", TensorProto.FLOAT, [1], [2.0]),
                    ),
                    make_node(
                        "Constant",
                        [],
                        ["zero"],
                        value=make_tensor("zero", TensorProto.FLOAT8E4M3FN, [1], [0.0]),
                    ),
                    make_node("QuantizeLinear", ["A", "scale", "zero"], ["Y"]),
                ],
                "g",
                [X],
                [Y],
            ),
            opset_imports=[make_opsetid("", 19)],
        )
    else:
        # This model is valid but the reference implementation has still a bug fixed by PR
        # https://github.com/onnx/onnx/pull/5295.
        model = make_model(
            make_graph(
                [
                    make_node("QuantizeLinear", ["A", "scale", "zero"], ["Y"]),
                ],
                "g",
                [X],
                [Y],
                [
                    make_tensor("scale", TensorProto.FLOAT, [1], [2.0]),
                    make_tensor("zero", TensorProto.FLOAT8E4M3FN, [1], [0.0]),
                ],
            ),
            opset_imports=[make_opsetid("", 19)],
        )
    return model


raw = create_model(False)
# Does not check zero_point is scalar but onnxruntime does.
check_model(raw)  
# print(raw)

if raw.graph.initializer:
    init = raw.graph.initializer[1]
    z = to_array(init)
    print(init, z.dtype, z)
    z8 = to_array_extended(init)
    print(init.data_type, z8.dtype, z8.shape, z8)

x = np.random.random((8, 16)).astype(np.float32)
feeds = {"A": x}

# onnx.reference
ref = ReferenceEvaluator(raw.SerializeToString())
y = ref.run(None, feeds)
print("onnx:", y)
```

**Comment by zhenhuaw-me** [comment]
@xadupre Why "zero point is a scalar"? Is that an restriction of onnxruntime? In the ONNX spec, zero point has the same shape as scale which can be a vector, i.e. per-channel quantization.

**Comment by xadupre** [comment]
zero point is a scalar only for float 8 because it is not used. The behaviour does not change for the int8, uint8.
