### ISSUE TITLE
Core ML: Duplicate value 'k_1_bias_0_to_fp16'

### ISSUE THREAD

**Issue by wangchou** [lutzroeder/netron#1115]
I found netron no longer open **.mlpackage** today.
I guess it's because the auto update?

![Screenshot 0005-07-03 at 12 46 02](https://github.com/lutzroeder/netron/assets/32716/e14d5208-8512-4686-b6ec-aef02a9faa32)

**Comment by lutzroeder** [comment]
@wangchou please share a model to reproduce this issue.

**Comment by wangchou** [comment]
I just found I can disable it by deleting app-update.yml.
![Screenshot 0005-07-03 at 14 22 17](https://github.com/lutzroeder/netron/assets/32716/e26d0085-f104-4f4e-9b86-23a3f5187e1b)

**Comment by lutzroeder** [comment]
Duplicate of #243
