### ISSUE TITLE
xmodel: subgraph support

### ISSUE THREAD

**Issue by sh39o** [lutzroeder/netron#1118]
Hi @lutzroeder ,

I've tried to enable the graph.groups in the xmodel.js. And I want to show the properties of each xmodel.Subgraph as subgraph properties on the sidebar after each mouse click, just like node-click do.

![image](https://github.com/lutzroeder/netron/assets/36195355/6603c467-f2e7-412c-92dc-1a41c5fbea3c)

I've studied the source code of netron and set the graph.groups in the xmodel.js. The netron successfully showed the subgraph. 

![image](https://github.com/lutzroeder/netron/assets/36195355/6e794f04-c38d-46f7-8107-188941eece65)

However, the properties of xmodel.Subgraph can't be shown on the sidebar after clicking the subgraph/graph.group. I think that the refactor of the view.js is too complicated for me.
I made a pull request on my local fork https://github.com/sh39o/netron/pull/2/files

Can you please give me some advices? Or support the feature in the main branch of netron?

Many Thanks

Best Regards.

**Comment by lutzroeder** [comment]
@sh39o can you share a sample mode file.

`groups` was an experiment using dagre clustering and is deprecated.

The approaches used for ONNX functions or nested TensorFlow graph attributes might be worth exploring for nested graphs. See #773 or screenshot below. #68 is tracking hierarchical graph expansion which isn't fully implemented.

![image](https://github.com/lutzroeder/netron/assets/438516/5c24c00b-13c0-42fb-bbe4-a2924a875072)

**Comment by sh39o** [comment]
Many thanks for explaining. The demo above is very clear and the visual performance is very suitable for showing complex branch structures. Unfortunately, the xmodel doesn't support conditional branch or loop structures. (e.g., Scan, For, If in onnx) for the constraint of xir. 
If Scan/Loop/If is supported by xir, I'll try to make it visual in netron then :)

I only want to show the attributes of xmodel.Subgraph. Below shows a simple demo with only a conv2d. Since the `group` is deprecated, I'll try to support the feature locally. Also, I'll close this issue.
[toy_release.zip](https://github.com/lutzroeder/netron/files/11974839/toy_release.zip)

Thanks again for providing great helps!

Best Regards
