### ISSUE TITLE
ONNX: The file '...' does not exist.

### ISSUE THREAD

**Issue by ruby11dog** [lutzroeder/netron#1129]
netron version: 7.07
platform: windows
when i open a onnx file without weight, report an error "the file 'transformer.encoder.layers.0.weight' does not exist.", and i can view this onnx file without weight normally in the previous version, can somebody fix this problem? thx!!

**Comment by lutzroeder** [comment]
@ruby11dog can you share the ONNX file to reproduce the issue or submit a pull request with a fix.
