### ISSUE TITLE
Way to save the visualized graph offline

### ISSUE THREAD

**Issue by Zireael07** [lutzroeder/netron#1133]
Title

**Comment by lutzroeder** [comment]
Duplicate of #965

**Comment by Zireael07** [comment]
Not quite! I don't want a PNG, I want to save the page so that I can scroll the same way I can online (PNG/SVG exports are VERY tall and hard to see anything in them)

BTW the hamburger menu is pretty small and poorly visible...

**Comment by lutzroeder** [comment]
@Zireael07 can you explain the scenario. The desktop app works offline.

**Comment by Zireael07** [comment]
I saved the website and it doesn't work. (I admit I didn't see that there *is*  a desktop app)
