### ISSUE TITLE
QNN support

### ISSUE THREAD

**Issue by Winterdirge** [lutzroeder/netron#1137]
The qnn bin file is currently not supported by Netron.

Reference
https://docs.qualcomm.com/bundle/publicresource/topics/80-63442-50/tools.html#qnn-onnx-converter

**Comment by lutzroeder** [comment]
@Winterdirge can you please share a sample model file, implement QNN support and submit a pull request.

**Comment by MeghnaNatraj** [comment]
@lutzroeder will there be support added for QNN in the future?

**Comment by lutzroeder** [comment]
@MeghnaNatraj can you share a few sample files?

**Comment by lutzroeder** [comment]
Duplicate of #1283
