### ISSUE TITLE
ONNX: custom function with attributes

### ISSUE THREAD

**Issue by yuxuan-z19** [lutzroeder/netron#1138]
- Netron app and version:  3.8.10 Python Server (ver. 7.1.3)
- OS and browser version: Windows11 Microsoft Edge (ver. 115.0.1901.203)

I was running into a bug while trying to reproduce [this piece of code](https://onnx.ai/onnx/intro/python.html#a-function-with-attributes). Everything goes fine (same as `check_model()`) until I try to visualize the model using `netron`: an error `TypeError Cannot read properties of null (reading 'name')` pops out in the browser

Steps to Reproduce:

0. `pip install onnx netron`
1. Run the code and dump the model cretead by `onnx.save(onnx_model, "test.onnx")`
2. `netron test.onnx` and the error `TypeError Cannot read properties of null (reading 'name')` occurs

**Comment by lutzroeder** [comment]
@yuxuan-z19 can you share the model file.

**Comment by lutzroeder** [comment]
[issue_1138.onnx.zip](https://github.com/lutzroeder/netron/files/12343684/issue_1138.onnx.zip)
