### ISSUE TITLE
TorchScript: Unknown function 'torch.wait'

### ISSUE THREAD

**Issue by ssyzxc** [lutzroeder/netron#1140]
![image](https://github.com/lutzroeder/netron/assets/141480707/1c8ecdf7-fc32-49db-aaf3-4aa991321f6a)
What is the reason for this situation?Is the model too large or something else？thanks

**Comment by ssyzxc** [comment]
The file cannot be uploaded, 9g. How should it be shared?

**Comment by lutzroeder** [comment]
If the file is too large to upload, try DropBox, GDrive, OneDrive or run the script below to remove the weights from the file. Make a copy of the file as the script will overwrite the original file.

```python
import os
import shutil
import sys
import tempfile
import zipfile

zip_file_path = sys.argv[1];
print(zip_file_path)
zip_dir = tempfile.mkdtemp()

with zipfile.ZipFile(zip_file_path, 'r') as zip_file:
    zip_file.extractall(zip_dir)
for folder, subfolders, files in os.walk(zip_dir):
    if folder.endswith('/data'):
        for file in files:
            path = os.path.join(folder, file)
            size = os.path.getsize(path)
            with open(path, 'w+b') as file_handle:
                file_handle.write(bytearray(size))
with zipfile.ZipFile(zip_file_path, 'w', zipfile.ZIP_DEFLATED) as zip_file:
    for folder, subfolders, files in os.walk(zip_dir):
        for file in files:
            path = os.path.join(folder, file)
            zip_file.write(path, os.path.relpath(path, zip_dir))
shutil.rmtree(zip_dir)
```

**Comment by ssyzxc** [comment]
Hello, the compression file was not successful either. Is the file too large? This is someone else's. PT file to find the shape of the input tensor and convert it into an. onnx model, or how can we share it with you?
