### ISSUE TITLE
Keras: Cannot read properties of null (reading 'littleEndian')

### ISSUE THREAD

**Issue by Chizkiyahu** [lutzroeder/netron#1141]
- Netron app and version:  website 7.1.4
- OS and browser version: macOS 13.5 + Chrome Version 115.0.5790.170 

Steps to Reproduce:

1. run code the code  to create the model 
```
import tensorflow as tf

c = tf.keras.layers.Conv2D(3, 3)
model = tf.keras.Sequential([c])
tf.keras.models.save_model(model, "working.keras")

layer_with_quantizer = tf.keras.layers.Wrapper(c)
model = tf.keras.Sequential([layer_with_quantizer])
tf.keras.models.save_model(model, "bug.keras")
```
2. when loading in netron.app the model  I got the error `TypeError Cannot read properties of null (reading 'littleEndian')`
[working.keras.zip](https://github.com/lutzroeder/netron/files/12399004/working.keras.zip)
[bug.keras.zip](https://github.com/lutzroeder/netron/files/12399006/bug.keras.zip)

Please attach or link model files to reproduce the issue if necessary.

**Comment by Chizkiyahu** [comment]
update 
look like is fixed on the main in https://github.com/lutzroeder/netron/commit/2a41b5480ece4b1ce2bc98648d025390b6c53f4c

**Comment by lutzroeder** [comment]
[issue1142.1.keras.zip](https://github.com/lutzroeder/netron/files/12407995/issue1142.1.keras.zip)
[issue1142.2.keras.zip](https://github.com/lutzroeder/netron/files/12407996/issue1142.2.keras.zip)

**Comment by lutzroeder** [comment]
[1141.zip](https://github.com/lutzroeder/netron/files/13329220/1141.zip)
