### ISSUE TITLE
TorchScript: Too many dimensions for input?

### ISSUE THREAD

**Issue by TechInterMezzo** [lutzroeder/netron#1142]
- Netron app and version: 7.1.4 Desktop app
- OS and browser version: Windows 10

Steps to Reproduce:

1. Download https://github.com/snakers4/silero-vad/blob/master/files/silero_vad.jit
2. Rename from silero_vad.jit to silero_vad.pt
3. Open silero_vad.pt with Netron

**Comment by lutzroeder** [comment]
[silero_vad.zip](https://github.com/lutzroeder/netron/files/12439374/silero_vad.zip)

**Comment by lutzroeder** [comment]
Duplicate of #1061
