### ISSUE TITLE
ONNX: sparse tensor type support

### ISSUE THREAD

**Issue by yuslepukhin** [lutzroeder/netron#1143]
Example: this model has one sparse tensor input
https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/test/testdata/sparse_to_dense_matmul.onnx

This model has a sparse tensor output:
https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/test/testdata/sparse_initializer_as_output.onnx

**Comment by lutzroeder** [comment]
[sparse_initializer_as_output.onnx.zip](https://github.com/lutzroeder/netron/files/12444481/sparse_initializer_as_output.onnx.zip)
[sparse_to_dense_matmul.onnx.zip](https://github.com/lutzroeder/netron/files/12444482/sparse_to_dense_matmul.onnx.zip)

**Comment by lutzroeder** [comment]
Duplicate of #741
