### ISSUE TITLE
RKNN: Unsupported container version 6

### ISSUE THREAD

**Issue by E-Kozyreva** [lutzroeder/netron#1147]
Hi! I'm converting yolov5s-seg, yolov7-seg, yolov8s-seg to rknn format with using rknn-toolkit 2. When open rknn file of yolov*-seg.rknn i have "Unsupported RKNN container version 6". 
![image](https://github.com/lutzroeder/netron/assets/83861300/07b66152-522b-400b-8270-43628d135b42)
models: https://drive.google.com/drive/folders/1_EXLkuHNP-ZRZ64q8RVbZp2nnhw8lGdk?usp=sharing 
files_path: yolov*-seg/rknn/model.rknn)
Netron version:  7.1.5

**Comment by lutzroeder** [comment]
Duplicate of #639
