### ISSUE TITLE
DaVinci OM: Duplicate name

### ISSUE THREAD

**Issue by lixinye666** [lutzroeder/netron#1150]
- Netron app and version: 
- OS and browser version: 

Steps to Reproduce:

1. website netron
2.
![image](https://github.com/lutzroeder/netron/assets/80538387/6fe6b394-d8e2-47c4-87e4-518d0e5bce8c)

Please attach or link model files to reproduce the issue if necessary.

**Comment by lutzroeder** [comment]
@lixinye666 please share a sample file to reproduce this issue.

**Comment by lixinye666** [comment]
https://1drv.ms/u/s!Ajxv5FC6C6UFggOfmxKSuvgeo0-O?e=w5JCEc onedrive
