### ISSUE TITLE
Keras: Functional support

### ISSUE THREAD

**Issue by Chizkiyahu** [lutzroeder/netron#1151]
- Netron app and version:  website 
- OS and browser version: Mac OS 13.5.2 Chrome 116.0.5845.187

Steps to Reproduce:

1. create a tf model and use the same layer object multiple times
-  multiple inputs to the same object (model1)
-  output of layer goes to the same layer (model2)
-  output of layer goes to the same layer with another layer in the middle (model3)

```
import tensorflow as tf

keras_input1 = tf.keras.Input((3, 10, 10))
keras_input2 = tf.keras.Input((3, 10, 10))
keras_input3 = tf.keras.Input((3, 10, 10))
tf_conv = tf.keras.layers.Conv2D(filters=16, kernel_size=3)
out1 = tf_conv(keras_input1)
out2 = tf_conv(keras_input2)
out3 = tf_conv(keras_input3)
inputs = [keras_input1, keras_input2, keras_input3]
outputs = [out1, out2, out3]

model1 = tf.keras.Model(inputs=inputs, outputs=outputs)
model1.save("model1.keras")

keras_input = tf.keras.Input((3, 10, 10))
tf_conv = tf.keras.layers.Conv2D(filters=10, kernel_size=3, padding="same")
out = tf_conv(keras_input)
for _ in range(5):
    out = tf_conv(out)
model2 = tf.keras.Model(inputs=[keras_input], outputs=[out])
model2.save("model2.keras")

keras_input = tf.keras.Input((3, 10, 10))
tf_conv = tf.keras.layers.Conv2D(filters=10, kernel_size=3, padding="same")
out = tf_conv(keras_input)
for _ in range(5):
    out = tf.keras.layers.ReLU()(out)
    out = tf_conv(out)
model3 = tf.keras.Model(inputs=[keras_input], outputs=[out])
model3.save("model3.keras")

```

2. open in netron 
- inputs name are not true -  is showing [ input kernel bias 0 1] and is [ input1, input2, input3, kernel, bias]
- output is showing only 1 
- the edges are okay in model1 and model3 but in model2 it looks like only goes from node to the same node but is actually 5-edge 
![Screenshot 2023-09-14 at 13 47 11](https://github.com/lutzroeder/netron/assets/37312901/916c74d5-935d-4c0d-867b-c194fcfb60c2)
![Screenshot 2023-09-14 at 13 58 29](https://github.com/lutzroeder/netron/assets/37312901/2509dc53-a951-4c93-8737-e74b75804096)
![Screenshot 2023-09-14 at 13 58 37](https://github.com/lutzroeder/netron/assets/37312901/7eb0c699-fb56-4220-8ac6-f0705a559abd)

Please attach or link model files to reproduce the issue if necessary.
[models.zip](https://github.com/lutzroeder/netron/files/12607951/models.zip)

**Comment by lutzroeder** [comment]
@Chizkiyahu can you help investigate and recommend a pull request with a fix.

**Comment by Chizkiyahu** [comment]
> @Chizkiyahu can you help investigate and recommend a pull request with a fix.

I am investigating these cases in my work project
When I understood the correct way to extract the data 
I will try to create PR with a fix

**Comment by lutzroeder** [comment]
[nested_function.keras.zip](https://github.com/lutzroeder/netron/files/13292203/nested_function.keras.zip)
