### ISSUE TITLE
DaVinci OM: Unsupported partition type

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#1154]
Please attach or link a model file to reproduce this issue.

**Comment by zhanjin113** [comment]
[image_HDR_enhance.zip](https://github.com/lutzroeder/netron/files/12780876/image_HDR_enhance.zip)

**Comment by zhanjin113** [comment]
> Please attach or link a model file to reproduce this issue.

[image_HDR_enhance.zip](https://github.com/lutzroeder/netron/files/12780890/image_HDR_enhance.zip)
