### ISSUE TITLE
OpenVINO: Duplicate value

### ISSUE THREAD

**Issue by andrei-kochin** [lutzroeder/netron#1157]
- Netron app and version: Website https://netron.app/
- OS and browser version: Chrome Version 117.0.5938.63 (Official Build) (64-bit)

Steps to Reproduce:

[IRs.zip](https://github.com/lutzroeder/netron/files/12747269/IRs.zip)
1. Load OpenVINO IR PReLU OK
2. Load OpenVINO IR Squeeze.xml NOK
![image](https://github.com/lutzroeder/netron/assets/72827868/4fcd4e41-0fcd-4147-b23e-09818828aefe)

**Comment by rkazants** [comment]
Hi Lutz (@lutzroeder),

I reproduced this issue on all of my IRs. The problems seems to relate with parsing port information:

```
			<output>
				<port id="0" precision="I32" names="x,x:0" />
			</output>
```

Best regards,
Roman

**Comment by lutzroeder** [comment]
@andrei-kochin @rkazants can you help validate if [main](https://github.com/lutzroeder/netron/blob/main/CONTRIBUTING.md) resolves this issue?

**Comment by rkazants** [comment]
@lutzroeder, 7.2.1 release fixes the problem.

Thanks,
Roman
