### ISSUE TITLE
TorchScript: Unsupported 'torch.le' expression type.

### ISSUE THREAD

**Issue by youchangkim** [lutzroeder/netron#1167]
- Netron app and version: 7.2.1 desktop version
- OS and browser version: macOS 13.2.1

Steps to Reproduce:

1. following trace can't be opened by Netron.
2.

Please attach or link model files to reproduce the issue.

```python
import torch

def func(a, b):
    return a <= b

trace = torch.jit.trace(func, [torch.ones([1]), torch.zeros([1])])
torch.jit.save(trace, 'trace.pt')
```

**Comment by lutzroeder** [comment]
[issue1167.pt.zip](https://github.com/lutzroeder/netron/files/12901438/issue1167.pt.zip)
