### ISSUE TITLE
DaVinci OM SVP model with null output

### ISSUE THREAD

**Issue by YYLCyylc** [lutzroeder/netron#1170]
- Netron app and version: <7.2.5>
- OS and browser version: <windows>

Steps to Reproduce:

1.Get nothing while input a DaVinci OM SVP model
![image](https://github.com/lutzroeder/netron/assets/50295520/c580d8c5-b23b-4ea6-8694-1bde2cd6aad7)

Please attach or link model files to reproduce the issue.
[yolov8.zip](https://github.com/lutzroeder/netron/files/12926292/yolov8.zip)

**Comment by lutzroeder** [comment]
[yolov8.om.zip](https://github.com/lutzroeder/netron/files/12981666/yolov8.om.zip)
