### ISSUE TITLE
Identify output tensor of each layer given tflite model

### ISSUE THREAD

**Issue by alesus97** [lutzroeder/netron#1171]
Hello, I'm currently working on input-aware approximation of neural networks and utilizing Netron to visualize tflite quantized NN models. I'm particularly interested in understanding how Netron determines the index of the output tensor for each layer in the network from the tflite model.

For instance, in the case of the LeNet5 model, I need to retrieve the index of the output tensors specifically for the Convolutional and Dense layers. How can I identify them?

![FirstLayer-LeNet5](https://github.com/lutzroeder/netron/assets/34303122/0fcb20fa-a6c9-41d7-b983-8fccff177528)
![SecondLayer-LeNet5](https://github.com/lutzroeder/netron/assets/34303122/47013a23-9907-4e6d-93dd-b34e6632d7d1)

**Comment by lutzroeder** [comment]
Location is the index into `subgraph.tensors`. See [here](https://github.com/lutzroeder/netron/blob/2c384a9bee51468606e105e004962b87830147fd/source/tflite.js#L195-L204).
