### ISSUE TITLE
Portable version of netron

### ISSUE THREAD

**Issue by oxygen-dioxide** [lutzroeder/netron#1179]
I uses [scoop](https://scoop.sh/) to manage all my softwares, including netron. Because my `C:/` is small, I put the directory in another drive. However, netron often installs a copy on my `C:/` drive which is very annoying. Can I have a fully portable netron package?

**Comment by lutzroeder** [comment]
@oxygen-dioxide currently there are no plans to add and maintain more installer options. Can you help investigate what it would take to make the current installer and updater approach work for your scenario, and if necessary drive fixes for dependencies upstream.
