### ISSUE TITLE
Keras: tensor inbound_node support

### ISSUE THREAD

**Issue by isetre** [lutzroeder/netron#1180]
Hi,
are there any plans to support models created with the _Functional API_ from the upcoming Keras 3.0?
Right now when trying to open the attached model I get the following error:
```
Error loading Keras model. Invalid inbound node '{"args":[{"class_name":"__keras_tensor__","config":{"shape":[null,null],"dtype":"float32","keras_history":["title",0,0]}}],"kwargs":{}}'.
```

[multi_input_and_output_model.zip](https://github.com/lutzroeder/netron/files/13241361/multi_input_and_output_model.zip)

**Comment by lutzroeder** [comment]
@isetre can you investigate adding support for `__keras_tensor__` and submit a pull request.

**Comment by lutzroeder** [comment]
[multi_input_and_output_model.zip](https://github.com/lutzroeder/netron/files/13241361/multi_input_and_output_model.zip)

**Comment by lutzroeder** [comment]
@isetre basic Functional models are supported. This is likely failing because `__keras_tensor__` needs to get added. can you share a source sample, help investigate and submit a pull request?

**Comment by isetre** [comment]
Hi @lutzroeder sorry for the late response. Thank you for your quick response and fix!

Since you already fixed this issue, it is probably not relevant for you anymore, but for anyone who is interested: The network was created following the developer guide for the upcoming [keras 3.0/keras-core](https://keras.io/keras_core/guides/functional_api/#models-with-multiple-inputs-and-outputs).
