### ISSUE TITLE
ONNX: description not seen in a large file

### ISSUE THREAD

**Issue by MaiZhiHao** [lutzroeder/netron#1182]
My onnx file is very large, It about 1.6 G .
Most of the time , the description is not seen on my onnx file .
However , if I open a small onnx file , I can see the description item .

I have a question , could you tell how to locate the code line if I am unable to find th
![netron-no-description](https://github.com/lutzroeder/netron/assets/142228020/0440477d-9b53-4153-b7e7-d71ff0904359)
e description item

**Comment by lutzroeder** [comment]
@MaiZhiHao please share a model file to reproduce the issue.

**Comment by MaiZhiHao** [comment]
Hi @lutzroeder , I am unable to upload this large ONNX file
 -> It prompts "File size too big: 25 MB are allowed, 904 MB were attempted to upload."
How can I upload this ONNX file with you ?

**Comment by lutzroeder** [comment]
@MaiZhiHao what about file sharing using Google Drive or Dropbox.
