### ISSUE TITLE
model shows "Invalid tensor data size." when click on the bias tensor

### ISSUE THREAD

**Issue by tensorbuffer** [lutzroeder/netron#1184]
I am working on a tool that manipulates tflite directly without using tf tools, it's mostly working, but when I use the web version of netron, click on the bias tensor of the conv nodes it says "Invalid tensor data size.". The bias was float values and I changed the tensor to int32 and quantized them, replaced the tensor buffer to be the new numpy array. Everything looks fine to me, I did the similiar thing to the weight tensor and it was fine, but looks like there are something else I missed. Wondering how to debug this issue, what's special about bias tensor? Is there a place I can upload my generated tflite model to? Or, if I sync the code, is there a doc explain how to run it on browser?

**Comment by lutzroeder** [comment]
@tensorbuffer can you share a sample file to reproduce the issue.

**Comment by tensorbuffer** [comment]
https://www.dropbox.com/scl/fi/3v9tixfmoolxwc0rq2f9r/output.tflite?rlkey=kdnr36an0djnq47fl3k4wcs4q&dl=0
