### ISSUE TITLE
Error loading DLC model. File contains 'NR64' data.

### ISSUE THREAD

**Issue by kingzcheung** [lutzroeder/netron#1185]
- Netron app and version:  Desktop app 7.2.8
- OS and browser version:  macOS 14.0 (23A344) + Microsoft Edge  119.0.2151.58

Steps to Reproduce:

1. double click dlc model.
2.
![image](https://github.com/lutzroeder/netron/assets/12839855/0f81fc8b-7b88-4572-a3c0-d661ead1002a)

![image](https://github.com/lutzroeder/netron/assets/12839855/0f125a9b-96c3-4b0d-928c-18ab39c48983)

 
[yolov8n.dlc.zip](https://github.com/lutzroeder/netron/files/13344012/yolov8n.dlc.zip)

Please attach or link model files to reproduce the issue.

**Comment by lutzroeder** [comment]
Duplicate of #1183
