### ISSUE TITLE
Not able to open this .pt model in Netron

### ISSUE THREAD

**Issue by alokguptaxilinx** [lutzroeder/netron#1188]
[detector.zip](https://github.com/lutzroeder/netron/files/13419889/detector.zip)
Not able to open this .pt model in Netron

**Comment by lutzroeder** [comment]
@alokguptaxilinx can you share the code and PyTorch version that was used to create this file. It looks like it was serialized in a way that would require the code for `image_agent.models.Detector` to be available.
