### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dmoham1476** [lutzroeder/Netron#119]
Hi
I get this error when I try to load some .pb files. How can I get rid of this issue?

**Comment by lutzroeder** [comment]
Is it possible for you to share a sample file or link to a sample file? Also, can you try opening the [browser version](https://lutzroeder.github.io/Netron/) in a browser other than Chrome to see if that makes a difference?

**Comment by yangboqwer** [comment]
Hi
I get the same error when I try to load pytorch int8 model. All browsers don't work. What should I do?

**Comment by yangboqwer** [comment]
Hi, 
I get the same error when I try to load pytorch int8 model. All browsers don't work. What should I do?

**Comment by yangboqwer** [comment]
Hi, 
    I get the same error when I try to load pytorch int8 model. All browsers don't work. What should I do?
https://github.com/yangboqwer/test_onnx/blob/master/test_int8.onnx
The error is "error loading ONNX model. Maximum call stack size exceeded in 'test_int8.onnx'."
@lutzroeder

**Comment by lutzroeder** [comment]
[netron_issue_119.onnx.zip](https://github.com/lutzroeder/netron/files/4260628/netron_issue_119.onnx.zip)

**Comment by lutzroeder** [comment]
[netron_issue_119.zip](https://github.com/lutzroeder/netron/files/4260629/netron_issue_119.zip)

**Comment by yangboqwer** [comment]
Thanks!
