### ISSUE TITLE
Python Error 'dill._dill._create_type' not implemented.

### ISSUE THREAD

**Issue by bestLastpt** [lutzroeder/netron#1192]
I am using a pytorch yolov8m for my project but when I try to load the weights it gives that error

**Comment by bestLastpt** [comment]
Maybe i'll get answers on monday.

**Comment by lutzroeder** [comment]
@bestLastpt can you share the model file to reproduce the issue,

**Comment by bestLastpt** [comment]
@lutzroeder I upload the weights.
