### ISSUE TITLE
TorchScript: Unknown function '_0.tolist'

### ISSUE THREAD

**Issue by ewwerpm** [lutzroeder/netron#1193]
![image](https://github.com/lutzroeder/netron/assets/25223652/36123919-c233-48eb-bd4d-de7ca6eea073)
报这个错，模型文件地址：https://huggingface.co/ewwerpm/m4-sWE-0.1B.pt/tree/main
是由 RWKV-4-World-CHNtuned-0.1B-v1-20230617-ctx4096.pth 文件，采用分片的方法，分片出来的第一个文件。关键的是分片的时候，采用了 torch.jit.script()函数，导致打不开。如果采用torch.jit.trace()函数保存，就可以打开。但是trace()保存下来的模型，没有用。只有script保存下来的模型，才有用。但是有用的打不开，如何才能用netron打开这个script保存下来的模型文件呢？谢谢

**Comment by lutzroeder** [comment]
Duplicate of #1061
