### ISSUE TITLE
TorchScript: inputs_ids not connected to graph

### ISSUE THREAD

**Issue by ewwerpm** [lutzroeder/netron#1194]
模型地址：https://huggingface.co/ewwerpm/m4-sWE-0.1B.jit.trace.pt/tree/main
![image](https://github.com/lutzroeder/netron/assets/25223652/38e307e3-8538-4069-8bd6-1e3e68c8d59a)

是由RWKV-4-World-CHNtuned-0.1B-v1-20230617-ctx4096.pth 文件采用 torch.jit.trace()保存下来的第一个分片模型文件。用netron打开后，input_ids后面没有箭头。如果测试的话，也不能输出期望中的张量。是什么原因？没有箭头是如何走计算流程的呢？

**Comment by lutzroeder** [comment]
@ewwerpm can you share the model file to reproduce the issue.
