### ISSUE TITLE
Linux AppImage: Gsettings critical error after pressing "Open Model" button.

### ISSUE THREAD

**Issue by grwlf** [lutzroeder/Netron#120]
Hi. I got an error after pressing "Open Model" button of Nextron 1.8.9, run as AppImage. The error is below:
```
(netron:21909): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
```
Most likely, the problem is missing `GSETTINGS_SCHEMAS_PATH` or invalid `XDG_DATA_DIRS`, but the appimage doesn't seem to react on setting this variables in the environment.

PS. Let me suggest implementing the ability to pass model paths via command line.

**Comment by lutzroeder** [comment]
Tried this on Ubuntu 16.04 and seems to work. Can you investigate what is causing the issue and provide a fix? The app supports command line arguments but not sure how Electron handles this for `.AppImage` -- can you investigate this as well if it doesn't work on your computer and provide a fix?There is also drag and drop support to drop files into the window.
