### ISSUE TITLE
CoreML: Loop support

### ISSUE THREAD

**Issue by Vaida12345** [lutzroeder/netron#1203]
Hey. Just wondering if you could add the support for `bodyNetwork` of `CoreML`. Currently, it is like this:
<img width="1001" alt="Screenshot 2023-12-12 at 11 23 36 AM" src="https://github.com/lutzroeder/netron/assets/91354917/696d86e0-42b1-4048-bade-84947d90edcb">
The layers should be linked together (I have checked this using protobuf), but it is not shown here, as the `bodyNetwork`s are not drawn.
It would be great if you can add support for this! Thank you in advance.

**Comment by lutzroeder** [comment]
@Vaida12345 can you share a sample file to reproduce this issue.

**Comment by Vaida12345** [comment]
[FrameGRUModel.mlpackage.zip](https://github.com/lutzroeder/netron/files/13643385/FrameGRUModel.mlpackage.zip)
Sure. Have a look at this package.

**Comment by lutzroeder** [comment]
[FrameGRUModel.mlpackage.zip](https://github.com/lutzroeder/netron/files/13649962/FrameGRUModel.mlpackage.zip)

**Comment by Vaida12345** [comment]
Thank you for your implementation in version 7.3.4. 
If I may, can I request another feature please? 

In this example, 
<img width="1716" alt="Screenshot 2023-12-17 at 5 52 44 PM" src="https://github.com/lutzroeder/netron/assets/91354917/30752fbe-9ba6-4ef1-825b-887452b92afb">
The `copy` in blue is an input to the `loop` in green. Can you add an arrow to link these two please, as the one in orange?

Thank you again for accepting my feature request. You can use the [same model](https://github.com/lutzroeder/netron/files/13643385/FrameGRUModel.mlpackage.zip) I sent before.

**Comment by lutzroeder** [comment]
@Vaida12345 see #1204. Can you help implement this and submit a pull request that works for all formats.

**Comment by Vaida12345** [comment]
I would love to, but I really don't know how. Javascript is not where I shine. If you give me an outline, I might be able to do that.
