### ISSUE TITLE
Invalid file content. File contains HTML markup.

### ISSUE THREAD

**Issue by saurabhtangri** [lutzroeder/netron#1206]
- Netron app and version: Both
- OS and browser version: All bowsers

Steps to Reproduce:

1. Location of model : https://github.com/onnx/models/blob/main/archive/vision/classification/mnist/model/mnist-12-int8.onnx
2.

Please attach or link model files to reproduce the issue.

**Comment by lutzroeder** [comment]
@saurabhtangri the file was downloaded incorrectly as an HTML page.
