### ISSUE TITLE
ONNX: show SinceVersion in Node Properties

### ISSUE THREAD

**Issue by yuc8939** [lutzroeder/netron#1207]
The "SinceVersion" property of ONNX ops is an important part of the OP's type. In particular, ops with the same type but different SinceVersions can have different functions and implementations. 
I think it is useful that Netron displays "SinceVersion" along with "type" in the "NODE PROPERTIES" view for ONNX models.

**Comment by lutzroeder** [comment]
The version is shown as part of the  documentation. The feature regressed. Fixed for next version.

<img width="279" alt="documentation" src="https://github.com/lutzroeder/netron/assets/438516/899bec28-b7cd-430f-b3aa-4fa19f1f7d5a">
<br><br>
<img width="274" alt="version" src="https://github.com/lutzroeder/netron/assets/438516/13204bc9-b3c7-4132-ac6d-ba003b0756b4">
