### ISSUE TITLE
ONNX: nested function initializers

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#1208]
**Examples:**
[my_image_classifier.zip](https://github.com/lutzroeder/netron/files/13789981/my_image_classifier.zip)
[my_image_classifier.json.zip](https://github.com/user-attachments/files/17140902/my_image_classifier.json.zip)
[gpt2_export.onnx.zip](https://github.com/lutzroeder/netron/files/14189783/gpt2_export.onnx.zip)
[yolov8n.onnx.zip](https://github.com/lutzroeder/netron/files/15214443/yolov8n.onnx.zip)
[Clara_DenseNet_dynamo.onnx.zip](https://github.com/user-attachments/files/15358151/Clara_DenseNet_dynamo.onnx.zip) - #1225

**Comment by zhouzq-thu** [comment]
Please support ONNX initializers in subgraph/function, test file: 
[yolov8n.onnx.zip](https://github.com/lutzroeder/netron/files/15212086/yolov8n.onnx.zip)
