### ISSUE TITLE
The connection was reset error in python version when executable generated using pyinstaller 

### ISSUE THREAD

**Issue by Nagamani732** [lutzroeder/Netron#121]
This code works fine when I execute through python terminal. 

`import netron`

`netron.serve_file("deploy.caffemodel", False, True)`

The problem here is, I used the above code to create an executable using pyinstaller, when I try to run the executable I ended up with the following error in the browser. 

**The connection was reset

The connection to the server was reset while the page was loading.**

Could you please help me to resolve this error?

Thanks in advance

**Comment by lutzroeder** [comment]
@Nagamani732, can you investigate this further and reply if you have an answer?

**Comment by Nagamani732** [comment]
@lutzroeder Since the Netron uses .css, .json and .html files pyinstaller doesn't bundle all these files. So these files became dependencies for the executable to run. So I just copied all the files whatever the netron uses and pasted in the directory where executable is present and it works. Thanks
