### ISSUE TITLE
Shapes are not displayed on macOS with Apple Silicon

### ISSUE THREAD

**Issue by xiongyihui** [lutzroeder/netron#1210]
- Netron app and version:  7.3.6 Desktop app
- OS version: macOS Sonoma 14.2.1, Apple M2

The shapes of inputs and outputs are not displayed

Steps to Reproduce:

1. just open any onnx model

Please attach or link model files to reproduce the issue.

+ on macOS 14.2.1 M2
![image](https://github.com/lutzroeder/netron/assets/948283/8f68139b-546f-4fde-8bdc-838fcdb18ee7)

+ on netron.app, macOS 14.1.1 (Intel CPU) or netron installed by pip, the shapes are displayed
![image](https://github.com/lutzroeder/netron/assets/948283/69efab9c-59fa-4cd5-8967-33b52adcd555)

[simple_lstm-sim.onnx.zip](https://github.com/lutzroeder/netron/files/13837005/simple_lstm-sim.onnx.zip)

**Comment by lutzroeder** [comment]
@xiongyihui can you check both views have the same **View** > **Hide Names** <kbd>⌘U</kbd> setting.

**Comment by xiongyihui** [comment]
Got it. forget that  I checked "Show Names" 😂
Maybe change "Hide Names" to "Hide Names & Show Shapes", "Show Names" to "Show Names & Hide Shapes",
or add an option to show both names and shapes.
