### ISSUE TITLE
PyTorch: torch.export support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#1211]
**Documentation:**
[torch.export](https://pytorch.org/docs/stable/export.html)

**Examples:**
[exported_program.pt2.zip](https://github.com/lutzroeder/netron/files/13855206/exported_program.pt2.zip)
[gpt2.pt2.zip](https://github.com/user-attachments/files/17270120/gpt2.pt2.zip)
[inception_v3.pt2.zip](https://github.com/user-attachments/files/17179803/inception_v3.pt2.zip)
[mobilenet_v2.pt2.zip](https://github.com/user-attachments/files/17171765/mobilenet_v2.pt2.zip)
[resnet18.pt2.zip](https://github.com/lutzroeder/netron/files/13855229/resnet18.pt2.zip)

**Tools:**
[torch_export_strip_weights.zip](https://github.com/user-attachments/files/15287567/torch_export_strip_weights.zip)

**Comment by amodab01** [comment]
Hey @lutzroeder 
Should we expect the .pt2 support on Netron anytime soon?

**Comment by dgcnz** [comment]
+1 on this feature :^)

**Comment by lix19937** [comment]
+1
