### ISSUE TITLE
Large graph layout alert and cancel option

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#1214]
Replace "Large graph detected" warning with an option to cancel long running graph layouts and message "Large graph layout might take a very long time to complete.".

**Comment by kartikpodugu** [comment]
both browser and app installed on windows, show warning "Large Model Detected", when i click ok, it keeps showing that processing status on the 'O' of netron, and eventually does nothing. Not sure what really is happening. Not sure whether to wait or kill the model loading. I am trying to open SDXL Turbo model from hugging face. Both model and weights are in separate files.
