### ISSUE TITLE
When I use netron to check yolov8 architecture, it dose not show any branch

### ISSUE THREAD

**Issue by JimXu1989** [lutzroeder/netron#1216]
- Netron app and version: 7.3.8
- OS and browser version: Ubuntu 22.04

Steps to Reproduce:

1. download a yolov8.pt model  https://github.com/ultralytics/ultralytics
2. use netron to check it

you can find the model here: model  https://github.com/ultralytics/ultralytics
 netron does not show any branch

**Comment by lutzroeder** [comment]
@JimXu1989 the model file contains only weights and the module hierarchy, not the architecture graph.

**Comment by lutzroeder** [comment]
Duplicate of #720
