### ISSUE TITLE
Darknet: open weights files in browser

### ISSUE THREAD

**Issue by flying66test** [lutzroeder/netron#1217]
Rename the file to `csresnext50-panet-spp.weights` so it matches the `.cfg` file and copy it next to the `csresnext50-panet-spp.cfg` file.

_Originally posted by @lutzroeder in https://github.com/lutzroeder/netron/issues/395#issuecomment-567199046_

**Comment by flying66test** [comment]
Hi this does not seem to work using netron in a browser.

**Comment by lutzroeder** [comment]
@flying66test can you try selecting both files and drag and drop them into the browser window.

**Comment by flying66test** [comment]
Thank you for the immediate response. 
Unfortunately this still does not work in my environment ubuntu 22.04, Chromium Version 120.0.6099.216 (Official Build) snap (64-bit). Tried all options drag and drop both files, first .weights, first .cfg, open model.

**Comment by lutzroeder** [comment]
@flying66test can you share the model files and a screenshot or description what you are seeing.

**Comment by flying66test** [comment]
I am using the standard yolov3.cfg & yolov3.weights files.
![Screenshot from 2024-01-23 12-43-17](https://github.com/lutzroeder/netron/assets/157136377/6cc98ce2-574d-40b5-9963-70df4c65dba6)

**Comment by lutzroeder** [comment]
@flying66test can you share the files (could be a corrupted file) or [debug](https://github.com/lutzroeder/netron/blob/main/CONTRIBUTING.md#debugging) why this happening.
