### ISSUE TITLE
Tensor Visualization

### ISSUE THREAD

**Issue by cybertk** [lutzroeder/Netron#122]
Sometimes, we need to inspect the layer's weights/bias, or the statistics info such as mean, standard error and etc.

Is it possible to visualize these info in Netron?

**Comment by lutzroeder** [comment]
Weights will show if they are stored in the model file. What model format are you using and can you share a sample file? #65 is tracking renderings other than plain numbers.

Stats are usually not stored in model files.

**Comment by cybertk** [comment]
I can see the raw weights/bias data in the panel, but it's hard to read and understand especially for a large size kernel in the fully connected layer. 

Actually what I asked is the plot/picture you mentioned in #65, in addition to some statistics info. It will help a lot to understand the tensor data.

Another proposal is exporting/save the tensor to a file, then use the existing tools to visualize them.

**Comment by lutzroeder** [comment]
If you have ideas what this should look like, feel free to add them to #65 and #125. For exporting a tensor, what format do you have in mind and which tools are you using for visualization?

**Comment by nrupatunga** [comment]
In mxnet, models weights are saved in .params and architecture in .symbol, 
And the weights are shown empty, How do we visualize the weights?

**Comment by lutzroeder** [comment]
@nrupatunga please open a new issue for tracking and add repro steps and files. If the weights are in a `-0000.params` next to `-symbol.json` they should get loaded up.

**Comment by lutzroeder** [comment]
@nrupatunga created #285 to track this separately.
