### ISSUE TITLE
Downloading large amounts of data when opening the app

### ISSUE THREAD

**Issue by echoonly** [lutzroeder/netron#1220]
Every time you open it,I will see the network traffic used. Even if don’t open any graph file and just open the app, the network bandwidth will be fully used.

- Netron app and version:  7.3.8
- OS and browser version:  macOS  12.7.3(21H1015)

Steps to Reproduce:

1. just open netron app

Please attach or link model files to reproduce the issue.

![iShot_2024-01-03_16 12 43](https://github.com/lutzroeder/netron/assets/11766632/b6580f46-58b3-45b4-b731-e5a540de0dac)

**Comment by lutzroeder** [comment]
@echoonly can you try `start $Env:LOCALAPPDATA\Programs\netron\Netron.exe` from command line which might show if an update is being downloaded? If not, is there a way for you to find out what is being downloaded?

**Comment by echoonly** [comment]
> @echoonly can you try `start $Env:LOCALAPPDATA\Programs\netron\Netron.exe` from command line which might show if an update is being downloaded? If not, is there a way for you to find out what is being downloaded?

I am using masOS platform, and I try 'open /Applications/Netron.app/Contents/MacOS/Netron' from command line.
```
$ open /Applications/Netron.app/Contents/MacOS/Netron
Checking for update
[87077:0125/112828.726430:ERROR:trust_store_mac.cc(750)] Error parsing certificate:
ERROR: Failed parsing extensions
```

So the reason for downloading data is to check for updates every time I start it. Can this update checking be turned off, or use a pop-up window to confirm whether an update is needed. Sometimes I don't need to update, or I am using a mobile network and don't want to use too much network data.
