### ISSUE TITLE
Python Server: experiment test requires file identifier

### ISSUE THREAD

**Issue by ParGG** [lutzroeder/netron#1222]
Environment:
Netron version: https://github.com/lutzroeder/netron/commit/e03d63730c9a35087618d58ff15e689eba253f04
Python version: 3.9.16
Operating System: MacOS 14.3

Description:
I am facing an issue while running the `_test_onnx` function in `test/backend.py`. The JSON graph is constructed and passed to the `_ContentProvider` as expected. However, when the `_HTTPServerThread` is started to display the graph, the Netron welcome page is loaded instead of the intended graph visualization.

The difference I noticed between the version on which I was working (from December 2022) and the current one on main, is that in [this loop](https://github.com/lutzroeder/netron/blob/e03d63730c9a35087618d58ff15e689eba253f04/source/browser.js#L17) there was the element `[Log] <meta name="file" content="/data/model.netron">` which isn't present anymore.

**Comment by lutzroeder** [comment]
@ParGG can you explain why you are using this experimental test instead of saving to a `.onnx` file and serving the file.

**Comment by ParGG** [comment]
Hey @lutzroeder, I need programmatic control over certain types of graphs for our purposes. Therefore, the Python interface is very useful.

**Comment by lutzroeder** [comment]
@ParGG can you provide more context. For example, why would it not work to use:
```python
onnx.save(model, 'example.onnx')
netron.start('example.onnx', browse=False)
```
