### ISSUE TITLE
Keras: YOLOV8Detector is not supported

### ISSUE THREAD

**Issue by SergCib** [lutzroeder/netron#1223]
Netron - 7.4.1
Message: YOLOV8Detector is not supported

Version keras_cv= 0.8.1
from keras_cv.models import YOLOV8Backbone, YOLOV8Detector
backbone = keras_cv.models.YOLOV8Backbone.from_preset( "yolo_v8_s_backbone_coco",)
model.save("model_yolo8.keras")

**Comment by lutzroeder** [comment]
@SergCib 
```
~: python
>>> from keras_cv.models import YOLOV8Backbone, YOLOV8Detector
Using TensorFlow backend
>>> backbone = keras_cv.models.YOLOV8Backbone.from_preset( "yolo_v8_s_backbone_coco",)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'keras_cv' is not defined
```
