### ISSUE TITLE
ONNX: Invalid int64 value

### ISSUE THREAD

**Issue by jerryhatestom** [lutzroeder/netron#1228]
I have added a self-defined attribute to ONNX OP Cast with type int64[], it is expected to show as **-1,32**, but it shows as **18446744073709551615,32**(with underline in below picture). I guess -1 is represented as unsigned int64, since **18446744073709551615** is the max unsigned int64 number. 

The issue can be found in version v7.6.4, and can not be found in old version v7.3.5.

![image](https://github.com/lutzroeder/netron/assets/38418170/70453321-c7f6-4be1-b57f-dcdc216784ce)

**Comment by lutzroeder** [comment]
@jerryhatestom  can you share an example file to reproduce this issue.
