### ISSUE TITLE
Use wingetcreate for package submissions

### ISSUE THREAD

**Issue by mdanish-kh** [lutzroeder/netron#1231]
### Problem

Currently, a lot of Netron package PRs are getting labeled with `Manifest-Version-Deprecated` over at winget-pkgs: https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+author%3Alutzroeder+is%3Aclosed+label%3AManifest-Version-Deprecated. This is because the action uses a hardcoded `1.2.0` schema version.

### Proposal

Use wingetcreate in the CI pipeline to handle package updates to winget. It'll always use the latest schema version and make improvements to the manifest for better readability.

### Workflow

Reference workflow file that can be used for this repo

```github
    name: Publish winget
    runs-on: windows-latest
    steps:
    - name: Sync winget-pkgs fork
      run : gh repo sync lutzroeder/winget-pkgs -b master
      env:
        GH_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
    - name: Submit package to Windows Package Manager Community Repository
      run: |
        $packageId = "LutzRoeder.Netron"
        $gitToken = "${{ secrets.PUBLISH_GITHUB_TOKEN }}"

        # Fetching latest release from GitHub
        $github = Invoke-RestMethod -uri "https://api.github.com/repos/lutzroeder/netron/releases"
        $targetRelease = $github | Select-Object -First 1
        $installerUrl = $targetRelease | Select-Object -ExpandProperty assets -First 1 | Where-Object -Property name -match 'Netron-Setup-\d+(\.\d+)*\.exe' | Select-Object -ExpandProperty browser_download_url
        $packageVersion = $targetRelease.tag_name.Trim("v")

        # Update package using wingetcreate
        Invoke-WebRequest https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
        .\wingetcreate.exe update $packageId --version $packageVersion --urls "$installerUrl|x86" "$installerUrl|arm64" --submit --token $gitToken
```

**Comment by lutzroeder** [comment]
@mdanish-kh can you recommend a fix that would not require taking a dependency on `wingetcreate`.

**Comment by mdanish-kh** [comment]
Well, the manual fix would be to use the latest schema version when it rolls out for winget. The `ManifestVersion` currently used is `1.2.0`, you can bump that to `1.6.0` in all yaml files to fix `Manifest-Version-Deprecated`
