### ISSUE TITLE
Isolated blocks in network visualisation

### ISSUE THREAD

**Issue by skrishnanv** [lutzroeder/netron#1235]
hello,
thanks for the Netron.
I have a doubt regarding the visualisation. I do not think it is an "issue". However, there seems to be no other way to discuss this than raise a issue.
Attached is an image of a simple cnn with standard blocks of conv, downsample, non-lin, a kind of residual connections etc. My doubt is: at the top why are the additional add_ blocks and two modules rendered? i have tried to see their input and output numbers but unable to map them at a quick glance.
i have rendered them in tensorboard and there i do not see these isolated blocks. However, i prefer to use netron.
so, any explanation to resolve this confusion will be deeply helpful.
thanks 

![model_scripted](https://github.com/lutzroeder/netron/assets/46158005/391de7c2-660c-49b4-8bf1-ec97967ddf84)

**Comment by lutzroeder** [comment]
@skrishnanv can you share a sample file and did you investigate why this is happening.

**Comment by skrishnanv** [comment]
Hi @lutzroeder ,
i will get this over the next weekend and post here.
thanks!
