### ISSUE TITLE
Reduce the complexity of drawing

### ISSUE THREAD

**Issue by shenck0** [lutzroeder/netron#1237]
With the increasing number of model operators at present, and models usually composed of several similar structural blocks.
To speed up visualization and clarity, we can add a scripting mechanism to the Netron which identify these subgraph e.g. Attention block, then it folds them into a single 'operator', which can be opened separately for viewing when the user is interested. 
And those scripts can be implemented by the community.

**Comment by lutzroeder** [comment]
@shenck0 can you provide some context how this is expected to work, an example file or a pull request.
