### ISSUE TITLE
OpenVINO: model will appear blank in 7.5.4

### ISSUE THREAD

**Issue by mdeisher** [lutzroeder/netron#1243]
- Netron app and version: Desktop app 7.5.3 and 7.5.4 (last known working version is 7.4.9)
- OS and browser version: Windows 11 Enterprise Version 10.0.22631 Build 22631

Steps to Reproduce:

1.  Open any OpenVINO IR using the desktop app.  The window will appear blank.
2.  Open any ONNX network and Netron behaves as expected.

Please attach or link model files to reproduce the issue.
[vww.zip](https://github.com/lutzroeder/netron/files/14594215/vww.zip)

**Comment by lutzroeder** [comment]
f6ad6291a47b328247e497a4818f2152028a84cc

**Comment by lutzroeder** [comment]
@mdeisher can you help [validate](https://github.com/lutzroeder/netron/blob/main/CONTRIBUTING.md) the fix in [main](https://github.com/lutzroeder/netron/tree/main).

**Comment by daniil-lyakhov** [comment]
Hi @lutzroeder, I'm unable to open any OpenvinoIR neither in the web app https://netron.app/ nor in my local app right now, is it possible to run the netron app with the fix locally?

**Comment by mdeisher** [comment]
@lutzroeder I tried, but I am a netron.exe user, not a Java developer.  I was able to install Node.js and run npm but it hangs with "[..................] / idealTree:netron: sill idealTree buildDeps".  How long is that supposed to take typically?

**Comment by mdeisher** [comment]
I installed 7.5.5 Netron.exe and it works just fine.  Thank you!
