### ISSUE TITLE
TorchScript: Unsupported 'torch.polar' expression type

### ISSUE THREAD

**Issue by hzhangxyz** [lutzroeder/netron#1251]
`torch.polar` is used to convert two real number to a complex number, which is useful in rotary position embedding for transformers. It would be helpful if netron could support it.

Currently, when using `torch.polar` in module, netron complains that "Python Error Unknown function 'torch.polar'."

**Comment by lutzroeder** [comment]
@hzhangxyz can you share a sample file to reproduce the issue.

**Comment by hzhangxyz** [comment]
@lutzroeder 

Here is an example to reproduce it:

```
import torch


class Example(torch.nn.Module):

    def forward(self, x):
        return torch.polar(torch.ones_like(x), x)


example = torch.jit.script(Example())

print(example(torch.arange(10, dtype=torch.float32)))

torch.jit.save(example, "example.pt")
```

**Comment by hzhangxyz** [comment]
`torch.polar` is used in llama to implement rotary positional embedding, see https://github.com/meta-llama/llama/blob/54c22c0d63a3f3c9e77f43a6a3041c00018f4964/llama/model.py#L103
