### ISSUE TITLE
do not upload file in chrom to netron

### ISSUE THREAD

**Issue by kuisu-GDUT** [lutzroeder/netron#1252]

**Comment by kuisu-GDUT** [comment]
<img width="694" alt="image" src="https://github.com/lutzroeder/netron/assets/46948531/7bf2f2f9-5cfe-4a93-b790-c476895ed674">

In the browser, the file cannot be uploaded

**Comment by lutzroeder** [comment]
@kuisu-GDUT can you add some context how to reproduce this?
