### ISSUE TITLE
ONNX: Tensor shape is not displayed

### ISSUE THREAD

**Issue by kumardesappan** [lutzroeder/netron#1253]
7.5.7 Website/Desktop
Windows Edge Version 123.0.2420.65 

Issue : Tensor shape is not displayed within ONNX _function_ , even though model has tensor information for all intermediate tensors.

Attached model has tensor shape for all layer in the pb file, but they are not displayed with in _function_.
Can you check this?

![image](https://github.com/lutzroeder/netron/assets/20221577/68724900-f723-4d6b-bc07-8da89f7aaa10)
![image](https://github.com/lutzroeder/netron/assets/20221577/e0c2a194-c003-45bc-b8a0-bbb2c8e14d25)

[tree_export.zip](https://github.com/lutzroeder/netron/files/14812141/tree_export.zip)

**Comment by lutzroeder** [comment]
@kumardesappan the `value_info` for the function connections is empty.

Please investigate or discuss with [onnx/onnx](https://github.com/onnx/onnx) and [pytorch/pytorch](https://github.com/pytorch/pytorch).

cc @justinchuby @gramalingam

**Comment by gramalingam** [comment]
The ability to add value_info for symbols within functions is a newly added feature (just out in last week's release of onnx). Value_info in main graph for symbols within functions is likely an error/experimentation in the model-exporter.
