### ISSUE TITLE
Reduce connection crossings

### ISSUE THREAD

**Issue by beru** [lutzroeder/netron#1257]
I see a lot of intersections of connection lines on the graph visualization. And in some cases, it should be possible to reduce the intersections by adjusting node positions.

[yolov5n.onnx](https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5n.onnx).

![image](https://github.com/lutzroeder/netron/assets/1131125/736fad1f-cb93-4b5a-b993-e8df1a4ebd3a)

**Comment by lutzroeder** [comment]
@beru please submit a pull request that shows this improvement to the layout algorithm.

**Comment by beru** [comment]
> @beru please submit a pull request that illustrates this improvement to the layout algorithm.

@lutzroeder I've opened #1261 for that. I only took care of low hanging fruits. So there's surely a lot of room for improvements. Please review it if you're somehow interested in it. If not, I'll close the PR.

**Comment by beru** [comment]
I've just found a related issue.

https://github.com/dagrejs/dagre/issues/357
