### ISSUE TITLE
Graph scrolling by dragging scrollbars doesn't work well on Firefox

### ISSUE THREAD

**Issue by beru** [lutzroeder/netron#1258]
- Netron app and version: Version 7.5.8 
- OS and browser version: Ubuntu 23.10 + Firefox 124.0.2 

Steps to Reproduce:

1. Go to https://netron.app/ on Firefox
2. Open a model file.
3. Start dragging a (vertical or horizontal) scroll-bar by clicking it and move your mouse to scroll.
4. The behaviour of scrolling is different from that of using a scroll-bar. It's as if dragging the graph area. The problem can be avoided by moving a mouse cursor outside of a browser window after pressing the scroll-bar and before scrolling but it's not possible when the browser window is maximized. I don't see this issue on Chrome browser (Version 123.0.6312.105).

Please attach or link model files to reproduce the issue.

[yolov5n.onnx](https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5n.onnx)

**Comment by lutzroeder** [comment]
@beru please investigate and submit a fix.
