### ISSUE TITLE
Caffe2 Detectron model Visualization

### ISSUE THREAD

**Issue by saikiran6** [lutzroeder/Netron#126]
Do Netron support visualization of caffe2's detectron models which are stored in pkl format. Thanks in Advance.

**Comment by lutzroeder** [comment]
Did you try the [converter](https://github.com/facebookresearch/Detectron/blob/master/tools/convert_pkl_to_pb.py) or get it fixed?

**Comment by saikiran6** [comment]
Hi. I tried the converter. I was able to convert the detectron model from pkl to pb format. But when Iam trying to serve the pb model, I am getting the following error

"From localhost:8080
Error loading TensorFlow model. invalid wire type 4 at offset 3"

Please help me out. Thanks

**Comment by lutzroeder** [comment]
Per Caffe2 convention model, the file needs to be called `xxxx_predict_net.pb` to be detected as a Caffe2 model. Otherwise it will be assume that it is in TensorFlow or ONNX protobuf format.

**Comment by saikiran6** [comment]
Thanks @lutzroeder . Iam bale to visualize the detectron model with above steps. Thanks for the quick response and thanks for helping me out.

**Comment by lutzroeder** [comment]
Duplicate of #1116
