### ISSUE TITLE
TNN: weight layer does not exist in model

### ISSUE THREAD

**Issue by SccotMu** [lutzroeder/netron#1264]
- Netron app and version: <windows 7.6.0>
 
I opened two tnn model, I can see the details of every op like bias weight for one model, but another, i can`t see the detailes.

here is the pictures:
![微信截图_20240420154126](https://github.com/lutzroeder/netron/assets/52561068/2824b790-b533-4175-8ac0-e31ca816f8b4)

model links:
https://drive.google.com/drive/folders/12lF6NtbCfwhxId1SpzpsQIf_idupKQ4I?usp=drive_link

**Comment by lutzroeder** [comment]
@masterwan96  @1627180283

**Comment by lutzroeder** [comment]
![image](https://github.com/lutzroeder/netron/assets/438516/59d9fa1c-b5ee-4342-bdc2-89a8a42652ac)

**Comment by SccotMu** [comment]
https://drive.google.com/drive/folders/12lF6NtbCfwhxId1SpzpsQIf_idupKQ4I?usp=sharing
visit this link with free access. Also, you have the edition access about the folder in google driver. Thanks!
