### ISSUE TITLE
File open dialog should be modal

### ISSUE THREAD

**Issue by beru** [lutzroeder/netron#1266]
The File Open Dialog isn't currently modal as though the File Export dialog is mordal.

The link to the code to open the File Open Dialog : [link](https://github.com/lutzroeder/netron/blob/0570a43e8f93ad118d445c5f5c979b1c1cdb9c0f/source/app.js#L177)

The link to the code to open the File Export Dialog : [link](https://github.com/lutzroeder/netron/blob/0570a43e8f93ad118d445c5f5c979b1c1cdb9c0f/source/app.js#L247)

I've confirmed that an optional `browserWindow` argument makes a file dialog modal when it's opened.
https://www.electronjs.org/docs/latest/api/dialog#dialogshowopendialogbrowserwindow-options

![image](https://github.com/lutzroeder/netron/assets/1131125/d0bad2f1-641c-484e-b579-f387437577e4)

Please consider to make it modal.

**Comment by lutzroeder** [comment]
@beru what are the pros and cons for making it modal? For example, TextApp on macOS seems to use a non-model dialog. When opening a file and then another file the dialog would be attached to one window and the new file in another.

**Comment by beru** [comment]
@lutzroeder I do not own Mac computers currently so I cannot test TextEdit program. As far as I see, Visual Studio Code, Visual Studio, Microsoft Edge, Firefox use modal file open dialogs on Windows.

The downside of the file open dialog being non-mordal is it can go behind Netron window so users tend to lose its location.

Since the dialog is currently non-mordal, I can select the File Open menu when the dialog is already opened but doing so doen't make any immediate changes to screen. And it took me by surprise that when I close the opened dialog, new file dialog is automatically opened since I selected the File Open menu when the dialog is already opened.

![netron_non_mordal_file_open](https://github.com/lutzroeder/netron/assets/1131125/ee80037e-e9a0-48e4-91cb-1a59661ed333)

Besides, the dialog is modal when I use Netron at https://netron.app/
