### ISSUE TITLE
Netron-Setup.exe doesn't work in windows.

### ISSUE THREAD

**Issue by gbbin** [lutzroeder/netron#1267]
I install netron in two windows machine, both of them failed.
The first , when i run netron,  got the following message.
MISS A SHORCUT
Windows was looking for Netron.exe.
![1713862128067](https://github.com/lutzroeder/netron/assets/19522882/f28200ab-7c69-4368-98ab-e8053c9480ed)

![1713862242190](https://github.com/lutzroeder/netron/assets/19522882/aff7e1b9-9ae7-45b6-a878-74dff6cd58f4)

The second machine, when i run netron, there was no response at all.

**Comment by lutzroeder** [comment]
@gbbin can you please investigate or provide more information why this is happening.
