### ISSUE TITLE
Toggle search item types

### ISSUE THREAD

**Issue by beru** [lutzroeder/netron#1268]
How about adding icons to toggle Initializers/Nodes/Edges on the FIND sider bar? It might be handy when there're a lot of items displayed with the similar name.

![netron_find_filter](https://github.com/lutzroeder/netron/assets/1131125/dc02f1b9-ad17-42d4-a089-7a915b3613fd)

impl : https://github.com/beru/netron/commit/bc2a0096059c9df13b860cf5e8eaeb48fe78b5c9

**Comment by lutzroeder** [comment]
@beru can you create a pull request? The list is using a monospaced font while the icons use the font in the search bar?
