### ISSUE TITLE
TensorFlow: duplicate value

### ISSUE THREAD

**Issue by yuc8939** [lutzroeder/netron#1271]
- Netron app and version: 7.6.2 Desktop app
- OS version: Windows 10

Steps to Reproduce:

1. Open a TensorFlow model, which has a feed and its corresponding Placeholder node, both named 'graph_emb' (which is legal in TensorFlow)
2. Netron failed to open the model and prompted "Error loading TensorFlow model: duplicate value 'graph_emb' "

**Comment by lutzroeder** [comment]
@yuc8939 can you please share a sample file and the steps to create it.
