### ISSUE TITLE
Manual graph layout

### ISSUE THREAD

**Issue by nirmalshah20519** [lutzroeder/netron#1272]
For long models there should be a feature to edit the position of blocks so that One can keep the image in a ppt slide by changing the positions.
![cnn_model](https://github.com/lutzroeder/netron/assets/73649031/a70c28b5-3e47-4851-93c5-b56eefa3f0b8)

**Comment by lutzroeder** [comment]
@nirmalshah20519 can you explain how you are planing to implement this feature and scale it for more complex scenarios.

* If the graph has 500+ nodes, would each of these have to be moved individually? 
* If a mistake is made or the app is restarted all repositioning would have to start over from scratch?
* Which other approaches and apps have you tried to that might be better suited for editing before publishing?
* Have you investigated if automatic graph layouts like snake layout are better suited to accomplish this purpose? 
* Are you planing sign up, implement this feature, create a pull request and maintain it going forward?
