### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by akj10** [lutzroeder/netron#1289]
- Netron app and version: 7.7.2 Desktop app
- OS and browser version: Windows 11 Pro 24H2 26085.1

Steps to Reproduce:

1. Double click on model_opt_nogrn.onnx to open with netron app
2. The circle rotates and you get "Maximum call stack size exceeded" error

This model is the unet from SDXL-Turbo, with a few onnx optimizations applied to reduce the number of nodes.
The original model is here: https://huggingface.co/stabilityai/sdxl-turbo/blob/main/unet/model.onnx
Even that doesn't open with Netron.

Please attach or link model files to reproduce the issue.
[model_opt_nogrn.zip](https://github.com/user-attachments/files/15782240/model_opt_nogrn.zip)

**Comment by akj10** [comment]
Hi @lutzroeder , thank you for the quick response on this and fixing the issue. How can we build windows app from the latest sources? I have used only the release version so far.

**Comment by lutzroeder** [comment]
See [CONTRIBUTING.md](https://github.com/lutzroeder/netron/blob/main/CONTRIBUTING.md)

**Comment by akj10** [comment]
This model is also showing blank screen. May be same as https://github.com/lutzroeder/netron/issues/1388
@lutzroeder Do you have an older version that will work?
