### ISSUE TITLE
Display of dimension for variable X at all nodes.

### ISSUE THREAD

**Issue by kartikpodugu** [lutzroeder/Netron#129]
For a particular node, this is the format Netron follows:
--------------------------------
Name of the Node, Inputs
Parameters of the Node
--------------------------------
Example:
------------------------
Conv X W B
strides = 2,2
pads = 1,1,1,1
kernel_shape = 3,3
-------------------------
Relu X
-------------------------
MaxPool X 
strides = 2,2
pads = 1,1,1,1
kernel_shape = 3,3
-------------------------

**When we hover on the Inputs, we come to know the dimensions of the Inputs**. This is very good. 
**But, somehow we get the dimensions of Inputs variable X only for the first node and not any other nodes**. It will be good if we can get the dimensions of X for all intermediate nodes to better understand the flow of data through the topology/network.

**Comment by lutzroeder** [comment]
#71
