### ISSUE TITLE
Core ML: function support

### ISSUE THREAD

**Issue by aseemw** [lutzroeder/netron#1290]
Core ML has added support for storing multifunction models of type `mlprogram` in `iOS18` / `macOS15`. Each function is an independent graph/program, that may point to shared weight blobs.  

Representationally it uses [this proto message](https://github.com/apple/coremltools/blob/001ef34deef644ffa228dfa1434df82122e041dc/mlmodel/format/Model.proto#L204) at the model level to encode multiple functions, and then within the `mlprogram` proto, it uses [block specializations](https://github.com/apple/coremltools/blob/001ef34deef644ffa228dfa1434df82122e041dc/mlmodel/format/MIL.proto#L69) as dictionary from function name to the function / program itself.  

Xcode UI displays the model using a toggle as show below

<img width="946" alt="image" src="https://github.com/lutzroeder/netron/assets/7546478/45626cf0-4fc0-4cbf-b2f4-c9c50b14dc22">

It would be great if Netron could also add a toggle to switch between multiple functions (when more than 1 is present)

Please find attached a sample model that has been generated by the code [here](https://apple.github.io/coremltools/docs-guides/source/multifunction-models.html#combining-models-toy-example-with-lora-adapters).

[combined_adpater_models.mlpackage.zip](https://github.com/user-attachments/files/15793898/combined_adpater_models.mlpackage.zip)

**Comment by lutzroeder** [comment]
**Examples:**
https://github.com/user-attachments/files/15793898/combined_adpater_models.mlpackage.zip

**Comment by lutzroeder** [comment]
@aseemw can you validate the latest changes at TIP?

Questions:

1. Is there an example using functions in the main graph?
2. Would `program.functions.main` be listed in the functions section or is it a special case for `model.description`?
3. Are functions supported in class non-program model?

**Comment by aseemw** [comment]
>  can you validate the latest changes at TIP?

Sure! Where can I find instructions to build Netron from source? 

> Are functions supported in class non-program model?

No, only for mlprograms

> Would `program.functions.main` be listed in the functions section or is it a special case for `model.description`?

In the case of a single main function in `program.functions.main` , it wont be present in the `model.description.functions`.
So only when `model.description.functions` is a non empty list, you would find the corresponding function names as keys in  `program.functions`

> Is there an example using functions in the main graph?
What do you mean by that?

**Comment by lutzroeder** [comment]
> Sure! Where can I find instructions to build Netron from source?

See [CONTRIBUTING.md](https://github.com/lutzroeder/netron/blob/main/CONTRIBUTING.md)

>> Is there an example using functions in the main graph?

> What do you mean by that?

The attached example contains only two functions, not a main function or how a function is invoked from another part of the graph?

**Comment by aseemw** [comment]
> The attached example contains only two functions, not a main function or how a function is invoked from another part of the graph?

Right, when there are more than 1 functions, it's not necessary for the `main` function to be present. 
And right now the functions are independent , there is no way to invoke another function from within a function.

**Comment by aseemw** [comment]
> See [CONTRIBUTING.md](https://github.com/lutzroeder/netron/blob/main/CONTRIBUTING.md)

Got it! 

I tried it. The multifunction support looks good, other than maybe good to call the field "function" instead of "graph"

**Comment by lutzroeder** [comment]
> And right now the functions are independent , there is no way to invoke another function from within a function.

Is there a way to invoke a function from the main graph or are functions only ever invoked from code? For example, a package with functions is more a way to package multiple graphs into a single file, not a way to add structure to model files?

**Comment by lutzroeder** [comment]
> And right now the functions are independent , there is no way to invoke another function from within a function.

Is there a way to invoke a function from the main graph or are functions only ever invoked from code? For example, a package with functions is more a way to package multiple graphs into a single file, not a way to add structure to model files?

**Comment by aseemw** [comment]
> Is there a way to invoke a function from the main graph or are functions only ever invoked from code? For example, a package with functions is more a way to package multiple graphs into a single file, not a way to add structure to model files?

" are functions only ever invoked from code" --> this one

" more a way to package multiple graphs into a single file" --> yes, and so to also allow those multiple graphs to share weights more seamlessly.
