### ISSUE TITLE
Core ML: state input type support

### ISSUE THREAD

**Issue by aseemw** [lutzroeder/netron#1291]
Core ML has added a new type of input in `iOS18` / `macOS15`: a [state type](https://github.com/apple/coremltools/blob/001ef34deef644ffa228dfa1434df82122e041dc/mlmodel/format/FeatureTypes.proto#L210) that can be at the input of the model. 

Here is a sample model attached (generated from example [here](https://apple.github.io/coremltools/docs-guides/source/stateful-models.html#converting-to-a-stateful-core-ml-model)) and how it looks in Xcode UI. 

<img width="929" alt="Xcode_stateful_model_io" src="https://github.com/lutzroeder/netron/assets/7546478/44d0ff9e-b504-4f7c-910c-f01039a9f881">

[accumulator_example_state_model.mlpackage.zip](https://github.com/user-attachments/files/15793987/accumulator_example_state_model.mlpackage.zip)

**Comment by lutzroeder** [comment]
**Example:**
[accumulator_example_state_model.mlpackage.zip](https://github.com/user-attachments/files/15793987/accumulator_example_state_model.mlpackage.zip)
