### ISSUE TITLE
File Export doesn't work on Raspberry Pi 5 

### ISSUE THREAD

**Issue by beru** [lutzroeder/netron#1295]
- Netron app and version: 7.7.2 Desktop app 
- OS and browser version: Ubuntu Desktop 24.04 LTS 

Steps to Reproduce:

1. Open a model file
2. Select File > Export... menu item
3. Select Export button and the dialog automatically closes

On x64 Linux/Windows, file export successfully works but it fails on Raspberry Pi 5 (AArch64 Linux).

I've confirmed that async `showSaveDialog` method works fine on both of x64 Linux and AArch64 Linux.
https://github.com/beru/netron/commit/0e7f90ef700b6fa7e078e73414acb8ba1066e80c

I'm not certain but this can be an issue of Electron.

**Comment by lutzroeder** [comment]
@beru can you help validate the change at TIP, ideally with multiple configurations.
