### ISSUE TITLE
Unknown function 'torch.kl_div'.

### ISSUE THREAD

**Issue by tT0NG** [lutzroeder/netron#1297]
- Netron app and version: 7.7.2-MacOS
- OS and browser version: macOS-14.1

Steps to Reproduce:

1. save a `pth` model with `kl_div`
2. open Netron, load the `pth` model 

<img width="400" alt="Screenshot 2024-06-14 at 1 57 23 PM" src="https://github.com/lutzroeder/netron/assets/10524225/63869fdc-89bf-4707-b459-88a1b755bcd0">

**Comment by lutzroeder** [comment]
@tT0NG please share a file file to reproduce the issue.
