### ISSUE TITLE
Irregular line thickness of edge lines found

### ISSUE THREAD

**Issue by beru** [lutzroeder/netron#1300]
- Netron app and version: 
- OS and browser version: 

Version 7.7.3 Desktop app  
OS : Windows 10

Steps to Reproduce:

1. Open `EfficientDet-d0.onnx` file archived in [EfficientDet-d0.onnx.zip](https://github.com/lutzroeder/netron/files/7786937/EfficientDet-d0.onnx.zip)
2. Find a node named `Unsqueeze_8463` and check the shape of an input edge named `9650`.
3. Another case: find a node named `BatchNormalization_7562` and check the shape of an output edge named `8722`.

<details>

![image](https://github.com/lutzroeder/netron/assets/1131125/38803835-58a1-47f2-9d83-6d8d40fbcbb6)

![image](https://github.com/lutzroeder/netron/assets/1131125/c09f6f88-507d-48e8-a450-98a63a46b4e9)

![image](https://github.com/lutzroeder/netron/assets/1131125/76a7e383-968d-4308-90b3-70fac1b709db)

</details>

Please attach or link model files to reproduce the issue.

- [EfficientDet-d0.onnx.zip](https://github.com/lutzroeder/netron/files/7786937/EfficientDet-d0.onnx.zip)

**Comment by lutzroeder** [comment]
@beru can you investigate and submit a fix.

**Comment by beru** [comment]
I've confirmed that this doesn't reproduce on Linux (Ubuntu 24.04 LTS).  

svg : [EfficientDet-d0.zip](https://github.com/user-attachments/files/15870989/EfficientDet-d0.zip)

**Comment by seanshpark** [comment]
Mine: Windows 10, Netron 7.7.3
- cannot reproduce
- ![image](https://github.com/lutzroeder/netron/assets/4616940/81356639-7b31-4909-a844-898edbc428a5)

**Comment by beru** [comment]
@seanshpark

I've noticed that the problem doesn't reproduce when Attributes/Weights/Names are shown on Windows 10. I'll check if it's the same on Linux.
