### ISSUE TITLE
Best-effort reading of PyTorch save files with arbitrary pickles

### ISSUE THREAD

**Issue by ntw-au** [lutzroeder/netron#1302]
Netron does not read all PyTorch save files if they include pickles of arbitrary non-PyTorch objects, and instead shows the error `File does not contain root module or state dictionary`. I suggest a change so that unreadable pickled data is treated as opaque and is replaced by a `Pickled object` placeholder string, rather than showing an error or hiding the presence of the data. Note that the pickled data may be for a type that Netron does not have type information for, particularly for custom objects like those that have come from a conda/pip dependency or an extension module.

This issue is part-way between a bug report (due to the error message) and a feature request (due to it extending existing functionality).

Script to Reproduce:

```python
import torch
import numpy as np

# Works
torch.save((torch.arange(100),), '1-tensor-in-tuple.pt')
torch.save((torch.arange(100), torch.tensor(10)), '2-tensors-in-tuple.pt')
torch.save({'a': torch.arange(100), 'b': torch.tensor(10)}, '3-tensors-in-dict.pt')

# Silently hidden, file opens but presence of non-tensor data is not acknowledged in Netron
# (Netron seems to handle arbitrary pickles better when they are in dictionaries, not tuples.)
torch.save({'a': torch.arange(100), 'b': 10}, '4-tensor-and-int-in-dict.pt')
torch.save({'a': torch.arange(100), 'b': 'hello'}, '5-tensor-and-string-in-dict.pt')  # Standard library pickled object

# Fails to open, "File does not contain root module or state dictionary"
torch.save((torch.arange(100), np.arange(100)), '6-tensor-and-array-in-tuple.pt')  # Non-standard-library pickled object
torch.save((torch.arange(100), [1,2,3,4,5,6], 234, "Hello"), '7-tensor-and-python-pickles-in-tuple.pt')  # Standard library pickled objects
torch.save((torch.arange(100), 234), '8-tensor-and-integer-in-tuple.pt')
torch.save((torch.arange(100), [456,789]), '9-tensor-and-list-in-tuple.pt')
torch.save({'a': torch.arange(100), 'b': np.arange(100)}, '10-tensor-and-array-in-dict.pt')  # Non-standard-library pickled object
torch.save({'a': torch.arange(100), 'b': [1, 2, 3, 4, 5, 6]}, '11-tensor-and-int-list-in-dict.pt')
```

Related: #543, #908

Environment:
- Netron app and version: 7.7.3 Desktop
- OS and browser version: Windows 11 Enterprise 23H2 (22631.3447)

**Comment by lutzroeder** [comment]
@ntw-au can you please submit a pull request addressing these issues in the codebase.

**Comment by lutzroeder** [comment]
Duplicate of #543
