### ISSUE TITLE
Parent sidebar should reselect item when child sidebar is closed

### ISSUE THREAD

**Issue by kylesayrs** [lutzroeder/netron#1306]
Steps to Reproduce:

1. Click on a node
2. Click on a tensor or connection
3. Close the tensor or connection sidebar
4. The node is not reselected on the graph in the same way you'd expect if you clicked on a node through a connection sidebar

**Comment by lutzroeder** [comment]
@kylesayrs can you submit pull requests to address these issues.

#1298
