### ISSUE TITLE
Add functionality for hdf5 files

### ISSUE THREAD

**Issue by frankenstein91** [lutzroeder/Netron#132]
could you please add a function for the files with the hdf5 extension?
These are used, for example, by the following project.
https://github.com/minimaxir/tweet-generator/blob/master/realDonaldTrump_dril_twitter_weights.hdf5

thank you very much

**Comment by lutzroeder** [comment]
Added `.hdf5` file extension. Note the file only contains weights and no model info. See #73.

**Comment by frankenstein91** [comment]
For the reference https://github.com/minimaxir/tweet-generator/issues/3
