### ISSUE TITLE
Color for custom onnx node

### ISSUE THREAD

**Issue by Gxiandy** [lutzroeder/netron#1321]
Hi,
Thanks for you work!
I came across a closed issue (https://github.com/lutzroeder/netron/issues/1046) that required custom node coloring in onnx visualization. I believe this functionality can be implemented as follows:

1.  Add a color attribute which contains the rgb color when create onnx node
`node.attribute.append(onnx.helper.make_attribute("color", "ffffff"))`
2.  Modify the view.js,  insert a new css rule to the grapher.css when add a node with `color` attribute
![image](https://github.com/user-attachments/assets/ef1f3359-cd83-46a2-9255-825d00bed478)

This patch is very hack, if you have any other good ideas, please let me know and i will be happy to help you finish this feature.

**Comment by lutzroeder** [comment]
@Gxiandy can you explain the scenario this is needed for and how it would be used.

- Encoding specific colors in model files is not ideal as users might have different desktop themes (dark mode, light mode).
- Attributes are strictly defined per operator and should not be extended. Some formats have other options to add metadata. For example, ONNX supports `metadata_props`. However, ideally such a mechanism should not be hardcoded for a single format.

**Comment by Gxiandy** [comment]
Here are a few application scenarios I can think of：
1. Onnx diff. Highlighting the different node between 2 onnx model files  can help developer to find the difference between 2 similar onnx model.
2. In a compiler pipeline, compiler will do different optimation on a model, we can highlight the node which are deleted/modified/newly added by a optimation pass to help developer understand what  this optimation pass does. (This is our need.)

I agree that use `metadata_props` is a better way to store `color`, and I think encode specific color in a node provides users with more flexibility, users must be responsible for their visual experience when they use this feature (set colors that fit their desktop theme).
