### ISSUE TITLE
Jupyter IFrame support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#1324]
```python
import netron
address = netron.serve('test.onnx')
netron.widget(address, height=800)
```

See #1346

**Comment by mattcattb** [comment]
Has this been implimented?

**Comment by vtemplier** [comment]
it seems to be working now.

![image](https://github.com/user-attachments/assets/1dde4130-2982-49b1-ac81-5acda4389dd4)

I leave it to @lutzroeder to close this issue, if it is solved correctly.

PS: Don't forget to add `browse=false` to avoid opening another window to view your model.
