### ISSUE TITLE
Outdated snap package 

### ISSUE THREAD

**Issue by DaniAffCH** [lutzroeder/netron#1326]
- Netron app and version: netron 7.4.9
- OS and browser version: Ubuntu 22.04

Steps to Reproduce:

1. Install Netron via Snap by running `sudo snap install netron`.
2. Launch Netron from the command line using `netron`.
3. Observe that the application launches with the same update prompt as described in issue #1164.

**Comment by lutzroeder** [comment]
electron-userland/electron-builder#7908 @Rychu-Pawel @mmaietta

**Comment by lutzroeder** [comment]
Duplicate of electron-userland/electron-builder#8423
