### ISSUE TITLE
Unknown function 'ops.prim.requires_grad'.

### ISSUE THREAD

**Issue by WorldPeace123** [lutzroeder/netron#1328]
- Netron app and version: <winget install -s winget netron>
- OS and browser version: <win11>

Steps to Reproduce:

1.the netron cant look the model(use pytorch , save as scriptmodle),and report the bug of "Unknown function 'ops.prim.requires_grad'.",I dont know how to do.(i find the keywords"ops.prim.requires_grad."in pytorch code and my softwar but cantf find the key words).what can i do that can get the model input shape?thanks !
![微信截图_20240821172741](https://github.com/user-attachments/assets/4d15074e-bb16-42a6-89df-376db7640059)

**Comment by lutzroeder** [comment]
@WorldPeace123 can you share a model file to reproduce the issue.

**Comment by WorldPeace123** [comment]
the file is too big ,can you give me a email,that i send to you ?

**Comment by WorldPeace123** [comment]
@lutzroeder  Hello my friend?the file is too big ,can you give me a email,that i send to you ?

**Comment by lutzroeder** [comment]
Can you share it with Dropbox or Google Drive or create a smaller file that produces the same issue.
