### ISSUE TITLE
PyTorch support

### ISSUE THREAD

**Issue by dmoham1476** [lutzroeder/netron#133]
Is there a plan to enable viewing pytorch models (mode.pt) with Netron?

**Comment by lutzroeder** [comment]
Can you share the `mode.pt` file?

**Comment by dmoham1476** [comment]
I downloaded it from the fair page - curl https://s3.amazonaws.com/fairseq-py/models/wmt14.v2.en-fr.fconv-py.tar.bz2 | tar xvjf -

**Comment by happyhusky** [comment]
Pytorch model can be exported to onnx file.

**Comment by dmoham1476** [comment]
thank you!

**Comment by Blusea** [comment]
some pytorch modules like pack_padded_sequence function does not be supported to export  onnx.

**Comment by zhouyuangan** [comment]
It raised an error that "Error loading PyTorch model  Root object does not contain modules" when I tried to open this [model.pth](https://download.pytorch.org/models/densenet121-a639ec97.pth) file using netron on my windows 10 machine, and my pytorch version is 0.4.1, is there anybody met this problem?

**Comment by zhouyuangan** [comment]
> @zhouyuangan The file does not contain any model graph, only serialized tensors. You need to serialize the entire model using `torch.save(model, 'model.pth`)`.
> 
> ```
> import torch
> from torchvision.models import densenet121
> model = densenet121(True)
> torch.save(model, 'densenet121.pth')
> ```
> The relationship between some modules in `pth` only exists in code so PyTorch support is only experimental and there will be limitations. The recommended approach is to save the model to [ONNX](https://pytorch.org/docs/stable/onnx.html).

Yes, it works. Thanks

**Comment by lutzroeder** [comment]
`.pth` files generated from https://github.com/yunjey/pytorch-tutorial.

[tutorial_models.zip](https://github.com/lutzroeder/netron/files/2587823/tutorial_models.zip)

**Comment by lutzroeder** [comment]
[pytorch_invalid_file.zip](https://github.com/lutzroeder/netron/files/3269093/pytorch_invalid_file.zip)

**Comment by abhigoku10** [comment]
@lutzroeder  the tutorial_models i am able to see the connections of the modules but y not in custom trained models ? should we follow some steps to do that

**Comment by lutzroeder** [comment]
Saving the `state_dict` only saves the tensors. Serializing to ONNX will save the graph. https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html

**Comment by lutzroeder** [comment]
[valid-bert-base-uncased.zip](https://github.com/lutzroeder/netron/files/4977150/valid-bert-base-uncased.zip)

**Comment by lutzroeder** [comment]
[alexnet.pkl.pth.zip](https://github.com/lutzroeder/netron/files/5213453/alexnet.pkl.pth.zip)
[inception_v3.pkl.pth.zip](https://github.com/lutzroeder/netron/files/5213454/inception_v3.pkl.pth.zip)
[resnet101.pkl.pth.zip](https://github.com/lutzroeder/netron/files/5213455/resnet101.pkl.pth.zip)
[squeezenet1_1.pkl.pth.zip](https://github.com/lutzroeder/netron/files/5213456/squeezenet1_1.pkl.pth.zip)

**Comment by lutzroeder** [comment]
[ENet.pth.zip](https://github.com/lutzroeder/netron/files/5368544/ENet.pth.zip)

**Comment by abitrolly** [comment]
Maybe document this properly explaining why this happens? I guess because links are left in the Python code that configures the model and is used for inference.

**Comment by lutzroeder** [comment]
PyTorch and TorchScript support multiple serialization formats. Based on which format is used `.pth` file might only contain tensor data or an incomplete model hierarchy without graph connections. [Saving and Loading Models](https://pytorch.org/tutorials/beginner/saving_loading_models.html) for mode context.

The recommended approach is to save the model to [ONNX](https://pytorch.org/docs/stable/onnx.html).

PyTorch support is experimental and there will be limitations.

**Comment by lutzroeder** [comment]
Duplicate of #720.
