### ISSUE TITLE
ONNX metadata_props display at 

### ISSUE THREAD

**Issue by elfman2** [lutzroeder/netron#1331]
The ONNX IR v10 specifies **metadata_props** field at several levels
refs:
https://github.com/onnx/onnx/blob/main/onnx/onnx.proto
https://github.com/onnx/onnx/blob/main/docs/IR.md

Netron is able to display them at Model level (ModelProto.metadata_props) and at Node level (NodeProto.metadata_props), **but not at:**

- Tensor initializers (TensorProto.metadata_props)
- model input (ValueInfoProto.metadata_props)
- model output (ValueInfoProto.metadata_props) 
- intermediate Tensor (ValueInfoProto.metadata_props)
- local Functions (FunctionProto.metadata_props)
- Graph (GraphProto.metadata_props)

**New feature proposal:** display metadata_props values at all levels when available

**Comment by lutzroeder** [comment]
@elfman2 can you share sample files illustrating how these fields are used.
