### ISSUE TITLE
Invalid file content. File contains optimization_guide.proto.PageTopicsOverrideList data.

### ISSUE THREAD

**Issue by lix19937** [lutzroeder/netron#1332]
when use netron open a proto bin file, it raise  
```
Invalid file content. File contains optimization_guide.proto.PageTopicsOverrideList data.
```

**Comment by lutzroeder** [comment]
@lix19937 there are many different proto formats. Is the file not `PageTopicsOverrideList` data (can you share the file) or do you expect something else to happen?
