### ISSUE TITLE
Restore scroll position and zoom when going back from function

### ISSUE THREAD

**Issue by beru** [lutzroeder/netron#1334]
Current version of Netron (as of now 7.8.5) doesn't restore graph scroll position and zoom level when going back from Function Definition. This resetting behavior can be a source of interruption to users.
![before](https://github.com/user-attachments/assets/ac2d65e8-64df-499f-927c-7c460020f5e8)

Restoring scroll position (and possibly zoom level too) might improve user experience a little. [link to adhoc change](https://github.com/beru/netron/commit/2c5afa4cb622dbc5d7a58a0181e0d78edc5836f8)
![after](https://github.com/user-attachments/assets/666d6596-7ce0-401d-a30a-1b50df2108af)

However, it doesn't work well when window size is shrinked. So a different workaround might be needed.
![after2](https://github.com/user-attachments/assets/487f2817-f253-46e8-adb9-274a22ae2662)

**Comment by lutzroeder** [comment]
@beru can you help address these issues and submit a pull request?
