### ISSUE TITLE
Error loading Caffe model. 

### ISSUE THREAD

**Issue by leexp0304** [lutzroeder/Netron#134]
hello, when I  loaded my caffemodel in the websites , It was show a message that ----->>>Error loading Caffe model. Protocol Buffer loader failed to decode caffe.NetParameter input stream (invalid wire type 6 at offset 7327617)

**Comment by lutzroeder** [comment]
The error usually indicates that the file is corrupt and not a valid protobuf. Can you share the model file and are you able to run it in Caffe?
