### ISSUE TITLE
New automatic scroll to selected node is disorienting

### ISSUE THREAD

**Issue by fdwr** [lutzroeder/netron#1352]
- **Netron app and version**: 7.8.6 Desktop app
- **OS and browser version**: Win11 23H2 22631.4169, Edge 128.0.2739.67

## Steps to Reproduce:

1. Open a graph.
2. Click on a node to see its properties.
3. Notice the whole graph now shifts around, and the node you just clicked on is several nodes away now. This is pretty jarring and a little confusing, especially when you have parts of the graph that repeat and look similar to each other. I don't remember it doing this before?? 😵‍💫 Is there a hidden option to disable this or a way to use a previous version? 🥲

> Please attach or link model files to reproduce the issue.

Any.

**Comment by fdwr** [comment]
It might be a collateral side effect of attempting to address this issue: https://github.com/lutzroeder/netron/issues/1344

**Comment by beru** [comment]
@fdwr When a node is selected, the app scrolls the selected node to the center of the graph view ([link](https://github.com/lutzroeder/netron/blob/0d9daa1be341723f4bef53ffe22b0511b3b81cf6/source/view.js#L589-L607)) and I personally think it's [a little excessive](https://youtu.be/M2QQg3LonfI?t=11). By updating the code like this [link](https://github.com/beru/netron/commit/b41eea6e54f883e584946e06aafd123fb749b119), the scrolling occurs less often but it might be less exciting to scrolling addicts.

**Comment by lutzroeder** [comment]
@beru can you create a pull request, ideally addressing the scrollbar issue.
@fdwr can you help test and review if the suggested change addresses the issue.

**Comment by beru** [comment]
@lutzroeder `element.clientWidth` doesn't include width of scrollbar so I'm thinking to use this.
https://stackoverflow.com/a/40568748

Currently, the app scrolls a selected node to the center of the graph view. With the change I'm about to introduce with a new PR, the scrolling will not occur when a whole rectanngle area of selected node is in the container client area. I'm not really sure if this change of behaviour is acceptable but I'll open a PR anyways.

**Comment by fdwr** [comment]
> @fdwr can you help test and review if the suggested change addresses the issue.

Sure, how? I just loaded ResNet into https://netron.app/, and the graph still shifts around on click 🤔. Might I need to explicitly refresh my browser cache?

**Comment by beru** [comment]
@fdwr the change for automatic scroll (f1ecfef71014cd4e100b1d4c273f966f1c724852) has landend to `main` branch very recently so it's not released yet. given that Lutz has released new versions weekly, next version (Version 7.8.9) would be released on 21/09/2024.

The istructions to test developmenet code are written in https://github.com/lutzroeder/netron/blob/main/CONTRIBUTING.md#debugging You may still experience sudden scrolls with the updated code, though I hope they are reduced.
