### ISSUE TITLE
Repeatedly opening and closing Find sidebar makes app screen broken

### ISSUE THREAD

**Issue by beru** [lutzroeder/netron#1358]
- Netron app and version: 7.8.8, Desktop App and Chromium based browser
- OS and browser version: Windows 10 22H2, Ubuntu 24.04.1 LTS, Microsoft Edge 128.0.2739.79

Steps to Reproduce:

1. Open [efficientdet-d3.onnx](https://github.com/phantrdat/onnx-efficientdet/blob/5efe7b1eb45d69f7ca4eef1022540aa8a2024ae8/efficientdet-d3.onnx) file.
2. Open the FIND sidebar.
3. Close the sidebar
4. Repeat open/close until the problem occurs.

Please attach or link model files to reproduce the issue.

- [efficientdet-d3.onnx](https://github.com/phantrdat/onnx-efficientdet/blob/5efe7b1eb45d69f7ca4eef1022540aa8a2024ae8/efficientdet-d3.onnx)

**Comment by lutzroeder** [comment]
@beru can you investigate why this is happening.

**Comment by beru** [comment]
@lutzroeder 

> can you investigate why this is happening.

Chromium based browsers shows `Error code: Out of Memory` though my PC has 64.0 GB of installed RAM. This problem happens on both of Windows and Linux.

<details><summary>screenshots</summary>

## Google Chrome Version 128.0.6613.138 (Official Build) (64-bit)
![image](https://github.com/user-attachments/assets/19683283-538a-4c3c-aa7c-0f855a70e089)

## Microsoft Edge Version 128.0.2739.79 (Official build) (64-bit)
![image](https://github.com/user-attachments/assets/ee076aa5-fbbb-4bcb-ad52-75e7a9e4b13e)

</details>

**Comment by lutzroeder** [comment]
@beru any insights why it is out of memory? Are there any structures not getting disposed?

**Comment by beru** [comment]
> any insights why this is happening? Are there any structures not getting disposed?

I'm not sure since I still haven't debugged Chromium for this. I suspect this is a memory leak defect.

**Comment by beru** [comment]
I've noticed that even without using a lot of `<svg>` elements in FIND sidebar, this problem eventually occurs after repeatedly open/close the sidebar.

<details><summary>screenshot</summary>

![image](https://github.com/user-attachments/assets/06aee036-157a-4ae1-b478-8981ad56a5f8)

<details>
