### ISSUE TITLE
Older versions keep disappearing from official PyPI project

### ISSUE THREAD

**Issue by futurwasfree** [lutzroeder/netron#1365]
Just few days ago I've bumped netron version used in my projeft to 7.8.8 since older one was no longer available.
Today I've had to do the same since 7.8.8 went missing. Looks like there are only 3 versions available?
https://pypi.org/project/netron/#history
This makes it very hard to use the library in environments with locked dependencies. 
Expectation here is to have version history available for longer time.

**Comment by lutzroeder** [comment]
7.8.8 was deleted accidentally when migrating to `pyproject.toml`.

However, the goal is for users to update to more recent versions. See #604.
