### ISSUE TITLE
PyPI version management

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#1366]
This issue serves as a place to gather feedback on PyPI version management.

Please consider the following two perspectives:

1. The aim is to improve the latest version while reducing long-term migration challenges. Instead of transfering this "burden" to others, please describe how you plan to contribute toward achieving this goal.

2. Provide details about your specific use case. For instance, explain why a specific version is required instead of the latest one. What version is not available. What obstacles are preventing you from using alternatives, such as the browser version or enterprise package solutions.

**Comment by brandonschabell** [comment]
@lutzroeder I still don't understand why you insist on deleting releases from Pypi. This is a horrible practice that breaks developer workflows. It's nearly universally agreed that version pinning is a best practice, and your process of deleting Pypi releases prevents many developers from using this package in a pinned environment. Further, vulnerability detection is much more difficult to perform when old releases are deleted. I fail to see any benefit of deleting releases.
