### ISSUE TITLE
Graph mistake for keras

### ISSUE THREAD

**Issue by amyburden** [lutzroeder/Netron#138]
Hi, thank you so much for your brilliant work to visualize the network. It helps a lot. I am testing some model with multiple inputs, multiple outputs, model as a layer, and the shared layer for Keras model. The tool works for most of the cases. And I find a corner case for this tool where the connection for Add layer which takes input and conv2d as input is not connected correctly. Plz check the model https://drive.google.com/open?id=1L3-NuE4EXSUKsYCtYON2cO-L0br0U6mn.

**Comment by lutzroeder** [comment]
Is this a similar issue to #130? Can you send a drawing what the model is expected to look like and verify that this model actually saves and loads correctly in Keras?

**Comment by amyburden** [comment]
https://drive.google.com/file/d/1eZlbTIq1QGgi9Wp7WViW0L-s_o9JP1n8/view?usp=drivesdk
It should be shared layer problem.

**Comment by lutzroeder** [comment]
[mimo.h5.zip](https://github.com/lutzroeder/netron/files/2565761/mimo.h5.zip)
[mimo.json.zip](https://github.com/lutzroeder/netron/files/2565762/mimo.json.zip)
![mimo](https://user-images.githubusercontent.com/438516/48261956-a32d6300-e3d5-11e8-8162-bd287940262d.jpg)
![mimo](https://user-images.githubusercontent.com/438516/48261963-aa547100-e3d5-11e8-9818-39c693e2a784.png)
