### ISSUE TITLE
google flan-t5-small gguf support

### ISSUE THREAD

**Issue by tensorbuffer** [lutzroeder/netron#1382]
- Netron app and version: 
- OS and browser version: 

Steps to Reproduce:

Tried to open this model in webbrowser and it says Unsupported GGUF type '0'.

Please attach or link model files to reproduce the issue.
The model is big (75M), not sure where to attach to.

**Comment by lutzroeder** [comment]
@tensorbuffer how was the file created or where did it originate?

**Comment by tensorbuffer** [comment]
download huggingface model from https://huggingface.co/google/flan-t5-small/tree/main
Then use llama.cpp's conversion python script to convert to gguf
