### ISSUE TITLE
PaddlePaddle IR support

### ISSUE THREAD

**Issue by wanghuancoder** [lutzroeder/netron#1384]
Hello, lutzroeder! I'm a Contributor of PaddlePaddle. PaddlePaddle has designed and developed a new version of IR, so the Saved model and tensor file's formats have also changed. The new files use the Json format. We would like to ask for your help to make Netron support the new version of Paddle's IR. Thank you very much! The design document of the new version of Save/Load is at: https://github.com/PaddlePaddle/community/blob/master/pfcc/paddle-code-reading/IR_Dialect/pir_save_load.md. Some of the key used when saving Json definitions are at: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/pir/serialize_deserialize/include/schema.h. 
Here are some typical model files:
[while_net.json](https://github.com/user-attachments/files/17505487/while_net.json)
[model.json](https://github.com/user-attachments/files/17505488/model.json)
[model_pylayer.json](https://github.com/user-attachments/files/17505489/model_pylayer.json)
[if_net.json](https://github.com/user-attachments/files/17505490/if_net.json)
[for_net.json](https://github.com/user-attachments/files/17505491/for_net.json)

**Comment by wanghuancoder** [comment]
> @wanghuancoder can you please create a pull request implementing the feature using this issue for tracking and questions.

like this? https://github.com/lutzroeder/netron/pull/1386

**Comment by lutzroeder** [comment]
@wanghuancoder a pull request is used to discuss the code change once you implemented it.

**Comment by wanghuancoder** [comment]
> @wanghuancoder a pull request is used to discuss the code change once you implemented it.
Did you mean to let me implement this new feature for netron? But I don't understand the design of netron and JavaScript. Can you provide some documents to introduce the design of netron and how to build the environment for debugging?

**Comment by lutzroeder** [comment]
[CONTRIBUTING.md](https://github.com/lutzroeder/netron/blob/main/CONTRIBUTING.md) and [python.js](https://github.com/lutzroeder/netron/blob/9bd15c515b1a98408fc3aec367bd93bdad972ed2/source/paddle.js#L80) contains a placeholder when these files are detected.

**Comment by wanghuancoder** [comment]
Can I let js call Python to load and parse the model file, then build a Graph containing Node and Eage information and return it to js?

**Comment by lutzroeder** [comment]
This is not possible as Python would not be available in a browser environment.

**Comment by wanghuancoder** [comment]
Can JS call the Python logic on the Service side? For example, what are the following two files used for?
https://github.com/lutzroeder/netron/blob/main/source/onnx.py
https://github.com/lutzroeder/netron/blob/main/source/pytorch.py

**Comment by lutzroeder** [comment]
A server will not always be available or have the correct libraries installed. For example, when running in the browser there is no server.

**Comment by wanghuancoder** [comment]
OK, thank you very much! I don't know JavaScript, I will recruit a volunteer to implement this new feature under the name of Paddle. I will ask you for advice then.

**Comment by lutzroeder** [comment]
Duplicate of #1407
