### ISSUE TITLE
ONNX: delay load external weights

### ISSUE THREAD

**Issue by seanshpark** [lutzroeder/netron#1387]
We have huge Transformer models to develop that having several GiB,
but current Netron loads for several minutes or somethings doesn't respond.

It would be great if we could have some options to skip loading huge weights parameters.

I've tested with an ONNX model having weights in external files,
total 4G with more than about 600 files, and with below changes, 
got loading time about 15 seconds compared to release version having about 60 seconds.

I would like to know about;
- can this feature be useful?
- how to define options for skip loading weights
- how to pass the flag to the actual model loading codes

one step further, we can provide delayed (or on-demand) weight loading.

---

```diff
diff --git a/source/onnx.js b/source/onnx.js
index a6adac9a..0e91398a 100644
--- a/source/onnx.js
+++ b/source/onnx.js
@@ -3,6 +3,8 @@ import * as protobuf from './protobuf.js';

 const onnx = {};

+onnx.skip_external = process.env.NETRON_SKIP_EXTERNAL;
+
 onnx.ModelFactory = class {

     match(context) {
@@ -1657,9 +1659,11 @@ onnx.ProtoReader = class {
                 location(tensor.indices);
                 location(tensor.indices);
             } else if (tensor.data_location === onnx.DataLocation.EXTERNAL && Array.isArray(tensor.external_data)) {
-                for (const entry of tensor.external_data) {
-                    if (entry.key === 'location') {
-                        locations.add(entry.value);
+                if (! onnx.skip_external) {
+                    for (const entry of tensor.external_data) {
+                        if (entry.key === 'location') {
+                            locations.add(entry.value);
+                        }
                     }
                 }
             }
```

**Comment by lutzroeder** [comment]
@seanshpark how are you loading the file, e.g. can you provide sample steps how you open the app and open the model.

**Comment by seanshpark** [comment]
> how are you loading the file

with release Windows App,
- run the program by clicking the Netron icon (I used pinned one on the task bar)
- ![image](https://github.com/user-attachments/assets/04640900-d05f-4cea-8ac9-07a8a99f19cd)
- click `Open Model...` button
- select huge ONNX model (ONNX itself is several hundred MB but has lots of separate weight files)
- wait till graph shows up

with modified Windows App
- I've used my local built exe file
- Run in Windows `Command Prompt`, as I need to provide environment variable
- ![image](https://github.com/user-attachments/assets/2f519f3e-c319-4b14-b03d-5e13a7dfd292)
- click `Open Model...` button, and afterwards, same as above

**Comment by seanshpark** [comment]
I've posted  #1388 and thought that if we could skip loading weight parameters, not only external ones, we might see at least the graph.

I think adding this feature to Netron for all types of models may take time,
but I would like to try with ONNX first.

**Comment by lutzroeder** [comment]
@seanshpark the right solution seems to delay loading the weights until `Tensor.values` is called? Those APIs would need to be converted to a `async` proxy so the UX can be delayed until the user opens a view that requires tensor data. For example, tensor metrics would not get auto-computed if a large external file needs to be loaded. Download or load progress would need to be tracked via the proxy. Can you have a look and submit a pull request?

**Comment by seanshpark** [comment]
> the right solution seems to delay loading the weights until Tensor.values is called?

Yes, I think so :)

> Can you have a look and submit a pull request?

I'll try... may take some time :) (not that good at JS async stuff...)

**Comment by lutzroeder** [comment]
**Example:**
https://netron.app#https://huggingface.co/Esperanto/whisper-medium-kvc-fp16-onnx/resolve/main/decoder/model.onnx

**Comment by lutzroeder** [comment]
@seanshpark can you help validate the [change](https://github.com/lutzroeder/netron/commit/e53cff193072e913c0b241ff7d419017ac805645) in main.

**Comment by lutzroeder** [comment]
@seanshpark can you help validate the changes in [main](https://github.com/lutzroeder/netron).

**Comment by lutzroeder** [comment]
@seanshpark can you help validate the changes in [main](https://github.com/lutzroeder/netron).

**Comment by seanshpark** [comment]
@lutzroeder , I'v check with latest release 8.0.2.
My test model loading time was decreased to about 20 seconds (which was more than a minute)!

But as in capture image, loading weights seems to have problem.
![image](https://github.com/user-attachments/assets/58898a1e-4708-442f-928f-f114daacb93e)

Anyway, loading the ONNX model itself is now fast! Thanks again!

**Comment by lutzroeder** [comment]
> But as in capture image, loading weights seems to have problem.

@seanshpark can you investigate why it does not render the value and provide a repro.

**Comment by seanshpark** [comment]
> can you investigate why it does not render the value and provide a repro.

I'll try :)

**Comment by seanshpark** [comment]
delay of loading weight file looks OK.

when press `+` key of weight of a `Conv` Op,
- `tensor.empty` is always true
- `tensor.toString();` fails with `peek` ? or somewhere else...

```diff
diff --git a/source/view.js b/source/view.js
index ea04980b..abdead49 100644
--- a/source/view.js
+++ b/source/view.js
@@ -3279,11 +3279,17 @@ view.TensorView = class extends view.Expander {
             content.innerHTML = '&#x23F3';
             const promise = value.peek && !value.peek() ? value.read() : Promise.resolve();
             promise.then(() => {
-                if (tensor.empty) {
-                    content.innerHTML = 'Tensor data is empty.';
-                } else {
+                console.log(`!!! content then !!!`);
+                console.log(`!!! content then ${tensor.empty}`);
+                console.log(`!!! content then value ${value.type.shape}`);
+                //if (tensor.empty) {
+                //    content.innerHTML = 'Tensor data is empty.';
+                //} else
+                {
                     content.innerHTML = tensor.toString();
+                    console.log(`!!! content then innerHTML ${content.innerHTML}`);
                     if (this._host.save && value.type.shape && value.type.shape.dimensions && value.type.shape.dimensions.length > 0) {
+                        console.log(`!!! content then value ok`);
                         this._saveButton = this.createElement('div', 'sidebar-item-value-button');
                         this._saveButton.classList.add('sidebar-item-value-button-context');
                         this._saveButton.setAttribute('style', 'float: right;');
@@ -3292,8 +3298,10 @@ view.TensorView = class extends view.Expander {
                             await this.export();
                         });
                         content.insertBefore(this._saveButton, content.firstChild);
+                        return;
                     }
                 }
+                content.innerHTML = 'Tensor data is empty.';
             });
         }
         return content;
```
got
```
[24232:1118/123311.095:INFO:CONSOLE(3282)] "!!! content then !!!", source: file:///D:/win-unpacked/resources/app.asar/source/view.js (3282)
[24232:1118/123311.095:INFO:CONSOLE(3283)] "!!! content then true", source: file:///D:/win-unpacked/resources/app.asar/source/view.js (3283)
[24232:1118/123311.097:INFO:CONSOLE(3284)] "!!! content then value [320,4,3,3]", source: file:///D:/win-unpacked/resources/app.asar/source/view.js (3284)
[24232:1118/123311.197:INFO:CONSOLE(751)] "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'peek')", source: file:///D:/win-unpacked/resources/app.asar/source/base.js (751)
```

**Comment by seanshpark** [comment]
I had a log line in `onnx.Tensor.read()` like
```js
    async read() {
        if (this._request) {
            const location = this._request.location;
            const offset = this._request.offset;
            const length = this._request.length;
            console.log(`!!! read _request exist ${offset}, ${length}`);
            this._data = await location.read(offset, length);
            delete this._request;
        }
    }
```
but this `!!! read _request exist` didn't show up.

added this
```js
console.log(`!!! peek? ` + Object.getOwnPropertyNames(value));
```
in `view.js` `get content()` and got 
```
"!!! peek? _category,_name,_type,_location"
```
there was no `peek`.

**Comment by seanshpark** [comment]
looks like `value.peek && !value.peek()` returns false.

cause `this._request = ...` wasn't executed,
cause `external_data.offset` and `external_data.length` are `undefined`

**Comment by seanshpark** [comment]
in `case onnx.DataLocation.EXTERNAL:` block,
one of the `tensor` JSON dump look like this

> {"dims":["2560","640"],"float_data":[],"int32_data":[],"string_data":[],"int64_data":[],"external_data":[{"key":"location","value":"onnx__MatMul_9599"}],"double_data":[],"uint64_data":[],"metadata_props":[],"data_type":1,"name":"onnx::MatMul_9599","data_location":1}

**Comment by seanshpark** [comment]
@lutzroeder , onnx delayed weight loading works perfectly and also normal models too :)
