### ISSUE TITLE
PyTorch: SymBool is not a constructor

### ISSUE THREAD

**Issue by sd-amzn** [lutzroeder/netron#1393]
- Netron app and version: 7.9.9 Desktop App 
- OS and browser version: MAC OSX

Steps to Reproduce:

1. Export a model that uses the `SymBool` type https://github.com/pytorch/pytorch/blame/main/torch/_export/serde/schema.py#L82 
2. We get the error that `torch._export.serde.schema.SymBool is not a constructor`

Please attach or link model files to reproduce the issue.

Unfortunately I am not able to attach the model with this issue, but hopefully the torch source link is useful.

**Comment by lutzroeder** [comment]
@sd-amzn can you please create and and share a minimal repro or help validate the change in main.
