### ISSUE TITLE
OpenVINO: Constant display error

### ISSUE THREAD

**Issue by ylei1** [lutzroeder/netron#1394]
- Netron app and version: netron-7.9.9

Steps to Reproduce:

1. netron model.xml --host 0.0.0.0 --port 8081

![image](https://github.com/user-attachments/assets/8e1821ac-38a0-4a9a-a0fc-0031df005883)

**Comment by lutzroeder** [comment]
@ylei1 please share a file to reproduce the issue, explain what the issue is and work with the OpenVINO team to submit a fix.

**Comment by ylei1** [comment]
[single-small-fq.zip](https://github.com/user-attachments/files/17671834/single-small-fq.zip)

Here is a single block that I used for testing, as you can see, the netron parsed -1.847991704940796 to 0.23774106800556183 wrongly. Couldyou give me some advice why this error occurs?
![image](https://github.com/user-attachments/assets/40dc4b09-df71-4e5c-8bfd-b940ffb5a114)
![image](https://github.com/user-attachments/assets/38e14fb9-d34d-4998-9dd8-85e4185584b4)

**Comment by lutzroeder** [comment]
@ylei1 opening the file shows below. Can you investigate or debug or your machine and check it is the correct file?

![Image](https://github.com/user-attachments/assets/3e3c7bfe-99d4-4498-a42a-c45e1487740d)

**Comment by ylei1** [comment]
> @ylei1 opening the file shows below. Can you debug on your machine and check it is the correct file?
> 
> ![Image](https://private-user-images.githubusercontent.com/438516/384212815-3e3c7bfe-99d4-4498-a42a-c45e1487740d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzU4NTMsIm5iZiI6MTczMTAzNTU1MywicGF0aCI6Ii80Mzg1MTYvMzg0MjEyODE1LTNlM2M3YmZlLTk5ZDQtNDQ5OC1hNDJhLWM0NWUxNDg3NzQwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQwMzEyMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjYwYzQ2ZjVhNmQzNTUxZmNmZjBmZDNlNTJkODUwNjY2ZmMyYWFjOGUwMjA5ZDVlZmMwMzc5NzYzMmY2MjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.05eW6hno3U8WybwR3Uyp_K7_Fp4uC9mJOA0ZnxnzfkQ)

Yes, I think it it correct
