### ISSUE TITLE
Keras: custom type is not supported

### ISSUE THREAD

**Issue by ELubicz** [lutzroeder/netron#1398]
- Netron app and version: Desktop 8.0.2
- OS and browser version: Windows 11 10.0.22631 Build 22631

Steps to Reproduce:

1. Create a custom Keras model
2. Export it as .keras

```python
import keras
import tensorflow as tf

class TestModel(keras.Sequential):
    def __init__(self, layers):
        super().__init__(layers=layers)

    def get_model(self):
        # This works on Netron without any issues
        return keras.Sequential(self.layers)
    
    def get_model2(self):
        # This generates an error on Netron
        return self
    
tm1 = TestModel([tf.keras.layers.Dense(512, activation='relu'),]).get_model()
tm2 = TestModel([tf.keras.layers.Dense(512, activation='relu'),]).get_model2()
tm1.save(os.path.join(CURR_DIR, "test_model1.keras")) # works
tm2.save(os.path.join(CURR_DIR, "test_model2.keras")) # doesn't work
```

Here are the exported models:
[test_models.zip](https://github.com/user-attachments/files/17817057/test_models.zip)

**Comment by lutzroeder** [comment]
@ELubicz Keras does not store the base type in the file.

**Comment by lutzroeder** [comment]
@ELubicz can you help [validate](https://github.com/lutzroeder/netron/blob/main/CONTRIBUTING.md) the change in [main](https://github.com/lutzroeder/netron).

**Comment by ELubicz** [comment]
I can confirm the fix is working. Thanks for the quick action!
