### ISSUE TITLE
Review request

### ISSUE THREAD

**Issue by megemini** [lutzroeder/netron#1404]
Hi @lutzroeder ~ Have you received my review request from https://github.com/lutzroeder/netron/pull/1400 ?
I'm not familiar with your workflow ~ 🤣
I need to create a issue for review request when I finished the modification, or just wait ? 
Sorry to bother you ~ Really thanks ! 😄

**Comment by lutzroeder** [comment]
@megemini yes, this is not a priority and will get to it as time permits.

**Comment by lutzroeder** [comment]
Duplicate of #1407
