### ISSUE TITLE
Key bindings (like up/down arrows) for scrolling the visualization.

### ISSUE THREAD

**Issue by OneForward** [lutzroeder/Netron#141]
It seems inefficient to scroll the views by

>  **pressing** the left mouse button and **meanwhile dragging**  the views **up** to scroll down.

Can adding arrow shortcut for scrolling through the visualization be a possible feature in future development?

**Comment by lutzroeder** [comment]
See #24 and the [scrollbars](/lutzroeder/Netron/tree/scrollbars) branch.

**Comment by OneForward** [comment]
Thank u for your dedicated contribution!!
