### ISSUE TITLE
Ubuntu: can't read file or directory names and buttons

### ISSUE THREAD

**Issue by eademir** [lutzroeder/netron#1412]
- Netron app and version: 8.0.7 Desktop
- OS and browser version: Ubuntu 24.04.1 LTS

Steps to Reproduce:

1. Open the app
2. Try to pick a model

Please attach or link model files to reproduce the issue.
![Screenshot from 2024-12-23 17-37-27](https://github.com/user-attachments/assets/84b875ed-3c89-4877-8591-d36813c70697)

**Comment by lutzroeder** [comment]
@eademir can you investigate why this is happening and how to reproduce it. Does this reproduce with other Electron apps?

**Comment by eademir** [comment]
Hi @lutzroeder . There is no problem with other electron apps. In the app, this only happens when I try to select a file. Rest of the content is readable.  I installed it using  `snap install netron` if this helps. And, arm64 Ubuntu LTS.

**Comment by lutzroeder** [comment]
@eademir have you tried the same file open dialog in other Electron apps and compared if they are deployed the same way, tried building from source or AppImage. electron-userland/electron-builder#5626 has no Snap support for `arm64` so assuming you are running `x64` bits using emulation? This will likely require you investigating further and driving fixes upstream.

**Comment by eademir** [comment]
@lutzroeder sorry, I was trying to write amd64. I'll investigate it. it works correctly when I try to use pop up in VS Code.
