### ISSUE TITLE
Allow to disable telemetry by not giving consent

### ISSUE THREAD

**Issue by jin-eld** [lutzroeder/netron#1413]
Hi,

as I understand right now one can either consent and allow sending telemetry or quit the application, there is no option to deny and continue (except for patching the code).

Wouldn't it be nicer for an open source project to allow users to decide if they want the application to "call home" or not?

I understand, that you'd like to only collect crash logs to improve the app, but it does not really feel right to enforce it.

Could we please get a "Reject" button too? :)

**Comment by lutzroeder** [comment]
The logs are used to improve the app for everyone. In the spirit of open source, not sending logs would shift the cost to other users and maintainers. To not send logs, you can [run the app from source](https://github.com/lutzroeder/netron/blob/main/CONTRIBUTING.md), which also allows you to contribute directly by identifying issues early and submitting fixes.
