### ISSUE TITLE
Error The script 'https://lutzroeder.github.io/Netron/tf.js' failed to load.

### ISSUE THREAD

**Issue by tensorbuffer** [lutzroeder/netron#143]
[frozen.zip](https://github.com/lutzroeder/netron/files/2330277/frozen.zip)

**Comment by lutzroeder** [comment]
How did you open Netron in the browser? The url changed to `https://lutzroeder.github.io/netron` instead of `https://lutzroeder.github.io/Netron`. Maybe a browser cache issue?
