### ISSUE TITLE
SVG export shows black boxes instead of notes

### ISSUE THREAD

**Issue by ostrokach** [lutzroeder/netron#144]
I installed the `Netron_2.0.9_amd64.deb` on Linux Mint 19 (based on Ubuntu 18.04).

When I load the `Inception v1` ONNX model and click `File -> Export -> SVG`, the resulting SVG file contains black boxes instead of nodes (see the attached image). PNG export works fine.

Thanks for the great project!

<details>
<summary><code>model.svg</code></summary>
<img src="https://user-images.githubusercontent.com/5614375/45040253-925a1d00-b033-11e8-94ae-ae3bde5f42ec.png" />
</details>

**Comment by lutzroeder** [comment]
Does the Linux viewer you are using support `CSS` styles in `SVG`? Both Chrome and Firefox seem to render the file correctly. If you want to tinker with inlining the styles, check the `export()` and `transferStyleSheet()` methods in `src/view.js`.

**Comment by ostrokach** [comment]
Can confirm that it works now. Thanks!
