### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by han-so1omon** [lutzroeder/netron#145]
Hi, lots of recommendations to use netron, but no documentation for it. Where is it or can it be generated?

**Comment by lutzroeder** [comment]
What kind of documentation are you looking for?

**Comment by han-so1omon** [comment]
It isn't clear that intended usage is as a net-app and not as a python API. Maybe just add that intended usage is with the cli. `Netron is a CLI tool for visualizing neural networks. Typical usage is to start the app as such:`. Something like that will clarify a lot.

**Comment by han-so1omon** [comment]
Beyond that it would be nice but not necessary to have api docs or a python notebook on how to integrate into a webapp.

**Comment by lutzroeder** [comment]
There isn't an intended usage pattern, hence the different install choices in `README.md` (desktop, browser, CLI). Python API isn't mentioned so adding Python API samples would make this less clear?

**Comment by okridgway** [comment]
Even just some example files would be helpful.
