### ISSUE TITLE
scaling values for input and output tensors for tflite quantized files

### ISSUE THREAD

**Issue by jnorwood** [lutzroeder/netron#147]
The tflite processing uses the scaling values from the input and output tensors, and from the weight tensors, in the calculation of the integer multiplier and shift  parameters that implement the downscale to uint8 from int32 accumulator for each kernel in the convolutions.

In the netron viewer, I can see the weight and bias scale values, and I can see the input shapes displayed, but I don't see the input scaling parameters, which should have been determined during training.

I'm trying to determine if this is just missing from the viewer, or if the model really doesn't contain these Scaling values for the inputs.

I'm using the MobileNet_v1_1.0_224_quant from this link.
https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md

Thanks ..

**Comment by jnorwood** [comment]
I see the values in the new release.  Thanks very much..  Nice addition of the displayed shapes also, and the new quantization display line in the Model Properties display is very helpful.

**Comment by learnerwang** [comment]
Dear lutzroeder:
    Could I export the data in tflite File? I want to parse the tflie file, and I can see all the tensors,scales ,zeropoint, OP type and parameters in Netron.   I want to  export them, could it be possible? and how can I get them?
Best regards
