### ISSUE TITLE
Instruction how to run

### ISSUE THREAD

**Issue by demid5111** [lutzroeder/netron#148]
Hi @lutzroeder ,

I would like to contribute to the tool you have made, however, I was not able to run it from scratch:
cloning and npm start is obviously not enough. 
What should I do to have it running on the local machine?

Also, what are the needed help things in this project, so that we could collaborate?

**Comment by lutzroeder** [comment]
Did you have a look at [DEVELOPMENT.md](https://github.com/lutzroeder/netron/blob/master/DEVELOPMENT.md)?

**Comment by demid5111** [comment]
oh, thank you, now it is working.

I want to experiment a bit with adding support to the model for the framework of my own. Where should I look at and start with?
