### ISSUE TITLE
Netron Command-line Arguments

### ISSUE THREAD

**Issue by GokulNC** [lutzroeder/netron#150]
Does the compiled binaries of Netron take any command-line arguments?

Atleast is there a way to pass my model path as arguments, something like
```netron --model blah-blah.pb```
... by typing which it will automatically show the visualization for the model passed in arguments.

If there's no support for that, can this be considered as a feature request for that??
Thanks @lutzroeder .

**Comment by GokulNC** [comment]
Is it as simple as removing the `process.platform == 'win32'` in the [app.js](https://github.com/lutzroeder/netron/blob/03e8040e40ac6c1d3338ea68216f494b5444deb8/src/app.js#L76) code?

If that's not the case, what does the function `_parseCommandLine()` do?

**Comment by lutzroeder** [comment]
`Netron.exe blah-blah.pb` should work?

**Comment by GokulNC** [comment]
Didn't work on Linux with the following command:

```netron tiny-yolo-voc.h5```

BTW, why are you so fast in closing issues even before they're solved? ;)
