### ISSUE TITLE
Fail to render .prototxt file

### ISSUE THREAD

**Issue by demid5111** [lutzroeder/netron#155]
I have [squeezenet_v1.1.protoxt](https://github.com/DeepScale/SqueezeNet/blob/master/SqueezeNet_v1.1/deploy.prototxt)

When I render it on the [demo site](https://lutzroeder.github.io/netron/), I get it rendered.

On the latest master, I get the following error: 

> Error loading Caffe model. File text format is not caffe.NetParameter (Right-hand side of 'instanceof' is not an object).

Because of $TextReader being `indefined` in caffe.js, line 1077:
```
NetParameter.decodeText = function decodeText(reader, block) {
                if (!(reader instanceof $TextReader)) <--------------
                    reader = $TextReader.create(reader);
                var message = new $root.caffe.NetParameter();
                reader.start(block);
```

**Comment by lutzroeder** [comment]
Does deleting `node_modules` and running `npm install` again help?
