### ISSUE TITLE
Error loading Keras model: config.forEach is not a function

### ISSUE THREAD

**Issue by marsantosh** [lutzroeder/netron#157]
When I try to load a h5 model I get the following error:

Error loading Keras model:
config.forEach is not a function

This model was trained on with the Keras version 2.2.3 on a server,
but when I train the same script and model (everything is totally the same)
on my local laptop with Keras version 2.2.2 I can open the file without any problem.

**Comment by lutzroeder** [comment]
Can you share the model file?

**Comment by marsantosh** [comment]
> Can you share the model file?

Sure, wait a sec.

**Comment by marsantosh** [comment]
I'm sorry, I'm new to github... How can I exactly do it?
