### ISSUE TITLE
Netron Demo Format Error on ONNX file

### ISSUE THREAD

**Issue by dbaechtel** [lutzroeder/netron#158]
Trying to view the attached file using Netron online Demo gets:
Error loading ONNX model. File format is not onnx. ModelProto (invalid wire type 7 at offset 40).

[torch.onnx.txt](https://github.com/lutzroeder/netron/files/2453067/torch.onnx.txt)

**Comment by lutzroeder** [comment]
The attached file looks like console debug output from PyTorch and is not a valid ONNX file but . 

Assuming you are following [this](https://github.com/pytorch/pytorch/blob/master/docs/source/onnx.rst) tutorial, running the Python script will produce a file called `alexnet.onnx` which is the actual ONNX file. 

If you don't have a GPU make sure you remove the `cuda` comments before running the Python script:

```
import torch
import torchvision

dummy_input = torch.randn(10, 3, 224, 224)
model = torchvision.models.alexnet(pretrained=True)

# Providing input and output names sets the display names for values
...
```
