### ISSUE TITLE
Export image via command line

### ISSUE THREAD

**Issue by phadjido** [lutzroeder/netron#162]
The visualization results of netron are really great. This is also true for the exported images. 
So, I am wondering if it will be possible:
a) to export the network to a png/svg file using the python http server
b) to export the network directly to a file by using a command line argument (ideally without starting a server or doing this within a python script)

**Comment by lutzroeder** [comment]
The layout and visualization is done in the browser in JavaScript. It is not something the server does without running a client. The desktop app has an option to export PNG/SVG via File > Export. Enabling the same for the browser version is possible but should be tracked as a separate issue.

**Comment by ahmedhosny** [comment]
I wonder if there is a way to serve the model statically from a html+js bundle. We want to keep [the model viewers](http://app.modelhub.ai/) running without have to run the server. I guess one way is to export the SVG and enable panning, albeit without the interactivity. When doing a "save as" from the browser, the resultant html does display the components in the graph but without text - before giving this expected error: 
`Error while requesting model. 0`
![test](https://user-images.githubusercontent.com/8398334/51848822-52e6e280-22ec-11e9-976f-8aebb9d10cc5.jpg)

**Comment by lutzroeder** [comment]
The web app doesn't require a server. To get interactivity the actual model data will have to be available and loaded by the browser client. For example, using `?url=` should work if the file location providing the model has the right cross-domain configuration.

http://lutzroeder.github.io/netron/?url=https://raw.githubusercontent.com/Microsoft/Windows-Machine-Learning/master/Samples/Emoji8/UWP/cs/Emoji8/Models/model.onnx.

**Comment by rinosh1989** [comment]
@lutzroeder It would be great if you could implement exporting of the model as png/svg from command line.

**Comment by grwlf** [comment]
Hi I experienced the similar problem with [Altair](https://github.com/altair-viz/altair) library for doing scientific plots, which also relies on web-client for rendering. Static PNG export is solved there in a separate project [Altair-saver](https://github.com/altair-viz/altair_saver). It works fine, but knowing details causes a kind of facepalm: they use Seleneum (or optionally Node-js) to capture the picture from web-client. Installing the those dependencies is a pain, but I think that export is very important option. So +1 from me to the above post..

**Comment by andrewcstewart** [comment]
Hi @lutzroeder - I see a lot of issues pointing back to this issue, but while the issue history here says its complete it looks like maybe you just closed it as a rejection of the feature request?  I'd say it's of course totally valid if you think it's not a reasonable feature request or you simply don't want to do it, etc, but imho it would probably at least be useful to leave a note to that effect on this issue?  (maybe even add a label like "wont do")

For what it's worth, I think an enabling step towards these types of feature requests could be to add support for programmatic image export via a REST API endpoint from the server, if that's at all possible in this Electron framework.  Basically a REST endpoint that does the same thing as clicking the "Export to PNG/SVG" option in the UI.  If that existed, then users would be able to programmatically export images by starting a headless server and hitting that API endpoint.  Just a thought.

**Comment by lutzroeder** [comment]
@andrewcstewart see ^^^. The app runs in the browser and is rendering client side, there is no server. There are ways to work around this, they would likely involve bringing up a browser head in Python. Feel free to investigate, submit a pull request and sign up for testing and maintaining this feature. Ideally this should be done in a way that doesn't add more dependencies or complexity to the architecture. "Closed" is to indicate that nobody is actively working on this.

**Comment by raphael-prevost** [comment]
Hi! I have just hacked a way of exporting the graphs as png/svg files via Python or command line (it works by starting a netron server, a browser and simulating the clicks on the right HTML elements). Might be a bit fragile but it does the job. 

Since there seems to be some interest for a solution, we have put it in a Python module available here: https://github.com/raphael-prevost/netron-export
