### ISSUE TITLE
Export network as PNG/SVG for browser version

### ISSUE THREAD

**Issue by phadjido** [lutzroeder/netron#163]
It would be very useful option to export PNG/SVG images in the browser version.

**Comment by lutzroeder** [comment]
`CmdOrCtrl+Shift+E` - Save as PNG
`CmdOrCtrl+Shift+Alt+E` - Save as SVG

**Comment by andres-fr** [comment]
In my case my Firefox wasn't grabbing the shortcuts. Tried several add-ons for different browsers, but only the visible part of the graph was getting printed. At some point I looked into the code, and this related line gave away the solution:

`https://github.com/lutzroeder/netron/blob/9d94068c7e1df438aec4546e2ef3b6d98046509c/src/view-browser.js#L429`

So this fixed it for me:

1. Open the firefox console
2. Type `this.__view__.export("my_net.svg")`


Hope it helps someone!  thanks for Netron is amazing
