### ISSUE TITLE
Display doc_string field for each node in visualization

### ISSUE THREAD

**Issue by jamesr66a** [lutzroeder/Netron#17]
This field is populated by front-ends with human-readable information about each node. For example, Pytorch populates this with stack trace information. Can we make this field accessible in the visualization?

**Comment by lutzroeder** [comment]
Definitely. Do you have a sample .onnx file you can share?

**Comment by jamesr66a** [comment]
Sure, the squeezenet example ONNX file was exported from pytorch with stack traces: https://github.com/onnx/tutorials/blob/master/tutorials/assets/squeezenet.onnx

**Comment by lutzroeder** [comment]
0.2.0 shows shortened doc_string as part of the attributes list. Click on it and it will show the full string the bottom in the sidebar. 'ATTRIBUTES' might turn into 'NODE DETAILS' at some point with a better distinction between name, doc_string and the other attributes.
