### ISSUE TITLE
ML.NET support

### ISSUE THREAD

**Issue by gitchomik** [lutzroeder/netron#170]
Is there a plan to enable viewing ML.NET (https://github.com/dotnet/machinelearning) models with Netron?

**Comment by lutzroeder** [comment]
ML.NET exports to ONNX. Is there anything specific you are looking for? Can you share the model files?

**Comment by gitchomik** [comment]
@lutzroeder
https://filebin.net/0nai0j82ec566d6x/Model.zip?t=ahokbzwt

**Comment by lutzroeder** [comment]
@gitchomik can you provide a complete JavaScript reader for ML.net files to enable loading these models.

[mlnet_reader_prototype.zip](https://github.com/lutzroeder/netron/files/2635657/mlnet_reader_prototype.zip)

**Comment by lutzroeder** [comment]
[IrisClassificationModel.zip](https://github.com/lutzroeder/netron/files/3559310/IrisClassificationModel.zip)

**Comment by lutzroeder** [comment]
[ep_model1.zip](https://github.com/lutzroeder/netron/files/4216033/ep_model1.zip)

**Comment by lutzroeder** [comment]
[ngram.zip](https://github.com/lutzroeder/netron/files/4216079/ngram.zip)

**Comment by lutzroeder** [comment]
[termlookup_with_key.zip](https://github.com/lutzroeder/netron/files/4216237/termlookup_with_key.zip)

**Comment by lutzroeder** [comment]
[ep_model3.zip](https://github.com/lutzroeder/netron/files/4216304/ep_model3.zip)
