### ISSUE TITLE
load model failed

### ISSUE THREAD

**Issue by hellobinbin1234** [lutzroeder/netron#171]
When I load model, the software remind me that File formate is not tensorflow.saveModel(invalid wire type 7 at offset 17). I guess  this is a bug for this software?

**Comment by lutzroeder** [comment]
How did you get the file and can you share it? What format do you expect the file to be in?

**Comment by hellobinbin1234** [comment]
[saved_model.zip](https://github.com/lutzroeder/netron/files/2528688/saved_model.zip)
This is my model file to test, I have test this model using tensorflow. So the model must can be used.

**Comment by lutzroeder** [comment]
The file is called `saved_model.pb` but is not in tensorflow.SavedModel format. If you rename the file to any name other than `saved_model` it will load as tensorflow.GraphDef.

See tensorflow/tensorflow#15061

**Comment by hellobinbin1234** [comment]
Thank you very much!
