### ISSUE TITLE
[CONTRIBUTING] Adding support for new ML Frameworks 

### ISSUE THREAD

**Issue by GokulNC** [lutzroeder/netron#173]
Is there a guide describing an outline of the execution flow of Netron, and how to add support for new ML Frameworks??

If no, can you please create one, or brief it in this issue??

Thanks :)

**Comment by lutzroeder** [comment]
See [DEVELOPMENT.md](https://github.com/lutzroeder/netron/blob/master/DEVELOPMENT.md) for build instructions. Create `xxxx-model.js` and add in `view.js`, `setup.py`, `view-browser.html` and `view-electron.html`. Add `XxxxModelFactory` in `loadContext` in `view.js`. Then follow patterns in existing loader like `OnnxModelFactory`. More general, what support are you trying to add, why and how are you planning to ensure maintenance going forward?

**Comment by GokulNC** [comment]
@lutzroeder 
Hey, I have a doubt. Let's say I want to group a certain no. of nodes as a sub-graph, and I want to indicate the user about this by drawing a shaded boundary around those particular nodes.

Something like this which I've done using GraphViz:
![image](https://user-images.githubusercontent.com/10559293/48126575-7ed36880-e2a7-11e8-8f0a-e6ea68d1392b.png)

Do we have support for this in Netron?
If no, shall I create a `feature-request` issue for this?

Thanks again. :)
