### ISSUE TITLE
loading model issues

### ISSUE THREAD

**Issue by Winowang** [lutzroeder/netron#178]
Hi,  
I just met issue below when I was trying to load a local model file (.meta ~ 5MB) 
"Large model detected. This graph contains a large number of nodes and might take a long time to render. Do you want to continue? "

There was no any response of the brower after clicking "OK" ,and I tried a smaller one and met the same problem.  What should I suppose to do? Thanks in advance.

**Comment by lutzroeder** [comment]
see #68
