### ISSUE TITLE
Can't open model.json file

### ISSUE THREAD

**Issue by haohaibo** [lutzroeder/netron#179]
![image](https://user-images.githubusercontent.com/5644013/48479603-c7a89580-e842-11e8-8f4b-3638dc77f322.png)

**Comment by haohaibo** [comment]
It's a internal network. It's format is the following
`{"inputs": [
        "input-0"
    ],
    "outputs": [
        "Softmax-182-1",
        "Concat-189-1",
        "ResizeArgmax-152-1"
    ],
"layers": [
        {
            "type": "input",
            "name": "input-0",
            "shape": [
                768,
                1280,
                3
            ]
        },
      {...
      }
      ...
]}`
Thanks

**Comment by lutzroeder** [comment]
What format is this and how was the file generated?

**Comment by haohaibo** [comment]
I think it's chainer format.

**Comment by lutzroeder** [comment]
Chainer is supported through ONNX.
