### ISSUE TITLE
can't open the web:http://localhost:8080/

### ISSUE THREAD

**Issue by Gepeng18** [lutzroeder/netron#184]
Great !, I am learning a lot. I do have a question about it. I install netron through running `pip install netron`
and run `import netron netron.start('model.h5')` .The website:'http://localhost:8080/' was opened in Browser 
but it shows that 'Model load request failed. 404'. How can i solve the problem?  I use chrome and window 10

**Comment by lutzroeder** [comment]
Are you running the latest version `2.5.3`? If yes, what OS and environment are you using?

**Comment by Gepeng18** [comment]
Thank you for your replying. I do run the latest version. My os is window 10 and use python 3.6

**Comment by Gepeng18** [comment]
I want to visualize keras model throuth it

**Comment by lutzroeder** [comment]
As a workaround you can open the web version at https://lutzroeder.github.io/netron and drag the `model.h5` file into the browser window. Still trying to reproduce the problem you are seeing but it is working for my Python 3.7, Windows 10, Chrome configuration.

**Comment by lutzroeder** [comment]
Best guess would be that the file `model.h5` doesn't exist in the current directory? Adding an error message to the next version. As a workaround, you can try using the web version at https://lutzroeder.github.io/netron to load the file.

**Comment by Gepeng18** [comment]
Sorry for the delay getting back to you.  Thank you very much. I have solved my question through opening the web version at https://lutzroeder.github.io/netron and draging the model.h5 file into the browser window. Thanks again for your help.
