### ISSUE TITLE
PaddlePaddle support

### ISSUE THREAD

**Issue by hshen14** [lutzroeder/netron#198]
https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/image_classification

Here is an example: http://paddle-imagenet-models.bj.bcebos.com/resnet_50_model.tar

**Comment by lutzroeder** [comment]
The `resnet_50_model.tar` file seems to only contain weight tensors and no model information. Is there a format description, files representing an actual model graph or a prototype how this would work?

**Comment by hshen14** [comment]
Please try http://paddle-inference-dist.bj.bcebos.com/int8/resnet50_int8_model.tar.gz, there is __model__ inside.

**Comment by hshen14** [comment]
Could you please take a look? Need to reopen?

**Comment by lutzroeder** [comment]
What is the format for the `__model__` file and how is it created?

**Comment by hshen14** [comment]
It is generated by protobuf by invoking PaddlePaddle save_inference_model in https://github.com/PaddlePaddle/Paddle/blob/9ced6da444ac759f755b9d7521a9d4882afabd1d/python/paddle/fluid/io.py.

**Comment by lutzroeder** [comment]
This is the `fluid/framework/framework.proto` format? Is there a model zoo with multiple such files?

**Comment by hshen14** [comment]
Yes. The file I sent is from Paddle model zoo.

**Comment by lutzroeder** [comment]
What are the links to some other files?

**Comment by lutzroeder** [comment]
@hshen14 can you please provide additional models and work with the Paddle team to share model files in the model zoo. Furthermore, can you provide information how Paddle files are correctly shared and detected (which file extension is used etc). Netron will now open the file you shared but since there is very little useful documentation and no other models available it will require your work to improve this. Please submit PRs to improve Paddle support.

**Comment by lutzroeder** [comment]
[tranformer_base.zip](https://github.com/lutzroeder/netron/files/5160568/tranformer_base.zip)

**Comment by lutzroeder** [comment]
[assign.pbtxt.zip](https://github.com/lutzroeder/netron/files/5485296/assign.pbtxt.zip)

**Comment by lutzroeder** [comment]
[recognize_digits_multilayer_perceptron_weights.tar.zip](https://github.com/lutzroeder/netron/files/5551009/recognize_digits_multilayer_perceptron_weights.tar.zip)

**Comment by lutzroeder** [comment]
Duplicate of #903
