### ISSUE TITLE
Adding new model formats

### ISSUE THREAD

**Issue by LoafingBunny** [lutzroeder/netron#202]
Hi, I have built for a university project a protobuf-based model description.
How can I add the support for it?

**Comment by lutzroeder** [comment]
How is this format different from existing ones like ONNX? Could the files be converted or stored as ONNX files using custom operators? Given each new format adds complexity there will be a high bar to accept PRs unless there is a clear benefit for a large user community.

That said, these are the steps too add a `foo` format:
1. Add a `tools/foo sync schema` script to create `src/foo-proto.js`. `tools/onnx` is a good template to follow.
2. Add `src/foo.js` and export `foo.ModelFactory` which implements `match()` and `open()`. `src/onnx.js` is a good template to follow.
3. Use a custom file extension other than `.pb` to avoid conflicts with other `.pb` formats.
4. Add a `register()` entry to `ModelFactoryService` in `view.js`. Dragging files into the window should load `foo.js` and invoke the `ModelFactory`.
5. Add the extension to file dialogs in `view-browser.html` (browser) and `app.js` (Electron).
6. Implement `foo.ModelFactory` to create `foo.Model`, `foo.Graph`, `foo.Node` etc.
7. If custom metadata is needed add a `foo-metadata.json` and follow the loading patterns of other formats.

**Comment by lutzroeder** [comment]
Duplicate of #1308
