### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by jnorwood** [lutzroeder/netron#204]
I didn't find a view item for summaries in the menu, so I'm assuming it isn't a current feature.
I'm looking for per layer and full model totals of resources and operations.
This netscope viewer has per layer info (scroll to bottom), but no model summary.
https://dgschwend.github.io/netscope/#/preset/resnet-50
Is any feature like that under development?  If not, please add it to a wish list.

**Comment by pawan9** [comment]
Can you please add MACCs, FLOPS and Memory access info per layer and for full model.

**Comment by lutzroeder** [comment]
@headdab

**Comment by Fannettembrown** [comment]
Called a Sequential model value....

**Comment by widiba03304** [comment]
Is there any plan to add this feature? If not, I am very interested in implementing this.

**Comment by lutzroeder** [comment]
Duplicate of #1240 and #1241
