### ISSUE TITLE
Can't delete folder of opened model file

### ISSUE THREAD

**Issue by letmaik** [lutzroeder/netron#208]
On Windows, when a model file is opened in Netron, then it's not possible to delete the folder that contains this file. It is possible though to delete the file itself, so the block seems to be somewhere else. This is a bit annoying when you are generating models on the fly during tests or similar and delete previously generated files/folders on each run. I admit it's a bit of an edge case but I thought that this should just work.

**Comment by lutzroeder** [comment]
Can you investigate why this is happening and see if you can find a fix? The app shouldn't hold a lock on the folder.

**Comment by lutzroeder** [comment]
need repro steps

**Comment by lutzroeder** [comment]
Detailed step by step how to reproduce the issue. Which version (Electron or Python Server), how is the file loaded etc. Ideally debug the code why this happening. Tried on a Windows machine and wasn't able to reproduce this.

**Comment by letmaik** [comment]
OS: Windows 10
Netron version: 2.7.4 (exe installer)

Steps:
- Create a new folder and save an ONNX model file into it
- Open the model file in Netron
- Keep Netron open
- Try to delete or rename the folder from Windows Explorer

Result:
![image](https://user-images.githubusercontent.com/530988/50142918-89701d00-02ab-11e9-935a-1652f418ed5a.png)

Following the method described [elsewhere](https://superuser.com/a/643312) I can verify that all three Netron.exe processes (main, gpu, renderer) hold a lock on that folder:

![image](https://user-images.githubusercontent.com/530988/50143312-96d9d700-02ac-11e9-8f5b-2d0b252c1232.png)




I haven't checked the Netron source yet to see why this is the case.

**Comment by lutzroeder** [comment]
Does not repro following the same steps with the same setup (Windows 10 Build 1803 17134.471). How are you opening the file, using the file dialog or drag and drop? Is `Associated Handles` locking the folder or the actual file name? If it is locking the folder could it be that you launched `Netron.exe` from that folder so the shell keeps it locked?

**Comment by letmaik** [comment]
That's weird. The locking happens when I double click on the file to open it, from Explorer. But when I open Netron first, and then open the file from inside Netron, then this issue doesn't appear. It also doesn't appear with drag and drop. I wonder if that's a general behaviour of Windows or related to the way Netron integrates with the explorer. Interestingly, when I right-click on the file and do it via "Open with..." then the issue also doesn't appear.
