### ISSUE TITLE
[TFLite] Restore tab view of input

### ISSUE THREAD

**Issue by FrozenGene** [lutzroeder/netron#212]
The latest TFLite model view is like this:
![image](https://user-images.githubusercontent.com/7287321/50582235-d6531680-0e9b-11e9-9141-729ea6c28bad.png)
However, I can not distinguish how many input tensors of op.

Previous version (2.7.2)
![image](https://user-images.githubusercontent.com/7287321/50582327-ad7f5100-0e9c-11e9-969f-57e4d12afc9b.png)
Previous version I can know it very clearly. This feature is important when I parse the model.

Could we restore the tab view of op? Thanks.

**Comment by lutzroeder** [comment]
Can you explain what you can not distinguish? The `weights` and `bias` show and `Cmd+D` will show the attributes as well?

**Comment by FrozenGene** [comment]
Thanks for replying. Current show is weight / bias in the previous attributes box. When I see the op, I will think weight / bias is attribute when I first see it. If I use cmd+D, the things will be worse.

![image](https://user-images.githubusercontent.com/7287321/50584713-2cc85100-0eac-11e9-9e3f-17384cb64403.png)

Weight / bias and other attributes will be in the same attributes box and I will treat weight / tensor as attributes when I first see them. However, the weight / bias is in fact in the op inputs. 

More specifically, I will parse TFLite's convolution like this using Python:
```python
if len(get_input_tensors(op)) == 3:
   has_bias = True
# stride_h is not in the op's inputs, just attributes
stride_h = conv2d_options.StrideH()
```
Previous (2.7.2) version, I will know weight / bias tensor is in the op's inputs and stride is in the conv2d's attributes very clearly.

**Comment by FrozenGene** [comment]
ping @lutzroeder I don't know whether you understand my question. If you think it is still good of current version, could you add one option like `cmd+D` to switch previous tab view? Or could you tell me which commit you do the modification? Thanks in advance.
