### ISSUE TITLE
netron.serve_file() error

### ISSUE THREAD

**Issue by SirishaRella** [lutzroeder/netron#219]
Hey, 
 I'm trying to use netron module in my python project. Whenever I'm trying to do netron.serve_file('model.onnx') it throws an error saying netron attribute doesn't contain serve_file. 

**Question-1:**
How to use netron in my python project. Is it just 

import netron
netron.serve_file('model.h5')/netron.serve_file('model.onnx') or do I need to do add anything else to use it.
Please do have a look at screenshot
![netron error](https://user-images.githubusercontent.com/42659275/51136424-1605f080-1802-11e9-86fe-a212268663f6.PNG)

Note:
Netron is already installed using pip install netron.

**Question-2:**
Should I always run python on some web server when I'm using netron in my project? Does it not work in google colab?

**Comment by lutzroeder** [comment]
`netron.start('model.onnx')` instead of `serve_file`.

**Comment by SirishaRella** [comment]
Thanks
