### ISSUE TITLE
Python package documentation

### ISSUE THREAD

**Issue by lucyktan** [lutzroeder/netron#220]
I see in your readme that there's netron.start(), but what are other functions provided by the Python package? Currently, I'm quitting the server each time I want to visualize a different model. How do I visualize another model without having to restart the server? And how do I stop the server without having to do Ctrl+D?

**Comment by lutzroeder** [comment]
`netron.stop()` or `netron.stop(port)` or `netron.stop(port, host)` will stop the server.

Running `netron.start()` again will also stop the server running on the same `port` and `host` if there is one running already before starting the new one.

**Comment by lucyktan** [comment]
I'm getting these errors:

```
>>> import netron
>>> netron.start('/Users/m057388/Downloads/stitches_models_iv3_dress_sleeve_length_05_0_9486___5_classifier.h5')
Serving '/Users/m057388/Downloads/stitches_models_iv3_dress_sleeve_length_05_0_9486___5_classifier.h5' at http://localhost:8080
>>> netron.stop()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/netron/server.py", line 173, in stop
    if port == thread.port and host == thread.host:
AttributeError: 'HTTPServerThread' object has no attribute 'port'
>>> netron.stop(8080)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/netron/server.py", line 173, in stop
    if port == thread.port and host == thread.host:
AttributeError: 'HTTPServerThread' object has no attribute 'port'
>>> netron.stop(8080, '127.0.0.1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/netron/server.py", line 173, in stop
    if port == thread.port and host == thread.host:
AttributeError: 'HTTPServerThread' object has no attribute 'port'
```

**Comment by ahmedhosny** [comment]
netron V2.8.1
I have no problems running 
`netron.start("model.h5")`
but I get the same error mentioned here when defining port or host instead of the defaults.
