### ISSUE TITLE
There is a bug to open a caffemodel

### ISSUE THREAD

**Issue by hiworldwzj** [lutzroeder/netron#222]
I want to open the caffemodel "pspnet50_ADE20K.caffemodel" from 
 https://drive.google.com/file/d/0BzaU285cX7TCN1R3QnUwQ0hoMTA/view
 but failed. there is an error, it shows "Error: invalid wire type 7 offset 8482".I try to fix it by myself, but I found it too difficult, I am very sure that the model file is OK, it can run very well in other applications.  

you can get more infs about the model from https://github.com/hszhao/PSPNet

hope to fix this bug quickly，thanks

**Comment by lutzroeder** [comment]
This is a known limitation of Caffe. The protobuf format might have changed in the fork you are using and is no longer compatible with the main Caffe fork (see #165). You will have to make sure that `./src/caffe-proto.js` matches the `caffe.proto` used to create the file.

**Comment by hiworldwzj** [comment]
thanks for your reply
