### ISSUE TITLE
cannot visualize .pbtxt file

### ISSUE THREAD

**Issue by Johnqczhang** [lutzroeder/netron#223]
Hi, I'm trying to visualize a network saved in [net.pbtxt](https://github.com/lutzroeder/netron/files/2801714/net.pbtxt.txt) file which was generated by my `caffe2` code using netron of both [web browser](https://lutzroeder.github.io/netron/) and [MacOS App](https://github.com/lutzroeder/netron/releases) versions. However, both of them gave me the following error message:

Error loading model. Unsupported file content for extension '.pbtxt' in 'net.pbtxt'.

What am I supposed to do to make it work?

**Comment by lutzroeder** [comment]
The file will load if you rename it to `predict_net.pbtxt`. Multiple ML formats are using protobuf and protobuf design makes it difficult to detect the file format from contents. Note the file contains a lot of nodes and connections so it might take a very long time to render. A warning is shown for graphs with more than 1500 nodes, this file is close having 1460 nodes.

**Comment by Johnqczhang** [comment]
The file uploaded previously was generated by caffe2 when training a model with 2 GPUs so it contains nodes on all GPUs (including gradient ops), which may cause the visualization very clutter. So, I upload a new file [predict_net.pbtxt.txt](https://github.com/lutzroeder/netron/files/2802044/predict_net.pbtxt.txt) which contains nodes with ops for inference only on single GPU, which can give a clear visualization of the network structure for better understanding. The network was proposed in [DensePose](http://densepose.org/) as a baseline model, which consists of a ResNet-50 as backbone network and three branches for person detection and dense pose estimation. More details can be found in the [paper](https://arxiv.org/abs/1802.00434) and its [code](https://github.com/facebookresearch/Densepose).

BTW, both uploaded files end with `.txt` instead of `.pbtxt` because the latter one is not supported by the github.
