### ISSUE TITLE
Error accessing from a different computer

### ISSUE THREAD

**Issue by devkicks** [lutzroeder/netron#226]
Hi,

I am simply trying to visualize the graph on a remote server PC. I want to be able to access the visualizer in a browser (something similar to tensorboard I guess). However, when I do this - it gives me error: ERR_CONNECTION_REFUSED in browser.

Here is the command I used:
netron -b saved_model.pb --port 6090 --host myserverpc

On my machine I go to the following in my browser:
http://myserverpc:6090

Many thanks!
Dev

**Comment by lutzroeder** [comment]
Run with `localhost:<port>` and try `curl localhost:<port>` on the server. If that works the issue is likely with opening that port so the other machine can access it.

**Comment by lutzroeder** [comment]
Run with `localhost:<port>` and try `curl localhost:<port>` on the server. If that works could the issue be that the port isn't open for the other machine to see?

**Comment by devkicks** [comment]
curl works. The same machine can be accessed with any port using tensorboard but doesnt work with netron.

**Comment by lutzroeder** [comment]
Did you try `netron saved_model.pb --port 6090 --host ''`? `-b` isn't necessary since the server won't be able to open the browser.
