### ISSUE TITLE
Optional inputs and outputs visualization.

### ISSUE THREAD

**Issue by arogowie-intel** [lutzroeder/netron#228]
Please add visualization of node's optional inputs/outputs which have empty name. Reference doc: [here](https://github.com/onnx/onnx/blob/master/docs/IR.md#optional-inputs-and-outputs).

**Comment by lutzroeder** [comment]
Can you please provide a sample file, repro steps, expected and actual.

**Comment by arogowie-intel** [comment]
Great thanks for quick solution!
