### ISSUE TITLE
Support Keras SeperableConv2d

### ISSUE THREAD

**Issue by pGit1** [lutzroeder/netron#233]
Cannot visualize a model with sepConv2d

**Comment by lutzroeder** [comment]
Can you share the model file?

**Comment by pGit1** [comment]
If you just use a simple conv2d mode with seperable conv layers it doesnt work. Any basic one will do.

**Comment by lutzroeder** [comment]
Can you share a model file or exact steps to reproduce the issue?

**Comment by pGit1** [comment]
```
inpp = layers.Input((28,28,3))
x = layers.SeparableConv2D(32,3)(inpp)
x = layers.Flatten()(x)
x = layers.Dense(24)(x)

model = models.Model(inpp,x)
model.save('netron_model.model')
netron.start('netron_model.model',port=8585)

```

![image](https://user-images.githubusercontent.com/13975114/53266932-2f774380-36b0-11e9-81f0-8018ddd118bd.png)

**Comment by pGit1** [comment]
Thanks for your help by the way.

**Comment by lutzroeder** [comment]
`.model` is CTNK or MXNet Model Server format. Keras files should have an `.h5` extension for HDF5 format.

**Comment by pGit1** [comment]
PERFECT. I see even though the file is saved as  .h5 .model breaks it. This is great thank you!
