### ISSUE TITLE
CLI?

### ISSUE THREAD

**Issue by GantMan** [lutzroeder/netron#238]
Wondering if there is/could be CLI support for netron.

### Motivation
I'd like to automatically generate a netron graph of a model.  Making a CLI makes this simple.

e.g.
```
$netron --input ./my/model/path.h5 --output ./graph.jpg
```

Maybe even the ability to output the model layers in text?   This would allow us to use netron as a mechanic in automation.

**Comment by lutzroeder** [comment]
Text output should be part of the framework. For image output see #162.
