### ISSUE TITLE
Scrollbars and zoom limits

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#24]
Investigate adding canvas limits and using browser scrollbars.

**Comment by iphton** [comment]
@lutzroeder Zoom limit is very annoying. Is there any solution to it? Model is very vertically long and it seems useless to use these tools in these cases!

**Comment by lutzroeder** [comment]
http://lutzroeder.github.io/netron?zoom=scroll&url=https://ibelem.github.io/webml-website/examples/image_classification/model/squeezenet1.1.onnx
