### ISSUE TITLE
404 for `brew cask install netron`

### ISSUE THREAD

**Issue by ryanorsinger** [lutzroeder/netron#241]
Following a fresh `brew update`, brew shows  `curl: (22) The requested URL returned error: 404 Not Found` after issuing the `brew cask install netron`

`Error: Download failed on Cask 'netron' with message: Download failed: https://github.com/lutzroeder/Netron/releases/download/v2.9.6/Netron-2.9.6-mac.zip`

Looking forward to trying this out :)

**Comment by lutzroeder** [comment]
Cask update is blocked by electron-userland/electron-builder#3779. Please download the `.zip` or `.dmg` from https://github.com/lutzroeder/netron/releases instead.

**Comment by ryanorsinger** [comment]
This works like a charm, thank you! I'm visualizing a .h5 file now. This is super awesome. Thank you for building and sharing!
