### ISSUE TITLE
Add support for spaCy models

### ISSUE THREAD

**Issue by mindscratch** [lutzroeder/netron#244]
Would be nice to have support for [spaCy](https://spacy.io/usage/models) models. 

Is there a process for adding support for a new model type? (i.e. what functions need to be implemented? tests? etc).

**Comment by lutzroeder** [comment]
Good way to get started is:
1) add `src/foo.js` which exposed `foo.ModelFactory` and implement `match()` and `open()`
2) add file extension in the `view.ModelFactoryService` constructor in `src/view.js`

Assuming the implementation of `match()` would check for `meta.json`. `.tar.gz` gets handled by `ModelFactoryService` and the content is presented to match.

Drag & dropping a file should trigger the `match()` method and if it succeeds `open()`.

Maybe check `src/onnx.js` for reference patterns to follow.

**Comment by lutzroeder** [comment]
Duplicate of #1308
