### ISSUE TITLE
MXNet shared weights

### ISSUE THREAD

**Issue by huangh12** [lutzroeder/netron#245]
Hello, 
     I've tried this tool recently, and feel it's really wonderful. But i find that there is some room for improvement of visualization when weights are sharing between convs in mxnet.
In the below, i share the weights of three convs. While the weight id of both the middle and the right conv are `id: [563,0]` , the left conv's weight id is `id: stage4_unit2_conv1_weight`.
![图片](https://user-images.githubusercontent.com/18748036/55122951-bef29500-513b-11e9-8712-87db7ea4e717.png)
![图片](https://user-images.githubusercontent.com/18748036/55122457-0c6e0280-513a-11e9-8608-cb921f54b140.png)
![图片](https://user-images.githubusercontent.com/18748036/55122973-d16cce80-513b-11e9-92fd-3ceb46e1ec20.png)
By guessing, I can figure out the left conv weight id is `id: [563,0]`. But it will be much better if the weight id of the original conv is given in digital form explicitly as well, along with its string name.

Thank you~

**Comment by lutzroeder** [comment]
Can you share a file to reproduce the issue?

**Comment by huangh12** [comment]
Thanks for timly reply, the model file are sharing [here](https://1drv.ms/u/s!Auak7jZaGVcugxX3slJsE5TO1N18).

**Comment by lutzroeder** [comment]
[conv_weights_sharing.json.zip](https://github.com/lutzroeder/netron/files/3016064/conv_weights_sharing.json.zip)

**Comment by lutzroeder** [comment]
@huangh12 can you verify the fix? Steps [here](https://github.com/lutzroeder/netron/blob/master/DEVELOPMENT.md).

**Comment by huangh12** [comment]
Problem is fixed. Thx！
