### ISSUE TITLE
Paddle model could be no type-inferred

### ISSUE THREAD

**Issue by MidoriYakumo** [lutzroeder/netron#246]
https://github.com/lutzroeder/netron/blob/9b3c1147486d63e67e67da2ece2b33049d1fd57e/src/paddle.js#L158

**Comment by lutzroeder** [comment]
Can you share a model file to reproduce the issue?

**Comment by MidoriYakumo** [comment]
[with_dummy_tensor_type.zip](https://github.com/lutzroeder/netron/files/3021210/with_dummy_tensor_type.zip)
[without_tensor_type.zip](https://github.com/lutzroeder/netron/files/3021211/without_tensor_type.zip)

**Comment by MidoriYakumo** [comment]
Like ONNX, the type info of Paddle model could sometimes be only inferred at runtime.
