### ISSUE TITLE
onnx reshape should have two inputs, but netron only shows one

### ISSUE THREAD

**Issue by jiafatom** [lutzroeder/netron#254]
I have an onnx model with Reshape op, it should have two inputs, see [operator.md](https://github.com/onnx/onnx/blob/master/docs/Operators.md), this schema occurs since opset 2. But when I see in netron, it only shows one input. The other input becomes an isolated node which is not connected to anything in netron.

![reshape_input](https://user-images.githubusercontent.com/30608893/56320506-3606c200-6119-11e9-9295-f8959e707e5b.png)

When I see the document of Reshape, 

![reshape_doc](https://user-images.githubusercontent.com/30608893/56320522-45860b00-6119-11e9-9c6a-19b176db8e54.png)

It shows an old version of schema which is Reshape-1, meaning that this is for onnx opset 1.
but see my model,

![model_version](https://user-images.githubusercontent.com/30608893/56320579-59317180-6119-11e9-95f2-7c0765f47c40.png)

my model is using onnx opset 10. This opset 10 is not officially released as of today (4/17/2019), I just used it from GitHub. Is there any way to fix this Reshape input issue? Thank you!

**Comment by jiafatom** [comment]
this may be related to https://github.com/lutzroeder/netron/issues/253
Does the fix handle the onnx version which is not released yet, like v10 here?

**Comment by lutzroeder** [comment]
Can you try [DEVELOPMENT.md](https://github.com/lutzroeder/netron/blob/master/DEVELOPMENT.md) and verify this now works as expected?

**Comment by lutzroeder** [comment]
Duplicate of #253
