### ISSUE TITLE
Netron is missing Operator Count in Model Properties

### ISSUE THREAD

**Issue by kenkoyanagi** [lutzroeder/netron#255]
Netron builds previously featured Operator Count/Breakdown in the Model Properties pane. I've noticed this crucial feature is missing in the latest builds. Can we expect to see this added again? 

Thanks.

**Comment by lutzroeder** [comment]
#204. Fundamental question here is if this should be 1) part of a UI tool that has no direct dependency to the runtime framework or 2) a feature of the actual runtime framework. Most related feature require #71.

**Comment by postrational** [comment]
+1 Would love to see the Operator Count/Breakdown in Model Properties pane again.

**Comment by lutzroeder** [comment]
Duplicate of #204
