### ISSUE TITLE
how to support user-defined operators

### ISSUE THREAD

**Issue by AmbercatXu** [lutzroeder/netron#256]
My tflite model needed the  the cos() function, which is not supported in tensorflow v1.13.1. so I add some patch to the tensorflow source code, and rebuild it by bazel. Then the tflite mode file with tf.cos() operation can be created, and can be interpreted by tf.lite.Interpreter(), but it cann't be recoginzed by netron.
Netron always said `cannot read property '__offset' of null in 'test.tflite'` when open this tflite file.
I don't know if there is something wrong in my patch, so the created tflite file has something wrong, or I should redirect/update the tensorflow libraries for netron?

this is my test tfile file:
[test.zip](https://github.com/lutzroeder/netron/files/3101992/test.zip)

**Comment by lutzroeder** [comment]
Added a fix for `builtin_options == null`. There is no user-defined operator in this file though?

<img width="852" alt="issue256" src="https://user-images.githubusercontent.com/438516/56484754-fd9f1500-6485-11e9-9217-a8b3871cae5a.png">

**Comment by AmbercatXu** [comment]
Thank you very much!
It seems the `tf.cos()` recognized as `Unique`

**Comment by lutzroeder** [comment]
[0256.tflite.zip](https://github.com/lutzroeder/netron/files/14074688/0256.tflite.zip)
