### ISSUE TITLE
visualize .dat model

### ISSUE THREAD

**Issue by abdou31** [lutzroeder/netron#257]
Hello Sir,
I ask about how can i visualize .dat model file with this tool?
If i can't , do you know any other tool can visualize .dat model? 
Thanks

**Comment by lutzroeder** [comment]
Which tool produces these files, can you provide a format description and sample files?

**Comment by abdou31** [comment]
Openface produce these files , please visit this link : 
https://github.com/TadasBaltrusaitis/OpenFace
