### ISSUE TITLE
int64 tensor value interpreted and displayed as unsigned int64

### ISSUE THREAD

**Issue by spandantiwari** [lutzroeder/netron#264]
I have created a simple model (attached in model.zip below) that has a onnx::Constant node where the `value` attribute is a int64 tensor. In this model, the tensor contains single element which is -1. 

Netron displays the type of the tensor correctly, but the displayed value is incorrect. It seems like the displayed value is interpreted as `uint64` instead of `int64`. 
![model](https://user-images.githubusercontent.com/23646532/56934265-4404fd00-6aa0-11e9-9e2d-0287fc9ff740.png)

Below's the relevant snippet from model's serialized string. As highlighted, the `raw_data` field shown below has -1. To interpret `raw_data`, content of each byte is shown in octal. `377` in octal is a byte full of ones. The entire raw_data has 8 bytes representing a single int64 value (8 bytes), and since all the bytes are octal 377, the binary representation of the int64 value is all 1s. Since the datatype is correctly showing as int64, all ones for 64-bit signed type should be interpreted as -1 (two's complement), but from the figure above, it seem to be interpreted as unsigned int64.
```
ir_version: 4
producer_name: "pytorch"
producer_version: "1.1"
graph {
  node {
    output: "1"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        data_type: INT64
        raw_data: "\377\377\377\377\377\377\377\377"
      }
      20: 4
    }
  }
  node {
    input: "A"
    input: "1"
    output: "output"
    op_type: "Add"
  }


```

[model.zip](https://github.com/lutzroeder/netron/files/3129566/model.zip)

**Comment by spandantiwari** [comment]
@lutzroeder - can the fix be tested in the browser version now?

**Comment by lutzroeder** [comment]
See [DEVELOPMENT.md](https://github.com/lutzroeder/netron/blob/master/DEVELOPMENT.md).
