### ISSUE TITLE
Add a prefix_url to the host

### ISSUE THREAD

**Issue by databill86** [lutzroeder/netron#266]
Is there any way we can add a prefix to the URL :
`self.url = 'http://' + host + ':' + str(port)`
So that we can serve over an adress like : localhost:8080/someprefix ? 
This would be very useful in my case, as I'm running the server behind Nginx. The reverse proxy can't find the static file with this configuration. 
Here is the Nginx config : 

location /myprefix {
      proxy_pass http://localhost:8080/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
}

Without the the trailing slash in localhost:8080/, nginx fails to redirect anything to the server. 

Thank you.

**Comment by lutzroeder** [comment]
What is the actual issue? Supporting a) a prefix option or b) how the URLs are handled via reverse proxy? Goal is to avoid to much complexity around a) unless there is prior art. For b) feel free to submit a PR.

**Comment by databill86** [comment]
The issue is a) supporting a prefix/suffix option.

**Comment by lutzroeder** [comment]
Are there any other tools supporting this approach? Ideally Netron's Python server should remain basic and other tools should be used for more complex routing. Another approach to try might be to serve only the model file and use `https://lutzroeder.github.io/netron?url=...` which is very similar to what the Python server is doing (make sure CORS is enabled).
