### ISSUE TITLE
Separation of generator and viewer

### ISSUE THREAD

**Issue by ZachSaucier** [lutzroeder/netron#271]
I'm trying to make it so that I can have a server running Netron and a client make requests to receive a visualization of the neural network. I got the basic framework of this setup fine using the Python server, but I believe that Netron is currently only set up to host the visualization in a new tab, correct? Not send it back as an object or HTML file?

Is it feasible to add functionality to instead send back a response and have it visualized on the request's page? I have full control over the client's setup, so I can load any handlers necessary on that side to make sure the visualization has full functionality.

**Comment by lutzroeder** [comment]
Netron is an interactive client UI app. Loading and rendering happens in the browser. The Python server is a plain web server serving the HTML/CSS/JS files for the client app. See #162.

**Comment by ZachSaucier** [comment]
Fair enough. I'll load the visualization into an iframe and generate a random port to host it I guess.

Is there a method in Netron to clean up previously created pages? Since the port number is random I need to do some cleanup in order to keep the server running.

**Comment by ZachSaucier** [comment]
Never mind, I just saw the `stop()` method. Sorry about that.

**Comment by lutzroeder** [comment]
The Python server isn't really required. It is entirely possible to load the bits statically from `lutzroeder.github.io/netron` and passing the model via `?url=` or other means. The `view-browser.html` and `view-browser.js` files act as a "hosting layer" and can be swapped for a different implementation.

**Comment by lutzroeder** [comment]
Duplicate of #162
