### ISSUE TITLE
Unwrap Tensor Iterator layer from OpenVINO IR

### ISSUE THREAD

**Issue by iefode** [lutzroeder/netron#274]
Reproducing steps:
1. download xml file with TensorIterator layer, which contain other layers (for example, LSMT cell and etc)
2. Netron visualized only TensorIterator layer without additional information like internal TI layers.
3. Double click on TensorIterator layer. Will created new layout with information about TensorIterator layer (type, name, inputs and outputs)

**Comment by lutzroeder** [comment]
@iefode can you add a sample file to reproduce the issue? @demid5111 can you have a look?

**Comment by iefode** [comment]
@lutzroeder Alexander have access to our project. I will send him link to model is able to reproduce issue
