### ISSUE TITLE
Caffe support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#276]

**Comment by lutzroeder** [comment]
[caffe_invalid_file.mlmodel.zip](https://github.com/lutzroeder/netron/files/3219685/caffe_invalid_file.mlmodel.zip)

**Comment by lutzroeder** [comment]
[caffe_invalid_file.caffemodel.zip](https://github.com/lutzroeder/netron/files/3219686/caffe_invalid_file.caffemodel.zip)

**Comment by lutzroeder** [comment]
[caffe_examples.zip](https://github.com/lutzroeder/netron/files/3288816/caffe_examples.zip)

**Comment by ThummalaJanardhanReddy** [comment]
Hi,
After taking latest code version, .prototxt model throwing error.
"File text format is not caffe.NetParameter (String is too short at 1:6) in 'deply.prototxt'."

var netParameter = caffe.proto.NetParameter.decodeText(reader);

prototxt.js : 
prototxt.TextReader.prototype.string = function() {
    var token = this.read(); // value = ' : '
    if (token.length < 2) {
        throw new Error("String is too short" + this.location());
    }

Model content : 
name: "LeNet"
input: "data"
input_dim: 1
input_dim: 1
input_dim: 28
input_dim: 28
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 20
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}

**Comment by lutzroeder** [comment]
Delete the `node_modules` folder and run `npm install` to get the updated `github:lutzroeder/protobuf.js#pbtxt` bits.

**Comment by lutzroeder** [comment]
[autocolorize.zip](https://github.com/lutzroeder/netron/files/4923194/autocolorize.zip)

**Comment by lutzroeder** [comment]
[feat_ext_C3D_examples_imagenet_alexnet_train.prototxt.zip](https://github.com/lutzroeder/netron/files/5534696/feat_ext_C3D_examples_imagenet_alexnet_train.prototxt.zip)

**Comment by lutzroeder** [comment]
[yolov3_gen.prototext.txt.zip](https://github.com/lutzroeder/netron/files/5615031/yolov3_gen.prototext.txt.zip)
