### ISSUE TITLE
TorchScript support

### ISSUE THREAD

**Issue by houseroad** [lutzroeder/netron#281]
PyTorch models can be saved in TorchScript format as well. (Details about TorchScript models: https://pytorch.org/docs/stable/jit.html#torchscript) 

Can we add the support for TorchScript models?

The serialization details can be found here: https://github.com/pytorch/pytorch/blob/master/caffe2/serialize/inline_container.h#L21

So far, the major problem is that, in the zip file, no graph is saved, instead script is saved. You may want to call some utility function to generate the IR to get the graph.

**Comment by lutzroeder** [comment]
@houseroad Are there any sample files? Given Netron runs in the browser how would the script by  converted into a graph using JavaScript without any dependencies on the torch runtime?

**Comment by lutzroeder** [comment]
[mnist_linear_torchscript.zip](https://github.com/lutzroeder/netron/files/3269066/mnist_linear_torchscript.zip)

**Comment by lutzroeder** [comment]
[mnist_linear_torchscript.zip](https://github.com/lutzroeder/netron/files/3269075/mnist_linear_torchscript.zip)

**Comment by lutzroeder** [comment]
[mnist_linear_torchscript.zip](https://github.com/lutzroeder/netron/files/3585288/mnist_linear_torchscript.zip)

**Comment by lutzroeder** [comment]
[blitz_cifar10_tutorial.zip](https://github.com/lutzroeder/netron/files/3748500/blitz_cifar10_tutorial.zip)

**Comment by lutzroeder** [comment]
[blitz_neural_networks_tutorial.zip](https://github.com/lutzroeder/netron/files/3748989/blitz_neural_networks_tutorial.zip)

**Comment by lutzroeder** [comment]
[mobilenet_quantization_scripted_quantized.zip](https://github.com/lutzroeder/netron/files/3801114/mobilenet_quantization_scripted_quantized.zip)

**Comment by lutzroeder** [comment]
[alexnet_traced.pt.zip](https://github.com/lutzroeder/netron/files/6096602/alexnet_traced.pt.zip)

**Comment by lutzroeder** [comment]
[alexnet.pkl.pth.zip](https://github.com/lutzroeder/netron/files/6096603/alexnet.pkl.pth.zip)

**Comment by lutzroeder** [comment]
[densenet161_traced.pt.zip](https://github.com/lutzroeder/netron/files/6096613/densenet161_traced.pt.zip)
[densenet161.pt.zip](https://github.com/lutzroeder/netron/files/6096614/densenet161.pt.zip)

**Comment by lutzroeder** [comment]
[mobilenet_v2_traced.pt.zip](https://github.com/lutzroeder/netron/files/6096623/mobilenet_v2_traced.pt.zip)
[mobilenet_v2.pt.zip](https://github.com/lutzroeder/netron/files/6096624/mobilenet_v2.pt.zip)

**Comment by lutzroeder** [comment]
[inception_v3_traced.pt.zip](https://github.com/lutzroeder/netron/files/6096627/inception_v3_traced.pt.zip)
[inception_v3.pt.zip](https://github.com/lutzroeder/netron/files/6096628/inception_v3.pt.zip)

**Comment by lutzroeder** [comment]
[r3d_18_traced.pt.zip](https://github.com/lutzroeder/netron/files/6096649/r3d_18_traced.pt.zip)
[r3d_18.pt.zip](https://github.com/lutzroeder/netron/files/6096650/r3d_18.pt.zip)

**Comment by lutzroeder** [comment]
[squeezenet1_1_traced.pt.zip](https://github.com/lutzroeder/netron/files/6096661/squeezenet1_1_traced.pt.zip)
[squeezenet1_1.pt.zip](https://github.com/lutzroeder/netron/files/6096662/squeezenet1_1.pt.zip)

**Comment by lutzroeder** [comment]
[resnet101_traced.pt.zip](https://github.com/lutzroeder/netron/files/6096666/resnet101_traced.pt.zip)
[resnet101.pt.zip](https://github.com/lutzroeder/netron/files/6096667/resnet101.pt.zip)

**Comment by lutzroeder** [comment]
[shufflenet_v2_x1_0_traced.pt.zip](https://github.com/lutzroeder/netron/files/6096670/shufflenet_v2_x1_0_traced.pt.zip)
[shufflenet_v2_x1_0.pt.zip](https://github.com/lutzroeder/netron/files/6096671/shufflenet_v2_x1_0.pt.zip)

**Comment by lutzroeder** [comment]
[mask_depthwise_conv.pt.zip](https://github.com/lutzroeder/netron/files/6186157/mask_depthwise_conv.pt.zip)
[refine_model.pt.zip](https://github.com/lutzroeder/netron/files/6186158/refine_model.pt.zip)
[rpn_model.pt.zip](https://github.com/lutzroeder/netron/files/6186159/rpn_model.pt.zip)

**Comment by lutzroeder** [comment]
Duplicate of #842
