### ISSUE TITLE
Need explanation of info displayed...

### ISSUE THREAD

**Issue by JohnCraigPublic** [lutzroeder/netron#289]
On some of my models displayed in Netron I see:

format  Onnx v3
Imports  ai.onnx v7

and others I see

Format Onnx v4
imports  ai.onnx v9

Question: the v7 or v9 shown at the end of the "imports" info -- do they correspond to "opset 7" and "opset 9" ?

**Comment by lutzroeder** [comment]
Yes.

**Comment by MAhaitao999** [comment]
> Yes.

What about the meaning of "format Onnx v3"?

**Comment by lutzroeder** [comment]
Format is the [version](https://github.com/onnx/onnx/blob/7480638f0de437f724289e230798b698b1e74a70/onnx/onnx.proto#L70) of the ONNX container format. Imports lists the operator [sets](https://github.com/onnx/onnx/blob/7480638f0de437f724289e230798b698b1e74a70/onnx/onnx.proto#L711) used by the model.
