### ISSUE TITLE
Dark Mode/Theme

### ISSUE THREAD

**Issue by csharpner** [lutzroeder/netron#290]
Can we get a dark theme or dark mode for the UI?  I've been switching everything to dark mode as bright UIs hurt my eyes and cause headaches.  Plus, dark mode looks cool too. ;)

Here's an example of what I'd like to see...

![Netron Dark](https://user-images.githubusercontent.com/8125269/60226660-35e21b80-985a-11e9-8a54-0a64ec6123ac.png)

**Comment by lutzroeder** [comment]
This is already supported on macOS (see screenshot in README.md) and in the browser version (Safari and recent Chrome beta). Windows support is blocked by electron/electron#15316 and electron/electron#18119.
