### ISSUE TITLE
Unexpected end of json input

### ISSUE THREAD

**Issue by suryasidd** [lutzroeder/netron#292]
Unable to run netron on Ubuntu 16.04 machine. I get the following error when launching netron.

```
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ConfigurationService.load (/opt/Netron/resources/app.asar/src/app.js:808:39)
    at Application._ready (/opt/Netron/resources/app.asar/src/app.js:91:29)
    at App.<anonymous> (/opt/Netron/resources/app.asar/src/app.js:57:18)
    at App.emit (events.js:199:15)
```

**Comment by lutzroeder** [comment]
Can you share the content of `~/.config/Netron/configuration.json`?

Deleting this file should resolve the issue.

**Comment by suryasidd** [comment]
Its empty should i delete it ?

**Comment by lutzroeder** [comment]
Yes

**Comment by suryasidd** [comment]
I'm getting a 
Unhandled rejection Error: ENOENT: no such file or directory, open '/opt/Netron/resources/app-update.yml'
    at /opt/Netron/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:460:27
    at Generator.next (<anonymous>)

**Comment by lutzroeder** [comment]
The updater error doesn't block the app from running -- right?

See #166, electron-userland/electron-builder#2364 and electron-userland/electron-builder#1138.

**Comment by suryasidd** [comment]
For me the app flashes and closes immediately. When i try to run it from the terminal, it shows me this error.

**Comment by lutzroeder** [comment]
Can you try the `.AppImage` instead of `.deb`?
