### ISSUE TITLE
hd5 support?

### ISSUE THREAD

**Issue by MehradAria** [lutzroeder/netron#293]
why not also hd5 format support for keras models?
why only h5?

**Comment by lutzroeder** [comment]
Do you have any examples of `hd5` files? Is it the same format with a different extension?

**Comment by MehradAria** [comment]
hd5, h5 and hdf5 are different extensions for the same format (Hierarchical Data).
[here](https://github.com/isi-vista/BusterNet/blob/master/Model/pretrained_busterNet.hd5)'s an example.
