### ISSUE TITLE
ncnn support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#296]
@nihui @BUG1989

**Comment by nihui** [comment]
wow, that's awesome !

**Comment by lutzroeder** [comment]
[ssdmobilenet.zip](https://github.com/lutzroeder/netron/files/5165601/ssdmobilenet.zip)

**Comment by lutzroeder** [comment]
[rnn-lstm-gru.zip](https://github.com/lutzroeder/netron/files/5800011/rnn-lstm-gru.zip)
