### ISSUE TITLE
Error loading tflite model

### ISSUE THREAD

**Issue by criss2525** [lutzroeder/netron#297]
I am trying to load this model into the tool but I get the error shown below:
I tried different combinations of OS & browsers but the problem persists: I tried Linux Ubuntu ( firefox and chrome) as well as Windows10. I also tried to install the tool on Linux but the same problem persisted. Any ideas?

Error loading TensorFlow Lite model. Invalid FlatBuffers signature 'ion ' in 'TFLITE model' in 'TFLITE MODEL'.

**Comment by lutzroeder** [comment]
Can you share the file? Likely it is not in ‘.tflite’ format.
