### ISSUE TITLE
print weight parameter value to txt or excel file

### ISSUE THREAD

**Issue by atrah22** [lutzroeder/netron#300]
Hello,

Is there any plan to provide options to printout the weight parameter values to txt file ?

**Comment by lutzroeder** [comment]
Save the tensor to disk as `.npy`:

<img width="499" alt="screenshot" src="https://user-images.githubusercontent.com/438516/61661284-89406180-ac80-11e9-8186-916701643bcb.png">

```
import numpy
x = numpy.load('tensor.npy')
numpy.savetxt('tensor.csv', x, delimiter=',')
```

**Comment by atrah22** [comment]
@lutzroeder I am visualizing a quantized tflite model. Saving the tensor to disk as .npy failed "NumPy Error: Unknown data type 'quint8'."

**Comment by keshavoct98** [comment]
> Save the tensor to disk as `.npy`:
> 
> <img alt="screenshot" width="499" src="https://user-images.githubusercontent.com/438516/61661284-89406180-ac80-11e9-8186-916701643bcb.png">
> 
> ```
> import numpy
> x = numpy.load('tensor.npy')
> numpy.savetxt('tensor.csv', x, delimiter=',')
> ```

I couldn't find it. Can you tell me the exact steps to export it to .npy.?

**Comment by lutzroeder** [comment]
<img width="1092" alt="Screen Shot 2020-01-25 at 10 50 06 AM" src="https://user-images.githubusercontent.com/438516/73125889-ff3fc100-3f60-11ea-8f6f-49211a6e34dd.png">

**Comment by keshavoct98** [comment]
This only saves the weights of that particular node. Can we save weights of whole network in a single file?

**Comment by lutzroeder** [comment]
#450 tracking exporting weights file.

**Comment by lutzroeder** [comment]
Duplicate of #1152
