### ISSUE TITLE
Summary of Parameters (trainable & non-trainable)

### ISSUE THREAD

**Issue by Asorie** [lutzroeder/netron#301]
It would be nice to see in the overview of the model summary of parameters (trainable & non-trainable) for the whole model.

**Comment by lutzroeder** [comment]
For which model format and how is this determined from the model file?

**Comment by Asorie** [comment]
Sry for the late answer. For keras-models its possible to get the weights with `mode.weights()`. This returns all the weights for the different layers. To count all the weights this function can be used:

`np.sum([np.prod(v.get_shape().as_list()) for v in model.weights])`

**Comment by lutzroeder** [comment]
What summary do you expect to see - only the total number of layers?

**Comment by Asorie** [comment]
Exactly, the total number of (trainable & non-trainable) weights tensors.

**Comment by liziru** [comment]
@lutzroeder  It's necessary to view the total number of models.

**Comment by Wenuka** [comment]
This would be a good thing to add.

**Comment by orena1** [comment]
@lutzroeder where can one see that ?
