### ISSUE TITLE
Integrating Netron into Dash Web Application

### ISSUE THREAD

**Issue by Aprilhuu** [lutzroeder/netron#302]
Hi,

I am developing a website using Dash (https://plot.ly/dash/) and React (https://reactjs.org/). I saw your app and it exactly fits part of our needs, so we are considering turning it into a widget using React and integrating it into our dashboard written in Dash. Do you think it is feasible? Do you have any suggestions on this integration or are there any better options? Any help will be really valuable.

Thanks,
April

**Comment by lutzroeder** [comment]
With CORS enabled you can pass the model via `?url=`. 

For example: https://lutzroeder.github.io/netron/?url=https://ibelem.github.io/webml-website/examples/image_classification/model/squeezenet1.1.onnx.
