### ISSUE TITLE
Auto update notification

### ISSUE THREAD

**Issue by MehradAria** [lutzroeder/netron#304]
**Auto update checker** and maybe **auto update installer** would be a great option to add.

**Comment by lutzroeder** [comment]
Can you explain? Current versions support auto update.

**Comment by MehradAria** [comment]
> 
> 
> Can you explain? Current versions support auto update.

I've never received any notification about available updates. there isn't any manual update check option either. I always check releases for new versions. :-/

**Comment by lutzroeder** [comment]
Duplicate of #1514
