### ISSUE TITLE
Dark theme on windows?

### ISSUE THREAD

**Issue by MehradAria** [lutzroeder/netron#305]
Could we have an "internal" option to change themes?
Having the dark theme on windows like [macOS version](https://raw.githubusercontent.com/lutzroeder/netron/master/media/screenshot.png) would be great.

I know about [this](https://github.com/electron/electron/issues/15316) bug but what i mean is a stand alone option regardless of windows theme mode.

**Comment by lutzroeder** [comment]
Duplicate #290

**Comment by lutzroeder** [comment]
There are no plans for a standalone option. Electron added dark mode support for Windows. Can you try latest Electron betas to see if this works?

**Comment by MehradAria** [comment]
sure, how can i do so? replacing beta files didn't work.

**Comment by lutzroeder** [comment]
@MehradAria `electron 6.0.0` is now public. Can you clone master, run `npm install` and `npm electron .` on a Windows machine to see if this works. Also `npm eletron-builder --win` and run `.\build\win-unpacked\Netron.exe` to see if there are any issues. It should now use the system dark mode setting.
