### ISSUE TITLE
Zooming and moving is not working with laptop touchscreen

### ISSUE THREAD

**Issue by GlebKazantaev** [lutzroeder/netron#308]
Some times ago amazing feature with touchscreen manipulation was broken, and now we can't move/zoom model with our fingers. We are really struggling...

**Comment by lutzroeder** [comment]
@GlebKazantaev can you investigate when this happened? I don't have a torch screen available.

**Comment by lutzroeder** [comment]
If you have a computer with a touch screen, would be great if you can debug why this is happening.

**Comment by GlebKazantaev** [comment]
@lutzroeder starting from 3.3.4 version it works as expected! So I'm closing this bug :)
