### ISSUE TITLE
Set CORS policy to be able to load models from GitHub URLs

### ISSUE THREAD

**Issue by lgeiger** [lutzroeder/netron#312]
Thanks for developing netron, it is a great visualisation tool when developing models.

### Describe the bug

When loading a model via a GitHub URL netron will fail when redirecting due to the CORS policy set in netron.

### To Reproduce
1. Navigate to: https://lutzroeder.github.io/netron/?url=https://github.com/hollance/YOLO-CoreML-MPSNNGraph/raw/master/Convert/yad2k/model_data/tiny-yolo-voc.h5 (the model link is copied from the netron README)
2. Netron won't load the model and will print the following error in the developer console:
   ```
   Access to XMLHttpRequest at 'https://github.com/hollance/YOLO-CoreML-MPSNNGraph/raw/master/Convert/yad2k/model_data/tiny-yolo-voc.h5?1565007583282' from origin 'https://lutzroeder.github.io' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://render.githubusercontent.com' that is not equal to the supplied origin.
   ```
### Expected behavior
Netron should behave the same when loading the models from `raw.githubusercontent.com` or from `github.com` directly. E.g the following URL works and gives returns the same model: https://lutzroeder.github.io/netron/?url=https://raw.githubusercontent.com/hollance/YOLO-CoreML-MPSNNGraph/master/Convert/yad2k/model_data/tiny-yolo-voc.h5

### Motivation
We are publishing pretrained binarized models in https://github.com/larq/zoo which are stored as assets in GitHub releases. We would like to provide a link to the models visualised by netron, but it is not possible to get a static `raw.githubusercontent.com` for those assets, instead GitHub redirects to a S3 address which might change in the future.

**Comment by lutzroeder** [comment]
How can this be enabled? CORS is a server setting?

**Comment by lgeiger** [comment]
I am not sure. Probably one cannot modify the GitHub pages settings.

Could this worked around by resolving the the URL redirect before making the request or, would that trigger the same CORS warning?

**Comment by lutzroeder** [comment]
You can publish the repo to ‘github.io’. That way it should be on the same domain and might work.

**Comment by lgeiger** [comment]
For future readers, using a CORS proxy like https://cors-anywhere.herokuapp.com/ works well: https://lutzroeder.github.io/netron/?url=https://cors-anywhere.herokuapp.com/https://github.com/larq/zoo/releases/download/birealnet-v0.2.0/birealnet.h5
