### ISSUE TITLE
TorchScript graph cannot be visualized

### ISSUE THREAD

**Issue by farkhor** [lutzroeder/netron#313]
Netron outputs the error ``Cannot read property 'type' of undefined in FILENAME`` upon opening the ``.pt`` torchscript model. Tried it with Pytorch versions 1.0 and 1.1 on Ubuntu 16.04.

The issue can be reproduced for this simple mnist example [here](https://github.com/pytorch/examples/blob/master/mnist/main.py) by adding ``@torch.jit.script_method`` decorator on the ``forward`` method and saving the model using ``torch.jit.save``.

**Comment by lutzroeder** [comment]
Can you share the actual code and `.pt` file?

**Comment by farkhor** [comment]
Below is the same program creating [this ``.pt`` file](https://drive.google.com/file/d/19kHJizHp1bV8jy_oJTiZXHXO_8vr2eI3/view?usp=sharing) with Pytorch 1.1.0 on Ubuntu 16.04:
```py
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(torch.jit.ScriptModule):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5, 1)
        self.conv2 = nn.Conv2d(20, 50, 5, 1)
        self.fc1 = nn.Linear(4*4*50, 500)
        self.fc2 = nn.Linear(500, 10)

    @torch.jit.script_method
    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2, 2)
        x = x.view(-1, 4*4*50)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x, dim=1)


model = Net()
torch.jit.save(model, 'mod.pt')
```
My Netron is at version 3.3.0.

**Comment by lutzroeder** [comment]
[netron_issue_313.zip](https://github.com/lutzroeder/netron/files/3540511/netron_issue_313.zip)

**Comment by lutzroeder** [comment]
[netron_issue_313.zip](https://github.com/lutzroeder/netron/files/3715300/netron_issue_313.zip)

**Comment by lutzroeder** [comment]
[netron_issue_313.zip](https://github.com/lutzroeder/netron/files/3721266/netron_issue_313.zip)
