### ISSUE TITLE
keras .Siamese network draw faults

### ISSUE THREAD

**Issue by lsh1994** [lutzroeder/netron#314]
Thanks for your work. But the siamese network draw faults. It draw many patch.  I use keras.

**Comment by lutzroeder** [comment]
Can you provide a sample file?

**Comment by lsh1994** [comment]
![image](https://user-images.githubusercontent.com/14355014/62528063-d3276b00-b86e-11e9-9010-07bb664247c8.png)
but keras plt_model show as:

**Comment by lsh1994** [comment]
![image](https://user-images.githubusercontent.com/14355014/62528435-72e4f900-b86f-11e9-9485-0052961820de.png)

**Comment by lutzroeder** [comment]
Can share the `.h5` file? also see #130.

**Comment by lsh1994** [comment]
I just upload the file in: 
https://github.com/lsh1994/CodeShare/blob/master/nothing_temp/rs_game_model.h5.

Thanks for you work. It is amazing.

**Comment by lutzroeder** [comment]
[rs_game_model.zip](https://github.com/lutzroeder/netron/files/3490404/rs_game_model.zip)
