### ISSUE TITLE
The way to add new schema

### ISSUE THREAD

**Issue by chenzomi12** [lutzroeder/netron#315]
Could our organization add new schema into NETRON? If I can, could you show me the basic way?

**Comment by lutzroeder** [comment]
What format do you want to add and why is there a need for yet another format?

Best way to get started is to look at `src/view.js` and the extension in the `ModelFactoryService` constructor. Add an entry and extension for `./foo` and then implement a `./src/foo.js` similar to the other formats starting with a `foo.ModelFactory` that has `match` the detect the content is valid and `open` to create the `foo.Model`.

**Comment by chenzomi12** [comment]
Your answer is so Great with many details! It helps a lot. For the reason to add another format because we develop our own SOC chip to accelerate these new format but also the framework like Tensorflow. And your program is very friendly to visualization!

On more question, after finished all the code as you said. How to build the windows exe file?  BTW: I hope to contribute codes to your project in the near future with your permission.

**Comment by lutzroeder** [comment]
Duplicate of #1308
