### ISSUE TITLE
Scrollbars of node properties are too wide to select text in Mac Edition

### ISSUE THREAD

**Issue by Jerzha** [lutzroeder/netron#319]
![image](https://user-images.githubusercontent.com/13013845/62846179-8de8ba80-bd00-11e9-95a1-b5c731870c9d.png)

I can't select the name for copying it :(

**Comment by lutzroeder** [comment]
Can you share the model file?

**Comment by Jerzha** [comment]
Model file:
https://1drv.ms/u/s!AptzmNNWT7VUmXhBVW2Dy68TKgCe?e=0lOQR8

**Comment by lutzroeder** [comment]
How do you get into the state that prevents selection and copying? The scrollbar only shows temporarily when you scroll the control and fades away after a second. Double click also works to select the content.

**Comment by Jerzha** [comment]
I think it's MAC's bug. The scrollbar is never hidden before.
After upgrading OSX, everything is  fine.
This issue could be closed.
