### ISSUE TITLE
Cannot open large models

### ISSUE THREAD

**Issue by zengzhi2015** [lutzroeder/netron#323]
It seems that the app cannot open large models like DeepLab. You could try this model. (I can open this using TensorBoard.)

[graph.zip](https://github.com/lutzroeder/netron/files/3539403/graph.zip)

**Comment by lutzroeder** [comment]
Duplicate of #68

**Comment by lutzroeder** [comment]
[0323.pbtxt.zip](https://github.com/lutzroeder/netron/files/14074343/0323.pbtxt.zip)
