### ISSUE TITLE
Questions about ONNX model input type

### ISSUE THREAD

**Issue by qw2208** [lutzroeder/netron#327]
Can we get the onnx type of the inputs?
For example, for outputs:
![image](https://user-images.githubusercontent.com/24438413/64146834-f5ea7680-ce50-11e9-8019-459a86ba6654.png)
we could get the output types of sequence<map<int, float>>. I'm wondering if the inputs could display the types as well?

**Comment by lutzroeder** [comment]
In the screenshot the input is a string array of size [1,2]?

**Comment by qw2208** [comment]
Actually I am wondering if input type of sequence of map could be shown?

**Comment by lutzroeder** [comment]
Why?

**Comment by qw2208** [comment]
I mean if one day I have a model whose input is sequence of map, could it be shown?

**Comment by lutzroeder** [comment]
Yes, it should show that.
