### ISSUE TITLE
Can't display Mask R-CNN model properly

### ISSUE THREAD

**Issue by Jerzha** [lutzroeder/netron#328]
Version: 3.3.2
Model: 
https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5
OR:
https://download.pytorch.org/models/maskrcnn/e2e_mask_rcnn_R_101_FPN_1x.pth

![image](https://user-images.githubusercontent.com/13013845/64226065-791ed180-cf10-11e9-9872-ef63773c5b86.png)

**Comment by lutzroeder** [comment]
These files only include weight tensors and no model graph?

**Comment by Jerzha** [comment]
It's include model graph. 
The second one come from Facebook Model Zoo that is a completed model.
