### ISSUE TITLE
Unable to visualize torch jit files [3.3.2 -> 3.3.3]

### ISSUE THREAD

**Issue by SrivastavaKshitij** [lutzroeder/netron#333]
Netron is not able to visualize standard torchvision models (saved in jit format) in version `3.3.3.` which was possible with `3.3.2`

Visualizing with `3.3.2`:

![Screenshot from 2019-09-11 09-42-32](https://user-images.githubusercontent.com/19312052/64703486-85f47580-d47a-11e9-8b65-724dc9c5bd22.png)

Visualizing with `3.3.3`:

![Screenshot from 2019-09-11 09-43-05](https://user-images.githubusercontent.com/19312052/64703605-cbb13e00-d47a-11e9-9c7d-8990e61845b4.png)

**Comment by lutzroeder** [comment]
Can you share the model file?

**Comment by SrivastavaKshitij** [comment]
File is too big to be shared here. However, the way the `jit` file can be created is :

```
import torch
import resnet

model = resnet.resnet50()
model = model.eval()
example_input = torch.rand(args.batch_size, 3, 224, 224, dtype=torch.float)
model = torch.jit.trace(model, example_input, check_trace=True, check_tolerance=1e-05, optimize=False,)
torch.jit.save(model, "resnet50_imagenet_unoptimized_jit.pt")
```

**Comment by lutzroeder** [comment]
@SrivastavaKshitij @houseroad The TorchScript format keeps changing. Which PyTorch version was this file created with? Without actual models available this will likely keep regressing.
