### ISSUE TITLE
PyTorch block expansion

### ISSUE THREAD

**Issue by hwasiti** [lutzroeder/netron#338]
I have this custom pytorch model (saved as .pth) and wonder whether it is possible to expand blocks that has a plus sign '+'.  Clicking over it does not seem to do anything.

Here is .pth model file:
[https://drive.google.com/open?id=1aK5p0sUbxjn1bmIlb2JZqgGZRsDqTfNT](https://drive.google.com/open?id=1aK5p0sUbxjn1bmIlb2JZqgGZRsDqTfNT)

Here is a picture:

![ScreenClip](https://user-images.githubusercontent.com/4212742/65830960-c1020000-e2e6-11e9-9ea7-579c449113c5.png)

**Comment by lutzroeder** [comment]
The subgraphs aren't stored in `.pth` files directly. Some modules include Python code which could be parsed similar to #281. Visualization would require #68.
