### ISSUE TITLE
GUI output is confusing for AlexNet batchnorm layers

### ISSUE THREAD

**Issue by abyszuk** [lutzroeder/netron#339]
Hi,
When I open AlexNet and look at one of the batchnorm layers, GUI labels don't match the variable names they are pointing to.  
<img width="360" alt="image" src="https://user-images.githubusercontent.com/2649455/66116021-4e3ca180-e5d2-11e9-88a5-fddd691de99b.png">

**Comment by lutzroeder** [comment]
Which format is that for and can you share a sample file?
