### ISSUE TITLE
Possibility of having a log file with the details of the graph 

### ISSUE THREAD

**Issue by Inesbenhmida** [lutzroeder/netron#344]
Hi, 

First I want to thank you for this great tool that I am using in my day to day neural network model visualization. 

Second, I wanted to ask you if there is during the process a log file that is generated with the details of the graph (node names input type and input shape for every node and most importantly for me the edges between the nodes) 
I tried to go through the source code to see where you extract these specifications but I am quiet new to Javascript. 

So my question is : is there a file that is generated during the process that contains the details of the model ( in my case a tensorflow frozen graph) and if not would there be a possibility to add it within netron?
Thank you in advance for your response. 

Best Regards, 
Inès

**Comment by lutzroeder** [comment]
There are currently no plans to support this. Can you describe why this is needed and which format you are using?

**Comment by Inesbenhmida** [comment]
Thank you for your response. I need to extract nodes and edges from my tensorflow graph for a smart mapping of my operations to my specific hardware. I need it to be automated and in the cost model I am trying to establish I would need to reconstruct the graph with the nodes specifications and edges. All the informations that I need are displayed by netron so I guess at a certain point you extract these informations from the graph. Could you may be please give me a hint where this is done because I am new to Javascript? 
Thank you again for your response.

**Comment by lutzroeder** [comment]
The right approach is probably to write a Python script that loads the TensorFlow protobuf directly and writes to console.
