### ISSUE TITLE
Keras: Weight groups

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#350]
https://www.kaggle.com/ashishpatel26/beginner-tutorial-nasnet-pneumonia-detection
https://www.kaggle.com/weeang763162/capsulenet-on-mnist-2ddbca/code
https://github.com/rcmalli/keras-squeezenet/releases
https://github.com/XifengGuo/CapsNet-Keras

**Comment by Fannettembrown** [comment]
Algorithms would be a good search for medical resource.
