### ISSUE TITLE
Please put the source tarball on PyPI so that it would be possible to install it with python's distutils

### ISSUE THREAD

**Issue by yurivict** [lutzroeder/netron#357]
https://pypi.org/project/netron/

**Comment by lutzroeder** [comment]
Can you provide some context why this is needed?

**Comment by yurivict** [comment]
To enable packaging. Packages for python projects are typically created with distutils. Otherwise most users have no chance to see netron because people mostly install software using packages these days.

**Comment by lutzroeder** [comment]
What kind of "packaging", what are examples? How is this different from `pip install netron` and why does it require a source tarball?

**Comment by yurivict** [comment]
packaging like OS-level package creation, for example rpm/yum in Renhat/Fedora, apt-get in Debian, pkg in FreeBSD.

They all require sources to build and install.

```pip``` is a python-specific packaging system. People mosty use OS-level packages to search for/install software, which is language-neutral.

TensorFlow for example is available this way for many systems: https://repology.org/project/tensorflow/versions

**Comment by lutzroeder** [comment]
The Netron `pip` package is used to launch Netron as a Python server and is language-specific. It should not be used without Python. 

The Netron client app and website get packaged through `electron-builder` and uploaded as `deb`, `AppImage` including source to https://github.com/lutzroeder/netron/releases. The script also pushes to `snap` but it's still experimental.

**Comment by yurivict** [comment]
When I take the tarball from GitHub and run a normal build procedure it fails:
```
error: can't copy 'node_modules/d3/dist/d3.min.js': doesn't exist or not a regular file
```

**Comment by lutzroeder** [comment]
What is a normal build procedure (what does it trigger) and what should it produce?

**Comment by yurivict** [comment]
```python setup.py config && python setup.py build && python setup.py install```
It takes the source tree and installs the package into a given directory.

**Comment by lutzroeder** [comment]
Running `npm install` first should resolve this, and there might be a way to run it as part of `python build` but not sure this is what you are actually looking for? For example, `apt install` should probably install the actual client app which is built via `npx electron-builder --linux` and is not using the python setup scripts at all. It might be helpful if you can provide some context of what you are trying to accomplish. What is the scenario and why does it need to get solved?

**Comment by yurivict** [comment]
> Running npm install first should resolve this

```npm install``` is unsafe. It downloads files from GitHub without checking their fingerprints. When a package is created all sources it is built from are fingerprinted. It is this way in for RedHat rpms, Debian debs, and FreeBSD pkg packages.

They just don't create packages for npm-based projects due to safety concerns.

**Comment by lutzroeder** [comment]
Are you planning to work on `electron-builder` and `npm` to fix those issues? `electron-builder` has an option to publish `rpm` to GitHub releases but sounds like this is not what you are looking for and probably would require some evidence this is actually needed. What exactly is the scenario you are trying to solve and why?

**Comment by yurivict** [comment]
> What exactly is the scenario you are trying to solve and why?

I was trying to build a package for ```netron``` so that it could be installed by users, but it doesn't seem that this can be done, because NodeJS's npm is inherently unsafe, and you are just looking for ways to push that unsafe code to users. RedHat and debian don't build rpms for npm projects due to security concerns. You seem to be trying to just ignore this.

**Comment by jiapei100** [comment]
> When I take the tarball from GitHub and run a normal build procedure it fails:
> 
> ```
> error: can't copy 'node_modules/d3/dist/d3.min.js': doesn't exist or not a regular file
> ```

Same here.... Exactly the same error message.
