### ISSUE TITLE
pytorch have some problem

### ISSUE THREAD

**Issue by zjp99** [lutzroeder/netron#359]
My model load shows 100 modules with no wires.
.pth   in https://github.com/xingyizhou/CenterNet
Use CenterNet  ----> ctdet_coco_dla_2x.pth   for detection

**Comment by lutzroeder** [comment]
Duplicate of #133

**Comment by lutzroeder** [comment]
Duplicate of #720

**Comment by lutzroeder** [comment]
Duplicate of #720
