### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by postrational** [lutzroeder/Netron#36]
It would be great to use some colors to add more information to the visual representation of graph. Constants could be one color, activation functions another color, etc.

**Comment by lutzroeder** [comment]
Latest version shows Constant nodes in a darker share of gray (not really a color). Generally graph initializers seem to be preferable to Constant nodes and most converters are using them now. Initializers will render in-place inside the operator node which is using them making the graph look a lot more compact. Do you have recommendations beyond Constant or not or is this the main request?

**Comment by lutzroeder** [comment]
Like the idea and looks like a bunch of things are needed here:

1) What are the right categories for operators? `reduction`, `activation`, `training`?
2) `OnnxNode`, `TensorFlowNode` etc would need a `category` property. Where is this category derived from? Should this be added to `ops.pbtxt` or `onnx` frameworks?
3) Maybe some designer input on how to match categories to some nice looking color palettes. Pioneering a single scheme and set of categories to follow will probably lead to a better outcome than adding lots of knobs and potions for users to customize colors. This seems to be less 'what colors do you like' and more 'what is the standardized color for activation'?

**Comment by lutzroeder** [comment]
a9f3832 adds color basic support.

**Comment by lutzroeder** [comment]
347d9ae3

**Comment by alexjung** [comment]
Is there some documentation to what the colors mean? I definitely can see patterns but it would be nice to know what color indicates a specific category.
