### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by postrational** [lutzroeder/Netron#37]
When dealing with a large graph, it would be great to hit Ctrl-F/Cmd-F and open a search dialog. 

All operations matching search could be highlighted in the graph, if only one is found zoom and pan could bring it into focus.

It would be great to search by name, but attribute values, operation types, etc. could also generate matches.

**Comment by lutzroeder** [comment]
Great idea.

**Comment by cybertk** [comment]
+1, need this feature especially for large network

**Comment by lutzroeder** [comment]
Find dialog shortcut is <kbd>Cmd</kbd>+<kbd>F</kbd> or <kbd>Ctrl</kbd>+<kbd>F</kbd>.
