### ISSUE TITLE
Darknet cfg convolution weights dimensions

### ISSUE THREAD

**Issue by Legorock** [lutzroeder/netron#370]
I noticed that when I use Darknet's .cfg files and visualize the network topology, I got 4D weights like 3x3x3x(# of filters). I think you are using 'channels' information in the .cfg file for all weights channels. This seems to be wrong since the input feature map channel dimension is equal to the previous convolution # of filters. Also, see the actual page for detailed rundown of this topology. 
[Tiny Darknet](https://pjreddie.com/darknet/tiny-darknet/)
![darknet_netron](https://user-images.githubusercontent.com/6500946/68677324-3571c500-055c-11ea-86d0-e3c861ee4be7.png)

If I missed something or have a false assumption, feel free to correct me ;)

**Comment by Legorock** [comment]
Hi,
If I had some free time, I would love to help. Unfortunately, this might not be as simple as it seems.
Since darknet topology configurations do not have this kind of information embedded inside, we need some sort of 'shape inference' to figure the intermediate operators tensor shapes. 

Cheers

Looking at ONNX which is the most mature in this context, they still have major problems with their shape inference. If you can think of other simpler ways to fix these kinds of issues, I may be willing to help in the near future. I didn't try but I suspect other neural network formats that are missing intermediate tensor shape info can have this issue as well.

**Comment by lutzroeder** [comment]
Yes, good summary. Darknet source is fairly straightforward and readable so it's probably easier to bring these over than for other formats. See also #71.
