### ISSUE TITLE
Netron does not work with OpenVINO IR v7

### ISSUE THREAD

**Issue by dorloff** [lutzroeder/netron#372]
Loading the attached IR file (in OpenVINO format) fails with the message: "Unknown precision 'null' in 'ir.xml'".
[ir.xml.zip](https://github.com/lutzroeder/netron/files/3846426/ir.xml.zip)

**Comment by demid5111** [comment]
@lutzroeder it seems to be an issue that I resolved yesterday about OpenVINO IR. Let me check, if so, I will add this example as a test (not artificial example that I wanted to prepare myself)

**Comment by lutzroeder** [comment]
```
TypeError: Cannot read property '_inputs' of undefined
    at openvino.Graph._replaceTensorIteratorWithSubgraph (/Users/lutzroeder/Projects/netron/src/openvino.js:281:32)
    at new openvino.Graph (./netron/src/openvino.js:129:14)
    at new openvino.Model (./netron/src/openvino.js:70:21)
    at ./netron/src/openvino.js:55:24
```

**Comment by demid5111** [comment]
@lutzroeder this is an extremely interesting and complex scenario - it will take more time to investigate than I expected, I will let you know when it is fixed (hopefully a couple of days)

**Comment by lutzroeder** [comment]
[netron_issue_372.zip](https://github.com/lutzroeder/netron/files/4447843/netron_issue_372.zip)
