### ISSUE TITLE
Keras submodel inner dependency

### ISSUE THREAD

**Issue by akkaze** [lutzroeder/netron#376]
In my model,there is a submodel having two output,one depends on the other.
Howerver,in the graph,this dependency is not showed as an edge

**Comment by lutzroeder** [comment]
Can you share the model file?

**Comment by akkaze** [comment]
This file is too big to upload,can i have your email address？

**Comment by akkaze** [comment]
The model is at [https://raw.githubusercontent.com/akkaze/model_file/master/yolo3_backbone.h5](model)
Please download by yourself
Pay attention to the layer named **yolo_darknet_maxpooling_4**
