### ISSUE TITLE
Netron cannot open graph with too many nodes

### ISSUE THREAD

**Issue by kobemini** [lutzroeder/netron#380]
hi， netron is good.  But when there are too many nodes in the graph, it is too slow or unable to open . Only patience and determination will keep you waiting.. So I want to ask if there is room for optimization
![netron](https://user-images.githubusercontent.com/12507968/70202865-ff3bf580-1755-11ea-8897-c9798561be4d.PNG)

**Comment by lutzroeder** [comment]
Duplicate of #68
