### ISSUE TITLE
Error loading ncnn model. Invalid signature in 'mobilenet_v2.param'

### ISSUE THREAD

**Issue by yippeesoft** [lutzroeder/netron#385]
app : win 3.6.2
web:https://lutzroeder.github.io/netron/

test file： mobilenet.param

https://github.com/Tencent/ncnn/tree/master/benchmark

**Comment by lutzroeder** [comment]
`mobilefacenet.param` does not exist in https://github.com/Tencent/ncnn/tree/master/benchmark?

**Comment by yippeesoft** [comment]
mobilenet.param

and :Error loading ncnn model. Invalid signature in 'mobilenet_yolov3.param'.
```` etc

**Comment by lutzroeder** [comment]
Are you running the latest version of Netron and can you check the file has this content when opening in an editor?

```
7767517
31 31
Input                    data                     0 1 data 0=224 1=224 2=3
Convolution              conv1                    1 1 data conv1_relu1 0=32 1=3 3=2 4=1 5=1 6=864 9=1
ConvolutionDepthWise     conv2_1/dw               1 1 conv1_relu1 conv2_1/dw_relu2_1/dw 0=32 1=3 4=1 5=1 6=288 7=32 9=1
Convolution              conv2_1/sep              1 1 conv2_1/dw_relu2_1/dw conv2_1/sep_relu2_1/sep 0=64 1=1 5=1 6=2048 9=1
ConvolutionDepthWise     conv2_2/dw               1 1 conv2_1/sep_relu2_1/sep conv2_2/dw_relu2_2/dw 0=64 1=3 3=2 4=1 5=1 6=576 7=64 9=1
Convolution              conv2_2/sep              1 1 conv2_2/dw_relu2_2/dw conv2_2/sep_relu2_2/sep 0=128 1=1 5=1 6=8192 9=1
ConvolutionDepthWise     conv3_1/dw               1 1 conv2_2/sep_relu2_2/sep conv3_1/dw_relu3_1/dw 0=128 1=3 4=1 5=1 6=1152 7=128 9=1
Convolution              conv3_1/sep              1 1 conv3_1/dw_relu3_1/dw conv3_1/sep_relu3_1/sep 0=128 1=1 5=1 6=16384 9=1
ConvolutionDepthWise     conv3_2/dw               1 1 conv3_1/sep_relu3_1/sep conv3_2/dw_relu3_2/dw 0=128 1=3 3=2 4=1 5=1 6=1152 7=128 9=1
Convolution              conv3_2/sep              1 1 conv3_2/dw_relu3_2/dw conv3_2/sep_relu3_2/sep 0=256 1=1 5=1 6=32768 9=1
ConvolutionDepthWise     conv4_1/dw               1 1 conv3_2/sep_relu3_2/sep conv4_1/dw_relu4_1/dw 0=256 1=3 4=1 5=1 6=2304 7=256 9=1
Convolution              conv4_1/sep              1 1 conv4_1/dw_relu4_1/dw conv4_1/sep_relu4_1/sep 0=256 1=1 5=1 6=65536 9=1
ConvolutionDepthWise     conv4_2/dw               1 1 conv4_1/sep_relu4_1/sep conv4_2/dw_relu4_2/dw 0=256 1=3 3=2 4=1 5=1 6=2304 7=256 9=1
Convolution              conv4_2/sep              1 1 conv4_2/dw_relu4_2/dw conv4_2/sep_relu4_2/sep 0=512 1=1 5=1 6=131072 9=1
ConvolutionDepthWise     conv5_1/dw               1 1 conv4_2/sep_relu4_2/sep conv5_1/dw_relu5_1/dw 0=512 1=3 4=1 5=1 6=4608 7=512 9=1
Convolution              conv5_1/sep              1 1 conv5_1/dw_relu5_1/dw conv5_1/sep_relu5_1/sep 0=512 1=1 5=1 6=262144 9=1
ConvolutionDepthWise     conv5_2/dw               1 1 conv5_1/sep_relu5_1/sep conv5_2/dw_relu5_2/dw 0=512 1=3 4=1 5=1 6=4608 7=512 9=1
Convolution              conv5_2/sep              1 1 conv5_2/dw_relu5_2/dw conv5_2/sep_relu5_2/sep 0=512 1=1 5=1 6=262144 9=1
ConvolutionDepthWise     conv5_3/dw               1 1 conv5_2/sep_relu5_2/sep conv5_3/dw_relu5_3/dw 0=512 1=3 4=1 5=1 6=4608 7=512 9=1
Convolution              conv5_3/sep              1 1 conv5_3/dw_relu5_3/dw conv5_3/sep_relu5_3/sep 0=512 1=1 5=1 6=262144 9=1
ConvolutionDepthWise     conv5_4/dw               1 1 conv5_3/sep_relu5_3/sep conv5_4/dw_relu5_4/dw 0=512 1=3 4=1 5=1 6=4608 7=512 9=1
Convolution              conv5_4/sep              1 1 conv5_4/dw_relu5_4/dw conv5_4/sep_relu5_4/sep 0=512 1=1 5=1 6=262144 9=1
ConvolutionDepthWise     conv5_5/dw               1 1 conv5_4/sep_relu5_4/sep conv5_5/dw_relu5_5/dw 0=512 1=3 4=1 5=1 6=4608 7=512 9=1
Convolution              conv5_5/sep              1 1 conv5_5/dw_relu5_5/dw conv5_5/sep_relu5_5/sep 0=512 1=1 5=1 6=262144 9=1
ConvolutionDepthWise     conv5_6/dw               1 1 conv5_5/sep_relu5_5/sep conv5_6/dw_relu5_6/dw 0=512 1=3 3=2 4=1 5=1 6=4608 7=512 9=1
Convolution              conv5_6/sep              1 1 conv5_6/dw_relu5_6/dw conv5_6/sep_relu5_6/sep 0=1024 1=1 5=1 6=524288 9=1
ConvolutionDepthWise     conv6/dw                 1 1 conv5_6/sep_relu5_6/sep conv6/dw_relu6/dw 0=1024 1=3 4=1 5=1 6=9216 7=1024 9=1
Convolution              conv6/sep                1 1 conv6/dw_relu6/dw conv6/sep_relu6/sep 0=1024 1=1 5=1 6=1048576 9=1
Pooling                  pool6                    1 1 conv6/sep_relu6/sep pool6 0=1 4=1
InnerProduct             fc7                      1 1 pool6 fc7 0=1000 1=1 2=1024000
Softmax                  prob                     1 1 fc7 output
```

**Comment by yippeesoft** [comment]
yes. open as text:

> 7767517
112 112
Input            data             0 1 data 0=3 1=224 2=224
Convolution      conv1            1 1 data conv1 0=32 1=3 2=1 3=2 4=1 5=0 6=864
BatchNorm        conv1/bn         1 1 conv1 conv1_conv1/bn 0=32
Scale            conv1/scale      1 1 conv1_conv1/bn conv1_conv1/scale 0=32 1=1
ReLU             relu1            1 1 conv1_conv1/scale conv1_relu1
ConvolutionDepthWise conv2_1/dw       1 1 conv1_relu1 conv2_1/dw 0=32 1=3 2=1 3=1 4=1 5=0 6=288 7=32
BatchNorm        conv2_1/dw/bn    1 1 conv2_1/dw conv2_1/dw_conv2_1/dw/bn 0=32
Scale            conv2_1/dw/scale 1 1 conv2_1/dw_conv2_1/dw/bn conv2_1/dw_conv2_1/dw/scale 0=32 1=1
ReLU             relu2_1/dw       1 1 conv2_1/dw_conv2_1/dw/scale conv2_1/dw_relu2_1/dw
Convolution      conv2_1/sep      1 1 conv2_1/dw_relu2_1/dw conv2_1/sep 0=64 1=1 2=1 3=1 4=0 5=0 6=2048
BatchNorm        conv2_1/sep/bn   1 1 conv2_1/sep conv2_1/sep_conv2_1/sep/bn 0=64
Scale            conv2_1/sep/scale 1 1 conv2_1/sep_conv2_1/sep/bn conv2_1/sep_conv2_1/sep/scale 0=64 1=1
ReLU             relu2_1/sep      1 1 conv2_1/sep_conv2_1/sep/scale conv2_1/sep_relu2_1/sep
ConvolutionDepthWise conv2_2/dw       1 1 conv2_1/sep_relu2_1/sep conv2_2/dw 0=64 1=3 2=1 3=2 4=1 5=0 6=576 7=64
BatchNorm        conv2_2/dw/bn    1 1 conv2_2/dw conv2_2/dw_conv2_2/dw/bn 0=64
Scale            conv2_2/dw/scale 1 1 conv2_2/dw_conv2_2/dw/bn conv2_2/dw_conv2_2/dw/scale 0=64 1=1
ReLU             relu2_2/dw       1 1 conv2_2/dw_conv2_2/dw/scale conv2_2/dw_relu2_2/dw
Convolution      conv2_2/sep      1 1 conv2_2/dw_relu2_2/dw conv2_2/sep 0=128 1=1 2=1 3=1 4=0 5=0 6=8192
BatchNorm        conv2_2/sep/bn   1 1 conv2_2/sep conv2_2/sep_conv2_2/sep/bn 0=128
Scale            conv2_2/sep/scale 1 1 conv2_2/sep_conv2_2/sep/bn conv2_2/sep_conv2_2/sep/scale 0=128 1=1
ReLU             relu2_2/sep      1 1 conv2_2/sep_conv2_2/sep/scale conv2_2/sep_relu2_2/sep
ConvolutionDepthWise conv3_1/dw       1 1 conv2_2/sep_relu2_2/sep conv3_1/dw 0=128 1=3 2=1 3=1 4=1 5=0 6=1152 7=128
BatchNorm        conv3_1/dw/bn    1 1 conv3_1/dw conv3_1/dw_conv3_1/dw/bn 0=128
Scale            conv3_1/dw/scale 1 1 conv3_1/dw_conv3_1/dw/bn conv3_1/dw_conv3_1/dw/scale 0=128 1=1
ReLU             relu3_1/dw       1 1 conv3_1/dw_conv3_1/dw/scale conv3_1/dw_relu3_1/dw
Convolution      conv3_1/sep      1 1 conv3_1/dw_relu3_1/dw conv3_1/sep 0=128 1=1 2=1 3=1 4=0 5=0 6=16384
BatchNorm        conv3_1/sep/bn   1 1 conv3_1/sep conv3_1/sep_conv3_1/sep/bn 0=128
Scale            conv3_1/sep/scale 1 1 conv3_1/sep_conv3_1/sep/bn conv3_1/sep_conv3_1/sep/scale 0=128 1=1
ReLU             relu3_1/sep      1 1 conv3_1/sep_conv3_1/sep/scale conv3_1/sep_relu3_1/sep
ConvolutionDepthWise conv3_2/dw       1 1 conv3_1/sep_relu3_1/sep conv3_2/dw 0=128 1=3 2=1 3=2 4=1 5=0 6=1152 7=128
BatchNorm        conv3_2/dw/bn    1 1 conv3_2/dw conv3_2/dw_conv3_2/dw/bn 0=128
Scale            conv3_2/dw/scale 1 1 conv3_2/dw_conv3_2/dw/bn conv3_2/dw_conv3_2/dw/scale 0=128 1=1
ReLU             relu3_2/dw       1 1 conv3_2/dw_conv3_2/dw/scale conv3_2/dw_relu3_2/dw
Convolution      conv3_2/sep      1 1 conv3_2/dw_relu3_2/dw conv3_2/sep 0=256 1=1 2=1 3=1 4=0 5=0 6=32768
BatchNorm        conv3_2/sep/bn   1 1 conv3_2/sep conv3_2/sep_conv3_2/sep/bn 0=256
Scale            conv3_2/sep/scale 1 1 conv3_2/sep_conv3_2/sep/bn conv3_2/sep_conv3_2/sep/scale 0=256 1=1
ReLU             relu3_2/sep      1 1 conv3_2/sep_conv3_2/sep/scale conv3_2/sep_relu3_2/sep
ConvolutionDepthWise conv4_1/dw       1 1 conv3_2/sep_relu3_2/sep conv4_1/dw 0=256 1=3 2=1 3=1 4=1 5=0 6=2304 7=256
BatchNorm        conv4_1/dw/bn    1 1 conv4_1/dw conv4_1/dw_conv4_1/dw/bn 0=256
Scale            conv4_1/dw/scale 1 1 conv4_1/dw_conv4_1/dw/bn conv4_1/dw_conv4_1/dw/scale 0=256 1=1
ReLU             relu4_1/dw       1 1 conv4_1/dw_conv4_1/dw/scale conv4_1/dw_relu4_1/dw
Convolution      conv4_1/sep      1 1 conv4_1/dw_relu4_1/dw conv4_1/sep 0=256 1=1 2=1 3=1 4=0 5=0 6=65536
BatchNorm        conv4_1/sep/bn   1 1 conv4_1/sep conv4_1/sep_conv4_1/sep/bn 0=256
Scale            conv4_1/sep/scale 1 1 conv4_1/sep_conv4_1/sep/bn conv4_1/sep_conv4_1/sep/scale 0=256 1=1
ReLU             relu4_1/sep      1 1 conv4_1/sep_conv4_1/sep/scale conv4_1/sep_relu4_1/sep
ConvolutionDepthWise conv4_2/dw       1 1 conv4_1/sep_relu4_1/sep conv4_2/dw 0=256 1=3 2=1 3=2 4=1 5=0 6=2304 7=256
BatchNorm        conv4_2/dw/bn    1 1 conv4_2/dw conv4_2/dw_conv4_2/dw/bn 0=256
Scale            conv4_2/dw/scale 1 1 conv4_2/dw_conv4_2/dw/bn conv4_2/dw_conv4_2/dw/scale 0=256 1=1
ReLU             relu4_2/dw       1 1 conv4_2/dw_conv4_2/dw/scale conv4_2/dw_relu4_2/dw
Convolution      conv4_2/sep      1 1 conv4_2/dw_relu4_2/dw conv4_2/sep 0=512 1=1 2=1 3=1 4=0 5=0 6=131072
BatchNorm        conv4_2/sep/bn   1 1 conv4_2/sep conv4_2/sep_conv4_2/sep/bn 0=512
Scale            conv4_2/sep/scale 1 1 conv4_2/sep_conv4_2/sep/bn conv4_2/sep_conv4_2/sep/scale 0=512 1=1
ReLU             relu4_2/sep      1 1 conv4_2/sep_conv4_2/sep/scale conv4_2/sep_relu4_2/sep
ConvolutionDepthWise conv5_1/dw       1 1 conv4_2/sep_relu4_2/sep conv5_1/dw 0=512 1=3 2=1 3=1 4=1 5=0 6=4608 7=512
BatchNorm        conv5_1/dw/bn    1 1 conv5_1/dw conv5_1/dw_conv5_1/dw/bn 0=512
Scale            conv5_1/dw/scale 1 1 conv5_1/dw_conv5_1/dw/bn conv5_1/dw_conv5_1/dw/scale 0=512 1=1
ReLU             relu5_1/dw       1 1 conv5_1/dw_conv5_1/dw/scale conv5_1/dw_relu5_1/dw
Convolution      conv5_1/sep      1 1 conv5_1/dw_relu5_1/dw conv5_1/sep 0=512 1=1 2=1 3=1 4=0 5=0 6=262144
BatchNorm        conv5_1/sep/bn   1 1 conv5_1/sep conv5_1/sep_conv5_1/sep/bn 0=512
Scale            conv5_1/sep/scale 1 1 conv5_1/sep_conv5_1/sep/bn conv5_1/sep_conv5_1/sep/scale 0=512 1=1
ReLU             relu5_1/sep      1 1 conv5_1/sep_conv5_1/sep/scale conv5_1/sep_relu5_1/sep
ConvolutionDepthWise conv5_2/dw       1 1 conv5_1/sep_relu5_1/sep conv5_2/dw 0=512 1=3 2=1 3=1 4=1 5=0 6=4608 7=512
BatchNorm        conv5_2/dw/bn    1 1 conv5_2/dw conv5_2/dw_conv5_2/dw/bn 0=512
Scale            conv5_2/dw/scale 1 1 conv5_2/dw_conv5_2/dw/bn conv5_2/dw_conv5_2/dw/scale 0=512 1=1
ReLU             relu5_2/dw       1 1 conv5_2/dw_conv5_2/dw/scale conv5_2/dw_relu5_2/dw
Convolution      conv5_2/sep      1 1 conv5_2/dw_relu5_2/dw conv5_2/sep 0=512 1=1 2=1 3=1 4=0 5=0 6=262144
BatchNorm        conv5_2/sep/bn   1 1 conv5_2/sep conv5_2/sep_conv5_2/sep/bn 0=512
Scale            conv5_2/sep/scale 1 1 conv5_2/sep_conv5_2/sep/bn conv5_2/sep_conv5_2/sep/scale 0=512 1=1
ReLU             relu5_2/sep      1 1 conv5_2/sep_conv5_2/sep/scale conv5_2/sep_relu5_2/sep
ConvolutionDepthWise conv5_3/dw       1 1 conv5_2/sep_relu5_2/sep conv5_3/dw 0=512 1=3 2=1 3=1 4=1 5=0 6=4608 7=512
BatchNorm        conv5_3/dw/bn    1 1 conv5_3/dw conv5_3/dw_conv5_3/dw/bn 0=512
Scale            conv5_3/dw/scale 1 1 conv5_3/dw_conv5_3/dw/bn conv5_3/dw_conv5_3/dw/scale 0=512 1=1
ReLU             relu5_3/dw       1 1 conv5_3/dw_conv5_3/dw/scale conv5_3/dw_relu5_3/dw
Convolution      conv5_3/sep      1 1 conv5_3/dw_relu5_3/dw conv5_3/sep 0=512 1=1 2=1 3=1 4=0 5=0 6=262144
BatchNorm        conv5_3/sep/bn   1 1 conv5_3/sep conv5_3/sep_conv5_3/sep/bn 0=512
Scale            conv5_3/sep/scale 1 1 conv5_3/sep_conv5_3/sep/bn conv5_3/sep_conv5_3/sep/scale 0=512 1=1
ReLU             relu5_3/sep      1 1 conv5_3/sep_conv5_3/sep/scale conv5_3/sep_relu5_3/sep
ConvolutionDepthWise conv5_4/dw       1 1 conv5_3/sep_relu5_3/sep conv5_4/dw 0=512 1=3 2=1 3=1 4=1 5=0 6=4608 7=512
BatchNorm        conv5_4/dw/bn    1 1 conv5_4/dw conv5_4/dw_conv5_4/dw/bn 0=512
Scale            conv5_4/dw/scale 1 1 conv5_4/dw_conv5_4/dw/bn conv5_4/dw_conv5_4/dw/scale 0=512 1=1
ReLU             relu5_4/dw       1 1 conv5_4/dw_conv5_4/dw/scale conv5_4/dw_relu5_4/dw
Convolution      conv5_4/sep      1 1 conv5_4/dw_relu5_4/dw conv5_4/sep 0=512 1=1 2=1 3=1 4=0 5=0 6=262144
BatchNorm        conv5_4/sep/bn   1 1 conv5_4/sep conv5_4/sep_conv5_4/sep/bn 0=512
Scale            conv5_4/sep/scale 1 1 conv5_4/sep_conv5_4/sep/bn conv5_4/sep_conv5_4/sep/scale 0=512 1=1
ReLU             relu5_4/sep      1 1 conv5_4/sep_conv5_4/sep/scale conv5_4/sep_relu5_4/sep
ConvolutionDepthWise conv5_5/dw       1 1 conv5_4/sep_relu5_4/sep conv5_5/dw 0=512 1=3 2=1 3=1 4=1 5=0 6=4608 7=512
BatchNorm        conv5_5/dw/bn    1 1 conv5_5/dw conv5_5/dw_conv5_5/dw/bn 0=512
Scale            conv5_5/dw/scale 1 1 conv5_5/dw_conv5_5/dw/bn conv5_5/dw_conv5_5/dw/scale 0=512 1=1
ReLU             relu5_5/dw       1 1 conv5_5/dw_conv5_5/dw/scale conv5_5/dw_relu5_5/dw
Convolution      conv5_5/sep      1 1 conv5_5/dw_relu5_5/dw conv5_5/sep 0=512 1=1 2=1 3=1 4=0 5=0 6=262144
BatchNorm        conv5_5/sep/bn   1 1 conv5_5/sep conv5_5/sep_conv5_5/sep/bn 0=512
Scale            conv5_5/sep/scale 1 1 conv5_5/sep_conv5_5/sep/bn conv5_5/sep_conv5_5/sep/scale 0=512 1=1
ReLU             relu5_5/sep      1 1 conv5_5/sep_conv5_5/sep/scale conv5_5/sep_relu5_5/sep
ConvolutionDepthWise conv5_6/dw       1 1 conv5_5/sep_relu5_5/sep conv5_6/dw 0=512 1=3 2=1 3=2 4=1 5=0 6=4608 7=512
BatchNorm        conv5_6/dw/bn    1 1 conv5_6/dw conv5_6/dw_conv5_6/dw/bn 0=512
Scale            conv5_6/dw/scale 1 1 conv5_6/dw_conv5_6/dw/bn conv5_6/dw_conv5_6/dw/scale 0=512 1=1
ReLU             relu5_6/dw       1 1 conv5_6/dw_conv5_6/dw/scale conv5_6/dw_relu5_6/dw
Convolution      conv5_6/sep      1 1 conv5_6/dw_relu5_6/dw conv5_6/sep 0=1024 1=1 2=1 3=1 4=0 5=0 6=524288
BatchNorm        conv5_6/sep/bn   1 1 conv5_6/sep conv5_6/sep_conv5_6/sep/bn 0=1024
Scale            conv5_6/sep/scale 1 1 conv5_6/sep_conv5_6/sep/bn conv5_6/sep_conv5_6/sep/scale 0=1024 1=1
ReLU             relu5_6/sep      1 1 conv5_6/sep_conv5_6/sep/scale conv5_6/sep_relu5_6/sep
ConvolutionDepthWise conv6/dw         1 1 conv5_6/sep_relu5_6/sep conv6/dw 0=1024 1=3 2=1 3=1 4=1 5=0 6=9216 7=1024
BatchNorm        conv6/dw/bn      1 1 conv6/dw conv6/dw_conv6/dw/bn 0=1024
Scale            conv6/dw/scale   1 1 conv6/dw_conv6/dw/bn conv6/dw_conv6/dw/scale 0=1024 1=1
ReLU             relu6/dw         1 1 conv6/dw_conv6/dw/scale conv6/dw_relu6/dw
Convolution      conv6/sep        1 1 conv6/dw_relu6/dw conv6/sep 0=1024 1=1 2=1 3=1 4=0 5=0 6=1048576
BatchNorm        conv6/sep/bn     1 1 conv6/sep conv6/sep_conv6/sep/bn 0=1024
Scale            conv6/sep/scale  1 1 conv6/sep_conv6/sep/bn conv6/sep_conv6/sep/scale 0=1024 1=1
ReLU             relu6/sep        1 1 conv6/sep_conv6/sep/scale conv6/sep_relu6/sep
Pooling          pool6            1 1 conv6/sep_relu6/sep pool6 0=1 1=0 2=1 3=0 4=1
Convolution      fc7              1 1 pool6 fc7 0=1000 1=1 2=1 3=1 4=0 5=1 6=1024000
Softmax          prob             1 1 fc7 prob 0=0

>
