### ISSUE TITLE
TF Lite tensor field is_variable isn't displayed

### ISSUE THREAD

**Issue by yurivict** [lutzroeder/netron#386]

**Comment by lutzroeder** [comment]
Do you have an example why this is needed?

**Comment by yurivict** [comment]
> Do you have an example why this is needed?

No, but once it is included in the format it should be displayed by TF Lite viewers.

**Comment by lutzroeder** [comment]
Can you share a file that is using this setting or some insights when it would be set to `true`?

**Comment by yurivict** [comment]
TF and TF Lite support variables. If ```is_variable=true``` then this tensor has no static data, instead data is provided at the computation time.

**Comment by lutzroeder** [comment]
tensorflow/tensorflow@a3273e090f7

**Comment by yurivict** [comment]
Sure: https://people.freebsd.org/~yuri/fully-connected-with-is_variable=true.tflite

**Comment by lutzroeder** [comment]
`is_variable` seems to be `false` for all tensors in this file?

```
name: tensor_input   is_variable: false
name: tensor_output  is_variable: false
name: tensor_weight  is_variable: false
name: tensor_bias    is_variable: false
```

**Comment by yurivict** [comment]
Sorry, my bad. I just updated the file.

**Comment by lutzroeder** [comment]
[netron_issue386.zip](https://github.com/lutzroeder/netron/files/3963414/netron_issue386.zip)

**Comment by lutzroeder** [comment]
[netron_issue_386.zip](https://github.com/lutzroeder/netron/files/3963415/netron_issue_386.zip)
