### ISSUE TITLE
Int64 toString() in JavaScript

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/Netron#39]

**Comment by BrandonDenton** [comment]
Taking a glance at your code, and I'm thinking this formatting can be done with a simple addition of NumPy. Would you mind if I added that in my fork? If there's a native tool for doing 64 bit ints, I've forgotten how to use it.

**Comment by lutzroeder** [comment]
The issue is with the JavaScript viewer. JavaScript can not represent tensors with large Int64 values as Number. Currently reading them as byte[] into in Int64 in view.js. The toString() for this class needs to be implemented.

**Comment by BrandonDenton** [comment]
Thanks for the clarification. Working on that and a couple other listed issues now.

**Comment by lutzroeder** [comment]
The issue is that JavaScript cannot represent large 64 bit integers as they are converted to Number: https://stackoverflow.com/questions/5353388/javascript-parsing-int64. They can be loaded as byte[] but rendering them will probably involve writing custom code to render each digit by running mod 10 and div 10 on the byte array.
