### ISSUE TITLE
MXNet models aren't displayed properly

### ISSUE THREAD

**Issue by yurivict** [lutzroeder/netron#390]
I use Gluon that helps to work with MXNet.
Gluon brought in the model in 2 files:
* ```~/.mxnet/models/ssd_512_resnet50_v1_voc-9c8b225a.params```
* ```/usr/local/lib/python3.6/site-packages/gluoncv/model_zoo/quantized/ssd_512_resnet50_v1_voc_int8-symbol.json```

The second file (json) is displayed like this: https://people.freebsd.org/~yuri/netron+mxnet.png Weights aren't shown as weights but as inputs.

The params file is large and contains weights, but it is shown as just a set of items lined up horizontally.

They should be shown together, I think, and the result should be more like TF Lite models are displayed. But netron doesn't seem to have any way how to combine these two files, ```netron -h```  only talks about the ```MODEL_FILE```.

**Comment by lutzroeder** [comment]
Copy the `.params` file to the same folder and rename to `ssd_512_resnet50_v1_voc_int8-0000.params`?

**Comment by yurivict** [comment]
It doesn't seem to help:
```
-rw-r--r--  1 yuri  users  147738774 Dec 15 14:43 ssd_512_resnet50_v1_voc-9c8b225a.params
-rwxr-xr-x  1 yuri  users     353674 Dec 15 20:09 ssd_512_resnet50_v1_voc_int8-symbol.json
lrwxr-xr-x  1 yuri  users         40 Dec 15 20:12 ssd_512_resnet50_v1_voc-9c8b225a-symbol.json -> ssd_512_resnet50_v1_voc_int8-symbol.json
```

I added a matching symbolic link but it still isn't shown.

**Comment by lutzroeder** [comment]
Option 1:
```
ssd_512_resnet50_v1_voc_int8-symbol.json
ssd_512_resnet50_v1_voc_int8-0000.params
```
Option 2:
```
ssd_512_resnet50_v1_voc_int8-9c8b225a.params
ssd_512_resnet50_v1_voc_int8-symbol.json
```

**Comment by yurivict** [comment]
I have Option 2 and it has the same problem.

IMO, the best solution is to give netron both files as arguments when the model is split like this.

**Comment by lutzroeder** [comment]
Can you share the files? In the 2 option the console output `.params` base is missing `_int8`?

> IMO, the best solution is to give netron both files as arguments when the model is split like this.

What if there are multiple weight files? What if the weight file is not specified or packaged with the symbol file into a compressed archive? If the files are in different folders how can they be opened in a single file open dialog for browser scenarios? Currently the Python server is a simple file server and having the ability to run the web client against any generic file server needs to be supported. Breaking that pattern or adding more options sure is possible if you want to work on this feature (would have to be supported for formats and frameworks) and test and support it going forward?

**Comment by lutzroeder** [comment]
Can you share the files? In the 2 option the console output `.params` base is missing `_int8` or the other way around `-9c8b225a-XXXX.params` to resolve to `-9c8b225a-symbol.json`?

> IMO, the best solution is to give netron both files as arguments when the model is split like this.

There is a lot of complexity here. Multiple frameworks and formats do things differently (some have weight files, others don't, some have fixed lookup strategies, some have multiple weight files). Models can be loaded from a single compressed archives. Browser support needs to open multiple files from a single file dialog. Currently the Python server is a simple file server without any format specific handling and having the ability to run the web client against a generic file server or a single URL is required by some users. Breaking that pattern or adding more options sure is possible if you want to work on this feature and support and test it for all frameworks going forward? A good starting point would be to add test coverage for the existing scenarios.

**Comment by yurivict** [comment]
I compressed the directory: https://people.freebsd.org/~yuri/mxnet-models.tgz
File names there match Option 2, but the model isn't displayed correctly.
But this model works fine in MXNet.

**Comment by lutzroeder** [comment]
The weight references in the `-symbol.json` file have an `ssd0_` prefix while the weight names in the `.params` file do not. Any ideas why that is? https://github.com/dmlc/gluon-cv/issues/925

**Comment by yurivict** [comment]
I don't know why there's this name mismatch. I installed MXNet/GluonCV, the json file was installed by GluonCV, and the params file was downloaded.

**Comment by yurivict** [comment]
You can run the self-contained Gluon example: https://gluon-cv.mxnet.io/build/examples_segmentation/demo_deeplab.html

It downloads the model into ~/.mxnet/models/deeplab_resnet101_ade-bf1584df.params and Netron also fails to show the structure. Again, Gluon reads it w/out a problem.

If you would search for why Gluon/MXNet doesn't save model structure you would find comments that MXNet models are dynamic and it is impossible to save them.

Then, when you say that you support MXNet models, what does this mean? You don't show their structure, only data tables.

**Comment by lutzroeder** [comment]
`.params` contains tensor weights only. MXNet graphs are saved as `-symbol.json`. https://mxnet.apache.org/api/python/docs/tutorials/packages/gluon/blocks/save_load_params.html.
