### ISSUE TITLE
Darknet weights support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#395]

**Comment by HagegeR** [comment]
I tried to drag a weights file and nothing happened
[csresnext50-panet-spp_final.weights](https://drive.google.com/file/d/1aNXdM8qVy11nqTcd2oaVB3mf7ckr258-/view?usp=sharing)

**Comment by lutzroeder** [comment]
Rename the file to `csresnext50-panet-spp.weights` so it matches the `.cfg` file and copy it next to the `csresnext50-panet-spp.cfg` file.
