### ISSUE TITLE
Please display TFLite numeric tensor IDs along with string IDs

### ISSUE THREAD

**Issue by yurivict** [lutzroeder/netron#396]
In TFLite tensors have numeric IDs.

TF would sometimes print such error message when something goes wrong:
> ValueError: Cannot set tensor: Dimension mismatch. Got 3 but expected 4 for input 59.

But netron currently can't help to find what ```input 59``` is because it only shows string IDs.

**Comment by lutzroeder** [comment]
Maybe this should be fixed in TensorFlow Lite to print the tensor name instead of or next to the index in error messages?

**Comment by yurivict** [comment]
IMO it should be fixed in both. When you work with TFLite numeric IDs is what you have along with string IDs. All tensors/streams are indexed by this ID, and there's also a string ID in the tensor description. People print whatever comes to their mind, but tools like netron should print both IMO.
