### ISSUE TITLE
error load ncnn model

### ISSUE THREAD

**Issue by LingQiu** [lutzroeder/netron#397]
hello,
error load ncnn model use the version of the netron 3.6.5(win10):`Invalid signature in 'det.param'`.
It's the `det.param:`
[det.txt](https://github.com/lutzroeder/netron/files/3981934/det.txt)
I have no idea about this, can you give some help?
thx.

**Comment by lutzroeder** [comment]
[0397.param.zip](https://github.com/lutzroeder/netron/files/14074806/0397.param.zip)
