### ISSUE TITLE
pytorch check point support

### ISSUE THREAD

**Issue by tensorbuffer** [lutzroeder/netron#401]
Hello, when I try to use the web version to load pytorch checkpoint file, I got this error: Error loading PyTorch model. File does not contain root module or state dictionary in 'checkpoint.pth'.
The checkpoint is saved as:
            checkpoint = {
                'model': model_without_ddp.state_dict(),
                'optimizer': optimizer.state_dict(),
                'lr_scheduler': lr_scheduler.state_dict(),
                'epoch': epoch,
                'args': args}
            torch.save(
                checkpoint, path_to_file)

This is pytorch standard way of saving checkpoint:
https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-a-general-checkpoint-for-inference-and-or-resuming-training

**Comment by lutzroeder** [comment]
Can you share the model file?

**Comment by tensorbuffer** [comment]
trying to attach

**Comment by tensorbuffer** [comment]
checkpoint.pth

**Comment by lutzroeder** [comment]
Can you share it using a cloud drive?

**Comment by tensorbuffer** [comment]
https://drive.google.com/file/d/1eIyTCGctlInencZBUwvBokPQikGz03Oq/view?usp=sharing

**Comment by lutzroeder** [comment]
`features.1.skip_add.observer.scale` tensor is `null`

**Comment by tensorbuffer** [comment]
great, thanks! I can load the checkpoint file.
However all that's shown are 'Module' blocks, there's no connection between them. Is this the right visualization?

**Comment by abhigoku10** [comment]
@tensorbuffer @lutzroeder @demid5111 @scottcjt   i am also facing the same issues not able to visualize any connection between the modules , any idea how to obtain the connections ??

**Comment by tensorbuffer** [comment]
I think this is because pytorch graph is dynamic, the graph is generated on the fly, so you have to feed an input and execute the model to get the graph.

**Comment by simphide** [comment]
Hi, I also have this problem with the models of this project: https://github.com/BloodAxe/Kaggle-2020-Alaska2/releases

Does anybody have an idea how I can see the connections etc.? Thank you!

**Comment by lutzroeder** [comment]
@simphide the file include training weights only. See #720.
