### ISSUE TITLE
The comparison of .onnx and .pb model.

### ISSUE THREAD

**Issue by chiehpower** [lutzroeder/netron#402]
Hi,
I have one ssd model which was downloaded from [Tensorflow detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md).
I took it to convert the model from pb to onnx. Of course, I am not sure whether its conversion is correct or not, but I just wanna try to compare their graphs of visualization.
My original model is ssd_mobilenet_v1_coco_2018_01_28.

First one is converted model (i.e., .onnx).

![ssd_onnx](https://lh3.googleusercontent.com/pH32mGYL6IRADb-gDcPia6O21hNTIejofj4t55OJwrBOnzD14aH8ooi_ZP-tw6LArjDoo9-a7R5tQVxu2OoVFrZoh4B0OBQJy7RyCEiReLI4vc79_iyjZYtrRYB6YtFO7AMctqRFJkCZQzTtPF4uxG1ffkDTzdiCRBI-uYeLKMsFOLtMZnUCQIyGN5-JOLZNVP7XODs1Ne9y7wkp-o_cUNF5U9FWhF4-9ZKD06kRmIFn0auc_kTBifUfyVvyaja-7Pw5LOdki10vswL2v9qSPs5HAqPgpmq54LSFyE_mEy0nd8CykTERvWRy7YANUxze4kzRjyY7Q9KUXf09_Nz2_L8OLaj108Wga-GzRXnvmgwCGNLyOYAl3-WUEed8pjqbDUMzw32jFzT1SFZJs3m9K9Q4OS4f2oY6DkexVpXULBS2dK4Yf_kzpAiyFenmsasWxkv-va-t9E01D5rJrJRykdzpJX2sn1wKv2xHNZdfjsFEtzaNa2KpgfTjp6ESQ4ckjzSEgu-ptRAdFUt9ZwDIiexUZ9y02PWRkauiCfVPpEmPHYMvaK_DcG-89PbJpKjgHI_-OoeND334aaL10T-Xdm2iTFLxzYXvRxBCm4ZNlyomXN2w0-UQnJwGD5wOwFPkhRdDeSAbrXwrDo0Nlq6qnU07HBZb8TsTz74ATlqEmI6VculVSLVYpTlbgnKsSxK_KAJ5VLa-pwRHMTRTOW2nvrsdscEjoSn-2Qm0QSGL5r2ha9Q=w628-h981-no)

Second one is frozen_inference_graph.pb model.
 ![pb](https://lh3.googleusercontent.com/yHTK8zC75J5P61mQTvsoZxeSBqUhBF5PXI2iDEkyuMehtt416GXP3OReIJHlfOwxwEBNInZW6jSKIspL3W8RUzeEVRHW_qZhKkraDLYqKOfLHSagbvi2xKr_CZj-1yxXsybzUVprKOCgX31h4tYUqNWW6jH-MweeZfZWJHoSXPLQ9KWj4_ucT7Nt96Kj6hWppd_1WOM3hLUpLcUCU2KQKgPR3igqD3fXTQ5hTctpTjbh_QOAKd0DZiKICK3tor3-q9fPSppjf47LrtjJ29KLs6orhhg0VFRXi1_uRN1gbinn9zSCwfbENRu9JGc5nT9yNEGhFMeiviHs3fPeeCcM1c7RX3L7J7_ergsVzBQt8tA1y5cIWyh-RcScB4UkRLJedruREEm8LeEmNEvK3tq98wPQ-gSIFfT5E9lefDNd6dqauGn0jKr3-LS3iXQ8a3B_uVwwiIbGbstzckvEu7QQQTL5gYQL2llxZHqlY0Xsl0nvYtCtJiF0kRXHj_E9KxpJnSMJpF4EdyhKHOj94-teKG7yUGTmiuthYTmnMTNd9Gfu06kQxpeHIU10l_WIlvLmQLu2jbC7HeYF7ppsxp8TLQ6sRW42y2gwdATo2s-UgIbsUGpCVWW-ED-BXZdHl2N8iO9GU1_xMYvCSC2V22Omyws7VMKR8DX_nhlG0IZ3Jm5SlRB6TVrR2xjDilAYt7mzWI-3skDq8n-j2uU8tY93LjoQxbcV7k_XecuFf0IRZIdqhc0=w1493-h132-no)

Obviously, both graphs are totally different. (BTW I am sorry about that the graph size is too big, so its resolution is quite poor.) 
In particular, the pb file took for a long time to visualize, but the onnx file was loaded very fast. When I saw the graph of pb model, I just wanna say that is it serious? lol 
I am not sure which one is wrong indeed. 

Is there any idea about these?
Thanks!!

**Comment by lutzroeder** [comment]
You can investigate this and consult the folks who wrote the converter. Please only file a Netron issue if there is an actual bug.
