### ISSUE TITLE
TensorFlow .ckpt support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#405]
https://github.com/serre-lab/deeplabcut_mgh/blob/master/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt

**Comment by lutzroeder** [comment]
[netron_issue_405.zip](https://github.com/lutzroeder/netron/files/4017943/netron_issue_405.zip)

**Comment by 00001101-xt** [comment]
How does this resolve the "ckpt" supporting issue?
