### ISSUE TITLE
wrong python path in virtualenv

### ISSUE THREAD

**Issue by tjingrant** [lutzroeder/Netron#41]
Hi, 

I use virtualenv and when I install netron, the python path is wrong in the netron executable script. I have to change that first line in the netron script (which indicates where python is located) to the python executable in the virtualenv. Just to let you know this could be a nuisance for others using virtualenv...

Best wishes,
Tian Jin.

**Comment by tjingrant** [comment]
Better to dynamically generate this line https://github.com/lutzroeder/Netron/blob/10d2b8cb795ec70a7e686b49df6cb49800da6aa3/src/netron.py#L1.

**Comment by lutzroeder** [comment]
Definitely. The installer is using `bdist_wheel` so not sure how to generate it. Looks like using `#!/usr/bin/env python` instead of `#!/usr/bin/python` would make this work?

**Comment by tjingrant** [comment]
Seems like a good idea and it works for me.
