### ISSUE TITLE
Darknet shortcut support for new fork

### ISSUE THREAD

**Issue by HagegeR** [lutzroeder/netron#410]
Hi @lutzroeder ,

I think that the `from` parameter is not implemented correctly.

A correct implementation is detailed here : [https://github.com/AlexeyAB/darknet/issues/4662](https://github.com/AlexeyAB/darknet/issues/4662)

I'm not sure that #335 is completely correct: from what I understand by the code, only `[scale_channel]` implement partially the from attribute, `[shortcut]` and `[sam]` layer should implement it too.

thanks for your help lately with the darknet implementation!

**Comment by lutzroeder** [comment]
@HagegeR can you create a fix and submit a PR.

**Comment by HagegeR** [comment]
@lutzroeder I'm not sure how to do it really, how do you get multiple inputs in there: [https://github.com/lutzroeder/netron/blob/a2c18fc79f519c102e34a9867b7c6db431a95df9/src/darknet.js#L204](https://github.com/lutzroeder/netron/blob/a2c18fc79f519c102e34a9867b7c6db431a95df9/src/darknet.js#L204)

**Comment by lutzroeder** [comment]
@HagegeR, check a few lines down for `const routes`.

**Comment by HagegeR** [comment]
So, basically, I tried that:
[https://github.com/HagegeR/netron/blob/f8e1a94d743f170a1db04b572915f37399eb0097/src/darknet.js#L171-L190](https://github.com/HagegeR/netron/blob/f8e1a94d743f170a1db04b572915f37399eb0097/src/darknet.js#L171-L190)

**Comment by HagegeR** [comment]
@lutzroeder hi, is this ok?

**Comment by lutzroeder** [comment]
[yolov3-tiny_3l_shortcut_multilayer_per_feature_softmax.cfg.zip](https://github.com/lutzroeder/netron/files/4074756/yolov3-tiny_3l_shortcut_multilayer_per_feature_softmax.cfg.zip)
