### ISSUE TITLE
Model conversion

### ISSUE THREAD

**Issue by photopea** [lutzroeder/netron#415]
I see, that parsers for various formats are a part of this project.

Would it be hard to extend Netron into a convertor from other formats to ONNX? As far as I know, there are some custom Python scripts all over the internet, which can convert specific formats to ONNX.

But it would be great, if people could get a ONNX version of a network simply by drag-and-dropping it into a web browser (as they can do now for visualization).

**Comment by lutzroeder** [comment]
This is currently not a priority.

> Would it be hard to extend...

Define "hard". Technically it is possible. You would have to do all the work and commit to fixing all future bugs that users might report. If you add it for ONNX you will have to add it for all other formats as well as users will expect that. Keep in mind those other tools get developed by multiple teams some of which might do this as a full time job. You would have to redo all this work of many people by yourself for free and as a hobby?

**Comment by photopea** [comment]
I wanted to ask you to do it. You are already working on this tool, so you could extend it with ONNX export (for the same reason you made a visualizer). I think there could be much more people, who would start using Netron, if it had this feature.

I guess you are loading all neural network formats into a common represetation (that is stored in the memory of your program). I thought it could be enough to make a convertor from that format to ONNX.

**Comment by lutzroeder** [comment]
This is currently not a priority. See [microsoft/MMdnn](https://github.com/microsoft/microsoft/MMdnn).

**Comment by vpenades** [comment]
I realize that, as stated, it is not a priority, but given that Netron has a very nice user interface, it would be really convenient if Netron could act as a sort of GUI for MMdnn, so adding the export feature would be a matter of calling MMdnn.

**Comment by photopea** [comment]
I think Netron would have 20x more users, if it could convert between network formats.

**Comment by JohnnyOpcode** [comment]
Check this out.

https://github.com/Microsoft/Windows-Machine-Learning/blob/master/Tools/WinMLDashboard/README.md

**Comment by lutzroeder** [comment]
Duplicate as #1445
