### ISSUE TITLE
Tensorflow Lite, Netron 3.7.9: TypeError "node.operator.split" is not a function

### ISSUE THREAD

**Issue by mendi80** [lutzroeder/netron#417]
This error appear only in tflite file and netron 3.7.9
Error does not appear in same network saved in h5 keras file.
Error does not appear in netron 3.7.8

**Comment by lutzroeder** [comment]
Can you share the model file?

**Comment by lutzroeder** [comment]
Duplicate of #416

**Comment by mendi80** [comment]
model uploaded

**Comment by mendi80** [comment]
BTW:
1) Is there any way to see number of parameters (per layer, total) in keras models?
2) Why is that in tflite file i can see the activation shape, but in keras h5 file i cant?

**Comment by lutzroeder** [comment]
> Is there any way to see number of parameters (per layer, total) in keras models?

Can you provide some more specifics?

> Why is that in tflite file i can see the activation shape, but in keras h5 file i can't?

The shapes are computed during conversion and stored in `.tflite` files. They are not stored in Keras files and have to be inferred. See #71.
