### ISSUE TITLE
Show Names hides the tensor sizes

### ISSUE THREAD

**Issue by fdwr** [lutzroeder/netron#420]
Netron 3.8.0 shows tensor dimensions which is useful :)...

![image](https://user-images.githubusercontent.com/1809166/73031290-8de10080-3df0-11ea-8ca6-09e0f0685454.png)

...and it can Show Names which is also useful :), but showing names disables the size info :(.

![image](https://user-images.githubusercontent.com/1809166/73031316-9f2a0d00-3df0-11ea-8080-0c391fd71c85.png)

**Request**: Can both be shown on two lines? It appears there is adequate room for both. I don't care much about the UI aspect and whether a Show Sizes option exists too independently from Show Names, just that I don't have to keep switching between the two, which reloads the model and loses the current view. Thanks. Mockup: 

![image](https://user-images.githubusercontent.com/1809166/73031626-8837ea80-3df1-11ea-995c-263d9672ce4f.png)

**Comment by oneengineer** [comment]
It seems show tensor dimension disappears? version 4.5.6
I can only see dimension at input and output.
