### ISSUE TITLE
Input of Conv1D layer is displayed as ?x100X3?

### ISSUE THREAD

**Issue by talhakabakus** [lutzroeder/netron#424]
The input shape of my CNN's first 1D convolution layer is `100x3`. When I load the model via Netron, the input shape is displayed as `?x100X3` as you may see below:

<img width="247" alt="Screen Shot 2020-02-09 at 02 14 03" src="https://user-images.githubusercontent.com/444482/74093354-dcc1b200-4ae1-11ea-9858-83ff43f938a9.png">

**Comment by lutzroeder** [comment]
Can you share the model file?

**Comment by talhakabakus** [comment]
Sure, you may find the model file as attached.

p.s. Since it is not possible to attach `.json` files, I attached it as an archive (`.zip`).

[best_cnn_model.json.zip](https://github.com/lutzroeder/netron/files/4176180/best_cnn_model.json.zip)

**Comment by lutzroeder** [comment]
The model contains `"batch_input_shape": [null, 100, 3]` so first column is the batch dimension?

**Comment by talhakabakus** [comment]
Here is relevant layer definition which is implemented using _Keras_:
`model.add(Conv1D(filters=16, kernel_size=kernel_size, input_shape=(100, 3)))`
