### ISSUE TITLE
scrolling issue

### ISSUE THREAD

**Issue by DrSlink** [lutzroeder/netron#425]
Right bar("node properties") doesn't scrolling. Can't see all opened weights, gamma, etc.
Tried versions 3.8.6-3.8.9, Windows 10

**Comment by cloudy-sfu** [comment]
Same problem. 3.8.9 on Windows 10

**Comment by lutzroeder** [comment]
eba5acc9c81737cc3c38b0dd5d1d6324aa9672f4 `<!DOCTYPE html>`
