### ISSUE TITLE
Keras: RetinaNet connection missing

### ISSUE THREAD

**Issue by DavidMrd** [lutzroeder/netron#426]
Hello, 
when I visualize my model with Netron, P5 and P4 seem not to be connected to any other nodes. But when I visualize RetinaNet using TensorBoard the graph is different. My model is based on RetinaNet.
![Screenshot from 2020-02-12 12-51-29](https://user-images.githubusercontent.com/59397892/74339283-145f8100-4da4-11ea-8b9b-51e982539ff9.png)
![Screenshot from 2020-02-12 12-50-51](https://user-images.githubusercontent.com/59397892/74339291-175a7180-4da4-11ea-825f-012bd3052dcc.png)

**Comment by lutzroeder** [comment]
Can you share the model file?

**Comment by DavidMrd** [comment]
It is too big, but you can find it here-> https://www.dropbox.com/s/avh4xyxfv3q3tqn/resnet50_csv_16.h5?dl=0

**Comment by lutzroeder** [comment]
[resnet50_csv_16.json.zip](https://github.com/lutzroeder/netron/files/4202466/resnet50_csv_16.json.zip)
