### ISSUE TITLE
not able to use the AppImage on Linux

### ISSUE THREAD

**Issue by vera121** [lutzroeder/netron#427]
Hello,
I had a try of the Netron-3.8.9.AppImage on Linux and found it couldn't work.
I use the command 
chmod +x Netron-3.8.9.AppImage
and then use 
./Netron-3.8.9.AppImage 
to open it.
There is only the frame with title showing; the middle panel is empty, no content or menu appear as in the usually python web server.

My system info: 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by lutzroeder** [comment]
@vera121 can you investigate why this is happening and submit a fix? It does not seem to repro on Ubuntu 18.04 LTS.

**Comment by vera121** [comment]
Hello, 
With another system (Ubuntu 16.04.6 LTS) I am able to open it.
But on a CentOS
	Linux 3.10.0-957.5.1.el7.x86_64
	OS:        CentOS Linux release 7.6
 it failed with another issue:
[41889:0212/233403.900654:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_NetronnHzCep/chrome-sandbox is owned by root and has mode 4755.

Maybe the issue is related to root access or chrome setup problem.

**Comment by mneilly-et** [comment]
FWIW - https://github.com/electron/electron/issues/17972
