### ISSUE TITLE
Keras ambiguous weight names

### ISSUE THREAD

**Issue by DrSlink** [lutzroeder/netron#428]
Layers with the same local name but different full names are combined into one, even if they are located in completely different places in the neural network. For example, a layer named 'Conv' and 'expanded_conv_3/squeeze_excite/Conv'
![image](https://user-images.githubusercontent.com/37940001/74521202-16534c80-4f2a-11ea-97ce-83ba53487c5d.png)

**Comment by lutzroeder** [comment]
Can you share the model file?

**Comment by DrSlink** [comment]
[example.zip](https://github.com/lutzroeder/netron/files/4218317/example.zip)

**Comment by lutzroeder** [comment]
[neton_issue_428.zip](https://github.com/lutzroeder/netron/files/4221530/neton_issue_428.zip)

**Comment by lutzroeder** [comment]
[netron_issue_428.zip](https://github.com/lutzroeder/netron/files/4221535/netron_issue_428.zip)

**Comment by lutzroeder** [comment]
[nested_bidrectional_lstm.zip](https://github.com/lutzroeder/netron/files/4304590/nested_bidrectional_lstm.zip)

**Comment by lutzroeder** [comment]
[nested_bidrectional.zip](https://github.com/lutzroeder/netron/files/4304644/nested_bidrectional.zip)
