### ISSUE TITLE
document not shown in latest 3.9.1

### ISSUE THREAD

**Issue by cnjsdfcy** [lutzroeder/netron#431]
Hi Lutz,

The question mark for type disappeared in latest 3.9.1 version, by which the document info is pretty helpful to me. How can I resume it?

Thanks,
Yu

**Comment by cnjsdfcy** [comment]
Seem like only .onnx models have type documents, .caffemodel doesn't.
Am I right?

**Comment by lutzroeder** [comment]
Yes. The descriptions are stored in `src/caffe-metadata.json` or `src/onnx-metadata.json`. For ONNX there is a script to update these files (`./tools/onnx sync install metadata`). For Caffe there is not. Adding the information manually would be possible as well if you want to take a look and submit a PR.

**Comment by cnjsdfcy** [comment]
Thanks for your quickly answer.
