### ISSUE TITLE
TorchScript unsupported functions in after update

### ISSUE THREAD

**Issue by lujq96** [lutzroeder/netron#432]
I have a lot of basic model files saved in TorchScript and they were able to be opened weeks ago. However I cannot many of them after update Netron to v3.9.1. Many common functions are not supported not, e.g. torch.constant_pad_nd, torch.bmm, torch.avg_pool3d.

**Comment by lutzroeder** [comment]
Can you share the model files? TorchScript keeps changing and there is lots going on under the covers needed to read all the different kinds of files created with different versions.

**Comment by lujq96** [comment]
I cannot open any of these simple nodes.
[nodes.zip](https://github.com/lutzroeder/netron/files/4223632/nodes.zip)

**Comment by lutzroeder** [comment]
[activation.zip](https://github.com/lutzroeder/netron/files/4226664/activation.zip)

**Comment by lutzroeder** [comment]
[bmm.zip](https://github.com/lutzroeder/netron/files/4226665/bmm.zip)

**Comment by lutzroeder** [comment]
[constant_pad_2d.zip](https://github.com/lutzroeder/netron/files/4226668/constant_pad_2d.zip)

**Comment by lutzroeder** [comment]
[netron_issue_432_activation.pth.zip](https://github.com/lutzroeder/netron/files/4226686/netron_issue_432_activation.pth.zip)

**Comment by lutzroeder** [comment]
[netron_issue_432_bmm.pth.zip](https://github.com/lutzroeder/netron/files/4226688/netron_issue_432_bmm.pth.zip)

**Comment by lutzroeder** [comment]
[netron_issue_432_constant_pad_2d.pth.zip](https://github.com/lutzroeder/netron/files/4226690/netron_issue_432_constant_pad_2d.pth.zip)

**Comment by lujq96** [comment]
Btw is there any way to downgrade netron to an older version? I believe I can open them in about v3.6

**Comment by lutzroeder** [comment]
@lujq96 can you try the steps in [DEVELOPMENT.md](https://github.com/lutzroeder/netron/blob/master/DEVELOPMENT.md) and check if changes in master resolve the issue? Repros for other operators like `torch.avg_pool3d` or the necessary changes to `pytorch-metadata.json` are welcome as well.

**Comment by lujq96** [comment]
Still many other models cannot be opened in v3.9.2. I tried a old version 3.5.9 and everything works fine. Is there any major change that weakened the parsing function between them?

**Comment by lutzroeder** [comment]
Can you share model files to reproduce these issues?

**Comment by lujq96** [comment]
[badcases.zip](https://github.com/lutzroeder/netron/files/4262350/badcases.zip)
These are all the badcases I found in my unit test models.

**Comment by linchaozhang** [comment]
i meet the same question, it works well for pres version, but unsupported after update.
@lujq96  @lutzroeder

**Comment by lutzroeder** [comment]
@linchaozhang please create a new issue and share the model file.
