### ISSUE TITLE
[caffe2] caffe2 int8 model support

### ISSUE THREAD

**Issue by lisa0314** [lutzroeder/netron#437]
I try to load a quantization int8 model consist of these ops (https://github.com/pytorch/pytorch/tree/master/caffe2/quantization/server#quantization-operators) using netron but it failed.  I want to make use whether the netron support caffe2 quantization model.

**Comment by lutzroeder** [comment]
Can you share the model file and describe the issue?

**Comment by lisa0314** [comment]
@lutzroeder this is the model which I used - https://github.com/cuiyanx/dnnl-models/blob/master/Image%20Classification/mobilenet/predict_net_int8.pbtxt.
And the result is as shown as below :
![image](https://user-images.githubusercontent.com/16891416/75981057-a3ccff80-5f1e-11ea-8b88-16b108da9168.png)
