### ISSUE TITLE
Wrong order of operator arguments in the rendering of the TFLite model

### ISSUE THREAD

**Issue by yurivict** [lutzroeder/netron#441]
This model https://people.freebsd.org/~yuri/model-netron-order-bug.tflite is rendered with a wrong order of Div arguments:

![image](https://user-images.githubusercontent.com/271906/76569204-c5bf0880-646f-11ea-8529-e13367d162be.png)

In the model the order is ```{input2,softmax}```, and in the rendering it is ```{softmax,input2}```.

**Comment by lutzroeder** [comment]
The order is shown in node properties. The graph layout is not order dependent. Not a priority to fix this but feel to submit a PR if you have a fix.

**Comment by lutzroeder** [comment]
[model-netron-order-bug.tflite.zip](https://github.com/lutzroeder/netron/files/4327238/model-netron-order-bug.tflite.zip)
