### ISSUE TITLE
onnx filter weight dimension

### ISSUE THREAD

**Issue by tensorbuffer** [lutzroeder/netron#442]
I would like to know when neutron shows weight dimension if it does any re-arrangement.
Attached onnx model, in neutron web interface, it shows the Conv has type: float32[4,3,3,2]
However when I used onnx-tensorflow project to open it it shows the weight has dimension (3, 2, 3, 4):
(Pdb) type (init)
<class 'onnx.onnx_ONNX_REL_1_6_ml_pb2.TensorProto'>
(Pdb) init.dims
[3L, 2L, 3L, 4L]

[model.onnx.zip](https://github.com/lutzroeder/netron/files/4327131/model.onnx.zip)

**Comment by lutzroeder** [comment]
Netron shows the dimensions in the same order stored in the ONNX file.

> https://github.com/onnx/onnx/blob/master/docs/Operators.md#Conv
> The weight tensor that will be used in the convolutions; has size (M x C/group x kH x kW)

[model.pbtxt.zip](https://github.com/lutzroeder/netron/files/4327230/model.pbtxt.zip)

```
ir_version: 3
producer_name: "pytorch"
producer_version: "0.3"
graph {
  node {
    input: "0"
    input: "1"           // --> initializer #1
    input: "2"
    output: "3"
    op_type: "Conv"
    // ...
  }

  initializer {
    dims: 4              // <--- 4, 3, 3, 2
    dims: 3
    dims: 3
    dims: 2
    data_type: 1
    name: "1"            // <--- initializer #1
    raw_data: ...
  }
```

**Comment by tensorbuffer** [comment]
Thanks!
