### ISSUE TITLE
Client Application can't select PaddlePaddle model file

### ISSUE THREAD

**Issue by DistChen** [lutzroeder/netron#443]
I can't select PaddlePaddle model file `__model__`  by client application(macOS).

But I can load PaddlePaddle model file `__model__`  by python server：
```
pip install netron
netron /***/__model__
```

I think something is wrong with the client application.

**Comment by DistChen** [comment]
This is a simple PaddlePaddle model file.
https://github.com/lutzroeder/netron/issues/198#issuecomment-443112438

**Comment by lutzroeder** [comment]
You can drag & drop the file into the app window. The macOS file dialog filters these files as they do not have a valid extension. To work around this would require allowing all file extensions which leads to a lot more failed loads and other bugs.

Please work with the PaddlePaddle team to introduce an official file extension for this format. Note protobuf based formats without a custom file extension are generally problematic as there is no mechanism to determine the protobuf format from the file content.

**Comment by DistChen** [comment]
@lutzroeder ok, thanks.
