### ISSUE TITLE
Export model weights file

### ISSUE THREAD

**Issue by wl3b10s** [lutzroeder/netron#450]
hi
i had a question on 

how to automatically save model's weights of each layer to  file through call netron from python? 
currently i only know the method to save weights of layer through webpage.

thank you.

**Comment by lutzroeder** [comment]
This is not supported and currently not a priority. To export all weights load the file with the framework it was created with and use the weights export or one of the many converters out there.

**Comment by lutzroeder** [comment]
Duplicate of #300
