### ISSUE TITLE
Windows Defender detects uninstaller for 4.0.0 as virus

### ISSUE THREAD

**Issue by RobinKa** [lutzroeder/netron#452]
After closing Netron and agreeing to updating to 4.0.0, Windows Defender detected the Netron uninstaller as a virus:

![image](https://user-images.githubusercontent.com/2614101/77831706-a3441500-7128-11ea-9f3b-40b9b83d27d1.png)

Maybe it should be submitted here https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by lutzroeder** [comment]
electron-userland/electron-builder#4793
