### ISSUE TITLE
Failed on X11 Forwarding

### ISSUE THREAD

**Issue by YuyaKobayashi** [lutzroeder/netron#455]
Hello, 

I was trying to visualize ONNX model via ssh but failed with the following message:

```fish
~> netron
X11 connection rejected because of wrong authentication.

(netron:21677): Gtk-WARNING **: 14:32:14.459: cannot open display: localhost:10.0

```

This error does not appear on other desktop application.

Does anybody know how to fix this?

**Comment by YuyaKobayashi** [comment]
Sorry, the versions are as below:
```
OS: Ubuntu18.04.3 LTS
Netron: 4.0.4
```

**Comment by lutzroeder** [comment]
Is this specific to Netron or are you having the same issue with other Electron apps as well?
