### ISSUE TITLE
cannot decode the relucel2 & unsqueeze op of the tmfile format

### ISSUE THREAD

**Issue by tuanhe** [lutzroeder/netron#456]
Hi，there
I had download the latest version of the Netron and open the tmfile , but found it cannot deocde the reducel2 and unsqueeze , could you help to confirm it ?
![图片](https://user-images.githubusercontent.com/4641886/78349425-2f958280-75d6-11ea-9a9b-26fb7c8a79d2.png)
The original model shows like:
![图片](https://user-images.githubusercontent.com/4641886/78349536-5653b900-75d6-11ea-845b-367e4fff7f61.png)

Thanks

**Comment by pierricklee** [comment]
Hi,
I found that in Tengine format these operators have not yet been defined according to: https://github.com/OAID/Tengine/blob/master/serializer/include/tengine/v2/tm2_format.h

If they are defined by yourself please commit them to Tengine's master branch and I'll keep Netron up-to-date with it.

Cheers.
