### ISSUE TITLE
Attributes change order on each time

### ISSUE THREAD

**Issue by NikolasMarkou** [lutzroeder/netron#459]
For every node we view attributes change order, it would be beneficial and increase ease of use if they were ordered in the same order always

**Comment by lutzroeder** [comment]
Can you share a sample file and screenshot?

**Comment by NikolasMarkou** [comment]
@lutzroeder 

Check the order here
![image](https://user-images.githubusercontent.com/1175820/78656333-e5f7b100-78cf-11ea-9e70-b75cb5805fe1.png)

and the order here
![image](https://user-images.githubusercontent.com/1175820/78656381-f9a31780-78cf-11ea-9b35-f642ae10e36a.png)

it would be convenient to have the order the same always

**Comment by lutzroeder** [comment]
What are downsides of always sorting this alphabetically for all formats and frameworks?

**Comment by NikolasMarkou** [comment]
@lutzroeder if its consistent for all i can't think of any downsides
