### ISSUE TITLE
import netron error

### ISSUE THREAD

**Issue by baolitoumu** [lutzroeder/Netron#46]
import onnx
import netron

#netron.serve_file("output/alexnet.onnx")
# Load the ONNX model
model = onnx.load("output/alexnet.onnx")

# Check that the IR is well formed
#onnx.checker.check_model(model)

# Print a human readable representation of the graph
#print(onnx.helper.printable_graph(model.graph))

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-13-43f7ecea263f> in <module>()
      1 import onnx
----> 2 import netron
      3 
      4 #netron.serve_file("output/alexnet.onnx")
      5 # Load the ONNX model

/usr/local/lib/python3.5/dist-packages/netron/__init__.py in <module>()
      1 #!/usr/bin/python
      2 
----> 3 from netron import serve_data
      4 from netron import serve_file

ImportError: cannot import name 'serve_data'

**Comment by lutzroeder** [comment]
This seems to be a Python 3.5 vs. Python 2.7 issue. Can you sync and check if latest works?

**Comment by baolitoumu** [comment]
i delete python2.7 and only use python3.6 and connect python to 3.6
