### ISSUE TITLE
Incorrect file extension split

### ISSUE THREAD

**Issue by craigmassie** [lutzroeder/netron#460]
When a URL is submitted as a parameter to Netron, the file extension is calculated from the substring of the last "." to the end of the url parameter. This breaks in the case that a URL has a user token i.e. `http:://someurl.com/file.h5?user_token=some.hash.with.dot`

As a workaround, this would extract the extension 'h5' from the url above:`url.split(/\#|\?/)[0].split('.').pop().trim();`

https://github.com/lutzroeder/netron/blob/5312521619c1071d24d7cfe5cd57e0f8c5aba7f1/src/view.js#L1167

**Comment by lutzroeder** [comment]
That approach would fail if the url is `http://someurl/download?filename=file.h5`? Adding `&identifier=file.h5` will override the filename used for detection. For example, `https://lutzroeder.github.io/netron?url=http:://someurl.com/file.h5?user_token=some.hash.with.dot&identifier=file.h5`.

**Comment by craigmassie** [comment]
Perfect, thanks Lutz.
