### ISSUE TITLE
Hope to support export as .ppt/.pptx file

### ISSUE THREAD

**Issue by GoingTime** [lutzroeder/netron#461]
Your software has given me great help. But in many cases, the exported .svg file is difficult to edit twice. For example, it may display abnormally when imported into Adobe Illustrator. If Netron support exporting to .pptx files, editing will be simpler, and compatibility issues will not easily occur. PowerPoint supports saving .pptx files as more than 20 different files, and many third-party files also provide extensive support for pptx files.

Thank you, best wishes

**Comment by GoingTime** [comment]
Don't consider supporting exporting to .pptx files in the future? Thank you

**Comment by lutzroeder** [comment]
@GoingTime can you work on this and submit a PR.

**Comment by GoingTime** [comment]
> @GoingTime can you work on this and submit a PR.

Sorry, I have n’t studied JavaScript, maybe I can do something in the future
