### ISSUE TITLE
Error loading model. Invalid file content. File contains Git LFS header.

### ISSUE THREAD

**Issue by jiapei100** [lutzroeder/netron#463]
I just tried the model at [bvlcalexnet-9.onnx](https://github.com/onnx/models/blob/master/vision/classification/alexnet/model/bvlcalexnet-9.onnx).

And after having successfully installed netrno by command `pip install --user netron`, and:

```console
➜  model git:(master) netron bvlcalexnet-9.onnx
Serving 'bvlcalexnet-9.onnx' at http://localhost:8080
``

I got this ERROR message:

> Error loading model. Invalid file content. File contains Git LFS header.


Can anybody give me a hand?

Cheers
Pei

**Comment by lutzroeder** [comment]
Open the file in a text editor and it will **not** and ONNX model but a text header from Git LFS. You incorrectly downloaded the file online or incorrectly cloned a Git LFS repository. It would be great if you can recommend an error message the would make this more obvious.

**Comment by jiapei100** [comment]
@lutzroeder 

Thank you ... Problem solved.  [https://github.com/onnx/models/blob/master/vision/classification/alexnet/model/bvlcalexnet-9.onnx](https://github.com/onnx/models/blob/master/vision/classification/alexnet/model/bvlcalexnet-9.onnx) is just empty. I've got to click on **Download** on that page to actually download the model file.

Thanks...

**Comment by lutzroeder** [comment]
@jiapei100 it would be helpful if you can make a recommendation how this error message should be phrased differently (but remain general) so you would have known what to do without asking.
