### ISSUE TITLE
how can i run it in 0.0.0.0 

### ISSUE THREAD

**Issue by baolitoumu** [lutzroeder/Netron#47]
now it's run in localhost:8080,i want run it in the *   ,and have i can stop the Processing

**Comment by baolitoumu** [comment]
sorry , i find the answer:     
`netron.serve_file(file='output/alexnet.onnx',host='0.0.0.0',port='8080')`

**Comment by baolitoumu** [comment]
but,how can i stop the process,not in shell like use the 'kill'   
it's better to be in Python

**Comment by lutzroeder** [comment]
Can you open a new issue with correct title for the 'stop process' issue. Also, isn't that more a general question on how you stop a python process once it's running? Would probably require some context on how to repro the issue...
