### ISSUE TITLE
New feature: display tflite metadata

### ISSUE THREAD

**Issue by freddan80** [lutzroeder/netron#470]
Hi @lutzroeder! Thanks for creating this project, it's extremely useful. I was wondering if you're interested in adding support for tflite metadata buffer interpretation (or accept contributions). More specifically, I'm interested in offline planned buffer metadata. Some background:

https://docs.google.com/document/d/16aTSHL5wxsq99t6adVbBz1U3K8Y5tBDAvs16iroZDEU/edit

Cheers!
Fredrik

**Comment by lutzroeder** [comment]
@freddan80 can you provide some more context. Is this a feature that is supported in TensorFlow Lite  and the current TensorFlow Lite engine or is this a proposal that you are planning implement for another engine? How would this information surface if supported in the UI? Is there official documentation for the officially supported TensorFlow Lite metadata properties?

**Comment by freddan80** [comment]
> @freddan80 can you provide more context:
> 
> * Is there official documentation enumerating valid TensorFlow Lite metadata properties?
It's only the RFC document above for now.
> * Sample files using metadata?
We can arrange a sample .tflite file.
> * Is `OfflineMemoryAllocation` officially supported and implemented in the current engine?
There's a PR for it currently. The RFC is approved though. Note that the functionality will only be supported the TFL for microcontrollers runtime, for now.
> * How would this information surface if supported in the UI?
We'd have to look into this, but I'm imagining a 'Metadata' field under model properties, that is expandable to display the relevant info.

Currently, I'm just exploring if there would be an interest in having this feature. I believe there'll be a big demand for this feature eventually, since it used by our ethos-u55 tools (see https://developer.arm.com/ip-products/processors/machine-learning/ethos-u55). 

Cheers!

**Comment by lutzroeder** [comment]
Let's circle back when there is some more clarity and this becomes part of the format standard. Adding an expander for metadata is an option, higher priority would probably be adding standard fields like `description` or `author` or `license` (see Core ML or ONNX). Looks like TensorLite Lit is trying a different approach [metadata_schema.fbs](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/support/metadata/metadata_schema.fbs).

**Comment by freddan80** [comment]
> Let's circle back when there is some more clarity and this becomes part of the format standard.

I'm not sure the format will ever be a part of schema.fbs, since the metadata buffer format is user defined.  

> Adding an expander for metadata is an option. It would have to be done in a way that keeps the UI simple, maybe similar to tensor initializers.

Agree. This is key.

> Looks like TensorLite Lite is trying a different approach metadata_schema.fbs.

I'm not sure what that experimental branch is actually for, but I'll check it out. Thanks! The offline planned tensor implementation is following this format:
https://github.com/tensorflow/tensorflow/blob/2d3828de27879655cc126bc2bb932de299b5153c/tensorflow/lite/schema/schema.fbs#L1056

> The main challenge here is probably keeping a balance between maintenance cost vs. walking down every experimental fork of the dozens of similar ML formats out there.

Absolutely agree! We can have a more detailed discussion when it's time.

Cheers!
