### ISSUE TITLE
Tex output

### ISSUE THREAD

**Issue by Aspie96** [lutzroeder/netron#471]
In reference to, https://github.com/HarisIqbal88/PlotNeuralNet/issues/63, I think it'd be beautiful to have some integration between the two.

Many ways are possible to achieve this.

**Comment by lutzroeder** [comment]
Netron works without Python installed and hence should not depend on Python packages. Integration with libraries requires that there is a guarantee these libraries get maintained and supported on all platforms going forward. Both would have to be addressed first.
