### ISSUE TITLE
Netron connects to Google Analytics without any warning

### ISSUE THREAD

**Issue by flatsiedatsie** [lutzroeder/netron#475]
Netron connects to Google Analytics, but doesn't offer any warning or consent option. This is not permitted under the GDPR.

**Comment by lutzroeder** [comment]
Please provide feedback if this works as expected. The rules are complicated and keep changing. Since this is a hobby it might be easier to deprecate support for some countries unless there is interest by someone local to debug and provide fixes.

**Comment by perone** [comment]
This doesn't seem to be working, I'm using Netron from a country that is listed in the countries that are supposed to be given consent, however I never got that consent confirmation. I checked the return from `https://ipinfo.io` and it is correct.

**Comment by lutzroeder** [comment]
@perone can you debug the issue and provide more context. Are you using the browser or desktop app?
