### ISSUE TITLE
The "Netron-Setup-4.1.0.exe" gets stuck while installing

### ISSUE THREAD

**Issue by SpikingNeuron** [lutzroeder/netron#476]
I am trying to install "Netron-Setup-4.1.0.exe" on windows 10 64 bit machine. And it gets stuck for a long time. See the screenshot below.
![image](https://user-images.githubusercontent.com/2289914/80325096-175eff00-8834-11ea-9976-4364788d806f.png)

**Comment by lutzroeder** [comment]
@SpikingNeuron can you investigate why this is happening and provide a fix or repro steps. This is likely either an [electron-builder](https://github.com/electron-userland/electron-builder) or machine-specific issue?

**Comment by alishobeiri** [comment]
Hi, I am having the same problem. 

For me, I had Netron installed, I uninstalled because it was not opening and then when I go to reinstall it, I get stuck exactly where SpikingNeuron is stuck. 

Is there a way around this or any files I need to clean off my machine?

**Comment by lutzroeder** [comment]
@alishobeiri same as above. There is no repro or indication what is causing this to happen so there isn’t a way to investigate. Can you check Event Viewer? Is there anything special with you Windows version? What version of Windows are you using. Can you search the electron-builder issues or file an issue there. It would be helpful if you can investigate this and provide some insights.
