### ISSUE TITLE
how to see size of each layer output feature

### ISSUE THREAD

**Issue by fengxiuyaun** [lutzroeder/netron#477]

**Comment by fengxiuyaun** [comment]
how to see size of each layer output feature and FLOPs of the whole net

**Comment by lutzroeder** [comment]
Output shape: See #71. The answer is different for each model format at the moment. Which model format are you using?

FLOPs: For metrics see #204. This is probably more of a feature of the specific runtime engine. If there is a general way to support this for all formats and you are interesting working on this we can discuss further.
