### ISSUE TITLE
The float32 value 0.001 is displayed as 0.0010000000474974513

### ISSUE THREAD

**Issue by yurivict** [lutzroeder/netron#478]
Testcase: https://people.freebsd.org/~yuri/model-containing-0.001.tflite

The test model has 0.001 in weights, but this number seems to be expanded to 'float64' when displayed.

Version 4.1.2

**Comment by lutzroeder** [comment]
@yurivict can you have a look and provide a fix?

**Comment by yurivict** [comment]
I don't have resources, sorry.

I am just a FreeBSD package maintainer and a user.

**Comment by NikolasMarkou** [comment]
@lutzroeder and @yurivict if you load up the data as float and then display it then the internal representation of 0.001 is not accurate in float32 or float64. So the only way to accurately show it is use numeric format when loading and avoid the conversion all together

**Comment by hollance** [comment]
There is no such thing as the 32-bit float value 0.001. Your tflite model does not have a weight that is 0.001. It has a weight that is 0.0010000000474974513.

Do the following in Python to see this (or your favorite language):

```
import numpy as np
a = np.array([0.001], dtype=np.float32)
print("%.20f" % a)
```

It will print 0.00100000004749745131.

**Comment by yurivict** [comment]
You are right!

```libdouble-conversion``` (https://github.com/google/double-conversion) says that the decimal representation for ```0x3a83126f``` is ```0.0010000000474974513```.

**Comment by lutzroeder** [comment]
```cpp
#include <stdlib.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
	unsigned char byte_array[] = { 0x6f, 0x12, 0x83, 0x3a };
	float float_value = *(float *)&byte_array;
	printf("%f\n", float_value);
	double double_value = float_value;
	printf("%f\n", double_value);
}
// 0.001000
// 0.001000
```

```C#
class Program
{
    static void Main(string[] args)
    {
        byte[] array = new byte[] { 0x6f, 0x12, 0x83, 0x3a};
        float float_value = System.BitConverter.ToSingle(array, 0);
        System.Console.WriteLine(float_value.ToString());
        double double_value = float_value;
        System.Console.WriteLine(double_value.ToString());
    }
}
// 0.001
// 0.0010000000474974513
```

**Comment by yurivict** [comment]
This shows that ```printf``` and ```System.Console.WriteLine``` have some arbitrary rounding thresholds and don't display floating point values properly.

libdouble-conversion converts to a decimal representation precisely, but it unfortunately only has a C API interface and is therefore more difficult to use.

**Comment by hollance** [comment]
Just to be pedantic about it :smile:, if you replace `printf("%f\n", float_value);` in the C version with `printf("%.20f\n", float_value);` it gives the 0.0010000000474974513 version.
