### ISSUE TITLE
Version 4.1.2 failing for certain models!

### ISSUE THREAD

**Issue by Roh1t129** [lutzroeder/netron#479]
[model.zip](https://github.com/lutzroeder/netron/files/4565705/model.zip)

We were using netron to visualize tflite flatbuffer models and various modified versions of them. The models and modified versions executed correctly on target systems and we could visualize them correctly using Netron version 3.9.7. But as soon as we updated to version 4.1.2 the modified graphs netron is giving the following error:

Error loading TensorFlow Lite model. Failed to execute 'decode' on 'TextDecoder': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'

I am attaching a sample model for your reference which will work in version 3.9.7 but not in 4.1.2, Please note that we were using "netron" as visualizer for our research. We found it as an amazing tool! We would appreciate your help

Thanks,
Rohit Sahu

**Comment by lutzroeder** [comment]
[netron_issue_479.zip](https://github.com/lutzroeder/netron/files/4565988/netron_issue_479.zip)
