### ISSUE TITLE
TensorFlow Lite metadata support

### ISSUE THREAD

**Issue by gustheman** [lutzroeder/netron#481]
Showing TF Lite metadata when viewing a model would help understanding it's usage
The same feature also allows the developer to append resources files to the model (like label and vocab files). Showing this would also be great

Official doc: https://www.tensorflow.org/lite/convert/metadata
lib code: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/support/metadata

**Comment by lutzroeder** [comment]
Can you provide a few sample files?

**Comment by lutzroeder** [comment]
[mobilenet_v1_0.75_160_quantized.zip](https://github.com/lutzroeder/netron/files/4569400/mobilenet_v1_0.75_160_quantized.zip)

**Comment by lutzroeder** [comment]
tensorflow/tensorflow#39109

**Comment by gustheman** [comment]
sorry for the delay in getting you a sample and thanks for already having it!!
