### ISSUE TITLE
Scale Factor Clarification

### ISSUE THREAD

**Issue by naveen-chander** [lutzroeder/netron#485]
I'm looking to hand-code the forward path for a quantized model using the values from Netron GUI.

I'm not sure what the value in the "quantization " field means. Is it the scaling factor? ( weight = q* uint8_number)
if so, then what is the meaning when the quantization has "0.046*q--9" in its field?(image attached)

![netron_image](https://user-images.githubusercontent.com/65017357/81397050-328b1200-9144-11ea-988a-ddf02f758c71.PNG)

**Comment by lutzroeder** [comment]
[schema.fbs](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs)

```
  // Given a quantized value q, the corresponding float value f should be:
  //   f = scale * (q - zero_point)
```
