### ISSUE TITLE
Weights export 

### ISSUE THREAD

**Issue by holoLens8** [lutzroeder/netron#489]
Is there a way to export weights as int8 instead of float32.
I tried to visualize a quantized network, but I always get float32 weights.

**Comment by lutzroeder** [comment]
Can you share the model file?

**Comment by lutzroeder** [comment]
Duplicate of #300

**Comment by holoLens8** [comment]
Here is the file.
Thanks


Nermine

Le lun. 11 mai 2020 à 16:57, Lutz Roeder <notifications@github.com> a
écrit :

**Comment by lutzroeder** [comment]
ONNX forums might be a better place to ask how quantization works in ONNX?
