### ISSUE TITLE
Integrate with Trains

### ISSUE THREAD

**Issue by bmartinn** [lutzroeder/netron#490]
Hi @lutzroeder 
I love what you are doing with Netron! 
It is an awesome tool, and I thought it might be nice to have Netron visualize models created in [Trains](https://github.com/allegroai/trains) .

Since Trains auto-magically logs (and can upload) any models stored with PyTorch/TF/Keras/Scikit/XgBoost , I thought it will be nice to have the ability to visualize them with Netron.

What do you think?

**Comment by lutzroeder** [comment]
Have you tried sending the model using the`?url=` parameter to the Netron browser version?

https://lutzroeder.github.io/netron?url=https://raw.githubusercontent.com/google/mediapipe/master/mediapipe/models/hair_segmentation.tflite

**Comment by bmartinn** [comment]
Yes, that works :)
I thought that it would be nice to somehow pass the URL through the server. Let's assume we have a server storing the file, and next to it a server running Netron. If the model file is large then download might take a while. If you are switching between different models, than downloading every model (which could be half a minute) is not the best experience. I thought it might be nice to somehow pass the model directly to the server running the Netron.
Do you think that's possible ?

**Comment by lutzroeder** [comment]
Netron is running on the client (in the browser), there is no "server". One approach to make downloads faster might be stripping the weights from the model file (or not serving weights files).

**Comment by bmartinn** [comment]
I see... Actually from how it looks, Netron could be statically served, e.g. Nginx could just serve the entire folder, correct?
Also, I was thinking I could  probably add an external interface to NodeJS , and run the processing part on a NJS server, and only send the display .json  for the client to display?
