### ISSUE TITLE
Blue screen

### ISSUE THREAD

**Issue by holoLens8** [lutzroeder/netron#491]
After installing the application on windows 10, I'm always getting a bluescreen.

**Comment by lutzroeder** [comment]
- Is this happening on multiple computers or only a single one?
- Is this happening for other Electron apps as well, [Caprine](https://github.com/sindresorhus/caprine/releases) for example?
- Can you provide steps to reproduce this behavior? For example, is the blue screen happening after the installer completes or when launching the app?
- Can you investigate if there are any error logs or what might be causing this issue?

**Comment by holoLens8** [comment]
> * Is this happening on multiple computers or only a single one?
> * Is this happening for other Electron apps as well, [Caprine](https://github.com/sindresorhus/caprine/releases) for example?
> * Can you provide steps to reproduce this behavior? For example, is the blue screen happening after the installer completes or when launching the app?
> * Can you investigate if there are any error logs or what might be causing this issue?

I did not try on multiple computers. 
The blue screen happens after launching the app or after closing it.
When uninstalled it, everything is back to normal.
