### ISSUE TITLE
pytorch: how to get pytorch input and output node information

### ISSUE THREAD

**Issue by lee64456546** [lutzroeder/netron#492]
how to get pytorch input and output node information

**Comment by lutzroeder** [comment]
Can you share a sample file? Based on the format you are using PyTorch might or might not store that information in the file.

**Comment by lee64456546** [comment]
[sample_net.zip](https://github.com/lutzroeder/netron/files/4619704/sample_net.zip)

**Comment by lutzroeder** [comment]
This format doesn't store all information about the graph. Even the graph is more a best guess extracted from what's in the file. Best approach is probably to use the code that produced this file and export to ONNX and use ONNX inference (see #71) to fill in the shapes.
