### ISSUE TITLE
Link to model files on Ubuntu 16.04

### ISSUE THREAD

**Issue by cowyyy** [lutzroeder/netron#493]
recently I upgrade from netron3 to netron4 on UBUNTU16.04 and find that only .APPIMAGE provided, but this won't automatically link to any models file(onnx, pt etc.), I have to open and drag model into Netron. I tried a lot(also snap) but cannot fix it.

**Comment by lutzroeder** [comment]
@cowyyy can you investigate this issue and recommend a fix?
