### ISSUE TITLE
Linux "cannot open display: :1" error

### ISSUE THREAD

**Issue by chankim** [lutzroeder/netron#496]
hi, 
I've installed netron by 'snap install netron' but how should I use it?
I tried 'netron' but didn't work. tried 'snap run netron' but it gives me

No protocol specified
(netron:11020): Gtk-WARNING **: 13:37:59.767: cannot open display: :1

I tried setting 'export DISPLAY = :0.0' to no avail. and tried 'sudo snap run netron' and it gives me
mkdir: cannot create directory '/run/user/0': Permission denied

I wish there be the direction for running it not just for installing it
(but I can run it on windows)

**Comment by lutzroeder** [comment]
Can you have a look at sindresorhus/caprine#1006 or electron/electron#10915 and try if this works?

**Comment by chankim** [comment]
Thanks,
by the way, I was doing it on a vnc window, so I tried it on console widow just now.
it runs ok with 'snap run netron'. so sure it is Xorg related(?). I'll try your method sooner or later.
