### ISSUE TITLE
PyTorch: Loading 10 GB model fails

### ISSUE THREAD

**Issue by psyhtest** [lutzroeder/netron#497]
Loading the [~10 GB DLRM model](https://dlrm.s3-us-west-1.amazonaws.com/models/tb0875_10M.pt) from [MLPerf Inference](https://github.com/mlperf/inference/tree/db0b7eb368f009adf703d073765aa212d1f3a026/v0.5/recommendation) [failed](https://github.com/mlperf/inference/issues/608#issue-623152831) on an Ubuntu 18.04 machine with 32 GB RAM:
- from the browser: `File read error '0'.`
- from the command line: `Error loading model. Unsupported file content for extension '.pt' in 'tb0875_10M.pt'.` (memory usage shoot up to 27 GB)

I would completely understand if the same thing happened with the ~100 GB model :), but maybe the ~10 GB one could be supported still?

P.S. Netron is a beautiful and useful tool - thank you so much for it @lutzroeder!

**Comment by lutzroeder** [comment]
[ColorizeVideo_PretrainOnly_gen.pth](https://www.dropbox.com/s/avzixh1ujf86e8x/ColorizeVideo_PretrainOnly_gen.pth?dl=0)

**Comment by lutzroeder** [comment]
https://console.cloud.google.com/storage/browser/vit_models/imagenet21k

**Comment by lutzroeder** [comment]
The desktop app now supports this. The Web and Python versions are constrained by the 2 GB browser limit.
