### ISSUE TITLE
sklearn ColumnTransformer and FeatureUnion support

### ISSUE THREAD

**Issue by mbalatsko** [lutzroeder/netron#498]
It would be great to add a feature of visualization branching inside `sklearn.pipeline.Pipeline`. For now, all transformers which are inside  `ColumnTransformer` or `FeatureUnion` are not visualized and are shown as attributes. This makes not possible to get pipeline structure insight. To be more clear I'll add an example how it should look like.

Current visualization:
![Current vizualization](https://user-images.githubusercontent.com/15967073/82681012-6c344080-9c4d-11ea-9e6b-4c1c0f1b4a0e.png)

Improved visualization:
![Improved visualization](https://user-images.githubusercontent.com/15967073/82681296-dea52080-9c4d-11ea-85eb-c388eeaddc87.png)

**Comment by mbalatsko** [comment]
I can help you with this improvement and actually get it done. If you are interested do not hesitate to contact me. Your project is used in one product that I really like and I would really appreciate this improvement

**Comment by lutzroeder** [comment]
@mbalatsko can you share a sample file?

**Comment by mbalatsko** [comment]
Code with column transformer:
```python
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_extraction.text import TfidfVectorizer


categorical_columns = ['Sex', 'JobType']
numeric_columns = ['Age', 'Salary']
text_columns = ['job_description']

model = Pipeline([
    ('preprocessing', ColumnTransformer([
        ('text_preprocessing', TfidfVectorizer(), text_columns),
        ('categorical_preprocessing', OneHotEncoder(), categorical_columns),
        ('numeric_preprocessing', Pipeline([('impute', SimpleImputer()), ('scale', StandardScaler())]), numeric_columns)
    ])),
    ('fs', SelectKBest(k=1000)),
    ('clf', LogisticRegression())
])
```
Model file:
[column_transformer_pipeline.zip](https://github.com/lutzroeder/netron/files/4670399/column_transformer_pipeline.zip)

**Comment by mbalatsko** [comment]
Code with feature union:
```python
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.compose import ColumnTransformer
from sklearn.decomposition import PCA, TruncatedSVD
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest

model = Pipeline([
    ('preprocessing', FeatureUnion([
        ('pca', PCA()),
        ('svd', TruncatedSVD()),
    ])),
    ('fs', SelectKBest(k=1000)),
    ('clf', LogisticRegression())
])
```
Model file:
[feature_union_pipeline.zip](https://github.com/lutzroeder/netron/files/4670418/feature_union_pipeline.zip)

**Comment by mbalatsko** [comment]
@lutzroeder https://github.com/lutzroeder/netron/pull/501 pls review my PR

**Comment by lutzroeder** [comment]
[column_pipeline.zip](https://github.com/lutzroeder/netron/files/4672437/column_pipeline.zip)
[column_transformer_pipeline.zip](https://github.com/lutzroeder/netron/files/4672438/column_transformer_pipeline.zip)

**Comment by mbalatsko** [comment]
@lutzroeder #502 pls review my PR
