### ISSUE TITLE
TensorFlow Lite: FlexBuffers support

### ISSUE THREAD

**Issue by ankandrew** [lutzroeder/netron#499]
I couldn't find an issue related. The doubt is why I can't see this model properly: https://github.com/google-coral/edgetpu/raw/master/test_data/efficientnet-edgetpu-S_quant_edgetpu.tflite

I just see the following:

![image](https://user-images.githubusercontent.com/61120139/82718841-8127c880-9c7b-11ea-8f62-457bc393385a.png)

**Comment by ankandrew** [comment]
Thanks

**Comment by ankandrew** [comment]
Behind the scenes edgetpu-custom-op is doing some commons operations, and in the case this is a strange format not considered yet, can't it get supported?

**Comment by ankandrew** [comment]
@lutzroeder a short comment could help

**Comment by lutzroeder** [comment]
It's a custom operator with binary data which is not included in the documentation. If you can find documentation feel free to add support.

**Comment by lutzroeder** [comment]
[quicknet.zip](https://github.com/lutzroeder/netron/files/5184953/quicknet.zip)

**Comment by lgeiger** [comment]
Thanks for the fast fix!
