### ISSUE TITLE
Inputs validation

### ISSUE THREAD

**Issue by yurivict** [lutzroeder/netron#500]
Testcase: https://people.freebsd.org/~yuri/model-bad-Split.tflite

The Split operator there only has one input (axis) when two inputs are required: axis and input

netron can easily show a warning about the input number mismatch.

Version: 4.1.2

**Comment by lutzroeder** [comment]
@yurivict make sure that when you find time to work on this it will support all operators and all 25+ supported formats.

**Comment by yurivict** [comment]
Sorry, I am only a user and a package maintainer, and don't have resources to develop patches.
