### ISSUE TITLE
Error: EACCES: permission denied, open "..." on Linux

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#504]
Snap on Linux will restrict folder access unless required [interfaces](https://snapcraft.io/docs/supported-interfaces) are connected. The [removable-media](https://forum.snapcraft.io/t/auto-connect-removable-media-for-netron/17919) interface is getting auto-connected. [Other](https://forum.snapcraft.io/t/auto-connect-personal-files-for-netron/33024) interfaces will require a manual connection.

**Comment by syedmohsinbukhari** [comment]
For me it is still causing this problem even after adding `removable-media` tag

**Comment by lutzroeder** [comment]
@syedmohsinbukhari can you investigate why this is happening or provide some context why it might happen that might help others investigate.

**Comment by zylo117** [comment]
I found out when the model files are in the hidden folder like `.hidden_folder/model.json` under linux, netron will report this error.

**Comment by lutzroeder** [comment]
@zylo117 this happens only if the hidden folder is under the `~` folder -- correct?

**Comment by zylo117** [comment]
Yes, it's under `~` and I'm using snap, but I haven't tried putting model files in folders other than `~` folder.
If I move the model files to `/tmp/.hidden_folder/` and drag the file into netron, a js error will occur saying there is no such file.

**Comment by karstenpatzwaldt** [comment]
This is still happening if the file opened is not owned by the same user as the one executing the tool, even if the user has read permissions.

**Comment by lutzroeder** [comment]
@karstenpatzwaldt can you investigate why this is happening and provide a fix?

**Comment by karstenpatzwaldt** [comment]
No.

**Comment by dragen1860** [comment]
any solutions?

**Comment by lutzroeder** [comment]
@dragen1860 can you investigate why this is happening and provide a fix?

**Comment by lutzroeder** [comment]
@dragen1860 can you investigate why this is happening and provide a fix?

**Comment by FrancescoTosetti** [comment]
@dragen1860 just change file's ownership. You can do this simply with `sudo chown -R <type_your_user_here> <model_path>`

**Comment by lutzroeder** [comment]
@FrancescoTosetti is this a limitation of Snap or is there an [interface](https://snapcraft.io/docs/supported-interfaces) to support this? There seems to be an approval process, can you help getting the right interfaces approved if they exist.
