### ISSUE TITLE
onnx model fails to open in web version

### ISSUE THREAD

**Issue by daquexian** [lutzroeder/netron#505]
https://drive.google.com/file/d/1x6owrQOCicgiRkd7dAcV-QP_O2yK_j1s/view?usp=sharing

it is a simple onnx model containing only a transpose node, whichl can be open in netron 4.2.7 installed from pypi, but cannot be open in https://netron.app

**Comment by lutzroeder** [comment]
How are you trying to open it, in which browser, which OS and what is not working?

**Comment by daquexian** [comment]
@lutzroeder it is on ubuntu 16.04, chrome 81. the error message is "Error loading model: Unknown node operator 'undefined' in 'ONNX v6'"

But the problem has disappeared after I refreshed the webpage just now, should I close this issue? ( I also refreshed several times before posting the issue but not work)
