### ISSUE TITLE
Provide local path as query string

### ISSUE THREAD

**Issue by akjoshi6** [lutzroeder/netron#506]
Like we are able to provide url parameter in query string for netron server. Can we also provide local file path as query string

For example:

https://localhost:8080/?filepath=/home/user/filename.pb

**Comment by lutzroeder** [comment]
How would this work given the browser doesn't have access to your files?

**Comment by akjoshi6** [comment]
I wanted to access local files where local server is running or self hosted files in case of server.

Got it running using this:
http://localhost:8080/?data=home/akshay/models/detection.pb

Thanks.
