### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by hl0737** [lutzroeder/netron#508]
hi, i want to visulize my pytorch network and i save it use 'torch.save(net, './best_model.pth')'

but when i input the commond 'netron best_model.pth' in console, it prompt

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 0: invalid continuation byte

so , whats the problem ????

**Comment by lutzroeder** [comment]
Can you share the model file? What OS and Python version are you using? Does the same error happen when you load the file in the web version?
