### ISSUE TITLE
Ensure version string gets added as meta tag in index.html in more build cases

### ISSUE THREAD

**Issue by shawnlewis** [lutzroeder/netron#509]
I'm using build_python to get an embeddable javascript bundle.

Currently the version meta tag only gets added to index.html by the publish_github_pages make step. It seems like it would be nice to add it earlier in the process, so that it's there if someone grabs the js bundle from dist.

**Comment by lutzroeder** [comment]
For context, this is not a supported scenario. `build_github_pages` builds a website, not a bundle.
