### ISSUE TITLE
TensorFlow Lite: activations removed from layers

### ISSUE THREAD

**Issue by mm7721** [lutzroeder/Netron#514]
Hi there,

First off, just wanted to say thanks for creating such a great tool - Netron is very useful.  

I'm having an issue that likely stems from Tensorflow, rather than from Netron, but thought you might have some insights. In my flow, I use TF 1.15 to go from .ckpt --> frozen .pb --> .tflite.  Normally it works reasonably smoothly, but a recent run shows an issue with the .tflite file: it is created without errors, it runs, but it performs poorly.  Opening it with Netron shows that the activation functions (relu6 in this case) have been removed for every layer.  Opening the equivalent .pb file in Netron shows the relu6 functions are present.

Have you seen any cases in which Netron struggled with a TF Lite model (perhaps it can open, but isn't displaying correctly)?  Also, how did you figure out the format for .tflite files (perhaps knowing this would allow me to debug it more deeply)?

Thanks in advance.

**Comment by lutzroeder** [comment]
`.tflite` file is a flatbuffer using [schema.fbs](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs). To convert to JSON you can run #487.

**Comment by lutzroeder** [comment]
Unrelated, `fused_activation_function` is not getting resolved correctly in 4.3.1 (#516).

**Comment by lutzroeder** [comment]
tensorflow/tensorflow#40363

**Comment by mm7721** [comment]
Awesome, thanks.  Exactly what I was looking for.

**Comment by mm7721** [comment]
Ok, got flatc working.  I notice that there are relu6 activations present in the json, but these don't show up in the Netron display.  Is this expected (perhaps related to the issue you mentioned about fused activations)?

For example:
          "type": "UINT8",
          "buffer": 227,
          "name": "FeatureExtractor/MobilenetV2/expanded_conv_12/expand/Relu6",
          "quantization": {
            "min": [
              0.0
            ],
            "max": [
              5.970459
            ],
            "scale": [
              0.023414
            ],
            "zero_point": [
              0
            ],
            "details_type": "NONE",
            "quantized_dimension": 0
          },
          "is_variable": false
        },

is from the json, but not displayed in Netron.

**Comment by lutzroeder** [comment]
Can you share the file?

**Comment by mm7721** [comment]
Sure, here's the .tflite file.  Will that suffice?

[model.zip](https://github.com/lutzroeder/netron/files/4767629/model.zip)

**Comment by lutzroeder** [comment]
<kbd>Ctrl</kbd>+<kbd>F</kbd> or <kbd>&#8984;</kbd>+<kbd>F</kbd>, search for `FeatureExtractor/MobilenetV2/expanded_conv_12/expand/Relu6`. It will show that this is a connection between two nodes with quantization min/max at 0...6.

<img width="1136" alt="screenshot" src="https://user-images.githubusercontent.com/438516/84449382-1f1b0d00-ac02-11ea-8c69-d10b5d7bc997.png">

**Comment by mm7721** [comment]
Ahhh so it is there, just not explicitly displayed.  I've got other builds of the same model (but with different param values), and sometimes the activation layer is displayed visually within the Conv2D or DepthwiseConv2D box.  What determines if it's displayed explicitly or if it's embedded in an arrow between layers?

![relu6_display](https://user-images.githubusercontent.com/48816441/84451074-cf8b1000-ac06-11ea-88af-958542d46a3c.png)

**Comment by lutzroeder** [comment]
Layer gets stripped from the model and replaced with min/max when quantitation is used? Like I said, TensorFlow repo is probably a better place to ask those questions. It’s all open source so you can even look at the code.
