### ISSUE TITLE
Unsupported datatype class '8' in Keras model

### ISSUE THREAD

**Issue by Tydus** [lutzroeder/netron#517]
When I was trying to import a keras model (namely WDSR, download from [google drive](https://drive.google.com/open?id=1JfQNGQZ9cG-lyC5EB0W3MpySjPlDJXpU)), it prompts me like this.

I'm not familiar with the internals so I cannot see what happened. Just guessed the reason is the lambda layers?

Keras shipped `plot_model` gave me as follows (ugly).
 ![download](https://user-images.githubusercontent.com/1108799/84339241-fe8a8d00-abd8-11ea-972a-81a3d5d336ad.png)

Any help is appreciated.

**Comment by lutzroeder** [comment]
The file only contains weights, no graph (see #73). Can you share the code that produced the file?

The error is due to a low level HDF5 parsing issue storing `initialized:0` for the normalization layers. It should be an easy fix but the spec is a bit vague.
