### ISSUE TITLE
Display node input and output names

### ISSUE THREAD

**Issue by postrational** [lutzroeder/netron#52]
Currently the Inputs and Outputs section for each node displays only the variable name from spec, but doesn't show the names contained in the open protobuf file. It's useful to see those when debugging a graph, so you know which operation you are looking at.

**Comment by lutzroeder** [comment]
Latest version allows clicking on all inputs and shows the input connection names. #50 is tracking work for a more general side bar view that shows all attributes, inputs and outputs for a given node.

**Comment by lutzroeder** [comment]
8a47a6c

**Comment by lutzroeder** [comment]
9be8149
