### ISSUE TITLE
Feature Request: Netron TensorBoard Plugin

### ISSUE THREAD

**Issue by dhruvin2910** [lutzroeder/netron#520]
First off, thank you for developing this project.

TensorBoard seems to be good at visualising graphs of the models, but only of its own ecosystem.
I think it'd be great if we can extend its functionality with Netron by providing a plugin for TB.

So I developed a TB plugin. I tested a couple of keras models and it seems to be working fine.

I was wondering if you think something like this could be a good addition to this project. Let me know if I should make a PR.

**Comment by lutzroeder** [comment]
It's not a priority at the moment. Can you explain some more how this would work and how it would be used? The general trend is that each "integration" comes with additional bugs and maintenance overhead so that would need to be addressed.

**Comment by dhruvin2910** [comment]
> It's not a priority at the moment. Can you explain this would work and how it would be used?

Please see this [video](https://imgur.com/a/j45SiiU).
Netron hosts the static files when `$ netron ...` is run.
Here, the tensorbaord hosts the files, provided by `netron` package.
The plugin is just a [wrapper](https://github.com/dhruvin2910/netron/blob/4a3ce8c9d309be948a8246eddc9ec5033f9820bf/src/tb_plugin.py) to bring the visualisations at one place.

> The general trend is that each "integration" comes with additional bugs and maintenance overhead so that would need to be addressed.

I can understand.

**Comment by dhruvin2910** [comment]
For people who may be looking for it, I published a plugin [here](https://github.com/dhruvin2910/tensorboard-plugin-netron).
