### ISSUE TITLE
Netron fails to start behind VPN

### ISSUE THREAD

**Issue by postrational** [lutzroeder/netron#522]
I had problems starting recent versions of Netron while being connected to our company VPN. The application was stuck on the initial spinner and never loaded a model. Disconnecting from VPN helped, the app started. It now starts normally.

Whatever call home Netron does as it's starting, perhaps it should timeout after a few seconds. 
Better support for detecting VPN settings may be a fix.

**Comment by lutzroeder** [comment]
Desktop or browser version? Can you run with a debugger and find what is causing it?

**Comment by postrational** [comment]
I'm using the Desktop version. How do I attach a debugger to it?

**Comment by lutzroeder** [comment]
See [DEVELOPMENT.md](https://github.com/lutzroeder/netron/blob/master/DEVELOPMENT.md). `Launch Program` to debug the host process which is running update. `Debug Renderer Process` to debug the actual view.
