### ISSUE TITLE
[Ubantu 18.04] How to save the visualization result  loaclhost:8080  to .html

### ISSUE THREAD

**Issue by daydayfun** [lutzroeder/netron#523]
I'm using this tool in Ubantu 18.04.
The visualization result is in localhost:8080, the result is execllent.  But I don't know how to save the result as a file.(such as resnet50.html/mlp.html/mobilenet.html...)

Can you help me fix the requirement, thanks very much!

**Comment by daydayfun** [comment]
I try to modify server.py to save the  visualization result, but failed...

**Comment by lutzroeder** [comment]
Duplicate of #162

**Comment by daydayfun** [comment]
Thanks very much,  I'm going to use the offline Appimage

**Comment by lutzroeder** [comment]
The browser version includes these options:

<img width="610" alt="screenshot" src="https://user-images.githubusercontent.com/438516/84862235-acf26000-b027-11ea-9889-4feb9a7fcc69.png">

**Comment by daydayfun** [comment]
How to use the appImage in command line, can you help me with some example
