### ISSUE TITLE
TorchScript: Unsupported function 'torch.empty'

### ISSUE THREAD

**Issue by lyfe667** [lutzroeder/netron#530]

**Comment by lutzroeder** [comment]
Can you share a sample file?

**Comment by lyfe667** [comment]
> 
> 
> Can you share a sample file?

Sorry, I can't upload the model because of the security policy of our company. It is yolov3 , the repo is there: https://github.com/eriklindernoren/PyTorch-YOLOv3 . I have solved the issue by modifying torch.empty to torch.zeros .
