### ISSUE TITLE
How to render custom ONNX annotations

### ISSUE THREAD

**Issue by maltanar** [lutzroeder/netron#532]
Hi! First of all, thank you for making Netron and sharing it with the community. We use Netron in our quantized neural network compiler FINN (https://github.com/Xilinx/finn) to visualize ONNX, including as part of Jupyter notebook visualizations and it's been immensely useful. 

I would like to extend Netron to render some ONNX annotations but I don't know where to start, so I thought I'd ask for some help here first. In our project we work with few-bit integer tensors and we use custom tensor annotations in ONNX to represent them, by using the ONNX `quantization_annotation` field to carry strings that indicate the datatype. I want to add the possibility of visualizing the tensor quantization annotation next to (or instead of) the tensor shapes that are printed, something like this:

![Screenshot from 2020-07-07 14-49-08-edited](https://user-images.githubusercontent.com/1880902/86791507-842b1c80-c061-11ea-8ab9-8aa9bea329ad.png)

How would I go about doing something like this? Any tips would be highly appreciated!

**Comment by lutzroeder** [comment]
Can you share a sample file?

**Comment by maltanar** [comment]
Sure, here is one:

[end2end_tfc_w1a1_oqnt_streamlined.zip](https://github.com/lutzroeder/netron/files/4885310/end2end_tfc_w1a1_oqnt_streamlined.zip)

Here's how accessing the annotations look like in Python, for reference:

```
maltanar@finn_dev_maltanar:/workspace/finn$ ipython
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import onnx                                                                                                                      

In [2]: model = onnx.load("/tmp/finn_dev_maltanar/end2end_tfc_w1a1_oqnt_streamlined.onnx")                                               

In [3]: model.graph.quantization_annotation[0]                                                                                           
Out[3]: 
tensor_name: "MatMul_0_param0"
quant_parameter_tensor_names {
  key: "finn_datatype"
  value: "BIPOLAR"
}

In [4]: model.graph.quantization_annotation[1]                                                                                           
Out[4]: 
tensor_name: "MatMul_1_param0"
quant_parameter_tensor_names {
  key: "finn_datatype"
  value: "BIPOLAR"
}
```

**Comment by lutzroeder** [comment]
[end2end_tfc_w1a1_oqnt_streamlined.zip](https://github.com/lutzroeder/netron/files/4885362/end2end_tfc_w1a1_oqnt_streamlined.zip)

**Comment by lutzroeder** [comment]
<img width="990" alt="screenshot" src="https://user-images.githubusercontent.com/438516/86795762-bec19480-c022-11ea-845c-d51efeaaeee8.png">

**Comment by maltanar** [comment]
Fantastic, thank you!
