### ISSUE TITLE
TensorRT support

### ISSUE THREAD

**Issue by israelwei** [lutzroeder/netron#533]
Hello, 
first of all, thanks for this awesome tool! It's extremely helpful.
Is there a possibility / option to open in Netron also "engine" files of TensorRT inference engine? Because currently I see it's not possible but I think it might be helpful...

**Comment by lutzroeder** [comment]
Can you share a sample file?

**Comment by israelwei** [comment]
> Can you share a sample file?
Attached below (standard imagenet classification model)
https://drive.google.com/file/d/1C6y4Pozah_0jMvSm5fCctFnvRZRiFFJC/view?usp=sharing

**Comment by lutzroeder** [comment]
Is this format documented?

**Comment by israelwei** [comment]
It's possible to deserialize such a file either in Python / C++, but there are prerequisites (cuda version and TensorRT version)
https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#serial_model_python
Important note: Since TensorRT applies device-specific optimizations, the engine file needs to run on the same kind of OS it was generated; So since I created the above model on an Ubuntu 18.04, the model can't be deserialized on other OS... I guess this is why it's not common to find such engine files online.

**Comment by lutzroeder** [comment]
Unless this format is documented not sure much can be done here. Netron has a browser-only version so even if a Python or C++ API existed (which is not only geared towards inference) it wouldn't be useful.

**Comment by lutzroeder** [comment]
Duplicate of #725.

**Comment by lutzroeder** [comment]
Duplicate of #725
