### ISSUE TITLE
ONNX: Subgraph support

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [lutzroeder/netron#535]
TF models show a "subgraph" dropdown for viewing subgraphs, but ONNX models do not.  The ability to view ONNX subgraphs would be extremely helpful to me.

**Comment by lutzroeder** [comment]
Can you share a sample file?

**Comment by TomWildenhain-Microsoft** [comment]
Sure.  This graph has a subgraph for the then and else branches.  Thanks!  [https://github.com/TomWildenhain-Microsoft/onnx-example-with-subgraphs/blob/master/k1.onnx](https://github.com/TomWildenhain-Microsoft/onnx-example-with-subgraphs/blob/master/k1.onnx)

**Comment by lutzroeder** [comment]
Duplicate of #168
