### ISSUE TITLE
Darknet: Cannot read property 'layer'

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#539]
Please provide steps or model files to reproduce this issue.

**Comment by Anafeyka** [comment]
If you don't fully comment out the layer
[ExampleBug.txt](https://github.com/lutzroeder/netron/files/4967978/ExampleBug.txt)

**Comment by lutzroeder** [comment]
[netron_issue_539.zip](https://github.com/lutzroeder/netron/files/4968179/netron_issue_539.zip)

**Comment by lutzroeder** [comment]
[netron_issue_539_1.zip](https://github.com/lutzroeder/netron/files/5048435/netron_issue_539_1.zip)

**Comment by lutzroeder** [comment]
[netron_issue_539_2.zip](https://github.com/lutzroeder/netron/files/5048436/netron_issue_539_2.zip)

**Comment by lutzroeder** [comment]
[netron_issue_539_3.zip](https://github.com/lutzroeder/netron/files/5612917/netron_issue_539_3.zip)
