### ISSUE TITLE
Error: Invalid argument identifier

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#540]
Please provide steps or model files to reproduce this issue.

[yolov3-tiny.h5.zip](https://github.com/lutzroeder/netron/files/5823763/yolov3-tiny.h5.zip)
[5_model_fold_0.h5.zip](https://github.com/lutzroeder/netron/files/6174822/5_model_fold_0.h5.zip)
[model_float32.h5.zip](https://github.com/lutzroeder/netron/files/7759357/model_float32.h5.zip)
[thisnotworks.h5.zip](https://github.com/lutzroeder/netron/files/7764266/thisnotworks.h5.zip)
[CODV7.h5](https://www.kaggle.com/darkmatter2222/codmw2019dnnmodels?select=CODV7.h5)

**Comment by lutzroeder** [comment]
[yolov3-tiny.zip](https://github.com/lutzroeder/netron/files/5192003/yolov3-tiny.zip)

**Comment by galaktyk** [comment]
It happen when using tf.math function in tensorflow 2 functional model.

> my_input = Input(shape=(224,224,3))
x = tf.math.abs(my_input)
x = Conv2D(20, 7, padding="same")(x)
model = Model(inputs=my_input, outputs=x)
model.save("thisnotworks.h5")

Now I'm using `tf.compat.v1.disable_eager_execution()` to save model in an old format.

**Comment by lutzroeder** [comment]
@galaktyk  running the code snippet returns`NameError: name 'Input' is not defined`. Can you upload a model file or code snippet that reproduces the error?

**Comment by lutzroeder** [comment]
[netron_issue_540_1.h5.zip](https://github.com/lutzroeder/netron/files/5748679/netron_issue_540_1.h5.zip)
[netron_issue_540_2.h5.zip](https://github.com/lutzroeder/netron/files/5748680/netron_issue_540_2.h5.zip)

**Comment by lutzroeder** [comment]
[yolov3-tiny.h5.zip](https://github.com/lutzroeder/netron/files/5823763/yolov3-tiny.h5.zip)

**Comment by cloudy-sfu** [comment]
[5_model_fold_0.zip](https://github.com/lutzroeder/netron/files/6161617/5_model_fold_0.zip)
Invalid argument identifier
'[["_CONSTANT_VALUE",-1,-0.019062494859099388,{}],["_CONSTANT_VALUE",-1,-0.023046385..
in '5_model_fold_0.h5'.

**Comment by lutzroeder** [comment]
@cloudy-sfu can you share the code that created this model?

**Comment by cloudy-sfu** [comment]
def build_network(params):
    main_input = Input(shape=(params['input_shape']), dtype='float32')
    x = cnn_block(main_input, **params)
    x = Bidirectional(GRU(12, input_shape=x.shape.as_list()[1:],
                    return_sequences=True,return_state=False))(x)
    x = LeakyReLU(alpha=0.3)(x)
    x = Dropout(0.2)(x)
    x = Bidirectional(GRU(12, input_shape=x.shape.as_list()[1:],
                    return_sequences=True,return_state=False))(x)
    x = Attention()([x, initializers.glorot_normal()(x.shape.as_list()[1:])])
    x = BatchNormalization()(x)
    x = LeakyReLU(alpha=0.3)(x)
    x = Dropout(0.2)(x)
    x = Flatten()(x)
    # x = Concatenate()([x, age_input])
    main_output = Dense(params['output_dim'],activation='softmax')(x)
    model = Model(inputs=[main_input], outputs=main_output)
    optimizer = tf.keras.optimizers.Adam(lr=params["learning_rate"])
    model.compile(loss='categorical_crossentropy',
                    optimizer=optimizer,
                    metrics=['accuracy'])
    return model

def cnn_block(layer, **params):
    for i, v in enumerate(params['filters_num']):
        x = BatchNormalization()(layer)
        x = Conv1D(filters=v,
                    kernel_size=params['kernel_size'][i],
                    padding='same',
                    kernel_initializer='he_normal')(x)
        x = LeakyReLU(alpha=params['leakyrelu_rate'])(x)
        x = Conv1D(filters=v,
                    kernel_size=params['kernel_size'][i],
                    padding='same',
                    kernel_initializer='he_normal')(x)
        x = LeakyReLU(alpha=params['leakyrelu_rate'])(x)
        x = Conv1D(filters=v,
                    kernel_size=params['kernel_size'][i],
                    strides = 2,
                    padding='same',
                    kernel_initializer='he_normal')(x)
        x = LeakyReLU(alpha=params['leakyrelu_rate'])(x)
        x = Dropout(params['dropout_rate'])(x)
    return x

**Comment by lutzroeder** [comment]
[5_model_fold_0.h5.zip](https://github.com/lutzroeder/netron/files/6174822/5_model_fold_0.h5.zip)

**Comment by lutzroeder** [comment]
[model_float32.h5.zip](https://github.com/lutzroeder/netron/files/7759357/model_float32.h5.zip)
