### ISSUE TITLE
Darknet: Invalid tensor shape '[0,0,0]'

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#541]
Please provide steps or model files to reproduce this issue.

**Comment by Anafeyka** [comment]
You mean it
[yolov4-tinyBug.txt](https://github.com/lutzroeder/netron/files/4967702/yolov4-tinyBug.txt)

**Comment by lutzroeder** [comment]
[netron_issue_541.zip](https://github.com/lutzroeder/netron/files/4968181/netron_issue_541.zip)
