### ISSUE TITLE
PyTorch: File does not contain root module or state dictionary

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#543]
Please provide steps or model files to reproduce this issue.

**Examples:**
[base_libri.pt.zip](https://github.com/user-attachments/files/16401716/base_libri.pt.zip)
[best.pt.zip](https://github.com/user-attachments/files/16401547/best.pt.zip)
[best.pt.zip](https://github.com/user-attachments/files/16401713/best.pt.zip)
[best_mask.pth.zip](https://github.com/user-attachments/files/16401712/best_mask.pth.zip)
[checkpoint_best.pth.zip](https://github.com/user-attachments/files/16401715/checkpoint_best.pth.zip)
[cpu_jit.pt.zip](https://github.com/user-attachments/files/16401711/cpu_jit.pt.zip)
[DRNL4x_dual_model.pth.zip](https://github.com/lutzroeder/netron/files/5505677/DRNL4x_dual_model.pth.zip)
[mcunet-5fps.pkl.zip](https://github.com/user-attachments/files/16401553/mcunet-5fps.pkl.zip)
[model_10_10_10.pth.zip](https://github.com/user-attachments/files/16401752/model_10_10_10.pth.zip)
[model_final.ckpt.zip](https://github.com/user-attachments/files/16401708/model_final.ckpt.zip)
[model_scripted.pt.zip](https://github.com/user-attachments/files/16401554/model_scripted.pt.zip)
[model_trt.pth.zip](https://github.com/user-attachments/files/16401618/model_trt.pth.zip)
[muzero_models.pb.zip](https://github.com/user-attachments/files/16401557/muzero_models.pb.zip)
[resnet18_cifar10_quantized.pt.zip](https://github.com/user-attachments/files/16401717/resnet18_cifar10_quantized.pt.zip)
[rng_state.pth.zip](https://github.com/user-attachments/files/16401709/rng_state.pth.zip)
[s2a-q4-small-en+pl.model.zip](https://github.com/user-attachments/files/16401714/s2a-q4-small-en%2Bpl.model.zip)
[tensor-and-integer-in-tuple.pt.zip](https://github.com/user-attachments/files/15879202/tensor-and-integer-in-tuple.pt.zip)
[weigths_0000000.pth.zip](https://github.com/user-attachments/files/16401710/weigths_0000000.pth.zip)

**Comment by lutzroeder** [comment]
[DRNL4x_dual_model.pth.zip](https://github.com/lutzroeder/netron/files/5505677/DRNL4x_dual_model.pth.zip)

**Comment by RobinKa** [comment]
Got redirected here by trying to open this file with Netron https://drive.google.com/file/d/1ORAeb4DlS_65WDkQN6LHx5dPyCM5PAVV/view

(Speaker encoder from https://github.com/auspicious3000/autovc)

My local version is 4.8.4 and I also tried it with the web version.

**Comment by rinne1998** [comment]
[corpus.zip](https://github.com/lutzroeder/netron/files/6510101/corpus.zip)

**Comment by betterhalfwzm** [comment]
> [DRNL4x_dual_model.pth.zip](https://github.com/lutzroeder/netron/files/5505677/DRNL4x_dual_model.pth.zip)


[weigths_0000000.zip](https://github.com/lutzroeder/netron/files/6569893/weigths_0000000.zip)
@lutzroeder

**Comment by ujsyehao** [comment]
@lutzroeder 
Hi, the model will re-direct here, I provide model below
[model_trt.zip](https://github.com/lutzroeder/netron/files/7788094/model_trt.zip)

**Comment by mehdismh24** [comment]
The model which led to this issue is attached.
Thanks in advance
[resnet18_cifar10_quantized.zip](https://github.com/lutzroeder/netron/files/7962516/resnet18_cifar10_quantized.zip)

**Comment by KarelPeeters** [comment]
Another case where this happens:
[muzero_models.zip](https://github.com/lutzroeder/netron/files/8207040/muzero_models.zip)

**Comment by HadiSDev** [comment]
[UnlimitedCapacity-4199584.zip](https://github.com/lutzroeder/netron/files/8589427/UnlimitedCapacity-4199584.zip)
From ml-agents. Also not workin

**Comment by MisakiTaro0414** [comment]
The model which led to this issue is attached.
Thanks in advance!

**Comment by MisakiTaro0414** [comment]
The model which led to this issue is attached.
Thanks in advance!
[](https://drive.google.com/file/d/1nW3yR1S_VnqAmHwed4FGzB8ARLyAyaUS/view?usp=sharing)

**Comment by MisakiTaro0414** [comment]
The model which led to this issue is attached.
Thanks in advance!

[](https://drive.google.com/file/d/1nW3yR1S_VnqAmHwed4FGzB8ARLyAyaUS/view?usp=sharing)

**Comment by MisakiTaro0414** [comment]
The model which led to this issue is attached.
Thanks in advance!

[https://drive.google.com/file/d/1nW3yR1S_VnqAmHwed4FGzB8ARLyAyaUS/view?usp=share_link](url)

**Comment by guozeyangshuai** [comment]
Another case where this happens:
[best_mask.zip](https://github.com/lutzroeder/netron/files/11096713/best_mask.zip)
Thanks in advance!

**Comment by zky001** [comment]
Another case where this happens:
[model_finished.zip](https://github.com/lutzroeder/netron/files/11120207/model_finished.zip)

Thanks in advance!

**Comment by leijobs** [comment]
Here is another case where this happens:
https://drive.google.com/file/d/170B_2Dql8jrbhDRxTXp3vnQzozjPLTEn/view?usp=sharing
Thanks in advance!

**Comment by chtholist** [comment]
Here is another case where this happens:
https://drive.google.com/file/d/1JGlrPHVG2guFeaiS7m2_nk_3YUj2qAji/view?usp=share_link
Thanks in advance!

**Comment by wangtiance** [comment]
[torchscript.zip](https://github.com/lutzroeder/netron/files/11571163/torchscript.zip)

**Comment by jmrp98** [comment]
This model led me to this issue with my trained weights, I tried an example weight and it worked.

https://github.com/milesial/Pytorch-UNet/tree/master

**Comment by fa1247** [comment]
https://github.com/mit-han-lab/tiny-training/blob/f60efb8c764e6e2ddfa9d4db40da8cc3489c36c2/algorithm/assets/mcu_models/mcunet-5fps.pkl

**Comment by QoT** [comment]
I got this issue with this PyTorch model and Netron 7.2:

https://drive.google.com/file/d/1vNe9n9hbtfqZSbdglxXJzarig7TJnxfa/view?usp=share_link

**Comment by ZeeRizvee** [comment]
As mentioned by @jmrp98 earlier, training with the code from this repository (https://github.com/milesial/Pytorch-UNet/tree/master) and then loading a trained weight file (.pth file) redirects to this issue.

**Comment by lutzroeder** [comment]
@ZeeRizvee please share a file to reproduce the issue.

**Comment by lazerliu** [comment]
I got this issue with v7.3 and pt file(https://dl.fbaipublicfiles.com/fairseq/data2vec2/base_libri.pt)

**Comment by Sonal-Monteiro** [comment]
Got redirected by Netron while trying to open this model:

https://api.loke.aws.unit.no/dlr-gui-backend-resources-content/v2/contents/links/89660f04-5c11-4dbf-adac-cbe2f11b0aeea25cbf78-7558-475a-b3c7-03f5c10b7934646b0720-ca0a-4d53-aded-daddbfa45c9e

**Comment by BBC-Esq** [comment]
I was directed to this page after trying to load this model from my local computer...providing the link to where it's at on huggingface:

[https://huggingface.co/collabora/whisperspeech/tree/main](https://huggingface.co/collabora/whisperspeech/tree/main)

It was this specific model:

![image](https://github.com/lutzroeder/netron/assets/108230321/05f34f9a-03b1-409f-a833-34d78c44edd0)

**Comment by aleph23** [comment]
Stable Diffusion Textual Inversion embeddings do not open.  Commonly used sample .pt file here [https://huggingface.co/yesyeahvh/bad-hands-5/resolve/main/bad-hands-5.pt](https://huggingface.co/yesyeahvh/bad-hands-5/resolve/main/bad-hands-5.pt) and "?download=true" for direct d/l
