### ISSUE TITLE
PyTorch: Module does not contain modules

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#544]
Please provide steps or model files to reproduce this issue.

**Comment by prameth** [comment]
**Error while loading PyTorch Model**
Was testing a pre-trained model(.pt) on MacOS, wasn't working. But the .pth version loads suprisingly.
No support for models wrapped in nn.DataParallel Models as well as nn.DistributedDataParallel too(in .pth format).

**Comment by lutzroeder** [comment]
@prameth can you share he model file?

**Comment by prameth** [comment]
Sure, here it is [yolov5m.pt](https://drive.google.com/file/d/1vobuEExpWQVpXExsJ2w-Mbf3HJjWkQJr/view?usp=sharing)
