### ISSUE TITLE
PyTorch: Failed to resolve module

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#545]
Please provide steps or model files to reproduce this issue.

**Comment by icedream2linxi** [comment]
Failed to resolve module 'ops._caffe2' in 'model.pt'.

model : https://drive.google.com/file/d/1nJ7p0y5Ng9lr1lH5SSBAoh8qbG2J89DX/view?usp=sharing

**Comment by lutzroeder** [comment]
[netron_issue_545_caffe2.pt.zip](https://github.com/lutzroeder/netron/files/5690362/netron_issue_545_caffe2.pt.zip)
