### ISSUE TITLE
PyTorch: Unsupported uninitialized argument

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#547]
Please provide steps or model files to reproduce this issue.

**Comment by powderluv** [comment]
[model_test.zip](https://github.com/lutzroeder/netron/files/5121555/model_test.zip)
you can rename the above file to model_test.pt and try to load it. I think it fails because there is no model/data.pkl .  the model_test.zip was created from torch c++. 

It fails with Error loading PyTorch model. Cannot read property '1' of undefined in 'model_test.pt'.

**Comment by lutzroeder** [comment]
@powderluv the model `forward` expects parameters like `a_dict`. To extract the graph the model would have to run guessing defaults. In particular this line expects `a_dict` to contain a `hello` key: `value0 = torch.add(value, (a_dict)[key])`. The default `a_dict` would be an empty dictionary not containing `hello`.

**Comment by lutzroeder** [comment]
[netron_issue_547_1.zip](https://github.com/lutzroeder/netron/files/5137393/netron_issue_547_1.zip)

**Comment by divideconcept** [comment]
https://drive.google.com/file/d/1-oLvAC6iVCMJ2HtQlbAspdBERf-atPC8/view?usp=sharing
Includes both the torchscript file (.pt) and the python file that generated it

**Comment by divideconcept** [comment]
Another, simpler example (both torchscript and python generator):
https://drive.google.com/file/d/1ZG0QYEJt9aVs964YiJIoa81fzcufyc-N/view?usp=sharing

**Comment by divideconcept** [comment]
Ok, I got a minimal repro:

```
import torch
import torch.nn as nn

class UNet(nn.Module):

    def __init__(self, n_class):
        super().__init__()
        self.upsample = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)        
        
    def forward(self, x):
        x = self.upsample(x)        
        return x

_model=UNet(2)
_scriptmodule = torch.jit.script(_model)
_scriptmodule.save("UNet.pt")
```

[upsample.zip](https://github.com/lutzroeder/netron/files/5408642/upsample.zip)

**Comment by divideconcept** [comment]
I see that made a commit but now when trying to load the upsample example in Netron 4.5.9 it says "unhandeld exception".

**Comment by lutzroeder** [comment]
@divideconcept `torch.jit.script` does not include input tensor size information so it is not always possible to run the code and extract the graph without user interaction (see #630). Saving a traced model should work around the issue.

```
import torch
import torch.nn as nn

class UpModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.upsample = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)

    def forward(self, x):
        x = self.upsample(x)
        return x

model = UpModel()
traced_model = torch.jit.trace(model, torch.rand([ 1, 3, 224, 224 ]))
torch.jit.save(traced_model, "UpModel.pt")
```

**Comment by divideconcept** [comment]
Indeed, traced models works much better than scripted model.
