### ISSUE TITLE
ONNX: File format is not onnx.ModelProto

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#549]
Please share the model as a Zip archive below to help reproduce and investigate this issue.

**Comment by AmpereKou** [comment]
I have a yolov5*.onnx transfered from yolov5*.pt. When I open it with netron, there will be some  bug as following:
yolov5x.onnx

**Comment by AmpereKou** [comment]
I have yolov5*.onnx transfered from yolov5*.pt
When I open them with netron v4.4.8, there will be some bugs as following:

yolov5x.onnx
![Screen Shot 2020-08-28 at 6 27 01 PM](https://user-images.githubusercontent.com/29347803/91551030-17931680-e95c-11ea-99df-b6c53be5706e.png)

yolov5l.onnx    no problem

yolov5m.onnx
![Screen Shot 2020-08-28 at 6 29 13 PM](https://user-images.githubusercontent.com/29347803/91551208-62ad2980-e95c-11ea-88b2-29b6887722fd.png)

yolov5s.onnx
![Screen Shot 2020-08-28 at 6 31 37 PM](https://user-images.githubusercontent.com/29347803/91551435-b7e93b00-e95c-11ea-942f-93a480546be8.png)

for your reference, thank you

**Comment by lutzroeder** [comment]
@AmpereKou can you share the model files, the original file and steps how they were transferred?

**Comment by AmpereKou** [comment]
Can you tell me how to send file to you?

**Comment by lutzroeder** [comment]
@AmpereKou Dropbox/GDrive/OneDrive or share a GitHub repo?

**Comment by AmpereKou** [comment]
https://drive.google.com/drive/folders/1nkDkXxnDbrjJ5OU_XIT0u1f4ERYCTC00?usp=sharing

**Comment by surprisedong** [comment]
I have the same problem, did you solve it?

**Comment by lutzroeder** [comment]
@surprisedong can you share the model file to reproduce the issue?

**Comment by surprisedong** [comment]
> @surprisedong can you share the model file to reproduce the issue?
Thanks for replying, I seem to be using a corrupted file, now the problem is solved

**Comment by MonTer998** [comment]
hi i have a model converted from pytorch i was using netron normally for few days and today i recive this message whenever i try to open it again. 
![image](https://user-images.githubusercontent.com/93642193/140670578-5f0ff505-8274-48ed-a04e-81f6c5fd2d04.png)

**Comment by sl-sergei** [comment]
I can reproduce this issue on https://netron.app/ with:
```
network = torchvision.models.resnet18()
dummy_input = torch.zeros([1,3,224,224])
torch.onnx.export(network, dummy_input, "resnet18_torchvision.onnx", opset_version=11)
```
Torchvision 0.11.1
PyTorch 1.10.0

[Model file](https://drive.google.com/file/d/1ibWv2oJyOQnZd8jZGZiHptp_T6QjlHQz/view?usp=sharing)

**Comment by lutzroeder** [comment]
@sl-sergei the file opened in both the browser app and the desktop app. What OS and browser version are you using?

**Comment by sl-sergei** [comment]
> @sl-sergei the file opened in both the browser app and the desktop app. What OS and browser version are you using and how did you open the file?

For some reason, the problem does not reproduce right now. If it didn't happen before, I wouldn't find this issue topice. Sorry for the inconvenience=/

**Comment by deyiluobo** [comment]
I got a same error when opening a model in browser app. The OS I am using is ubuntu18. this is the model repo:https://github.com/deyiluobo/reformer2onnx_err

Torchvision 0.11.1
PyTorch 1.10.0

**Comment by lutzroeder** [comment]
@deyiluobo loading `reformer2onnx.onnx` with ONNX shows an error as well?
```
~: python
Python 3.9.12...
>>> import onnx
>>> model = onnx.load("reformer2onnx.onnx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python3.9/site-packages/onnx/__init__.py", line 121, in load_model
    model = load_model_from_string(s, format=format)
  File "python3.9/site-packages/onnx/__init__.py", line 158, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "python3.9/site-packages/onnx/__init__.py", line 99, in _deserialize
    decoded = cast(Optional[int], proto.ParseFromString(s))
google.protobuf.message.DecodeError: Error parsing message with type 'onnx.ModelProto'
```

**Comment by deyiluobo** [comment]
@lutzroeder  When I execute this code(model = onnx.load("reformer2onnx.onnx")) for the first time, it will not report an error, but after I use the browser app to open the model, I will have this error(google.protobuf.message.DecodeError) when I execute the same code again.
I uploaded another model file, you can try.
repo:https://github.com/deyiluobo/reformer2onnx_err

**Comment by deyiluobo** [comment]
@lutzroeder Thank you for your help! I have found my problem now. When using pycharm to download to the local, the size of the model has changed, and the original model 500M has become very small after transmission.I am now able to successfully open the model in the browser app.

**Comment by XYz-dev-max** [comment]
Hello, I have a question using this project, likes this error, my onnx file can loaded by onnx as
![image](https://user-images.githubusercontent.com/61358218/170953794-fb496784-5358-4bc6-beb4-45984d3c5db3.png)

**Comment by lutzroeder** [comment]
@XYz-dev-max can you share the model file?

**Comment by EricWiener** [comment]
I saw this issue after using `cp` to copy an ONNX engine. The copied engine failed to load in Netron with this error, but the original file loaded correctly. When I diffed the hex of the two files, the copied engine (which failed to load) had an additional `0A` at the end (line feed).

**Comment by lutzroeder** [comment]
@EricWiener, can you provide some more context. `cp` should not modify the file contents -- correct?

**Comment by mengxyokok** [comment]
> I saw this issue after using `cp` to copy an ONNX engine. The copied engine failed to load in Netron with this error, but the original file loaded correctly. When I diffed the hex of the two files, the copied engine (which failed to load) had an additional `0A` at the end (line feed).

i have the same problem, thank u .

**Comment by lutzroeder** [comment]
@mengxyokok can you share the command used for copying and the model file that failed to load.

**Comment by daxiongpro** [comment]
> @lutzroeder Thank you for your help! I have found my problem now. When using pycharm to download to the local, the size of the model has changed, and the original model 500M has become very small after transmission.I am now able to successfully open the model in the browser app.

your solution work! thx!

**Comment by jingyanwangms** [comment]
[orca2-2l-emb-spar_execution_model_training.zip](https://github.com/lutzroeder/netron/files/14146736/orca2-2l-emb-spar_execution_model_training.zip)
This is a 2 layers version of https://huggingface.co/microsoft/Orca-2-7b with an experimental optimization.

**Comment by lutzroeder** [comment]
@jingyanwangms can you share the steps how this file was created. It seems to be a corrupt Protocol Buffer.
```
~/ python
>>> import onnx
>>> onnx.load("orca2-2l-emb-spar_execution_model_training.onnx")
    raise _DecodeError('Wrong wire type in tag.')
google.protobuf.message.DecodeError: Wrong wire type in tag.
```

**Comment by jingyanwangms** [comment]
> @jingyanwangms can you share the steps how this file was created. It seems to be a corrupt Protocol Buffer.
> 
> ```
> ~/ python
> >>> import onnx
> >>> onnx.load("orca2-2l-emb-spar_execution_model_training.onnx")
>     raise _DecodeError('Wrong wire type in tag.')
> google.protobuf.message.DecodeError: Wrong wire type in tag.
> ```

It's from https://github.com/microsoft/onnxruntime/blob/23996bbbbe0406a5c8edbf6b7dbd71e5780d3f4b/orttraining/orttraining/python/training/ortmodule/_graph_execution_manager.py#L423

**Comment by lutzroeder** [comment]
@jingyanwangms can you try to recreate the file to rule out that it got corrupted after it was created. If the issue reproduces reliably please raise this with the ONNX or PyTorch ONNX exporter teams.

**Comment by fefe982** [comment]
Has a model file with a lot of parameters that is larger than 3G.

Netron failed to allocate the buffer for hold the whole file.

**Comment by lutzroeder** [comment]
@fefe982 can you share the file or some details where the exact error is happening when [debugging](https://github.com/lutzroeder/netron/blob/main/CONTRIBUTING.md).

**Comment by fefe982** [comment]
Sorry I cannot share the file.

The code fails [here](https://github.com/lutzroeder/netron/blob/fcb142807f1ea1c0f0d179855cd34e35520012e1/source/electron.mjs#L635):

```
    peek(length) {
        length = length !== undefined ? length : this._length - this._position;
        if (length < 0x1000000) {
            const position = this._fill(length);
            this._position -= length;
            return this._buffer.subarray(position, position + length);
        }
        const position = this._position;
        this.skip(length);
        this.seek(position);
        const buffer = new Uint8Array(length); // <<<<<< here
        this._read(buffer, position);
        return buffer;
    }
```

The `new Uint8Array(length)` fails with `RangeError: Array buffer allocation failed`: (`length` is `3440629643`)

```
Exception has occurred: RangeError: Array buffer allocation failed
  at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at host.ElectronHost.FileStream.peek (..../netron/source/electron.mjs:635:24)
    at new protobuf.BinaryReader (..../netron/source/protobuf.js:13:65)
    at protobuf.BinaryReader.open (..../netron/source/protobuf.js:9:23)
    at view.Context.read (..../netron/source/view.js:5177:50)
    at onnx.ProtoReader.read (..../netron/source/onnx.js:1608:57)
    at async onnx.ModelFactory.open (..../netron/source/onnx.js:36:9)
    at async view.ModelFactoryService._openContext (..../netron/source/view.js:5650:35)
    at async view.ModelFactoryService.open (..../netron/source/view.js:5390:27)
```

call stack is generated with v7.4.9

**Comment by BowenBao** [comment]
Hi @fefe982, how were you able to produce a model protobuf that is larger than 2GB?

**Comment by fefe982** [comment]
It contains a lot of large convolutions, say, 1024 channels. The weight tensor would be 1024 x 1024 x kernel_size x kernel_size. If the kernel size is 3 and weight is in float32, the weight tenosr would be 36M . 

Actually the graph contains many such convolutions and the channel number is more than 1024.

**Comment by BowenBao** [comment]
I'm actually curious how it worked... For context protobuf is limited to the maximum size of 2GB, and usually you would hit an error serializing an onnx model above this size limit. Usually the way to workaround it is by saving model weight as external data, e.g., with `save_as_external_data=True` in `onnx.save` call, and then you won't have a `.onnx` model file over 2GB.

**Comment by fefe982** [comment]
With the python module onnx=1.15.0 which I'm using, onnx.save generated this large onnx file without any problem.

I generated the file on Linux.

**Comment by BowenBao** [comment]
> With the python module onnx=1.15.0 which I'm using, onnx.save generated this large onnx file without any problem.
> 
> I generated the file on Linux.

This is unexpected, cc @gramalingam. Wonder if this could be related https://github.com/protocolbuffers/protobuf/issues/11729

**Comment by gramalingam** [comment]
> > With the python module onnx=1.15.0 which I'm using, onnx.save generated this large onnx file without any problem.
> > I generated the file on Linux.
> 
> This is unexpected, cc @gramalingam. Wonder if this could be related [protocolbuffers/protobuf#11729](https://github.com/protocolbuffers/protobuf/issues/11729)

Interesting. Yes, it could be related to this issue.
