### ISSUE TITLE
custom colors for operator nodes 

### ISSUE THREAD

**Issue by gfrogat** [lutzroeder/Netron#55]
Is it currently planned to offer the possibility to set your own (custom or predefined) colorschemes for coloring the different types of operators?

Thank you

**Comment by lutzroeder** [comment]
See #36. Thinking about it but haven't settled on a design. Better to have known patterns and categories, unclear what those are and how they would be driven by data, none of the op schemas have a an automatic way to categorize operators. Would probably also need some designer input to not make the colors look nice.
