### ISSUE TITLE
Error: Unsupported file content

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#550]
Please provide steps or model files to reproduce this issue.

**Comment by vera121** [comment]
Hello @lutzroeder,
I encounterd this issue when trying to open the onnx model zoo sample test pb file.
E.g. you can download it at https://github.com/onnx/models/tree/master/vision/classification/mnist 
![image](https://user-images.githubusercontent.com/19971688/88876894-d9201400-d256-11ea-8aa0-aaf9c814cc55.png)

**Comment by Acebee** [comment]
Hello @lutzroeder,
I encounterd this issue when trying to open the onnx model  pb file at the version  4.43.
the url of the .pb file is http://download788.mediafire.com/kabm01gd8n2g/i72ll9k5i7x6qfh/graph.pb

**Comment by lutzroeder** [comment]
@Acebee This is not an ONNX model. The content looks like TensorFlow `.pbtxt`. How was this file created?

**Comment by Acebee** [comment]
> @Acebee This is not an ONNX model. The content is TensorFlow `.pbtxt`. The file size exceeds the TextDecoder limit.

Sorry,I made a mistake. It is indeed a  TensorFlow project  .The git url is https://github.com/ildoonet/tf-pose-estimation

**Comment by Acebee** [comment]
> @Acebee This is not an ONNX model. The content is TensorFlow `.pbtxt`. The file size exceeds the TextDecoder limit.

Sorry,I made a mistake. It is indeed a TensorFlow project .The git url is https://github.com/ildoonet/tf-pose-estimation

**Comment by 9lash** [comment]
Are there any updates on this error? I too get the same error when I try to load an object detection model in Netron.

**Comment by lutzroeder** [comment]
@9lash this error is a catch if the format of a file cannot be identified. Recent issues might be fixed when running from [source](https://github.com/lutzroeder/netron/blob/main/DEVELOPMENT.md). Please share the model file to reproduce the issue.

**Comment by fdb** [comment]
I'm trying to open a file from [Snap Lens Studio](https://lensstudio.snapchat.com/), specifically this model:

[brows_model.zip](https://github.com/lutzroeder/netron/files/5116993/brows_model.zip)

I get the error "Unsupported file content" but I'm not sure if Netron would be able to support this file format or not.

**Comment by lutzroeder** [comment]
@fdb can you share the specification for this file format?

**Comment by fdb** [comment]
That's the point - I didn't really understand the format so I wanted to see if Netron knew about it :-)

Here are some ML templates in Snap Lens Studio: https://lensstudio.snapchat.com/templates/ml/ml-templates-library/

It seems that they mostly support ONNX files, but the template files seem to contain .dnn files.
Here's two other ones:

[add_remove_beard_models.zip](https://github.com/lutzroeder/netron/files/5117337/add_remove_beard_models.zip)

**Comment by andrewssobral** [comment]
I had the same problem when I use NVIDIA RAPIDS to train a machine learning model on GPU (e.g. using Random Forest). 
[myModel.model.zip](https://github.com/lutzroeder/netron/files/6044204/myModel.model.zip)

**Comment by lutzroeder** [comment]
[myModel.model.zip](https://github.com/lutzroeder/netron/files/6047227/myModel.model.zip)

**Comment by 424778940z** [comment]
Tried open holistic_landmark models from mediapipe giving me this error

**Comment by D3m0n92** [comment]
I tried to open this model but give me this error.

[tracking.zip](https://github.com/lutzroeder/netron/files/7202300/tracking.zip)

**Comment by lutzroeder** [comment]
@D3m0n92 what format is the file expected to be in and how did you acquire it? The file has an `obfs` header and it would be good to know how this was created?

**Comment by D3m0n92** [comment]
I recover it from SnapML (foot tracking example)

**Comment by zchrissirhcz** [comment]
Hi, @lutzroeder, I failed to view an MegEngine model.
The model file is downloaded from `wget https://github.com/Megvii-BaseDetection/storage/releases/download/0.0.1/yolox_s.mge`, 

The error message is:
![图片](https://user-images.githubusercontent.com/3831847/205567618-93403c1f-5523-405e-8ede-008e25c4ee76.png)

**Comment by lutzroeder** [comment]
@HuaHua404 @Ysllllll @dingshaohua960303 @FateScript ^^^

**Comment by FateScript** [comment]
@zchrissirhcz You might need to regenerate a yolox-s mge/tm file with the newest megengine. The file you are using is only used for deployment but not to visualize.

**Comment by zchrissirhcz** [comment]
@FateScript OK, got it now. Thank you.

**Comment by taeheej** [comment]
I tried to visualize DLRM pytorch model after saving it through torch.jit.trace. 
However, 'unsuported file content' error comes out. The error seems related with 'EmbedingBag.num_embeddings' in the DLRM architecture. 
Is there any solution?

**Comment by lutzroeder** [comment]
@taeheej please share a sample file to reproduce the issue and script that was used to create the file.

**Comment by lutzroeder** [comment]
This issue is a catch all for files with unknown content.

Please share a model file to reproduce this issue or information about the file format.

**Comment by davidldennison** [comment]
Hi @lutzroeder ! Thanks for Netron!

Recently received `Unsupported file content '227b37570100000066f5c2d600000000'.`

I was trying to open `nvinfo.pb` from `C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_ea7f458f0e49497d` which is the directory where Nvidia's displays drivers are kept.

![](https://github.com/user-attachments/assets/2b7ffdeb-2dc1-4788-82ac-e7ee642ff4c5)
