### ISSUE TITLE
PaddlePaddle weights support

### ISSUE THREAD

**Issue by XDUXK** [lutzroeder/netron#552]
I am using PaddlePaddle to train and save a model. For the purpose of debugging, all the weights of the training model are expected to be imported and shown in the loaded structure map. I wonder if this is supported in current version and how to do? Thanks!

For example, it would be very nice if the exact values of the following two parameters can be shown in this map,
![image](https://user-images.githubusercontent.com/26429100/88483823-ffb32600-cf9c-11ea-82b1-b9ce3e57e12a.png)

**Comment by lutzroeder** [comment]
Can you share a sample file?

**Comment by XDUXK** [comment]
> @XDUXK, can you share a sample file?

I found an example of TensorFlow (https://lutzroeder.github.io/netron/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fsrom%2Fchessbot%2Fmaster%2Fmodel%2Fchessbot.pb), where the values of some weights can be shown just like the content in the yellow rectangle
![image](https://user-images.githubusercontent.com/26429100/88519926-785dc500-d025-11ea-9c37-2c2844590d63.png)

I wonder if this possible for PaddlePaddle models?

**Comment by lutzroeder** [comment]
@XDUXK, can you share a sample PaddlePaddle model file or the file your are trying to view?

**Comment by XDUXK** [comment]
Attach file is a trained example model of PaddlePaddle, where files named "fc_1.w_0" is one of the files that saves weight.
[recognize_digits_multilayer_perceptron_model.zip](https://github.com/lutzroeder/netron/files/4981016/recognize_digits_multilayer_perceptron_model.zip)

**Comment by lutzroeder** [comment]
[recognize_digits_multilayer_perceptron_model.zip](https://github.com/lutzroeder/netron/files/4983737/recognize_digits_multilayer_perceptron_model.zip)

**Comment by lutzroeder** [comment]
[recognize_digits_multilayer_perceptron_model.zip](https://github.com/lutzroeder/netron/files/4985730/recognize_digits_multilayer_perceptron_model.zip)

**Comment by lutzroeder** [comment]
@XDUXK, this now works if built from source: [DEVELOPMENT](https://github.com/lutzroeder/netron/blob/main/DEVELOPMENT.md).

**Comment by XDUXK** [comment]
Do you mean this new feature can work only for developing version and I have to build it from latest source? By the way, when will this feature be released in next version? Thank you.

**Comment by lutzroeder** [comment]
[recognize_digits_multilayer_perceptron_model.zip](https://github.com/lutzroeder/netron/files/4985730/recognize_digits_multilayer_perceptron_model.zip)
[ch_ppocr_mobile_v2.0_det_infer.zip](https://github.com/lutzroeder/netron/files/8748319/ch_ppocr_mobile_v2.0_det_infer.zip)

**Comment by lutzroeder** [comment]
[recognize_digits_multilayer_perceptron_model.zip](https://github.com/lutzroeder/netron/files/4985730/recognize_digits_multilayer_perceptron_model.zip)
[ch_ppocr_mobile_v2.0_det_infer.zip](https://github.com/lutzroeder/netron/files/8748319/ch_ppocr_mobile_v2.0_det_infer.zip)
[critic.pdparams.zip](https://github.com/lutzroeder/netron/files/8748332/critic.pdparams.zip)
