### ISSUE TITLE
Keras Model Containing Constant "Infinity" Failed to Open

### ISSUE THREAD

**Issue by imxieyi** [lutzroeder/netron#553]
- Netron app and version: 4.4.2 Desktop
- OS and browser version: Windows 10 2004 + Chrome 84.0.4147.89

Minimum reproducible example:

```python
from tensorflow import keras

input = keras.Input(shape=(1))
x = keras.backend.sqrt(input)

model = keras.Model(input, x)
model.compile(optimizer='adam', loss='mse')

model.save('fail.h5')
```

Example model:
[fail.zip](https://github.com/lutzroeder/netron/files/4979264/fail.zip)

Error:

`Unexpected token I in JSON at position 562 in 'fail.h5'.`

**Comment by lutzroeder** [comment]
@imxieyi see #435 and tensorflow/tensorflow#37196.

`Infinity` is not valid in JSON. Please file an issue in the Keras or TensorFlow repository.

**Comment by lutzroeder** [comment]
[netron_issue_553.zip](https://github.com/lutzroeder/netron/files/4979486/netron_issue_553.zip)

**Comment by lutzroeder** [comment]
@imxieyi Please file an issue in [tensorflow](https://github.com/tensorflow/tensorflow/issues) repository.

See #435 and tensorflow/tensorflow#37196. `Infinity` is not valid in JSON.
