### ISSUE TITLE
Cannot display value of attributes

### ISSUE THREAD

**Issue by PeterPanZH** [lutzroeder/netron#557]
You changed some proto specification from `Function` to `Class` recently.
For example `ActivationReLU` in CoreML:
[https://github.com/lutzroeder/netron/blob/main/src/coreml-proto.js#L2526](https://github.com/lutzroeder/netron/blob/main/src/coreml-proto.js#L2526)

This will cause value of attributes cannot be formatted properly.
[https://github.com/lutzroeder/netron/blob/main/src/view-sidebar.js#L346](https://github.com/lutzroeder/netron/blob/main/src/view-sidebar.js#L346)
`value.constructor.name` will always be an empty string in a class instance.

A static property name should be added in specification classes.
```
$root.CoreML.Specification.ActivationReLU = class ActivationReLU {

    static name = 'ActivationReLU';

    constructor() {
    }

    // ...
};
```
This will fix the problem.

By the way,
duplicated `value.constructor.name` in [https://github.com/lutzroeder/netron/blob/main/src/view-sidebar.js#L346](https://github.com/lutzroeder/netron/blob/main/src/view-sidebar.js#L346)
and also duplicated code in [https://github.com/lutzroeder/netron/blob/main/src/view-sidebar.js#L276-L281](https://github.com/lutzroeder/netron/blob/main/src/view-sidebar.js#L276-L281)

**Comment by lutzroeder** [comment]
@PeterPanZH can you share a model file to repro the issue.

**Comment by PeterPanZH** [comment]
Sorry my bad.

I'm trying to build a web app with netron and using webpack to pack it.
During the process I use terser to compress javascript files in src.
It will remove the name of a class expression and make the class anonymous.
I'll figure out another solution.

Sorry for taking your time.
