### ISSUE TITLE
Darknet: conv_lstm inference

### ISSUE THREAD

**Issue by HaolyShiit** [lutzroeder/netron#562]
This is conv_lstm layer: AlexeyAB/darknet#3114

The layers after conv_lstm layer can not be drawn normally. Please try below: [yolo_v3_tiny_lstm.cfg.txt](https://github.com/AlexeyAB/darknet/files/3199770/yolo_v3_tiny_lstm.cfg.txt)

**Comment by lutzroeder** [comment]
[yolo_v3_tiny_lstm.zip](https://github.com/lutzroeder/netron/files/4999065/yolo_v3_tiny_lstm.zip)
