### ISSUE TITLE
Darknet: Invalid tensor shape '[0,0,96]' in 'maxpool'

### ISSUE THREAD

**Issue by skydestroyer** [lutzroeder/netron#569]
I  encountered this problem when I use the latest version 4.4.3.
However, when I converted this network to prototxt, it could be drawn correctly (but  without tensor shape calculation displayed).

[test.txt](https://github.com/lutzroeder/netron/files/5020481/test.txt)

**Comment by lutzroeder** [comment]
[netron_issue_569.zip](https://github.com/lutzroeder/netron/files/5025566/netron_issue_569.zip)

**Comment by lutzroeder** [comment]
#541
