### ISSUE TITLE
.pd file (container graph & weight) netron parese network structure very complexity

### ISSUE THREAD

**Issue by blackhu** [lutzroeder/netron#570]
- Netron app and version: 
Mac 10.14.6
Netron app: v4.4.3
- OS and browser version: 

Steps to Reproduce:

1.  I have a pd file(container graph & weight) ,size 300MB, Parser result is very complexity.
2.
![image](https://user-images.githubusercontent.com/5728454/89623532-5850c000-d8c7-11ea-987d-26231ea55903.png)

Please attach or link model files to reproduce the issue if necessary.

**Comment by lutzroeder** [comment]
Duplicate of #68
