### ISSUE TITLE
OpenVINO: IRv10 graphs with TensorIterator and LSTMCell do not display correctly

### ISSUE THREAD

**Issue by mdeisher** [lutzroeder/netron#572]
- Netron app and version: 4.4.4
- OS and browser version:  Windows 10 64bit

Steps to Reproduce:

1. Open OpenVINO IR XML file in netron
2.

Please attach or link model files to reproduce the issue if necessary.

I cannot share the proprietary model that shows dozens of disconnected nodes, but the one linked below does show disconnected subgraphs after conversion to OpenVINO IR.  Note that the IR generated using the --generate_deprecated_IR_V7 option displays correctly.

https://github.com/ARM-software/ML-KWS-for-MCU/blob/master/Pretrained_models/Basic_LSTM/Basic_LSTM_S.pb

Convert using:

python 'C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\model_optimizer\mo.py' --input_model .\Basic_LSTM_S.pb --input=Reshape:0 --input_shape=[1,490] --output=Output-Layer/add

This results in the following disconnected graph display:

![image](https://user-images.githubusercontent.com/871270/90190363-b708b480-dd73-11ea-909f-b08d86854b52.png)

**Comment by lutzroeder** [comment]
@mdeisher can you share the OpenVINO `.xml` file and report this issue in [openvinotoolkit/openvino](https://github.com/openvinotoolkit/openvino).

@demid5111

**Comment by demid5111** [comment]
> @mdeisher can you share the OpenVINO `.xml` file and report this issue in [openvinotoolkit/openvino](https://github.com/openvinotoolkit/openvino).
> 
> @demid5111

If there is no xml attached till Monday, I will try to convert the original model and attach it here. Also, I will take a look at the problem

**Comment by mdeisher** [comment]
[Temp.zip](https://github.com/lutzroeder/netron/files/5079919/Temp.zip)

**Comment by lutzroeder** [comment]
@mdeisher this looks different from your screenshot?

<img width="1136" alt="screenshot" src="https://user-images.githubusercontent.com/438516/90487684-a8155f80-e0ef-11ea-8101-87db8ec75cb6.png">

**Comment by mdeisher** [comment]
@lutzroeder, sorry I grabbed the wrong file.  That is the IRv7 version which displays just fine.  Here is the IRv10 one.
[Basic_LSTM.zip](https://github.com/lutzroeder/netron/files/5090719/Basic_LSTM.zip)

**Comment by lutzroeder** [comment]
@demid5111 can you have a look?

**Comment by mdeisher** [comment]
Closed without resolution or comment???

**Comment by lutzroeder** [comment]
> @mdeisher [...] and report this issue in openvinotoolkit/openvino.

**Comment by demid5111** [comment]
> @demid5111 can you have a look?

yes, I will take a look at why it happens. I was able to reproduce the issue:

![image](https://user-images.githubusercontent.com/4301327/90862506-2eeb6600-e396-11ea-8de0-4454c04c7329.png)

There is a clearly disconnected graph component and it is not valid processing of such models.
