### ISSUE TITLE
xxd hexdump support

### ISSUE THREAD

**Issue by hpssjellis** [lutzroeder/netron#574]
Feature Request: TensorflowLite .h files

Background:   TensorlfowLite .tflite files for mobile platforms can be converted into .h (C header) files for micro-controllers using the command

```
xxd -i model.tflite model.h
```

I assume there is a way to convert these files back from .h to .tflite , but I have not yet found that command. 
It would be useful to be able to view the Netron output directly from a TensorflowLite .h header file as these can be available from the web for micro-controllers without the corresponding .tflite file.

It would also be good to be able to compare the 2 types of TensorflowLite files with other models from TensorflowJS, Keras and Tensorflow.

**Comment by lutzroeder** [comment]
The general case would be any arbitrary source code file containing any potential number of model files in binary encoding. Not a priority given the error conditions and special cases this may produce. It should be possible to write the byte[] back to a file if needed.
