### ISSUE TITLE
Double-click no longer opens the onnx file

### ISSUE THREAD

**Issue by dashesy** [lutzroeder/netron#575]
- Netron app and version: 4.4.6 
- OS and browser version: Windows, Edge 

this used to work in all the previous versions, now it opens Netron but does not load the model

Steps to Reproduce:

1. Double click on onnx file from explorer
2.

Please attach or link model files to reproduce the issue if necessary.

**Comment by gttiankai** [comment]
same question

**Comment by amirebrahimi** [comment]
Thank you, @lutzroeder, for this awesome tool!

**Comment by dashesy** [comment]
and thanks for such quick fix!
