### ISSUE TITLE
Very high CPU usage when idle

### ISSUE THREAD

**Issue by dashesy** [lutzroeder/netron#579]
- Netron app and version: 4.4.7
- OS and browser version: Windows 10, Edge

Steps to Reproduce:

1. Seems like it starts after searching for a node and selecting it
2. Then doing nothing, idle

Please attach or link model files to reproduce the issue if necessary.
Seems any model.
This morning I realized the open onnx file from last night was heating my laptop.

![image](https://user-images.githubusercontent.com/873905/90915977-1e86bb80-e395-11ea-882f-2ffe544e1863.png)

**Comment by dashesy** [comment]
I can repro this on Chrome too
While dashed line animation is running:
![image](https://user-images.githubusercontent.com/873905/91078599-b84da300-e5f7-11ea-88c9-a3d5162038e8.png)

Then I hit Esc it goes down but remains high
![image](https://user-images.githubusercontent.com/873905/91078645-cac7dc80-e5f7-11ea-944a-133821a4aa02.png)


Will try to find the reason. Will also send you a sample ONNX file if you want to take a look.

**Comment by lutzroeder** [comment]
@dashesy did you try removing the animation(s) for `.select` in `view-grapher.css`?

**Comment by dashesy** [comment]
After removing animation from `.select .node.border` the CPU usage went down:

![image](https://user-images.githubusercontent.com/873905/91337846-ddbde680-e788-11ea-8b44-9b8d0df08237.png)

I first did not remove animation from `.select.edge-path` and the CPU usage after selecting an edge was still high:

![image](https://user-images.githubusercontent.com/873905/91337970-0d6cee80-e789-11ea-83be-4e8287b17afe.png)

After removing animation from there, it went down too

![image](https://user-images.githubusercontent.com/873905/91338237-7c4a4780-e789-11ea-9152-5ef33f16697c.png)


1. This is more acute on the laptop (Surface)
2. It is more acute on large models, even though searching a node and selecting it zooms in

So it is animation
