### ISSUE TITLE
on summary page graphs/inputs section should show appropriate description for input type if available

### ISSUE THREAD

**Issue by seanmcd-msft** [lutzroeder/Netron#58]
for onnx it could pick up the inputs "description:" from onnx-operator.json for the first operator in the graph.  e.g. for resnet50 it shows float[1,3,224,224] : gpu0_data0  
it would be helpful if it somehow included 
"Input data tensor from previous layer; has size (N x C x H x W), where N is the batch size, C is the number of channels, and H and W are the height and width. Note that this is for the 2D image. Otherwise the size is (N x D1 x D2 ... x Dn)" to explain the values inside the brackets.

something analogous could be probably be done for outputs although that might be more confusing since the descriptions are described in terms of inputs to the final layer which is less clear from the summary page.

**Comment by lutzroeder** [comment]
Would this always lead to meaningful results? In case of `Conv` the input documentation might make sense but not sure this would always work? Inputs could feed into multiple nodes. `TensorProto` on `ValueInfoProto`can have a `doc_string` and maybe that's what should be shown on the summary page if available?
