### ISSUE TITLE
SnapML support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#581]
https://lensstudio.snapchat.com/guides/machine-learning/ml-overview

#550

**Comment by lutzroeder** [comment]
@fdb can you provide context if this format is documented.

**Comment by fdb** [comment]
I've asked on the Lens forums - I'll let you know if there's an update.

**Comment by lutzroeder** [comment]
[brows_model.zip](https://github.com/lutzroeder/netron/files/5118426/brows_model.zip)

**Comment by fdb** [comment]
This is the answer I got on [the forum](https://support.lensstudio.snapchat.com/hc/en-us/community/posts/360072647211-SnapML-is-the-dnn-format-documented-?page=1#community_comment_360012681352):

> Lens Studio converts all .onnx and .pb model to our .dnn internal format, which will be used by our own engine for mobile inference. Currently we do not support converting dnn models back to ONNX format.

But it seems like you've managed quite well without the format spec :-) 👍
