### ISSUE TITLE
Wrong parameter parsing for mix-precision model in PyTorch 1.6.0

### ISSUE THREAD

**Issue by Cliff-Lin** [lutzroeder/netron#585]
I use PyTorch 1.6.0 to train a model under mix precision. It works fine under PyTorch environment, but when I use Netron to view the model, many parameters are not in the reasonable range, and some of them are NaN, which is quite different from the parameters shown in PyTorch.

**Comment by lutzroeder** [comment]
@Cliff-Lin can you share the model file and provide which parameters stored in the model file are shown differently.

**Comment by Cliff-Lin** [comment]
The link of the model file:
https://drive.google.com/file/d/1VcdvbZuksoSwx1A0ZArabrKC18Rui8Kl/view?usp=sharing

**Comment by Cliff-Lin** [comment]
Sorry for the late reply. All parameters are different in Netron and PyTorch environment.

**Comment by Cliff-Lin** [comment]
I found that Netron cannot parse the parameters correctly in PyTorch 1.6 no matter it is trained under mix-precision or not.

**Comment by Cliff-Lin** [comment]
How do I update the application under Windows? Thank you.

**Comment by lutzroeder** [comment]
[DEVELOPMENT.md](https://github.com/lutzroeder/netron/blob/main/DEVELOPMENT.md) until the next update is released.

**Comment by Cliff-Lin** [comment]
Got it. Thank you.
