### ISSUE TITLE
Error: Unsupported Protocol Buffers content

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#593]
Please provide steps or model files to reproduce this issue.

**Comment by lutzroeder** [comment]
@sunyuan789 ONNX files need to use `.onnx` as a file extension instead of `.pth`.

**Comment by nasircsms** [comment]
Unsupported Protocol Buffers content '1:2,2:2,3:2' for extension '.model' in 'spm_char.model'.

[covost2_en_asr_vocab_char.zip](https://github.com/lutzroeder/netron/files/6607278/covost2_en_asr_vocab_char.zip)

**Comment by mikhail-barg** [comment]
Unsupported Protocol Buffers content '' for extension '.pb' in '192x15-2021_0823_1130_56_656.pb'.

https://training.lczero.org/get_network?sha=7b1ec0ff403d3eb36e3cd04c8e4481d10be612ed4b45f65a0b46c3d0bf518f87

**Comment by wangxudong-cq** [comment]
![image](https://user-images.githubusercontent.com/76459010/147627890-597525ba-12b9-4e43-85e2-5739813d0eb8.png)

**Comment by lutzroeder** [comment]
@wangxudong-cq can you share the model file? How was it created?

**Comment by wangxudong-cq** [comment]
sure
[output_1.zip](https://github.com/lutzroeder/netron/files/7787521/output_1.zip)
!

**Comment by wangxudong-cq** [comment]
```
ONNX_NAMESPACE::TensorProto output_proto;
    output_proto.clear_data_type();
    output_proto.set_data_type(ONNX_NAMESPACE::TensorProto_DataType_FLOAT);
    
    output_proto.clear_dims();
    for (int i=0; i<dims.size(); i++)
        output_proto.add_dims(dims[i]);
    
    output_proto.clear_float_data();
    for (int i=0; i<data.size(); i++)
        output_proto.add_float_data(data[i]);

    auto fd = open(fpath.c_str(), O_CREAT | O_TRUNC | O_RDWR, 0644);
    if(fd<=0)
    {
        std::cout<<"[outputData2PB]: fopen file error"<<std::endl;
        return false;
    }
    if(!output_proto.SerializeToFileDescriptor(fd))
    {
        std::cout<<"[outputData2PB]: SerializeToFileDescriptor Failed!"<<std::endl;
        return false;
    }
```

Is this problem related to raw_data or float_data?

**Comment by wangxudong-cq** [comment]
@lutzroeder What does the content '1:0,2:0,4:2' mean?

**Comment by wangxudong-cq** [comment]
@lutzroeder  Is there a version that can be verified?

**Comment by huiyan2021** [comment]
![image](https://user-images.githubusercontent.com/88080182/205851412-4ba1b222-6e65-4b66-895c-ebff81a64e1c.png)

**Comment by yuslepukhin** [comment]
I have a model that loaded yesterday, and it does not load today.

**Comment by ikamensh** [comment]
so often this is solved by just renaming your model to .onnx extension. I wish error message suggested this much. I had model with no extension at all, `my_onnx`

**Comment by lutzroeder** [comment]
@ikamensh thank you for the feedback. What would you recommend a better error message looks like? Keep in mind there are many different Protocol Buffers formats so "add .onnx file extension" would be misleading to CoreML or TensorFlow users.
