### ISSUE TITLE
Error: Unsupported JSON content

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#595]
Please provide steps or model files to reproduce this issue.

**Comment by py2ai** [comment]
filename = 'OO.json'
out_file = open(filename,'w+')


from networkx.readwrite import json_graph
import matplotlib.pyplot as plt
import networkx as nx
import json
from networkx.drawing.nx_agraph import graphviz_layout


subtask_list = ['A','B','C']
conn_list = [('A','B'),('B','C')]

G = nx.DiGraph()

for name in subtask_list:
    G.add_node(name, label=name)

for names in conn_list:
    G.add_edge(names[0], names[1])
    
nx.nx_agraph.write_dot(G, 'test_subtask.dot')

filetype = 'png'
fig = plt.figure(figsize=(10, 10))
plt.title(f'{filename}.{filetype}')
pos = graphviz_layout(G, prog='dot')
nx.draw(G,
        pos=pos,
        with_labels=True,
        node_shape="s",
        bbox=dict(facecolor='skyblue', edgecolor='black', boxstyle='round,pad=0.3'))
plt.savefig(f'{filename}.{filetype}')
print('Graph generated:', f'{filename}.{filetype}')
d = json_graph.adjacency_data(G)
print(d)
json.dump(d,out_file)

**Comment by py2ai** [comment]
This complete code will generate the OO.json file

**Comment by FrostBird347** [comment]
#856
