### ISSUE TITLE
Netron continuing to execute after closing; Shows up in task manager

### ISSUE THREAD

**Issue by amirebrahimi** [lutzroeder/netron#597]
Doesn't happen consistently, but it does happen. It may be one of the child processes that get spawned?

- Netron app and version: Desktop app 4.5.1

Steps to Reproduce:

1. Open a model in netron by double clicking
2. Close the model
3. Notice netron is still running in task manager

Please attach or link model files to reproduce the issue if necessary.
![image](https://user-images.githubusercontent.com/904110/93276376-2fe49d00-f774-11ea-893f-184588d06679.png)

**Comment by lutzroeder** [comment]
Duplicate of #322
