### ISSUE TITLE
MindSpore support 

### ISSUE THREAD

**Issue by YvetteLaw** [lutzroeder/netron#600]
Hello, Lutz Roeder. 

I'm an employee of Huawei inc. I have extened Netron to support MindSpore, which is an AI framework developed by Huawei (https://www.mindspore.cn/). Could you please let me merge my work into Netron?

**Comment by lutzroeder** [comment]
@YvetteLaw can you create a PR?

**Comment by lutzroeder** [comment]
[blazeface_quant.ms.zip](https://github.com/lutzroeder/netron/files/6097966/blazeface_quant.ms.zip)
[control_flow_ut_while_0122.ms.zip](https://github.com/lutzroeder/netron/files/6097967/control_flow_ut_while_0122.ms.zip)

**Comment by lutzroeder** [comment]
[mnist.ms.zip](https://github.com/lutzroeder/netron/files/6128484/mnist.ms.zip)
[squeezenet1.1.ms.zip](https://github.com/lutzroeder/netron/files/6128485/squeezenet1.1.ms.zip)
