### ISSUE TITLE
Error loading PyTorch model. Unknown expression 'dict' in the model.

### ISSUE THREAD

**Issue by SrivastavaKshitij** [lutzroeder/netron#603]
Hi There

I encounter the following error when trying to visualize my model in netron. I dont have a way to reproduce the error for now but could you please confirm if the error is related to python dictionaries and if yes, are python dicts supported in netron ?

PS: I will try to reproduce the error in the near future. 

Thanks

**Comment by lutzroeder** [comment]
@SrivastavaKshitij Can you share a sample file to reproduce the issue?
