### ISSUE TITLE
Unknown 'torch.eq' expression type

### ISSUE THREAD

**Issue by waicool20** [lutzroeder/netron#609]
- Netron app and version: Netron-4.5.3.AppImage
- OS and browser version: Arch Linux 5.8.10

Steps to Reproduce:

1. Change extension to .pt and open the file below in Netron, this model was traced and exported to torchscript from [here](https://github.com/magicleap/SuperGluePretrainedNetwork) 
[superpoint.zip](https://github.com/lutzroeder/netron/files/5306616/superpoint.zip)

2. Netron presents this error
![image](https://user-images.githubusercontent.com/5538666/94707293-dab0aa00-0375-11eb-9161-3b9c89fec5bc.png)

Please attach or link model files to reproduce the issue if necessary.

**Comment by lutzroeder** [comment]
[superpoint.pt.zip](https://github.com/lutzroeder/netron/files/5309273/superpoint.pt.zip)

**Comment by lutzroeder** [comment]
[netron_issue_609.pt.zip](https://github.com/lutzroeder/netron/files/5309279/netron_issue_609.pt.zip)
