### ISSUE TITLE
Navigating large graphs

### ISSUE THREAD

**Issue by NikolasMarkou** [lutzroeder/netron#610]
While navigating large graphs, it becomes tedious to follow the edges.
It would be preferable to have a button on the side panel (inputs and outputs) so that we could easily go to the specified node

**Comment by Fannettembrown** [comment]
Copy paste a separate file away from your search bar

**Comment by lutzroeder** [comment]
Duplicate of #1122

**Comment by NikolasMarkou** [comment]
Thank you sir
