### ISSUE TITLE
Show layer number

### ISSUE THREAD

**Issue by Moldoteck** [lutzroeder/netron#611]
Please add an option to show the number of the layer in the loaded network

**Comment by lutzroeder** [comment]
@Moldoteck can you provide details? Which format? Show the numbers where?

**Comment by Moldoteck** [comment]
@lutzroeder , Well, for example when you load a Keras model in python, you have access to a list of it's layers. Would be cool if Netron would display indexes of the layers according to that list

**Comment by lutzroeder** [comment]
@Moldoteck can you provide some details how this is expected to work, for example for nested networks? Where are the indices shown? The indices in Keras are more of an implementation detail and less stable than using names. Why is it not possible to use `model.get_layer('layer-name`)` instead?
