### ISSUE TITLE
4.5.5 windows version  question

### ISSUE THREAD

**Issue by chumingqian** [lutzroeder/netron#613]
Hi, @lutzroeder :
      This  window  4.5.5 version , models cant  represent  any  arrow connection  on  .pth     and  cant  open .weigth  file,  did  i  don sth wrong,   i  just  down the  4.5.5exe  file, and the  run it.
  ( and  what 's function  of  exe.blockmap, i couldn't  run it)

**Comment by lutzroeder** [comment]
Duplicate of #236

**Comment by lutzroeder** [comment]
Duplicate of #472

**Comment by lutzroeder** [comment]
Duplicate of #133

**Comment by lutzroeder** [comment]
@chumingqian please share the actual files to reproduce the behavior.
