### ISSUE TITLE
Sample models download for MXNet model inception_v3  and Darknet Model Yolo is broken

### ISSUE THREAD

**Issue by Tekrific** [lutzroeder/netron#619]
OS and browser version: macOS 10.15.7 + Chrome Version 86.0.4240.80

Steps to Reproduce:

1. Click on MXNet model inception_v3 doesn't initiate download but redirects to a raw file page:
https://raw.githubusercontent.com/soeaver/mxnet-model/master/cls/inception/inception_v3-symbol.json

2. Click on Darknet Model Yolo yields the same result as above:
https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolo.cfg

NB: All the other sample models work fine for both download and in-browser sampling.

**Comment by lutzroeder** [comment]
Default browser behavior for text files.

**Comment by Tekrific** [comment]
For clarification, since this is expected behaviour shouldn't this be a persistent problem with all the sample files or am I missing something here? Are these sample files generated differently depending on the origin of the models? Sorry if I'm obtuse and missing something obvious (most likely scenario).

**Comment by lutzroeder** [comment]
They are in different formats. Some are binary files. Others are standard text formats browsers recognize and have a default behavior.

**Comment by Tekrific** [comment]
I see, thanks for clearing that up. If I can make a UX suggestion it would be to separate those two models and have them in a separate section that makes it clear they can't be downloaded as the others but still used in the web app demo.
