### ISSUE TITLE
Reporting Usage Information / Privacy

### ISSUE THREAD

**Issue by jvhoffbauer** [lutzroeder/netron#623]
When starting Netron, it says: This app uses cookies to report errors and anonymous usage information

What exactly is reported and are there any differences between the version on https://netron.app/ and local versions? 

Many thanks
Jan

**Comment by lutzroeder** [comment]
> What exactly is reported and are there any differences between the version on https://netron.app/ and local versions?

* Error messages shown to the user
* Model format loaded (for example: `TorchScript v1.6`)
* File extension to understand how often users try open file types which are not supported
* Model node count to understand how often users open really large models that won't render successfully
* Screen progression (for example, Welcome > Load > Graph), currently not very useful but the goal is to add load times in the future to better understand app performance

There shouldn't be major differences between web and desktop beyond using GA vs. UA. The code is included in the repro in `source/index.js` and `source/electron.js`.
