### ISSUE TITLE
Enhance export model feature

### ISSUE THREAD

**Issue by giorg0s** [lutzroeder/netron#624]
Hi! I'm wondering about improving the way you export a model graph into an image. At least in my case using the snap version of Netron on Ubuntu 20.04 I've seen that the only way to export my graph to an image is clicking 'Export...' button and writing manually the name of the exported file **including the extension** in the system context menu. 
There is no way to ignore this neither to use another format apart from .png or .svg. I think there is a lot of potential within this tool and should be be more intuitive.

Thanks! ;)

**Comment by lutzroeder** [comment]
@giorg0s thank you for the feedback! Could you clarify what specific improvements you'd like to see during export?
