### ISSUE TITLE
can not export full image

### ISSUE THREAD

**Issue by wwdok** [lutzroeder/netron#625]
- Netron app and version: Windows Desktop 4.6.2
truncated
Steps to Reproduce:
I want to export image of my model, but the output image is like this:
model : https://drive.google.com/file/d/1IL4OiogcbIruB6tq3RGRP_mHHf_bWSrr/view?usp=sharing
exported image : https://pic.downk.cc/item/5fb3e29cb18d62711321afa9.png
The lower part of image is transpant:
![image](https://user-images.githubusercontent.com/43233772/99404562-bcebd400-2926-11eb-954f-cfde9b56884c.png)

**Comment by lutzroeder** [comment]
This is a known limitation with the Chrome engine. Please export to SVG and use an app for the conversion or try the browser version of Netron in a different browser like Safari or Firefox.

**Comment by mervess** [comment]
Hello, I'm using _netron.app_ on Firefox-88.0 on a Linux machine. The output of `export` is more or less the same as above. Both _png_ and _svg_ exports come with huge gaps. I'm fixing them via image editing, but still have wanted to let you know the situation. A fix would have been great of course.

The one with transparency below is _png_, and the other one is the view of _svg_ file.

![png](https://user-images.githubusercontent.com/20180883/143765784-c2ac0e64-0ce7-45c5-951f-bac48b0ca76c.png)
![svg](https://user-images.githubusercontent.com/20180883/143765785-05af1125-c53a-4774-8915-866efa64f2ac.png)
