### ISSUE TITLE
PyTorch: l.slice is not a function in

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#630]
- Netron app and version: 4.6.3 Desktop

Steps to Reproduce:

```
import torch
model = torch.hub.load('pytorch/vision:v0.7.0', 'deeplabv3_resnet50', pretrained=True)
model.eval()
torch.jit.save(torch.jit.script(model), 'deeplabv3_scripted.pt')
```

[deeplabv3_scripted.pt.zip](https://github.com/lutzroeder/netron/files/5604999/deeplabv3_scripted.pt.zip)

**Comment by lutzroeder** [comment]
pytorch/pytorch#48525

**Comment by clay001** [comment]
how do you solve this unsupported issue? why closed?
