### ISSUE TITLE
Multiple Application Instances

### ISSUE THREAD

**Issue by 8** [lutzroeder/netron#631]
Hi,

thanks for the great application!

Currently I am using the netron electron app on win10 and I would like to open multiple instances of netron so that I can compare the architecture of two models more easily next to each other.

Another user had the same issue on mac:
https://github.com/lutzroeder/netron/issues/299 
and found a workaround by using the web application version.

Instead of switching to the web app, I would like to keep using the electron app (eg. not potentially uploading the model, easier and faster startup, etc).

Is there a reason why it's restricted to a single instance? Is there some kind of trick to get it spawn a second instance?

Thanks!

Take care,
Martin

**Comment by lutzroeder** [comment]
Double clicking on multiple files or File > Open will open in separate windows on Windows 10.
