### ISSUE TITLE
DLC support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#640]
SNPE Deep Learning Container (DLC)

**v2** (undocumented)
[mobilenet-SSD.dlc.zip](https://github.com/lutzroeder/netron/files/10528507/mobilenet-SSD.dlc.zip)

**v4** (undocumented)
[yolov8n_op11_v2.dlc.zip](https://github.com/lutzroeder/netron/files/10527012/yolov8n_op11_v2.dlc.zip)
[sample.dlc.zip](https://github.com/lutzroeder/netron/files/12207883/sample.dlc.zip)
[mobilenet_edgetpu_224_1.0_htp.dlc.zip](https://github.com/lutzroeder/netron/files/12207884/mobilenet_edgetpu_224_1.0_htp.dlc.zip)

[inception_v3_quantized.dlc.zip](https://github.com/lutzroeder/netron/files/5615377/inception_v3_quantized.dlc.zip)
[dmonitoring_model_q.dlc.zip](https://github.com/lutzroeder/netron/files/8767255/dmonitoring_model_q.dlc.zip)
[dmonitoring_model_q.zip](https://github.com/lutzroeder/netron/files/8767267/dmonitoring_model_q.zip)
[model_front_mibokeh_video.dlc.zip](https://github.com/lutzroeder/netron/files/8767521/model_front_mibokeh_video.dlc.zip)
[mobile_mosaic_hta.zip](https://github.com/lutzroeder/netron/files/8767531/mobile_mosaic_hta.zip)
[yolov8n_op11_v1.dlc.zip](https://github.com/lutzroeder/netron/files/10527011/yolov8n_op11_v1.dlc.zip)

**Comment by lutzroeder** [comment]
[inception_v3_quantized.dlc.zip](https://github.com/lutzroeder/netron/files/5615377/inception_v3_quantized.dlc.zip)

**Comment by MeghnaNatraj** [comment]
@lutzroeder i've attached a sample DLC model.

When loading the [mobilenet-SSD.dlc.zip](https://github.com/lutzroeder/netron/files/10528507/mobilenet-SSD.dlc.zip) in [#316](https://github.com/lutzroeder/netron/issues/640#issue-753357013) I get an error: "Error loading DLC model. File contains undocumented DLC v2 data." While loading the attached "sample.dlc" model I get an error: "Error loading DLC model. File contains undocumented DLC v4 data."

**Comment by lutzroeder** [comment]
@MeghnaNatraj please also share the format documentation and a pull request for adding support.

**Comment by MeghnaNatraj** [comment]
I was unable to find the format documentation, but if you unzip the model itself (unzip sample.dlc.zip --> sample.dlc and further unzip it, sample.dlc --> sample folder). This folder contains:
- dlc.metadata
- model (not sure what this format is)

The DLC file (sample.dlc) can be visualized using [DLC model viewer](https://developer.qualcomm.com/sites/default/files/docs/snpe/tools.html#tools_snpe-dlc-viewer)

![dlc_viewer](https://github.com/lutzroeder/netron/assets/8790823/45be842f-a6f7-4eea-a2ce-801f7acedf79)
