### ISSUE TITLE
Error: Cannot read property

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#647]
Please provide steps or model files to reproduce this issue.

**Comment by raymon-tian** [comment]
Cannot read property 'name' of null in 's2.onnx'.

I exported such a onnx graph:

```python
attrs = "abcd"
attrs = g.op("Constant", value_s=attrs)
return g.op("ai.onnx.contrib::MyAdd", x, y, attrs)
```
[s2.zip](https://github.com/lutzroeder/netron/files/6189334/s2.zip)

**Comment by lutzroeder** [comment]
[s2.onnx.zip](https://github.com/lutzroeder/netron/files/6191354/s2.onnx.zip)

**Comment by assael07** [comment]
Hi @lutzroeder .. I saw this issue again when I open Centernet and EfficientDet from Tensorflow model zoo
https://tfhub.dev/tensorflow/collections/object_detection/1

**Comment by Haider-Asif** [comment]
Hi, @lutzroeder I saw this issue again while opening my self-created model's pb file: "Cannot read property '0' of undefined in model.pb"

**Comment by lutzroeder** [comment]
@Haider-Asif can you share a the model file or try if this reports at TIP.

**Comment by mdeisher** [comment]
I'm seeing this error on a confidential model that cannot be shared.  It would be nice if the error message included the name of the node that cannot be processed by Netron.

**Comment by lutzroeder** [comment]
@mdeisher can you [run](https://github.com/lutzroeder/netron/blob/main/DEVELOPMENT.md) this in the debugger and submit a fix. This is likely in OpenVINO code so maybe someone at Intel can have a look?

**Comment by mdeisher** [comment]
Sure.
On Windows, what is the “./netron root folder”?
Is it C:\Users\username\AppData\Roaming\Netron ?

--Mike

**Comment by lutzroeder** [comment]
> On Windows, what is the “./netron root folder”?
The folder the repo was clone into.

**Comment by mdeisher** [comment]
Please forgive my ignorance since I'm not a Java developer.  I can run Netron via the Visual Studio Code debugger.  But it is not finding the source code.  I get a message like "<path>\netron/node_modules/.bin/electron.cmd .\source\app.js
Could not read source map for file:///<path>/netron/node_modules/electron/dist/resources/default_app.asar/main.js: ENOENT, main.js.map not found in <path>\netron\node_modules\electron\dist\resources\default_app.asar".  If you will help me sort this out, I will provide detailed information about the issue.  Thanks.

**Comment by lutzroeder** [comment]
@mdeisher did you set the Visual Studio Code debugger to `Debug Renderer Process` in the `Debug` tab? The app has a main process and a separate "renderer" process for each view. Those messages should only show in the main process and can be ignored.

> To attach the debugger to a render process select the Debug tab and Debug Renderer Process before launching.

**Comment by mdeisher** [comment]
When I do that a dialog pops up saying “Unable to launch browser: ‘Could not connect to debug target at http://localhost:9222: Promise was canceled’”.

I am able to launch the Python web server which causes an instance of Netron to appear in a Chrome browser tab.  But I'm not sure how to connect the Visual Code Debugger to that process.

**Comment by lutzroeder** [comment]
@mdeisher you can use the built-in Chrome debugger (press F12) when running in Chrome.

**Comment by mdeisher** [comment]
I'm still not able to debug it.  But I did try it on another machine with Netron 4.6.5 installed and it can display the XML just fine.

**Comment by AlexRux** [comment]
Hi guys. i got this problem after 19 months that my model worked. What it's happening? 

[Model.zip](https://github.com/lutzroeder/netron/files/6464003/Model.zip)

The same models that before worked now they're not.

**Comment by mdeisher** [comment]
I resolved my issue.  It turned out to be a malformed model that included an edge with a bad port number.

**Comment by AlexRux** [comment]
> I resolved my issue. It turned out to be a malformed model that included an edge with a bad port number.

I'm using the same models that before worked with Netron. Then suddenly I got this problem.

**Comment by mdeisher** [comment]
@AlexRux, yes there is an issue.  As I mentioned above, previous versions of Netron could render my bad graph.

**Comment by lutzroeder** [comment]
This issue is a catch all for crashes caused by null references.
@AlexRux the issue is related to custom activations in Keras, already fixed by commit above.
@mdeisher can you add a change to guard against malformed OpenVINO graphs or provide a minimal repro?

**Comment by mdeisher** [comment]
Here is a reproducer.
[netronRepro.zip](https://github.com/lutzroeder/netron/files/6473074/netronRepro.zip)

**Comment by KarelPeeters** [comment]
A pytorch-exported model that causes this issue, the popup redirected me here:

![image](https://user-images.githubusercontent.com/7887115/124456516-13f5ca80-dd8b-11eb-9926-43fe72590801.png)

[model_0_epochs.zip](https://github.com/lutzroeder/netron/files/6763472/model_0_epochs.zip)

**Comment by lutzroeder** [comment]
[model_0_epochs.pt.zip](https://github.com/lutzroeder/netron/files/6765569/model_0_epochs.pt.zip)

**Comment by KarelPeeters** [comment]
@lutzroeder Is that a smaller version of my file or do you have another file that happens to give the same error with the same name?

**Comment by alokguptaxilinx** [comment]
[detector.zip](https://github.com/lutzroeder/netron/files/13419681/detector.zip)
Not able to open this .pt model in netron
