### ISSUE TITLE
New version 4.6.6 is broken.

### ISSUE THREAD

**Issue by zjuwyz** [lutzroeder/netron#652]
- Netron app and version: 4.6.6
- OS and browser version: Ubuntu 16.04

The latest version fails to execute, saying "Update for version 4.6.6 is not avaliable (latest version: 4.6.6, downgrade is disallowed)." and then stuck after checking for update.

**Comment by lutzroeder** [comment]
@zjuwyz can you investigate why this is happening or provide a patch. The message is printed by the update library and is expected. Is this happening for AppImage, Snap or both? No repro on Ubuntu 20.04.
