### ISSUE TITLE
Option to disable automatic updates

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [lutzroeder/netron#653]
I'd like to disable checking for updates when I close Netron.  I don't like being constantly asked to give admin.

**Comment by lutzroeder** [comment]
Duplicate #653

**Comment by TomWildenhain-Microsoft** [comment]
Did you intend to mark this as a duplicate of itself?

**Comment by lutzroeder** [comment]
The goal is for users to be on the latest version and limit support complexity. One alternative is to use the browser version. macOS and Linux silently update in the background. The dialog is more of an issue with Windows, might be a good area for contributions in electron-builder if you have time that could benefit a lot of apps.

**Comment by TomWildenhain-Microsoft** [comment]
Ah interesting, I didn't realize this is an electron limitation.  Thanks!

**Comment by lutzroeder** [comment]
@TomWildenhain-Microsoft not sure why the dialog shows. Feel free to investigate.

**Comment by lutzroeder** [comment]
`4.6.8` is now using `perMachine=false` installing to a user folder. The previous `4.6.7` version needs to be uninstalled manually.

**Comment by TomWildenhain-Microsoft** [comment]
Thanks!

**Comment by oxygen-dioxide** [comment]
@TomWildenhain-Microsoft You can Install netron with pip: `pip install netron` which won't update automatically
