### ISSUE TITLE
Please stop the notification SPAM

### ISSUE THREAD

**Issue by adewes** [lutzroeder/netron#654]
It seems you're starring and unstarring your own project every few hours, which leads to my notification screen showing the same notification over and over again:

![image](https://user-images.githubusercontent.com/550026/102690115-6ca4b200-4203-11eb-8e15-de3691611f46.png)

I understand that you want to promote the project and I love following people but honestly this made me unfollow you as I don't want to be spammed on Github, especially since there's no way to turn these notifications off for specific projects / people I follow. Thanks.

**Comment by lutzroeder** [comment]
I didn't know this shows up in some feed. It's the easiest way to get the exact numbers for some of the counters.
