### ISSUE TITLE
OpenVINO bf16 support

### ISSUE THREAD

**Issue by Vladimir9812** [lutzroeder/netron#660]
Loading the attached IR file (in OpenVINO format) fails with the message: "Error loading OpenVINO model. Unknown precision '"bf16"' in 'squeezenet1.0_bf16.xml'.".
[squeezenet1.0_bf16.zip](https://github.com/lutzroeder/netron/files/5756813/squeezenet1.0_bf16.zip)

**Comment by lutzroeder** [comment]
@demid5111 @mdeisher
