### ISSUE TITLE
pytorch .pth file opened with netron shows the nodes(layers) but no edges (interconnections).

### ISSUE THREAD

**Issue by eddydw** [lutzroeder/netron#664]
- Netron app and version: 
- OS and browser version: 

Steps to Reproduce:

1.
2.

Please attach or link model files to reproduce the issue if necessary.

**Comment by lutzroeder** [comment]
Can you share a model file to reproduce the issue.

**Comment by abitrolly** [comment]
@lutzroeder here is one https://github.com/abitrolly/ai_people_counter/blob/master/ucsd_UNet.pth

Looks like this.

![image](https://user-images.githubusercontent.com/8781107/114293820-fffb3f00-9aa1-11eb-948d-0adc5acb3169.png)

**Comment by lutzroeder** [comment]
Duplicate of #236
