### ISSUE TITLE
tf2.0 hdf5 model can not load correct

### ISSUE THREAD

**Issue by zhaohb** [lutzroeder/netron#665]
Now I get a hdf5 model file, and I want use netron to see the model struct, but I get a error:
  inbound_node is not iterable in **.h5

I use tf2.2 to get the hdf5

who can help me ? thank you  very much

**Comment by lutzroeder** [comment]
Can you share the model file?

**Comment by zhaohb** [comment]
ok，thank you very much
please give me the email, and I will send the model to you through the email

**Comment by lutzroeder** [comment]
@zhaohb can you attach it to this issue, share a link via a file sharing or upload to a GitHub repo?

**Comment by zhaohb** [comment]
@lutzroeder share a link  may not be a good idea，that model will be used in our production environment，I am sorry.  my email is zhaohongbocloud@gmail.com , you can send me an email first

**Comment by zhaohb** [comment]
@lutzroeder issue had be closed?

**Comment by lutzroeder** [comment]
There is no repro so it is not actionable. It can be reopened once there is a repro.

**Comment by zhaohb** [comment]
ok, thank you very much
