### ISSUE TITLE
Conflict between model summary and netron for conv2D dimension

### ISSUE THREAD

**Issue by gjkunde** [lutzroeder/netron#668]
- Netron app and version: Mac version 4.7.0.dmg
- OS and browser version: mac 10.14.6

Hello,

I just opened my model and the graph has incorrect layer dimensions .....

In the attachment I am comparing the model.summary statement with the Netron  image.

<img width="660" alt="Screen Shot 2021-01-13 at 10 52 54 AM" src="https://user-images.githubusercontent.com/7330890/104490391-07d44180-558e-11eb-878a-bebd8ee1ccc7.png">

Here in writing, Netron is on the right

Layer (type)                 Output Shape              Param #   
=================================================================
reshape_1 (Reshape)          (None, 1, 2, 128)         0                       NETRON ?x2x128
_________________________________________________________________
zero_padding2d_1 (ZeroPaddin (None, 1, 2, 132)         0         
_________________________________________________________________
conv1 (Conv2D)               (None, 256, 2, 130)       1024               NETRON 1x3 x 1x256  <<==========
_________________________________________________________________
dropout_1 (Dropout)          (None, 256, 2, 130)       0         
_________________________________________________________________
zero_padding2d_2 (ZeroPaddin (None, 256, 2, 134)       0           
_________________________________________________________________
conv2 (Conv2D)               (None, 80, 1, 132)        122960            NETRON 2x3 x 256x80 <<=========
_________________________________________________________________
dropout_2 (Dropout)          (None, 80, 1, 132)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 10560)             0         
_________________________________________________________________
dense1 (Dense)               (None, 256)               2703616             NETRON 10560x256
_________________________________________________________________
dropout_3 (Dropout)          (None, 256)               0              
_________________________________________________________________
dense2 (Dense)               (None, 8)                 2056                      NETRON 256x8
_________________________________________________________________
activation_1 (Activation)    (None, 8)                 0         
_________________________________________________________________
reshape_2 (Reshape)          (None, 8)                 0         
=================================================================
Total params: 2,829,656
Trainable params: 2,829,656

Thanks for looking into this.

PS. Cannot attach the zipped h5 file.

**Comment by lutzroeder** [comment]
It looks like you are comparing the shapes of the weight tensors for each layer with the shapes of the outputs. The app doesn't do shape inference for Keras at this point as it is running int the browser without inference from the Keras runtime available. For some formats like Darknet there is browser inference available. Nobody has done the work for Keras.
