### ISSUE TITLE
MindSpore: Unsupported file content

### ISSUE THREAD

**Issue by ljdang** [lutzroeder/netron#670]
Error loading model. Unsupported file content (18000000140018000000040000000800) for extension '.ms' in 'mobilenetv2.ms'.
The model to test:
https://download.mindspore.cn/model_zoo/official/lite/mobilenetv2_openimage_lite/mobilenetv2.ms

**Comment by lutzroeder** [comment]
@ljdang please open an issue in [mindspore-ai/mindspore](https://github.com/mindspore-ai/mindspore) to track this.

@YvetteLaw

**Comment by lutzroeder** [comment]
Duplicate of #600
