### ISSUE TITLE
Can Netron visualize models generated by old schemas?

### ISSUE THREAD

**Issue by YvetteLaw** [lutzroeder/netron#674]
Does Netron support visualization of old TensorFlow Lite models? TensorFlow Lite has multiple versions of schemas (see https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/schema    ). There are schema_v0, schema_v1 and so on.   Can Netron visualize models generated by an old schema? How does Netron handle the schema version issue?

**Comment by lutzroeder** [comment]
All models available publicly seem to be `v3` or later. Before `v3` the schema has no `file_identifier` and likely will not load. Since `v3` the changes are additive, new schema versions are compatible with old schemas.
