### ISSUE TITLE
MindSpore: version r1.1 support

### ISSUE THREAD

**Issue by YvetteLaw** [lutzroeder/netron#676]
In the update of version r1.1 just released by MindSpore, due to the unification of operator prototypes of the cloud-end and mobile-end(mslite), the scehma of mslite has been greatly modified, making r1.1  and r1.0 not compatible. At present, the main users of mslite are our internal developers, and there are fewer external users. We have assessed that the impact of version incompatibility is relatively small. We hope to temporarily remove support for mslite and we will re-add support for the new version of mslite at about the end of the month. What do you think?

**Comment by lutzroeder** [comment]
Option 1) Fix the problem and stop breaking users
Option 2) Deprecated `mslite` and use another format instead

**Comment by YvetteLaw** [comment]
For the option 2:
Could the standard format be our unification of operator prototypes of the cloud-end and mobile-end(mslite)?  Can we remove mslite support and re-add it after completing this format?

**Comment by YvetteLaw** [comment]
> Option 1) Fix the problem and stop breaking users
> Option 2) Deprecated `mslite` and use a standard format instead

For the option 2:
Could the standard format be our unification of operator prototypes of the cloud-end and mobile-end(mslite)? Can we remove mslite support and re-add it after completing this format?

**Comment by lutzroeder** [comment]
Option 2) is to adopt an existing format instead of inventing another one that is not much different from all the other ones that exist already.

**Comment by YvetteLaw** [comment]
> Option 2) is to adopt an existing format instead of inventing yet another one that is not much different from all the other ones that already exist.

Because of the international political influence, it is not appropriate for Huawei to use another standard format. We have to use our own format. However，we had not designed it properly at the beginning, so there was a compatible problem. Since the  number of users is small, and the impact is not great. We hope the original version can be discarded, and we will support a new version.

**Comment by YvetteLaw** [comment]
> Option 1) Fix the problem and stop breaking users
> Option 2) Deprecated `mslite` and use a standard format instead

Or could you offer another option?

**Comment by lutzroeder** [comment]
[control_flow_ut_while_0122.ms.zip](https://github.com/lutzroeder/netron/files/6097926/control_flow_ut_while_0122.ms.zip)

**Comment by lutzroeder** [comment]
Duplicate of #600
