### ISSUE TITLE
PyTorch: Unknown expression `dict`

### ISSUE THREAD

**Issue by geogeo28** [lutzroeder/netron#677]
- Version: 4.7.3 Desktop app, macOS 10.15.6 (19G73)

Steps to Reproduce:

1. Load a model.pt with returns a dict in forward method.

<img width="1018" alt="Screen Shot 2021-02-03 at 6 53 59 PM" src="https://user-images.githubusercontent.com/11450275/106838982-1de79600-6652-11eb-861d-b496e4b0a55b.png">

**Comment by lutzroeder** [comment]
>Please attach or link model files to reproduce the issue if necessary.

**Comment by geogeo28** [comment]
[dummy.pt.zip](https://github.com/lutzroeder/netron/files/5923074/dummy.pt.zip)

```python
import torch.jit
import torch.nn as nn
class DummyModel(nn.Module):
    def __init__(self):
        super().__init__()

        self._conv1 = nn.Conv2d(4, 8, 3, padding=1)
        self._conv2 = nn.Conv2d(8, 16, 3, padding=1)
        self._conv3 = nn.Conv2d(16, 24, 3, padding=1)
        self._conv_aux = nn.Conv2d(4, 24, 3, padding=1)

    def forward(self, input: torch.Tensor):
        y1 = self._conv1(input)
        y2 = self._conv2(y1)
        y3 = self._conv3(y2)
        aux = self._conv_aux(input)
        return {
            'pred': [None, y2, y3],
            'aux': [aux, None, None]
        }

model = DummyModel()
model_jit = torch.jit.script(model)
model_jit.save('/tmp/dummy.pt')
```

**Comment by lutzroeder** [comment]
[netron_issue_677.pt.zip](https://github.com/lutzroeder/netron/files/5923245/netron_issue_677.pt.zip)

**Comment by lutzroeder** [comment]
[netron_issue_677.pt.zip](https://github.com/lutzroeder/netron/files/5923252/netron_issue_677.pt.zip)
