### ISSUE TITLE
Showing all attributes even if one is default (or missing) in ONNX models

### ISSUE THREAD

**Issue by fengyuentau** [lutzroeder/netron#679]
Hi, great work on the visualizer for ONNX and other models!

Recently I am working on something requiring hacking into ONNX models and viewing all the attributes of its operators. I tried to open the ONNX model with vim, but I can only see some keywords such as `kernel_shape`, while the value is some weird characters and not human-readable. Your visualizer helped me a lot to retrieve most of the attributes. However, some of the attributes is missing, such as the `auto_pad` from [Conv](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Conv). Are these attributes missing because of missing in the ONNX file or suppression if the value is default? Could you kindly adding an option to show all attributes even if on is default or missing?

**Comment by lutzroeder** [comment]
Can you provide a model and description to reproduce the issue?

The defaults for a framework are not stored in the model file and would have to be hardcoded in the tool. To do this reliably you will have to sign up to work on providing and maintaining such metadata for all operators in all supported frameworks.
