### ISSUE TITLE
Error: Failed to render tensor

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#681]
Please provide steps or model files to reproduce this issue.

**Comment by codgeek** [comment]
reproduce steps:
1.  download the  sparsed "mobilenet v1 1.0 " model  in xnnpack page: https://github.com/google-research/google-research/tree/master/fastconvnets, link is [https://storage.googleapis.com/fast-convnets/tflite-models/mbv1_100_90_12b4_684.tflite](https://storage.googleapis.com/fast-convnets/tflite-models/mbv1_100_90_12b4_684.tflite)

2.  open model file with netron, choose the first "densify block", unfold the inputs 1,    
3. crash! 

![image](https://user-images.githubusercontent.com/20918280/112447426-45bec480-8d8c-11eb-8a37-52d4113fd601.png)
