### ISSUE TITLE
TensorFlow.js weights support

### ISSUE THREAD

**Issue by TheNewSound** [lutzroeder/netron#683]
Netron does support loading the model.json, but does not seem to recognize the weights.bin uploaded with it.

**Comment by TheNewSound** [comment]
No repro?

Is this a feature that is already added? It is not to my knowledge...

**Comment by lutzroeder** [comment]
Can you share a sample file, steps how to load the file and what isn't working or submit a PR to fix the issue.

**Comment by TheNewSound** [comment]
Sure!

2 files: model.json (works). weights.bin (is not recognized, missing feature likely, not a bug I assume)

Have to upload it as .zip to github, see attachment.

Just extract the 2 files and upload them to netron.
[model.zip](https://github.com/lutzroeder/netron/files/5999859/model.zip)

**Comment by TheNewSound** [comment]
weights.bin can be read out with the following small piece of javascript:

[view-source:https://worldwidecrap.nl/weights.html](view-source:https://worldwidecrap.nl/weights.html)
Demo: [https://worldwidecrap.nl/weights.html](https://worldwidecrap.nl/weights.html)
