### ISSUE TITLE
OpenVINO bin support

### ISSUE THREAD

**Issue by Vladimir9812** [lutzroeder/netron#692]
Loading the attached IR file (in OpenVINO format) fails with the message: "Error loading OpenVINO model. Unknown precision '"bin"' in ''resnet50-binary-0001.xml".

[resnet50-binary-0001.zip](https://github.com/lutzroeder/netron/files/6063220/resnet50-binary-0001.zip)

**Comment by lutzroeder** [comment]
@Vladimir9812 in the future please submit pull requests to fix OpenVINO issues or get the right folks at Intel involved.

**Comment by Vladimir9812** [comment]
Thank you very much, @lutzroeder
