### ISSUE TITLE
ONNX: sparse_initializer support

### ISSUE THREAD

**Issue by yuslepukhin** [lutzroeder/netron#693]
Would be nice to visualize graph.sparse_initializer in COO format

**Comment by lutzroeder** [comment]
@yuslepukhin can you share a sample file and some context?

**Comment by yuslepukhin** [comment]
Currently, if a graph has a constant initializer, which is an initializer that is not overriding any input, Netron displays it as one of the corresponding operator inputs.

However, if we sparsified that initializer and put it into graph.sparse_initializer, the model would be evaluated as before, the corresponding operator would receive it as input. It is not visualized though. 

Consider the attached model.  [coo_normal_sparse.zip](https://github.com/lutzroeder/netron/files/6078074/coo_normal_sparse.zip)

MatMul has two inputs and one of them is fed from sparse_initializer B. If you run this model with a single input, it will run.

If B was a dense initializer within graph.initializer, it would be visualized, but its sparse version is not visualized.

![image](https://user-images.githubusercontent.com/11303988/109848601-4fc62b00-7c05-11eb-93fa-133f66b059ec.png)

**Comment by lutzroeder** [comment]
[coo_normal_sparse.onnx.zip](https://github.com/lutzroeder/netron/files/6080534/coo_normal_sparse.onnx.zip)

**Comment by lutzroeder** [comment]
Duplicate of #6
