### ISSUE TITLE
Allow loading models from file url

### ISSUE THREAD

**Issue by JarnoRFB** [lutzroeder/netron#697]
Very cool app!

Momentarily it is possible to load model from a http url like https://netron.app/?url=https://raw.githubusercontent.com/srom/chessbot/master/model/chessbot.pb 

It would be very useful if the model file could also be specified via a local file url like  https://netron.app/?url=file:/home/myuser/chessbot.pb 

The usecase I have is that I want to track model architectures in mlflow. So currently I can easily save my architecture in the mlflow ftp artifact store. Next I would like to run a private netron instance that has access to that artifact store mounted on its file system and save a url together with the model architecture in mlflow, so I can open the architecture with one click.

Also happy to implement this if the feature sounds useful, I would probably need a few pointers where to look though.

**Comment by lutzroeder** [comment]
@JarnoRFB can you clarify how this is expected to work and maybe submit a pull request? Since the app is running in the browser which is a sandbox without access to the file system, how is this expected to work?

**Comment by JarnoRFB** [comment]
@lutzroeder  Not sure if I understand you correctly. I mean one does load models from the file system via the UI or one can specify the path to the model file from the command line when starting the server. Therefore I thought that it would be possible to utilize one of those mechanisms to also load models from the file system specified via a URL. 

If you think that this is possible I can attempt an implementation.

**Comment by JarnoRFB** [comment]
@lutzroeder Just noticed that mlflow also exposes its artifacts via its http API, so an access via a local file URL is no longer required for my usecase.

**Comment by lutzroeder** [comment]
> Not sure if I understand you correctly. I mean one does load models from the file system via the UI or one can specify the path to the model file from the command line when starting the server.

First approach is the browser exposing a dialog or drag & drop gesture which requires user interaction. Second approach requires running a server. Neither allows the code running in the browser to directly access the local file system.
