### ISSUE TITLE
Double-click does not open the ONNX file in the viewer.

### ISSUE THREAD

**Issue by spandantiwari** [lutzroeder/Netron#70]
Awesome tool! 

Whenever I try to open a model for viewing by double-clicking on it, Netron fires up fine (I have .onnx file extension mapped to Netron app) but the model does not show up in the viewer. It is blank. I have to open the model file again by selecting. Is it possible to fix this?

**Comment by lutzroeder** [comment]
Is this still happening in the latest version `1.4.0`? Are you running Windows, macOS or Linux? Is it happening with all files or just specific ones?

**Comment by lutzroeder** [comment]
812ab07dc3ce1a582054b776eaeb7b6bf21d2437

**Comment by lutzroeder** [comment]
Can you check if this works in the latest version `1.4.1`?

**Comment by spandantiwari** [comment]
Yes, it's fixed. Thanks.
