### ISSUE TITLE
[Question] How to determine re-scaling factor for quantization?

### ISSUE THREAD

**Issue by atyshka** [lutzroeder/netron#702]
I'm working on implementing a tiny MNIST classifier on FPGA and was looking at this tool for inspecting the tflite graph. I know when performing an operation such as conv2d, the input and weights will be multiplied into int32 products. accumulated with int32 biases, and then a relu op will be applied. Then the output needs to be re-scaled to int8. My question is how do I determine the re-scaling from the info netron gives? According to netron, my input quantization is 
0 ≤ 0.003921568859368563 * (q - -128) ≤ 1
and my output is
0 ≤ 0.010280518792569637 * (q - -128) ≤ 2.6215322017669678

For the re-scaling is it simply dividing the output by 2.62? If I do that and plot a histogram, over a third of the values overflow 255. Is that kind of thing normal or am I mis-interpreting how to do the re-quantization? Sorry this isn't an issue, just trying to figure out how to understand the info from netron.

**Comment by lutzroeder** [comment]
@atyshka the code is [here](https://github.com/lutzroeder/netron/blob/main/source/tflite.js#L485-L501). Please reach out to TensorFlow Lite folks if more context is needed. If this can be improved in any way feel free to submit a pull request.

**Comment by atyshka** [comment]
Oh I see. It looks like netron currently does not support the per-filter quantization which is why this didn't show up. On conv2d's it will make a separate scale factor for each channel on the output. Multiplying input by that factor gives reasonable results.

**Comment by atyshka** [comment]
Don't have time to contribute changes under project timeline but maybe later
