### ISSUE TITLE
Appending of timestamp to model URL breaks mlflow artifact API

### ISSUE THREAD

**Issue by JarnoRFB** [lutzroeder/netron#708]
- Netron app and version: 4.8.1
- mlflow version: 1.7.1

As described in #697 I want to automatically open netron with artifacts saved in mlflow. I got it working now, but stumbled over a probelm. In https://github.com/lutzroeder/netron/blob/main/source/index.js#L438 the current time is appended to the model URL as a query parameter. However, since it only contains a value and not a key, it somehow breaks the mlflow URL parser, resulting in an internal server error. My workaround is to simply remove this line in my deployment, but I would like to understand what it is for and whether it could be changed to a key value format. 

Unfortunately, it is a bit difficult to publicly reproduce the error, as one would need a public mlflow instance and enable CORS for netron there. I hope the problem is stll clear enough.

Steps to Reproduce:

1. Track a keras model as .h5 file as an artifact in mlflow. 
2. Try to open the url in netron, an example URL would look like http://netron.app/?identifier=model.h5&url=http://mlflow.my-domain.com/get-artifact?path%3Dmodel.h5%26run_id%3D79a796f0dd5449b58e6e7e6d0a638f51
3. An internal server error is triggered in mlflow.

**Comment by lutzroeder** [comment]
@JarnoRFB please investigate and submit a pull request with a fix if needed.
