### ISSUE TITLE
Highlight all nodes of a specific type

### ISSUE THREAD

**Issue by addisonklinke** [lutzroeder/netron#712]
Currently you can `ctrl + F` to search for specific nodes by name and have them highlighted in the graph. Is it possible to extend this to highlight all nodes of the same type? For instance, searching "reshape" would highlight reshape_1, Reshape_2, reshape/3, etc. This should support all the major types of nodes: concat, conv, unsqueeze, etc. Since the metadata for node type is already included in the graph, I imagine this would only require a UI update

Although you can tell some information about the node type based on its color scheme, I think highlights would be more helpful. Most colors have multiple types (green = gather, transpose, unsqueeze, etc) so you cannot zoom out and see the "big picture" location of where a specific type is used in the graph. As a machine learning engineer, sometimes I want to remove/replace certain nodes that run slower on specialized hardware, so this would be an easy way to visualize how frequently and where they are used

**Comment by lutzroeder** [comment]
@addisonklinke can you implement this and submit a pull request.

**Comment by addisonklinke** [comment]
I have pretty minimal experience in JavaScript, but I could give it a try if you're able to provide a conceptual outline of what changes need to be made in which files?

**Comment by lutzroeder** [comment]
`sidebar.FindSidebar` in `view-sidebar.js` implements the search dialog and is probably a good place to get started.
