### ISSUE TITLE
LSTM internal weights in TFLite

### ISSUE THREAD

**Issue by efard** [lutzroeder/netron#714]
As you know, LSTM cell has four internal gates: forget, input, output and cell gate (https://colah.github.io/posts/2015-08-Understanding-LSTMs/) When we convert a model containing LSTM to TFLite format, we can see the internal weights in groups like "std.constant9" (with no specific name). But it isn't clear that which weight group is related to which gate. In other words, how do we recognize weights for each internal gate?
Sample files are attached if needed. Thanks in advance.

**Comment by efard** [comment]
[tflite_models.zip](https://github.com/lutzroeder/netron/files/6252043/tflite_models.zip)

**Comment by lutzroeder** [comment]
@efard please investigate this issue and submit a pull request with a fix.

**Comment by efard** [comment]
For test reasons, I made some minor changes in code, like this (line 44 of tflite-metadata.json):
{ "name": "output_bias", "type": "T", "description": "Output gate bias tensor.", "visible": false},
to 
{ "name": "output_bias", "type": "T", "description": "Output gate bias tensor.", "visible": true },

or this (line 86 of tflite-metadata.json):
{ "name": "input", "type": "T" },
to
{ "name": "input!!!!!!", "type": "T" },

But no changes are applied in netron GUI, even after system restart. Did I do something wrong?
