### ISSUE TITLE
Error loading TensorFlow Lite model. Tensor data type 'boolean' is not implemented.

### ISSUE THREAD

**Issue by zero15** [lutzroeder/netron#719]
I opend a tflite model in browser and this error comes out. The previous version of netron  works with the same model.

**Comment by lutzroeder** [comment]
@zero15 can you share the model file?

**Comment by zero15** [comment]
> @zero15 can you share the model file?

[https://github.com/zero15/GITTest/blob/master/tacotron2.zip.001](url)
[https://github.com/zero15/GITTest/blob/master/tacotron2.zip.002](url)
