### ISSUE TITLE
Summary page not reporting input dimensions

### ISSUE THREAD

**Issue by BenPYeh** [lutzroeder/Netron#72]
I created a model like so:
numChannels = 1
width = 1
height = 3

input = C.input_variable((numChannels, width, height), dtype=np.float32)
z = element_times(constant(1), input)
z.save("identity.onnx", format=C.ModelFormat.ONNX)

I think it is a valid model. I tried verifying like so:
input = np.array([[[1, 4 ,7]]])
output = z.eval({z.arguments[0]:input})
print(output)
>>>[[[[ 1.  4.  7.]]]]

But the summary page reports the input as "float : Input3" without its dimensions. While the output looks like "float[1,1,1,3]", which should also be the input.

**Comment by lutzroeder** [comment]
Can you attach the model?

**Comment by BenPYeh** [comment]
Sure here it is.

**Comment by BenPYeh** [comment]
Done
[identity_1_1_3.zip](https://github.com/lutzroeder/Netron/files/1697177/identity_1_1_3.zip)

**Comment by lutzroeder** [comment]
@ebarsoum, looks like a CNTK exporter issue?

**Comment by ebarsoum** [comment]
@BenPYeh which version of CNTK are you using?

**Comment by BenPYeh** [comment]
The latest - 2.4
