### ISSUE TITLE
input.split is not a function in 'saved_model.pb'

### ISSUE THREAD

**Issue by satmonkey** [lutzroeder/netron#726]
[saved_model.zip](https://github.com/lutzroeder/netron/files/6337150/saved_model.zip)

Error appears after the model load.
Custom trained ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8
Netron 4.8.8

**Comment by lutzroeder** [comment]
@satmonkey can you try this again in 4.8.9? Are there specific steps after loading the model to repro this issue?

**Comment by satmonkey** [comment]
in 4.8.9, it is loading successfully :)
Thank you!
