### ISSUE TITLE
Nvidia file formats

### ISSUE THREAD

**Issue by JohnnyOpcode** [lutzroeder/netron#729]
NVIDIA has added three additional formats into the model universe.

Will it be difficult to add the capability to Netron?

EJRVS - Inference models used on their Jarvis runtime
TLT - Transfer learning models
NEMO - Conversational AI models

**Comment by lutzroeder** [comment]
@JohnnyOpcode can you create separate issues for each format, provide a link to a format specification, sample files and ideally a pull request to implement support.
