### ISSUE TITLE
Keras Error: HDF5 file has no 'model_config' data.

### ISSUE THREAD

**Issue by salihkaragoz** [lutzroeder/Netron#73]
Ubuntu 16.04 LTS
Netron has installed from .deb file
python version 2.7.12
Tensorflow version 1.6.0-dev20180126 (CPU)
Keras Version 2.1.3

```
from keras.applications import ResNet50
model = ResNet50
model.save_weights('test_netron.h5')
```
After the weights saved I open with Netron desktop and I faced this error.

![error_netron_ubuntu](https://user-images.githubusercontent.com/22906895/35918235-20d408cc-0c22-11e8-9149-d1aa23cc0685.png)

**Comment by lutzroeder** [comment]
`save_weights` saves only the weights without information about the graph. Use `save` instead to save the graph and weights.

```
from keras.applications import ResNet50
model = ResNet50()
model.save('test_netron.h5')
```
