### ISSUE TITLE
Show/Hide Attributes/Initializers per node

### ISSUE THREAD

**Issue by TheRisenPhoenix** [lutzroeder/netron#730]
I came across a case where I need to display the attributes of some specific components (e.g. an Activation Node), but want to hide them for all other nodes, as this would be too much information and thus confusing. As far as I have seen, there is only the option to turn the view on and off for all nodes at the same time.

It would be nice to have a checkbox in the properties window of each node to enable showing (respectively hiding) attributes (or also initializers) for this single node.

**Comment by lutzroeder** [comment]
Can you provide more specifics? Why is this needed for Activation nodes? What is the problem and are there other potential solutions? Is there an example how checkboxes in the properties window would work? For example, is this a common feature supported by other tools that is already known to most users? Can this be done in a way that is intuitive to most users or would it lead to a different kind of confusion?

**Comment by TheRisenPhoenix** [comment]
The Activation example was only meant as an example. In general, my thought was that it could be helpful for visualization purposes (e.g. in a presentation or scientific paper) if you could show only the details of individual nodes. Especially if you want to focus the presentation on a certain area of the network, you could show the details for that (e.g. at .h5, for an activation node, because it is interesting here which activation function is used), but for the rest of the network you could hide the details, because they might be confusing for the audience.
I do not know if other tools already provide this functionality, I have only worked with netron so far. 
The checkbox in the properties window was also just a spontaneous thought, since this window already presents details about the individual node. Therefore I thought it would be suitable to directly edit visual properties of the node (that's also the first place where I looked for such a feature). An alternative could be a right-click context menu on the node itself.
I don't think that this feature would lead to much confusion among users, but of course I can't speak for everyone. I personally would find this feature helpful, and that's why I wanted to suggest it here and put it up for discussion.

**Comment by lutzroeder** [comment]
Some formats handle activation by having different operators for each function. For example, ONNX will show `Relu` instead of `Activation` as the node type. Are there other examples where this would be needed or is this specific to how some formats store `Activation`, `Binary` or `Unary` operators which could be handled differently?

**Comment by TheRisenPhoenix** [comment]
I guess it could be helpful for any kind of node - completely depending on what to put the focus on when using it for visualization. I'm thinking of large nets, where you want to show the specific configuration of a certain part, but not of the rest. 
I think that it's always helpful to be able to customize a visualization as precisely as possible and tailor it to your specific needs. 
But of course, I see your point that it might get too confusing.
