### ISSUE TITLE
Exporting Visualised Graphs for Further Manipulation

### ISSUE THREAD

**Issue by yunuscukran** [lutzroeder/netron#731]
Hi,

Is there a way to export a visualized Netron graph to a text / JSON (or another kind of) file? This might be a great cross-platform way to represent and modify NNs!

Cheers

**Comment by lutzroeder** [comment]
Can you be more specific or submit a pull request for what you are trying to accomplish? The app supports dozens of formats for representing graphs. Formats like ONNX are intended for model exchange. For visuals there is export to SVG and PNG.
