### ISSUE TITLE
Winget install netron fails: "Opening manifest failed"

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [lutzroeder/netron#733]
![image](https://user-images.githubusercontent.com/67606533/116124120-e0fbd000-a691-11eb-8ddc-8ac02f4d5cb9.png)

**Comment by lutzroeder** [comment]
@TomWildenhain-Microsoft does this repro with the most recent version of winget?

**Comment by TomWildenhain-Microsoft** [comment]
haha nope.  Apparently an old winget version was the issue.
