### ISSUE TITLE
ONNX: sparse tensor type support

### ISSUE THREAD

**Issue by yuslepukhin** [lutzroeder/netron#741]
Need to include support for models and nodes that accept SparseTensor and may have sparse outputs.
I am not able to attache either an onnx or python files.

**Comment by lutzroeder** [comment]
@yuslepukhin can you create and share a file to reproduce the issue?

**Comment by yuslepukhin** [comment]
[SparseInModels.zip](https://github.com/lutzroeder/netron/files/6510688/SparseInModels.zip)

**Comment by lutzroeder** [comment]
[sparse_initializer_as_output.onnx.zip](https://github.com/lutzroeder/netron/files/6512243/sparse_initializer_as_output.onnx.zip)

**Comment by lutzroeder** [comment]
[sparse_initializer_as_output.onnx.zip](https://github.com/lutzroeder/netron/files/6512243/sparse_initializer_as_output.onnx.zip)
[sparse_initializer_as_output.json.zip](https://github.com/lutzroeder/netron/files/12444489/sparse_initializer_as_output.json.zip)
[sparse_to_dense_matmul.onnx.zip](https://github.com/lutzroeder/netron/files/12444490/sparse_to_dense_matmul.onnx.zip)
