### ISSUE TITLE
Font not showing in open file dialog

### ISSUE THREAD

**Issue by jeranio** [lutzroeder/netron#752]
Ubuntu 4.9.7 Desktop

Clicking on the "Open Model" button, the resulting file dialog shows up but all the text is just tiny rectangles in place of the text. No text itself is legible. Any ideas? What font am I missing?

**Comment by lutzroeder** [comment]
Please report this as an Ubuntu or Electron issue. This [issue](https://github.com/electron-userland/electron-builder/issues/5217) sounds similar and has a few pointers.
