### ISSUE TITLE
Clarification request for the "runtime" field

### ISSUE THREAD

**Issue by 21kc-caracol** [lutzroeder/netron#753]
In Netron model viewer, what does the "runtime" field means?

Is it the TensorFlow version that used to create this model? 
[https://i.stack.imgur.com/ko6E5.png](Screenshot of Netron model properties section)

**Comment by lutzroeder** [comment]
For TensorFlow lite contains the `min_runtime_version` [required](https://stackoverflow.com/questions/67881794/fetching-tflite-version-information-from-tflite-model) to run the model.

**Comment by 21kc-caracol** [comment]
By the way I posted your answer on [StackOverFlow](https://stackoverflow.com/questions/67987360/in-netron-model-viewer-what-does-runtime-mean) and put a link to this thread.

Thanks!
