### ISSUE TITLE
extension name missing . in paddle register

### ISSUE THREAD

**Issue by junluan** [lutzroeder/netron#756]
The last two file extension name in [https://github.com/lutzroeder/netron/blob/main/source/view.js#L1406](https://github.com/lutzroeder/netron/blob/main/source/view.js#L1406) missing `.` and this can cause useless paddle.js load in [https://github.com/lutzroeder/netron/blob/main/source/view.js#L1641](https://github.com/lutzroeder/netron/blob/main/source/view.js#L1641) when I did not load a paddle model.

**Comment by lutzroeder** [comment]
`model` (no extension) is a file name used by legacy `.tar` models. Can you provide a repro for when this is causing an issue?

**Comment by junluan** [comment]
Hi @lutzroeder 

I think you can just remove paddle.js and load a none paddle model such as onnx model. You can see the error:

`The script 'file:///xxx/netron/dist/web/paddle.js' failed to load.`

I extend netron to support a custom model type. And remove all other model type's related files to minimum integrate with our inner product.
