### ISSUE TITLE
open error

### ISSUE THREAD

**Issue by wm901115nwpu** [lutzroeder/netron#758]
Error loading Python module. Unsupported function 'torch.quantize_per_tensor' in 'resnet18_fx_graph_mode_quantized.pth'.

**Comment by lutzroeder** [comment]
@wm901115nwphu can you please share the model file.

**Comment by lutzroeder** [comment]
[resnet18_fx_graph_mode_quantized.pth.zip](https://github.com/lutzroeder/netron/files/6716842/resnet18_fx_graph_mode_quantized.pth.zip)

**Comment by wm901115nwpu** [comment]
yes, this file
