### ISSUE TITLE
In node.js 14.16.0 version error: "Unsupported function 'torch.addmm' in 'traced_online_pred_layer.pt'."

### ISSUE THREAD

**Issue by jiankebe** [lutzroeder/netron#760]
- Netron app and version: 
- OS and browser version: 

Steps to Reproduce:

1. node.js runtime
2. model is traced_online_pred_layer

Please attach or link model files to reproduce the issue if necessary.

When I use node.js 14.16.0, netron can not read the model(Error: "Unsupported function 'torch.addmm' in 'traced_online_pred_layer.pt'.") but in browser netron is ok, please help me how to use in node.js  
Runtime

https://raw.githubusercontent.com/ApolloAuto/apollo/master/modules/prediction/data/traced_online_pred_layer.pt

**Comment by jiankebe** [comment]
Netron code version from branch is master
OS: Mac OS
NodeJS: 14.16.0

**Comment by lutzroeder** [comment]
No repro on macOS and Node.js 14.17.1 and 16.4. Please investigate and submit a pull request with a fix.
