### ISSUE TITLE
TensorFlow.js: File text format is not graph-model

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#764]
Please provide steps or model files to reproduce this issue.

**Comment by Rincewindrunner** [comment]
I can reproduce the issue with this model file: (a Yolov3-tiny model that I trained with Darknet and then converted across to Tensorflow.js)

[model.zip](https://github.com/lutzroeder/netron/files/7149425/model.zip)

**Comment by lutzroeder** [comment]
[yolo3_tiny_darknet.zip](https://github.com/lutzroeder/netron/files/7150178/yolo3_tiny_darknet.zip)
