### ISSUE TITLE
Error on loading darknet config file

### ISSUE THREAD

**Issue by triwahyuu** [lutzroeder/netron#765]
- Netron app and version: 5.0.0 Website (July 6, 2021)
- OS and browser version: Ubuntu 20.04 + Chrome 91.0.4472.114

Steps to Reproduce:

1. open darknet config file [from here](https://github.com/WongKinYiu/yolor/blob/main/cfg/yolor_p6.cfg)
2. got the following:
```
Error loading Darknet model. Layer before convolutional layer must output image in 'yolor_p6.cfg'.
```

Please attach or link model files to reproduce the issue if necessary.
https://github.com/WongKinYiu/yolor/blob/main/cfg/yolor_p6.cfg

**Comment by lutzroeder** [comment]
[yolor_p6.cfg.zip](https://github.com/lutzroeder/netron/files/6767257/yolor_p6.cfg.zip)

**Comment by triwahyuu** [comment]
hi, thanks for the quick reply, really appreciate it. Keep up your good work 👍
