### ISSUE TITLE
Viewing ncnn weight

### ISSUE THREAD

**Issue by BinhBa** [lutzroeder/netron#768]
Hi @lutzroeder,
I'm using netron to work with ncnn. I saw in an discussion with nihui that we could see both graph and weight with the netron. But when I tried to grab both ".param" and ".bin" file and put them in netron, two window popped up. One open the ".param" file and one said that there is no ".xml" in ".bin" file as image attached.
I'm doing something wrong here?
![image](https://user-images.githubusercontent.com/33077168/125433347-df4ef79a-08dd-4052-b698-e41552a64216.png)

**Comment by lutzroeder** [comment]
Can you please include files to reproduce this behavior.

**Comment by lutzroeder** [comment]
@nihui

**Comment by BinhBa** [comment]
I included a sample model. One model contains 2 file .param.bin and .bin. I translated a issue in ncnn https://github.com/Tencent/ncnn/issues/2861 and he said that he can grab 2 file and open in netron so that he can view the weight. ^^ I wonder did I do some step wrong?
[weight_file.zip](https://github.com/lutzroeder/netron/files/6809837/weight_file.zip)

**Comment by lutzroeder** [comment]
[mnet.25.zip](https://github.com/lutzroeder/netron/files/6813063/mnet.25.zip)

**Comment by BinhBa** [comment]
@lutzroeder 
Thank you for your fix. With the mnet.25.zip, things are fine. But with other model the problem still there. My weights used to test [cc_irse_facenet_18_opt.zip](https://github.com/lutzroeder/netron/files/6819921/cc_irse_facenet_18_opt.zip)
![image](https://user-images.githubusercontent.com/33077168/125718126-eafa0fb5-d2df-4a57-94d7-f368bd7b9cd3.png)

**Comment by BinhBa** [comment]
@lutzroeder 
Thank you for your fix. With mnet.25.zip, things are fine. But with others model the problem still there, I uploaded my test model for you in Drive [link](https://drive.google.com/file/d/1VKwdAA2H-_Ll-6Ec2Zg3Ou9e0D4G2jeZ/view?usp=sharing)
![image](https://user-images.githubusercontent.com/33077168/125718792-0b8be935-e642-4282-a3ec-58bb2b1662ae.png)

**Comment by lutzroeder** [comment]
@BinhBa Please investigate this issue and submit a pull request with a fix.
