### ISSUE TITLE
Problems using the online version of netron

### ISSUE THREAD

**Issue by Zengyf-CVer** [lutzroeder/netron#772]
My browser version: chrome-stable:91.0.4472.164
I use online netron: https://netron.app/
When I loaded the model.json model of tfjs, this message popped up:
`Error loading TensorFlow model. Unknown weight data type size 'bool' in 'model.json'.`

This is the link to my model.json model:
https://drive.google.com/file/d/16JxAZkcLqhKESop17O47BBTGhctuVn-P/view?usp=sharing

**Comment by lutzroeder** [comment]
@Zengyf-CVer can you share the weights files as well?

**Comment by Zengyf-CVer** [comment]
> @Zengyf-CVer can you share the weights files as well?
https://drive.google.com/file/d/16JxAZkcLqhKESop17O47BBTGhctuVn-P/view?usp=sharing
