### ISSUE TITLE
ONNX function support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#773]
[model_local_func_test.onnx.zip](https://github.com/lutzroeder/netron/files/6845111/model_local_func_test.onnx.zip)

**Comment by zhouzq-thu** [comment]
Please support ONNX nested function.

**Comment by kumardesappan** [comment]
Was this onnx model generated from pytorch code? If, yes can you share the code for reference. If no, is it possible to generate this function node from pytorch code?

**Comment by lutzroeder** [comment]
@zhouzq-thu this is tracked by #1208. Please attach a sample file and submit a pull request to implement this feature.
