### ISSUE TITLE
file cannot begin with spaces

### ISSUE THREAD

**Issue by Chenzk1** [lutzroeder/netron#775]
- Netron app and version: 5.0.2
- OS and browser version: macOS 11.4

Steps to Reproduce

1. A file with extension "pbtxt"
2. If every line of the file begin with 2 spaces, netron cannot open it and show as follows:
![image](https://user-images.githubusercontent.com/35548458/126648570-e4acf629-75ef-41d3-9a01-abdc38dbf7c0.png)

**Comment by lutzroeder** [comment]
@Chenzk1 can you please share a sample file?

**Comment by lutzroeder** [comment]
Duplicate of #774
