### ISSUE TITLE
open deeplabv3 

### ISSUE THREAD

**Issue by wm901115nwpu** [lutzroeder/netron#779]
l.slice is not a function in 'deeplabv3_resnet50_scripted.pth'.

**Comment by wm901115nwpu** [comment]
When I upload the file, it always fails.

**Comment by lutzroeder** [comment]
Did you try uploading as a Zip file? If the file is too large maybe use Dropbox or GDrive and share the link.

**Comment by wm901115nwpu** [comment]
Ok, I have a try.

**Comment by wm901115nwpu** [comment]
https://www.dropbox.com/s/eatcsfojvlbm6vt/deeplabv3_resnet50_scripted.pth?dl=0
