### ISSUE TITLE
how to build a .exe file of netron which can be installed on my windows computer

### ISSUE THREAD

**Issue by hnuhchen** [lutzroeder/netron#780]
Hello, i am a user of netron, now i want to visual my models by using netron, but the format of my model is different from any other frameworks, such as caffe, pytorch, paddle, mnn and so on. So i want to add my format to netron and rebuild it, then i can install the .exe application on my windows computer to visual my models.

**Comment by lutzroeder** [comment]
See [DEVELOPMENT.md](https://github.com/lutzroeder/netron/blob/main/DEVELOPMENT.md) and [Makefile](https://github.com/lutzroeder/netron/blob/41135278264ac9d9595594e7d2c89c104215fc8c/Makefile#L46).
