### ISSUE TITLE
Request for Swish Function simplication

### ISSUE THREAD

**Issue by jangmin-deepx** [lutzroeder/netron#781]
Hi guys

In YoloV4, YoloV5 or any SOTA model uses Swish function for Activation
![image](https://user-images.githubusercontent.com/67268979/128801175-71d7d309-b563-412a-b602-f33d986c2ebe.png)

`Swish(x) = labmda x: x* Sigmoid(x)`

It can be confused when User parse Skip layers or something

Can it be merged into one Node ?

If don't, why it can be merged ?

Thanks.

**Comment by lutzroeder** [comment]
@jangmin-deepx can you please share a sample file?

**Comment by jangmin-deepx** [comment]
I forget to attach onnx file
[OnnxFile](https://drive.google.com/file/d/13WZ7VlY8X9bRR_kN-O2xJpb7z5uMW0Lp/view?usp=sharing) 
This is my Target model to parse

**Comment by lutzroeder** [comment]
The app shows the graph in the file. The encoding would be a question for ONNX.
