### ISSUE TITLE
TensorFlow: Saved Model content detection

### ISSUE THREAD

**Issue by sddi** [lutzroeder/netron#782]
- Netron app and version: <windows10 Desktop app 5.1.0 -->

Steps to Reproduce:

1. I use tf.SavedModelBuilder saving my model.
2. it shows:
![image](https://user-images.githubusercontent.com/4221050/128868452-952adb4b-9f92-4773-a694-8ea5991dfe95.png)

there is no logs........

**Comment by lutzroeder** [comment]
@sddi can you please share a sample file?

**Comment by lutzroeder** [comment]
See tensorflow/tensorflow#15061

**Comment by lutzroeder** [comment]
[saved_model_xxx.pb.zip](https://github.com/lutzroeder/netron/files/6965264/saved_model_xxx.pb.zip)

**Comment by lutzroeder** [comment]
Duplicate of #1015
