### ISSUE TITLE
TensorFlow Lite: Signature support 

### ISSUE THREAD

**Issue by abattery** [lutzroeder/netron#783]
From TensorFlow 2.7 versions, the signature information will be automatically enabled in the all the converter APIs.

It would be nice to show the signature information in the summary of the graph.

One nice new feature is added for the ability to add multiple entry points through signatures as well.

For the details,
https://www.tensorflow.org/lite/guide/signatures

**Comment by lutzroeder** [comment]
@abattery please implement this for all frameworks and submit a pull request.

**Comment by lutzroeder** [comment]
[tflite_signature_samples.zip](https://github.com/lutzroeder/netron/files/6965263/tflite_signature_samples.zip)

**Comment by Fannettembrown** [comment]
There is no version level on TensorFlow from my knowledge only builds an deploy( ML) powered applications. There a generator system Phython 2.7 that a good system connection according what phone, computer or tablet your system uses for good connection accepted flow...
