### ISSUE TITLE
TensorFlow: signature support

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [lutzroeder/netron#784]
- Netron app and version: 5.1.0
- OS and browser version: Windows 10 desktop

I love the new subgraph UI to access subgraphs via nodes, but the removal of a global subgraph list for TF saved models makes most subgraphs inaccessible.  (only the save/restore subgraphs are referenced by the metagraph. Inference graphs are referenced by signatures but not directly called by the metagraph).

Example model:
https://tfhub.dev/google/tf2-preview/nnlm-en-dim50/1?tf-hub-format=compressed

**Comment by lutzroeder** [comment]
@TomWildenhain-Microsoft which subgraph in the sample file is not accessible and how is it accessed by signatures?

**Comment by TomWildenhain-Microsoft** [comment]
The primary graph of interest is __inference___call___110 which calls __inference__preprocess_88 (the later can also be called independently)

![image](https://user-images.githubusercontent.com/67606533/129610708-dee018ce-daae-490c-8e5f-8d21958cb26b.png)

The signatures can be found using the saved model cli with `saved_model_cli show --dir C:\Users\tomwi\Downloads\nnlm --all` and are:

```
Defined Functions:
  Function Name: '__call__'
    Option #1
      Callable with:
        Argument #1
          sentences: TensorSpec(shape=(None,), dtype=tf.string, name='sentences')

  Function Name: '_preprocess'
    Option #1
      Callable with:
        Argument #1
          sentences: TensorSpec(shape=(None,), dtype=tf.string, name='sentences')
```

This model is of course just one example (simplest I could find).

**Comment by Fannettembrown** [comment]
TF1 is a hub format, you also can use segments model Url as well.

**Comment by lutzroeder** [comment]
```
tf/half_plus_two_saved_model.pb
tf/saved_model_xxx.pb

tf/0342.zip
tf/resnet_v2_fp16_savedmodel_NHWC_saved_model.pb

tf/tensorflow_issue_9169_saved_model.pbtxt
tf/myTag.pb
```
