### ISSUE TITLE
DaVinci OM support

### ISSUE THREAD

**Issue by 946166920** [lutzroeder/netron#786]
Hello, lutzroeder.  
I'm an employee of Huawei inc. I have extened Netron to support HiAI Foundation, which is an AI framework developed by Huawei Hisilicon(https://developer.huawei.com/consumer/cn/hiai#Foundation). Could you please let me merge my work (https://github.com/946166920/netron_om) into Netron?

**Comment by lutzroeder** [comment]
@946166920 Please discontinue the `.om` format and use a standard format like `.onnx`. This format provide little value, duplicates existing formats and creates additional work. See also #600.

**Comment by lutzroeder** [comment]
@946166920 Please discontinue the `.om` format and use a standard format like `.onnx`. This format duplicates existing formats and creates additional work. See also #600.

**Comment by lutzroeder** [comment]
@946166920 Please use a standard format like `.onnx`. This format duplicates existing formats and creates additional work. See also #600.

**Comment by lutzroeder** [comment]
Duplicate of #799

**Comment by hungtooc** [comment]
thank for supporting this model type

**Comment by hungtooc** [comment]
Hi @946166920, I have a .om (format DaVinci OM) file already inference-able on mobile app (android), How could I inference this file on limux server?, python?
