### ISSUE TITLE
DaVinci om model can not be recognized

### ISSUE THREAD

**Issue by 946166920** [lutzroeder/netron#788]
Steps to Reproduce:

1.when I open hiai_noaipp.om model on latest Netron code, the .om model can not be recognized.
[hiai_noaipp.om.zip](https://github.com/lutzroeder/netron/files/7038979/hiai_noaipp.om.zip)

2.review  the  code, source/app.js should add om in 176 line, and source/index.html should add .om in 364 line.

**Comment by lutzroeder** [comment]
Would it make sense to discontinue the OM format and use a standard format like `.onnx` or `.pb`? Supporting these formats creates overhead and they provide little value.

**Comment by lutzroeder** [comment]
Duplicate of #786
