### ISSUE TITLE
Circle support

### ISSUE THREAD

**Issue by glistening** [lutzroeder/Netron#790]
Hello, lutzroeder.

I work at Samsung Electronics. We are developing an on-device AI framework named [`ONE`](https://github.com/Samsung/ONE).
`ONE` uses model format named `circle` (not related to CircleCI), which is basically based on `tflite` format.
`circle` has more operation, which is (was) not supported by `tflite`, and quantization scheme,
Also, it is used as input to compiler for devices with other computing units (including NPU).

To view `circle` model, we've extended `netron`. Could you please let `circle` in `netron`? 
If you're okay, I will rebase our `circle` support changes to latest version and create PR.

**Comment by glistening** [comment]
@lutzroeder I am sorry for late response. (I was off Monday, and get vaccinated yesterday). Let me explain current status. I am doing under our company's open source process to contribute our code to external. It usually takes a long time to finish. Also, our current source is based on v4.6.5. I need to rebase the code. How do you want us to proceed this task? May I push PR in this repo when we are ready?

**Comment by lutzroeder** [comment]
@glistening are there any `circle` sample model files available?

**Comment by glistening** [comment]
@lutzroeder 
I can only found our circle models in `ONE` are  in `.reipe` format. (our internal text format). Thus, I attach here some samples - [circle_model_samples.zip](https://github.com/lutzroeder/netron/files/7481360/circle_model_samples.zip).  Each model has only 1 operator. If you want bigger model, I will put more models.

**Comment by lutzroeder** [comment]
[circle_model_samples.zip](https://github.com/lutzroeder/netron/files/7489768/circle_model_samples.zip)

**Comment by lutzroeder** [comment]
@glistening after looking at this some more it is not clear why Circle has forked the TensorFlow Lite format to an essentially identical yet outdated and incompatible variant without clear benefits. The right course of actions seems to be for Circle to work towards adopting a more recent version of the TensorFlow Lite format?

**Comment by glistening** [comment]
@lutzroeder Thank you for your comment! I appreciate your suggestion and your time.

`ONE` project has started as closed source a few years ago before it is open-sourced under the name of `ONE` . At the beginning, we don't want to create from scratch. We've chosen the most recent version of tflite schema at that time. Then, we've added or modified several things including operators, quantization and so on, which were missing or awkward from original tflite at that time. It is the reason the current circle schema looks like outdated and incompatible tflite format. We've implemented runtime, frontend (open-sourced in `ONE`), and more things (something exists yet internally) based on circle schema. The changes you've suggested require us several time and efforts. But I will reference your comment in our project so that our members can consider it.

**Comment by lemmaa** [comment]
@lutzroeder , Thank you for your continued interest and help. In fact, we have already started working on it. https://github.com/Samsung/ONE/issues/7589 However, due to some compatibility issues between recent versions of TensorFlow and our internal release schedule, it has been delayed for a while. We expect to be able to start again soon. :)
