### ISSUE TITLE
Paddle Lite support

### ISSUE THREAD

**Issue by Leonardo-Ding** [lutzroeder/netron#796]
Hi, I'm a [Paddle-Lite](https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/README_en.md) developer, I want to know extremely how netron can support Paddle-Lite .nb format visualization. Thanks.

**Comment by lutzroeder** [comment]
@Leonardo-Ding can you please provide additional information. The `.nb` format does not seem to support versioning so any change to the format will break tooling for existing files?

**Comment by lutzroeder** [comment]
Duplicate of #797
