### ISSUE TITLE
TensorRT support

### ISSUE THREAD

**Issue by Qiancj0605** [lutzroeder/netron#803]
Can netron visualize TRT models？
I tried it, and netron doesn’t seem to be able to visualize the TRT model。
Is there a way to visualize the TRT model？Thanks。

**Comment by lutzroeder** [comment]
`.trt` is an undocumented format and hence cannot be supported. Please ask the creators of the format.

**Comment by lutzroeder** [comment]
Duplicate of #533

**Comment by lutzroeder** [comment]
Duplicate of #725
