### ISSUE TITLE
When debug Render Process in VS code then netron often get stuck in startup 

### ISSUE THREAD

**Issue by RockySong** [lutzroeder/netron#805]
- Netron app and version: Desktop app, 4.9.0 and later 
- OS and browser version: Windows 10 1909 to 21H1 (19043.1165)

Steps to Reproduce:

1. Open Netron folder with Visual Studio Code
2. Set debug mode to "Debug Render Process", then start debug in VS Code.

this issue can be reproduced in at least 5 of 6 computers, all are self owned laptops by students (not uniformly configured).

![netron_debug_render_process_stuck](https://user-images.githubusercontent.com/3039105/132791954-f646d3e3-645c-46f2-aea7-7604e7f9b11c.png)

**Comment by lutzroeder** [comment]
@RockySong since this repros for you, can you investigate and submit a fix.

**Comment by RockySong** [comment]
We did some investigation but no progress right now...
