### ISSUE TITLE
Brew install not updating

### ISSUE THREAD

**Issue by ajaichemmanam** [lutzroeder/netron#806]
Steps to Reproduce:

1. brew install netron Installs the app on macos
2. brew update/upgrade won't install an updated version of netron
3. Everytime has to brew reinstall netron to keep it updated

Expected Results:
brew upgrade
updates the netron, just like other brew modules

**Comment by lutzroeder** [comment]
@ajaichemmanam my understanding is this the case for most brew casks. Brew installs the initial version and the apps tend to bring their own auto-update mechanism to install further updates. For example, running `/Applications/Netron.app/Contents/MacOS/Netron` from Terminal will bring some information what the updater is up to. Can you investigate this further and make work on a pull request if any of this should change?
