### ISSUE TITLE
about room

### ISSUE THREAD

**Issue by wang-kangkang** [lutzroeder/netron#814]
发现在5.2.4版本里，强制把之前滚轮实现缩放的功能，改成滚轮实现上下的功能。这个改动真的十分反人性。希望再改回去

**Comment by wang-kangkang** [comment]
In 5.2.4, it was forced to change the scroll wheel function from zoom to up and down.  This change is really anti-human.  I wish I could change it back  
I hope you take this problem seriously and don't shut it down

**Comment by lutzroeder** [comment]
Can you explain what the problem is? The scroll wheel is used to scroll pages up and down in most apps.

**Comment by wang-kangkang** [comment]
> Can you explain what the problem is? The scroll wheel is used to scroll pages up and down in most apps.

The core of the problem is that model-structure-viewing software has different requirements than most other software.
There are two core operations to use Netron: 1: view network collation structure and 2: view different OP. In previous versions of Netron, viewing the network structure was moving by holding down the left mouse button, and viewing the OP details was zooming with the scroll wheel. The two operations achieve two functions, use together very flexible, and the actual use of the OP details more often than the network structure. However, in 5.2.4, viewing OP details is implicitly used as an auxiliary function, and only shortcut key combinations can be used, greatly increasing the difficulty of operation.
Other software zoom, itself is auxiliary function. Or other software to perform scaling, will keep a fixed scaling ratio, continue to work. Netron is for looking at models, and there will never be a case for maintaining a fixed scale. So the point you're considering is not valid.

**Comment by LuJyKa** [comment]
+1
