### ISSUE TITLE
Ubuntu: Open dialog error

### ISSUE THREAD

**Issue by Xxfore** [lutzroeder/netron#815]
- Netron app and version: 5.2.5 Desktop 
- OS and browser version: Ubuntu 20.04

Steps to Reproduce:

1. Install app
2. run and click "Open Model"

It cant open File picker windows, and shows error like
"[10351:0928/152251.289511:ERROR:browser_main_loop.cc(269)] Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed
"
Please attach or link model files to reproduce the issue if necessary.

**Comment by lutzroeder** [comment]
electron/electron#31152
