### ISSUE TITLE
Error Loading Model. "functional" is not supported in model.h5

### ISSUE THREAD

**Issue by brrbaral** [lutzroeder/netron#818]
Hi thanks for Netron. I really like it.  I am using netron for web projects. I got this error 
**Error Loading Model. "functional" is not supported in model.h5** 
while loading  the model. The model is created using vgg19 transfer learning.
![image](https://user-images.githubusercontent.com/45137751/135259101-83f994db-9fe2-4dc2-bfe3-9973d4accb1c.png)
Thanks.

**Comment by lutzroeder** [comment]
@brrbaral can you share the model file?

**Comment by brrbaral** [comment]
@lutzroeder thanks for your response. Here is the model file.
https://drive.google.com/file/d/1ZUqO9TjnuraxLjFWFtJQCm9QvGSh3F46/view?usp=sharing

**Comment by lutzroeder** [comment]
@brrbaral loads without error in the latest version? Note the name of the shared file is different from the screenshot.
