### ISSUE TITLE
winget install netron "Multiple packages found matching input criteria. Please refine the input."

### ISSUE THREAD

**Issue by dstampher** [lutzroeder/netron#820]
- Netron app and version: 
N/A

- OS and browser version: 
Edition	Windows 10 Home
Version	20H2
Installed on	‎9/‎26/‎2020
OS build	19042.1237
Experience	Windows Feature Experience Pack 120.2212.3530.0

Steps to Reproduce:

1.  Open windows CLI
2.  execute the command "winget install netron"

Note:  executing the command "winget install LutzRoeder.Netron" works.

**Comment by lutzroeder** [comment]
microsoft/winget-cli#1523
