### ISSUE TITLE
TorchScript: Order operators in output network

### ISSUE THREAD

**Issue by docongminh** [lutzroeder/netron#821]
Dear author, I have a question about order output of my network ? 
In image 1: my output network order to get node value are `pre_yaw, pre_pitch, pre_roll`. But when i convert my model to ncnn and visualize by netron i got  3 nodes as same as image 2. I don't know order of output same as `pre_yaw, pre_pitch, pre_roll` in image 1 is. Can't anyone help me explain this problem ? thank you
- Image 1:
<img width="532" alt="Screen Shot 2021-10-05 at 21 29 17" src="https://user-images.githubusercontent.com/34453681/136043470-1b2bb34f-1694-4640-bd19-6f33480e9c28.png">

- image 2:
<img width="720" alt="Screen Shot 2021-10-05 at 21 29 24" src="https://user-images.githubusercontent.com/34453681/136043482-666cfd25-f94b-4dcc-bd96-b65050a24970.png">

**Comment by lutzroeder** [comment]
@docongminh can you share a sample model file.

**Comment by docongminh** [comment]
@lutzroeder  My model used from [deep-head-pose](https://github.com/natanielruiz/deep-head-pose) by Nataniel Ruiz. And convert step by step as same as ncnn guide: 

1. [Pytorch->Onnx](https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx). 
2. [Onnx -> Ncnn](https://github.com/Tencent/ncnn/tree/master/tools/onnx)
3. [Optimized Model](https://github.com/Tencent/ncnn/wiki/use-ncnnoptimize-to-optimize-model)
- Rather more, my converted models in [here](https://github.com/docongminh/ncnn-deep-head-pose/tree/dev/models_converted). Could you view it via netron ?
