### ISSUE TITLE
fold and unfold a block or a stack of layers

### ISSUE THREAD

**Issue by jamesben6688** [lutzroeder/netron#824]
Hello, thank you for your great work.

I wonder if you can provide a feature, where we can fold or unfold a block, for example, we may want to fold a bottleneck block, or a stack of same layers. Usually the neural network is very long, so if we can fold a block, we can have a better understanding of the whole network.

In addition, it would be better if the output size of each layer can be presented in the graph.

**Comment by lutzroeder** [comment]
@jamesben6688 can you share a sample file?
