### ISSUE TITLE
Export: Caffe to ONNX

### ISSUE THREAD

**Issue by jnulzl** [lutzroeder/netron#831]
Netron could visual ONNX, TensorFlow Lite, Keras, Caffe format and so on  

Hope to support "save as"  function, such as:  from caffe save as to onnx 
and even from one of {caffe, onnx, mnn, ncnn, tflite} to one of {caffe, onnx, mnn, ncnn, tflite}

**Comment by lutzroeder** [comment]
Duplicate of 415

**Comment by lutzroeder** [comment]
Duplicate of #415

**Comment by lutzroeder** [comment]
Duplicate of #1445
