### ISSUE TITLE
TensorFlow: Memmapped support

### ISSUE THREAD

**Issue by awsomecod** [lutzroeder/netron#836]
The deepspeech project produce a model in pbmm format: 

https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/deepspeech-0.9.3-models.pbmm

Does Netron support pbmm? 

I changed the extention pbmm to pb and gave the result to Netron. But I received this error: Unsupported file content.

**Comment by lutzroeder** [comment]
@awsomecod please submit pull requests to fix any remaining issues.

**Comment by lutzroeder** [comment]
[output_graph.pbmm.zip](https://github.com/lutzroeder/netron/files/8645971/output_graph.pbmm.zip)
