### ISSUE TITLE
Export models as graph

### ISSUE THREAD

**Issue by erelon** [lutzroeder/netron#849]
At the moment - exporting supports PNG/SVG formats.

Is it possible to create an export to one/more of the "classic" graph formats (GML, GraphML, etc.)?

**Comment by dalerxli** [comment]
您好！您的邮件已收到，谢谢。

**Comment by lutzroeder** [comment]
@erelon this is currently not a priority. Feel free to provide more context or submit a prototype. [DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) might be another option.
