### ISSUE TITLE
Torchvision scripted detection models doesn't work

### ISSUE THREAD

**Issue by kkontny** [lutzroeder/netron#851]
- Netron app and version: 5.4.1 Linux

Steps to Reproduce:
Run following Python script to export torchvision model to torchscript. (Here is example based on ssdlite320_mobilenet_v3_large but all other doesn't work too)
```
import torch
import torchvision

torch.no_grad()
model_name = "ssdlite320_mobilenet_v3_large"
model_ft = torchvision.models.detection.__dict__[model_name](pretrained=True)
model_ft.eval()

script_cell = torch.jit.script(model_ft)
frozen = torch.jit.freeze(script_cell)

torch.jit.save(frozen, model_name + ".pt")
```
2. Open file with Netron.
3. Netron can't open file: AssertionError inside model.

**Comment by lutzroeder** [comment]
@kkontny can you please investigate this further and submit a pull request.
