### ISSUE TITLE
Question regarding privacy

### ISSUE THREAD

**Issue by perone** [lutzroeder/netron#853]
Hi, I wasn't able to find an answer for this question and also wasn't able to find another place to ask the question so I'm opening this issue to check: does Netron (when used as Desktop app in MacOS for instance) sends any information to any server or is it purely offline ? This is more a question regarding the privacy of using Netron. It would be nice if there is a section about that in the README. Thank you !

**Comment by lutzroeder** [comment]
The app sends error messages and file format counts to Google Analytics using `anonymizeIp`. See also #475 and #623.
