### ISSUE TITLE
Disconnected graph due to multiple inputs to TFLambdaLayer

### ISSUE THREAD

**Issue by negvet** [lutzroeder/netron#855]
- Netron app and version: 5.4.5 Desktop app
- OS and browser version: Windows 10

Graph is visualied as disconnected (although it is working)
![image](https://user-images.githubusercontent.com/17028475/146423494-cc38081b-6b97-424c-bea8-0a9101a41303.png)
Most probably, the reason is that TFLambdaLayer inbound_nodes could have format `[['bn1', 0, 0 {'y': ['bn2', 0, 0], 'name': None}]]` for multiple inputs instead of `[['bn1', 0, 0, {}], ['bn2', 0, 0, {}]]`

Steps to Reproduce:

Create and save the model with
```
from tensorflow import keras
from tensorflow.keras import layers

input = keras.Input(shape=(10))
x1 = layers.Dense(10)(input)
x2 = layers.Dense(10)(input)
output = x1 + x2 + input

model = keras.Model(inputs=input, outputs=output)
model.save('~/tmp/test.h5')
```

**Comment by lutzroeder** [comment]
[netron_issue_855.h5.zip](https://github.com/lutzroeder/netron/files/7729736/netron_issue_855.h5.zip)
