### ISSUE TITLE
TensorFlow: Inconsistent Placeholder detection

### ISSUE THREAD

**Issue by tdomagal** [lutzroeder/netron#863]
- Netron app and version: 5.4.9 Desktop app
- OS and browser version: Windows 10 Enterprise 

Attaching simple graph from tensorflow 2.6.2, it's collected after placer.

Graph is cotaining 2 placeholders and 2 ops on them. 
Node A and B are the same type - Placeholder, and the same dtype.
Netron 5.4.9 draws them completely different style, what is more clicking to one of them points to model prop. instead of node properties.

![Capture 1](https://user-images.githubusercontent.com/41364371/148076174-a49b8f29-87bf-4fed-861e-c689eb497786.PNG)
![Capture 2](https://user-images.githubusercontent.com/41364371/148076181-418401a0-9935-4f04-afd6-40b2575c50b4.PNG)
[placer_output.zip](https://github.com/lutzroeder/netron/files/7808335/placer_output.zip)
.

**Comment by lutzroeder** [comment]
@tdomagal thank you for reporting this. For context, the Placeholders are represented as graph inputs and expected to show as model inputs in the sidebar.
