### ISSUE TITLE
Starting app with link to model url

### ISSUE THREAD

**Issue by enpasos** [lutzroeder/netron#867]
I'm so happy to have netron. Very nice tool.

Is it possible to start the browser version with providing an external model.onnx link?

The idea is to provide a link to netron app on some page that has the model url included as a parameter such that netron opens together with the model.

**Comment by enpasos** [comment]
At the moment I provide links to netron.app and model separately: 
https://enpasos.ai/muzero/How#onnx
I would like to improve the UX.

**Comment by lutzroeder** [comment]
Duplicate of #811

**Comment by lutzroeder** [comment]
> At the moment I provide links to netron.app and model separately:
> https://enpasos.ai/muzero/How#onnx

"...for your browser the Neutron App." is a typo?

**Comment by enpasos** [comment]
How cool ... works like a charm!

**Comment by enpasos** [comment]
> > At the moment I provide links to netron.app and model separately:
> > https://enpasos.ai/muzero/How#onnx
> 
> "...for your browser the Neutron App." is a typo?

Ups ... thanx
