### ISSUE TITLE
CoreML 5: File Not Found

### ISSUE THREAD

**Issue by anklebreaker** [lutzroeder/netron#873]
- Netron app and version: 
- OS and browser version: 

Steps to Reproduce:

1. Drag and drop any .mlpackage file into site

Results in 'File Not Found' error. Error occurs even with sample model EfficientB0.mlpackage used in other issues.

**Comment by anklebreaker** [comment]
The mlpackage needs to be zipped first and then it appears to work

**Comment by lutzroeder** [comment]
@anklebreaker which browser and OS are you using?

**Comment by lutzroeder** [comment]
Duplicate of apple/coremltools#1219
