### ISSUE TITLE
Serving a model directory

### ISSUE THREAD

**Issue by a1trl9** [lutzroeder/netron#875]
Hi,

Would it be helpful to support serving a model directory so that people can access models inside the directory directly like:

```
${BASENAME}:${PORT}/models/${MODEL_A}
${BASENAME}:${PORT}/models/${MODEL_B}
```

Would like to make a PR if it would be a useful feature.

**Comment by lutzroeder** [comment]
@a1trl9 can you provide an example how this would work?
