### ISSUE TITLE
Unable to open some pytorch recursive models

### ISSUE THREAD

**Issue by antifriz** [lutzroeder/netron#876]
When recursive script modules are used [here](https://github.com/lutzroeder/netron/blob/1a8fce4154b5e02e9c2905c502c14f7aaabfab35/source/pytorch.js#L591
) `this._value.__parent__` is recursive. Since current object comparison is done through `JSON.stringify` it will fail.

It should be replaced with a deep comparison of the two objects, something like [this](https://stackoverflow.com/a/1144249)).

**Comment by lutzroeder** [comment]
@antifriz can you provide a sample model file to reproduce this issue?

**Comment by antifriz** [comment]
[model.pt.zip](https://github.com/lutzroeder/netron/files/8030235/model.pt.zip)
