### ISSUE TITLE
TorchScript: ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by pbsds** [lutzroeder/netron#882]
- Netron app and version: web app 5.5.9?
- OS and browser version: Manjaro GNOME on firefox 97.0.1

# Steps to Reproduce:

1. use torch.broadcast_tensors
2. export with torch.trace(...).save()
3. open in netron.app

I have also gotten a `Unsupported function 'torch.broadcast_tensors'`, but have been unable to reproduce it due to this current error. Most likely, the fix for the following repro will cover two bugs.

# Please attach or link model files to reproduce the issue if necessary.

![image](https://user-images.githubusercontent.com/140964/155521606-1cac8a7a-dfe9-4c67-81ba-238c95607caa.png)

Repro:
```python
import torch

class Test(torch.nn.Module):
    def forward(self, a, b):
        a, b = torch.broadcast_tensors(a, b)
        assert a.shape == b.shape == (3, 5)
        return a + b

torch.jit.trace(
    Test(),
    (torch.ones(3, 1), torch.ones(1, 5)),
).save("foobar.pt")
```

Zipped foobar.pt: [foobar.zip](https://github.com/lutzroeder/netron/files/8132340/foobar.zip)

**Comment by leeqiaogithub** [comment]
I had a similar problem. After quantitative training, I converted  pth format model to pt format model via TorchScript. Then  open it with netron.app.
But I got the same error----"Error loading Python module. ValudError: not enough values to unpack(expected 2,actual 1) in 'model.pt' "

**Comment by lutzroeder** [comment]
@leeqiaogithub can you share the model file?

**Comment by leeqiaogithub** [comment]
Of course. But I couldn't upload it on Github.
It says, something went really wrong, and we can't process that file.

**Comment by pbsds** [comment]
zip it

**Comment by leeqiaogithub** [comment]
@pbsds that is what i did

**Comment by pbsds** [comment]
https://rigorousthemes.com/blog/best-firefox-send-alternatives/

**Comment by leeqiaogithub** [comment]
@pbsds By the way, have you solved the problem you mentioned earlier

**Comment by pbsds** [comment]
Huh, doesn't seem so. His fix worked for the smaller repro i provided, but not my medium model:
![image](https://user-images.githubusercontent.com/140964/159261044-5074046f-48dd-4e97-88f9-dd8eef800ba0.png)
[model.zip](https://github.com/lutzroeder/netron/files/8315352/model.zip)

**Comment by leeqiaogithub** [comment]
@lutzroeder The file may not be uploaded for some reason. Do you have any thoughts on this issue?

**Comment by leeqiaogithub** [comment]
> Huh, doesn't seem so. His fix worked for the smaller repro i provided, but not my medium model: ![image](https://user-images.githubusercontent.com/140964/159261044-5074046f-48dd-4e97-88f9-dd8eef800ba0.png) [model.zip](https://github.com/lutzroeder/netron/files/8315352/model.zip)
I tried to open your model with the latest version of the app and got the same error as in the picture.

**Comment by lutzroeder** [comment]
Three different issues:
1) @leeqiaogithub need a repro file, there are many ways for `ValueError: not enough values to unpack` to happen
2) model.pt `ValueError: not enough values to unpack` is fixed
3) model.pt `Unsupported function 'torch script.broadcast_tensors'` is a different error that happens later while tracing the TorchScript code. The model has a complex input signature which the app would have to "guess" from tracing the code. See pytorch/pytorch#48525.

**Comment by lutzroeder** [comment]
Three different issues:
1) @leeqiaogithub need a repro file, there are many ways for `ValueError: not enough values to unpack` to happen. If upload is not an option, try Dropbox/GDrive/OneDrive or share a GitHub repo? 
2) model.pt `ValueError: not enough values to unpack` is fixed
3) model.pt `Unsupported function 'torch script.broadcast_tensors'` is a different error that happens later while tracing the TorchScript code. The model has a complex input signature which the app would have to "guess" from tracing the code. See pytorch/pytorch#48525.

**Comment by leeqiaogithub** [comment]
[models.zip](https://github.com/lutzroeder/netron/files/8324673/models.zip)
Both models in the attachment have similar problems.

**Comment by leeqiaogithub** [comment]
@lutzroeder I think I know the reason, because TorchScript doesn't support some torch's operations when quantizing. such as torch.split

**Comment by glenn-jocher** [comment]
@lutzroeder I see this error in [YOLOv5](https://github.com/ultralytics/yolov5) TorchScript models with torch.split(). I've attached a YOLOv5n model (8MB) that reproduces the error.

I confirm torch.split() is the cause because:
```python
a, b, c = x.split((2, 2, 85), -1)  # error
a, b, c = x[..., 0:2], x[..., 2:4], x[..., 4:85]  # works
```
[yolov5n.torchscript.zip](https://github.com/lutzroeder/netron/files/8405066/yolov5n.torchscript.zip)

**Comment by lutzroeder** [comment]
[model_fnet.pt.zip](https://github.com/lutzroeder/netron/files/8457286/model_fnet.pt.zip)
[yolov5n.torchscript.zip](https://github.com/lutzroeder/netron/files/8457287/yolov5n.torchscript.zip)

**Comment by thelou1s** [comment]
so it's done?
