### ISSUE TITLE
ONNX: textual syntax support

### ISSUE THREAD

**Issue by AlexHJH** [lutzroeder/netron#883]
noticed that `.onnxtxt` suffix has bin registered in the recent commit, will it be completely supported in the future?

network file like this
<div  align="center"> 
<img src="https://user-images.githubusercontent.com/30765323/155871658-af8837ab-a085-4808-95a5-8dc6c14624ab.png" width="50%" height="50%">
<div>

**Comment by AlexHJH** [comment]
onnx has a new feature
(https://github.com/onnx/onnx/blob/main/docs/Syntax.md)
The syntax enables a compact and readable representation of ONNX models，like prototxt  in caffe

**Comment by AlexHJH** [comment]
@lutzroeder so i think it is possible to describe the onnx network in a textual way，and visualize it

**Comment by lutzroeder** [comment]
@AlexHJH can you share a few more complex example files?

**Comment by lutzroeder** [comment]
Duplicate of #884

**Comment by gramalingam** [comment]
@AlexHJH : please note that the syntax you describe is an experimental feature of ONNX (as mentioned in the documentation). You can use the parser documented there (in C++ or python) to create a standard .onnx protobuf file which can be consumed by Netron or any other tool. It is not meant to be an interchange standard at this point, just a tool to help users easily create onnx protobuf files.

**Comment by AlexHJH** [comment]
i think it a very good idea to describe the model  in a textual syntax, but few people know it now.  in the past, i wanted to modify onnx model but hvae to go back to the code and reorganize them, maybe just a little change. but now i can modify it on the text directly after i convert it to text representation, i tried and it really work @gramalingam

**Comment by lutzroeder** [comment]
Duplicate of #884

**Comment by lix19937** [comment]
How to use pbtxt convert to onnx file ? @lutzroeder
