### ISSUE TITLE
ONNX text support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#884]
[Syntax](https://github.com/onnx/onnx/blob/main/docs/Syntax.md) - [parser.h](https://github.com/onnx/onnx/blob/main/onnx/defs/parser.h), [parser.cc](https://github.com/onnx/onnx/blob/main/onnx/defs/parser.cc)

[text_example.txt.zip](https://github.com/lutzroeder/netron/files/8190032/text_example.txt.zip)
[text_function.txt.zip](https://github.com/lutzroeder/netron/files/8189629/text_function.txt.zip)
[text_constant.txt.zip](https://github.com/lutzroeder/netron/files/8189630/text_constant.txt.zip)

**Comment by AlexHJH** [comment]
i have created a  repo to transfer onnx proto file(.onnx) to textual file, and put a mobilenetv3 within for test 
[example](https://github.com/AlexHJH/onnx_text/blob/main/deploy.onnxtxt) @lutzroeder
