### ISSUE TITLE
Export the model's input/output's name/type to a json file?

### ISSUE THREAD

**Issue by JaykingLJK** [lutzroeder/netron#887]
Hi I would like to know if I can export the model's input/output name/type to a json file or any other txt file type.
For example after I get a model file, with this feature I can quickly get a json file with the model's input/output data.

**Comment by lutzroeder** [comment]
@JaykingLJK this is not a supported feature. Can you describe the scenario and workflow?

**Comment by JaykingLJK** [comment]
@lutzroeder Hi the workflow is that after opening a model using Netron, I just want to save the model properties shown in the picture as an easy-to-read file type (like json).
![image](https://user-images.githubusercontent.com/45059360/157569855-fbc8e103-9433-4ecd-a2f6-1543e97b2e89.png)

**Comment by lutzroeder** [comment]
@JaykingLJK how would you be using the exported file? For example, would it make sense to write script using the actual framework that was used to produce the model file?

**Comment by JaykingLJK** [comment]
@lutzroeder Hi actually it can be done if I write the script myself. I am just thinking that Netron could be better with more features. :>
