### ISSUE TITLE
TensorFlow Lite: show quantization params for per-channel quantized tensor

### ISSUE THREAD

**Issue by robert-kalmar** [lutzroeder/netron#891]
TensorFlow Lite format enables the filter tensor in various convolutions to be quantized in per-channel (per-axis) form. Here each 'channel' has specific quantization params (scale and zero-point). 
Currently _netron_ only shows the quantization params for per-tensor quantized filters.

**Comment by lutzroeder** [comment]
@robert-kalmar can you share a sample file?

**Comment by robert-kalmar** [comment]
@lutzroeder , example of such a model is here: https://tfhub.dev/tensorflow/lite-model/efficientnet/lite1/int8/2 . See filter/weights details in any Conv2D or DepthwiseConv2D does not contains quantization details: 
![netron-efficientdet](https://user-images.githubusercontent.com/56120470/159005373-a7268aa8-08f4-4d2e-85b2-c7781f9c0d75.png)
