### ISSUE TITLE
Exporting image crops out connection

### ISSUE THREAD

**Issue by erikfurevik** [lutzroeder/netron#892]
- Netron app and version: Python server via pip
- OS and browser version: Windows 10 10.0.19043 + Firefox 98.0.1

Steps to Reproduce:

1. Build U-Net model (possibly others) in pytorch.
2. Export to onnx with torch.onnx.export()
3. Import to Netron python server (works fine!)
4. Export as either svg or png, horizontal or vertical.
5. Uppermost connection is cropped from exported image.
![Unet onnx](https://user-images.githubusercontent.com/59777571/159451580-db53ccf0-3891-47eb-b1c8-757b40a8985d.png)

**Comment by lutzroeder** [comment]
@erikfurevik can you share a model to reproduce this issue?

**Comment by erikfurevik** [comment]
Here is an example pl module.

```python
import torch
import torch.nn as nn
import pytorch_lightning as pl
import torch.nn.functional as F
from torch.optim import Adam
from torch.onnx import export

class NetworkModule(pl.LightningModule):
    def __init__(self):
        super().__init__()
        
        self.conv = nn.Conv2d(8,8,3,1,1)
        self.reduce = nn.Conv2d(16,8,3,1,1)

    def forward(self,x):
        d1 = self.conv(x)
        d2 = self.conv(d1)
        d3 = self.conv(d2)
        d4 = self.conv(d3)
        d5 = self.conv(d4)
        
        u3 = self.reduce(torch.cat([d4,d5],1))
        u2 = self.reduce(torch.cat([d3,u3],1))
        u1 = self.reduce(torch.cat([d2,u2],1))
        u0 = self.reduce(torch.cat([d1,u1],1))
        
        return u0

    def configure_optimizers(self):
        return Adam(self.parameters())
    def training_step(self,batch,bid):
        return F.mse_loss(self.forward(batch[0]),batch[1])

batch = torch.rand((4,8,64,64))
net = NetworkModule()
export(net,batch,"test.onnx")
```

Which gives this output for me after exporting from netron, where the uppermost connection is cropped out.
![test](https://user-images.githubusercontent.com/59777571/159713317-db8fab4d-f9d0-432e-955d-4fea133cf5dd.png)
Again it's the same for svg/png and horizontal/vertical.

Note that the model is displayed perfectly in the browser, only the export has this problem. I can use screenshot for a small model like in this example, but that don't work for larger models. I found out that I can circumvent this by selecting "show attributes" in the menu:
![test2](https://user-images.githubusercontent.com/59777571/159714355-8059e9f4-4682-41e8-a57e-b8e8afb1f892.png)
Although this only works in the horizontal case.

**Comment by lutzroeder** [comment]
[netron_issue_892.onnx.zip](https://github.com/lutzroeder/netron/files/8339044/netron_issue_892.onnx.zip)
