### ISSUE TITLE
TensorFlow: object attribute support

### ISSUE THREAD

**Issue by zvika-adler** [lutzroeder/netron#895]
- OS and browser version: Ubuntu20 + Chrome 97.0.4692.99
- Netron version 5.6.6

Steps to Reproduce:

1. Take attached file and change extension to .pbtxt (this was changed due to GitHub restrictions). This model is build by Protobuf GraphDef structure that enables func structure. 
2. Load with Web Netron
3. Press on Placeholder node to view attributes.

Current behavior: OutTensorInfo parameter is of type func and cannot be viewed. If pressing OutTensorInfo link, it doesn't show the data.
Expected behavior: OutTensorInfo parameter can be shown and collapses/de-collapses after clicking "+" button.

Please attach or link model files to reproduce the issue if necessary.
[myModel.txt](https://github.com/lutzroeder/netron/files/8389336/myModel.txt)

**Comment by lutzroeder** [comment]
[netron_issue_895.pbtxt.zip](https://github.com/lutzroeder/netron/files/8459475/netron_issue_895.pbtxt.zip)

**Comment by DoDoENT** [comment]
In general, it would suffice to simply display TF func's as key-value maps, as [this is the way they are written in the protobuf file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/attr_value.proto#L46).

Furthermore, we also use [list of funcs](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/attr_value.proto#L40) for some of our models, so it would be great if this was supported too.
