### ISSUE TITLE
PyTorch: Monai Unet does not have right architecture

### ISSUE THREAD

**Issue by ldelaoa** [lutzroeder/netron#898]
- Netron app and version: Online webapp
- OS and browser version: Google Chrome

Steps to Reproduce:

1.x class MyModule(torch.nn.Module):
    def unet(self,x):
        x =  monai.networks.nets.UNet(
        spatial_dims=2,
        in_channels=1,
        out_channels=1,
        channels=(4, 8, 16, 32, 64),
    strides=(2, 2, 2, 2),
    )
       return x
2. traced = torch.jit.trace(model, torch.rand(1, 1, 512, 512))
torch.jit.save(traced, 'scriptmodule.pt')

Attached there is a copy of the displayed moduled in netron, not properly build and also the file I'm currently used to create it 

![scriptmodule pt (1)](https://user-images.githubusercontent.com/46694700/162214304-d7ddab9c-cefd-41a5-ae19-adf5702ce2ca.png)
![scriptmodule pt](https://user-images.githubusercontent.com/46694700/162214531-22680546-72c3-4251-b619-a8212fc742ef.png)

**Comment by lutzroeder** [comment]
@ldelaoa can you share a model file and some context on what output is expected?

**Comment by ldelaoa** [comment]
Sure, please find it attached as zip, because I was not able to upload it as .pt

And I was expecting something with encoding/decoding architecture, similar as images on the following links: https://opg.optica.org/getImage.cfm?img=QC5sYXJnZSxib2UtMTEtOS01MzIxLWcwMDE
https://miro.medium.com/max/1400/1*OkUrpDD6I0FpugA_bbYBJQ.png

Thanks for that quick reply

[scriptmodule.zip](https://github.com/lutzroeder/netron/files/8444326/scriptmodule.zip)
