### ISSUE TITLE
Keras: invalid inbound connection _CONSTANT_VALUE 

### ISSUE THREAD

**Issue by NikolasMarkou** [lutzroeder/netron#900]
5.6.7 Desktop app

5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Open model file
![image](https://user-images.githubusercontent.com/1175820/162390080-00d0f101-9324-46ef-aca9-ad0101e2e1e0.png)

2.

Please attach or link model files to reproduce the issue if necessary.
[model_denoise.h5.zip](https://github.com/lutzroeder/netron/files/8449748/model_denoise.h5.zip)

**Comment by lutzroeder** [comment]
[model_denoise.h5.zip](https://github.com/lutzroeder/netron/files/8452765/model_denoise.h5.zip)
