### ISSUE TITLE
Pass model to netron.app as base64 encoded parameter?

### ISSUE THREAD

**Issue by lukasberbuer** [lutzroeder/netron#904]
Would be a great option to open local models in the browser version.

Opening models by url seems to work with: `https://netron.app/?url=<...>`
Is there are way to pass models directly as parameters, e.g. as base64 encoded strings?

**Comment by lutzroeder** [comment]
URLs have a size limit. Multiple formats can not be detected from content so a file extension needs to get passed. There isn't a straightforward way to create the URL. All this would likely lead to errors. Can the same be accomplished by using the `gist` parameter? For example, https://netron.app?gist=e65799e70358c6782b1b
