### ISSUE TITLE
Slicing expected array in 'opt_xx.pt'.

### ISSUE THREAD

**Issue by mollon650** [lutzroeder/netron#910]
- Netron app and version: 5.7.9
- OS and browser version: macos 12.3

Steps to Reproduce:

1.got Slicing expected array  error when open the torch pt file

**Comment by lutzroeder** [comment]
@mollon650 can you share a sample file to reproduce the issue?

**Comment by mollon650** [comment]
https://drive.google.com/file/d/1vZiVxO5YDu4H2Ux_A6NcKLF959Mw-A0M/view?usp=sharing model is here， u can download it and test

**Comment by lutzroeder** [comment]
Duplicate of #913
