### ISSUE TITLE
netron.stop() never returns (Python package)

### ISSUE THREAD

**Issue by nrudakov** [lutzroeder/netron#912]
Netron version: 5.8.0
Python version: 3.9.12
OS: Windows 10 Pro build 19044.1706
Steps to reproduce:
1. Run the script with the following content:

```python
import netron

address = netron.start(file=r'/path/to/model.onnx', browse=False)
netron.stop(address)
print('Stopped')
```

Expected behavior:
1. netron.stop(...) returns
2. 'Stopped' get printed
3. Script execution finishes

Actual behavior:
1. netron.stop(...) never returns
2. 'Stopped' is not printed
3. Script is running forever

Looks like server is stopped but the thread is not joining.

**Comment by lutzroeder** [comment]
@nrudakov can you investigate why this is happening with your computer and suggest a fix?
