### ISSUE TITLE
PyTorch: Slicing expected array

### ISSUE THREAD

**Issue by mollon650** [lutzroeder/netron#913]
Netron app and version: 5.7.9
OS and browser version: macos 12.3
Steps to Reproduce:

1.got Slicing expected array error when open the torch pt file, 
https://drive.google.com/file/d/1vZiVxO5YDu4H2Ux_A6NcKLF959Mw-A0M/view?usp=sharing model is here，
i test it and  u can access it and download it and test @lutzroeder

**Comment by lutzroeder** [comment]
[opt_xx.pt.zip](https://github.com/lutzroeder/netron/files/8747908/opt_xx.pt.zip)

**Comment by lutzroeder** [comment]
Duplicate of pytorch/pytorch#48525
