### ISSUE TITLE
ONNX: TypeProto optional_type support

### ISSUE THREAD

**Issue by fdwr** [lutzroeder/netron#914]
Netron fails to load this model [test_optional_get_element.zip](https://github.com/lutzroeder/netron/files/8744935/test_optional_get_element.zip) from the [ONNX backend test suite](https://github.com/onnx/onnx/blob/main/onnx/backend/test/data/node/test_optional_get_element/model.onnx) containing an [`OptionalGetElement-15` operator](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Optional) with the following error:

![image](https://user-images.githubusercontent.com/1809166/169623383-5028eeeb-be14-4e4f-b19b-74b0497c40e7.png)

Can Netron display the parts of the graph that it *does* recognize (perhaps still display a warning, but show the node names at least)? Thanks.

```
ir_version: 8
producer_name: "backend-test"
graph {
  node {
    input: "optional_input"
    output: "output"
    op_type: "OptionalGetElement"
  }
  name: "test_optional_get_element"
  input {
    name: "optional_input"
    type {
      optional_type {
        elem_type {
          tensor_type {
            elem_type: 1
            shape {
              dim {
                dim_value: 4
              }
            }
          }
        }
      }
    }
  }
  output {
    name: "output"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 4
          }
        }
      }
    }
  }
}
opset_import {
  version: 15
}
```

**Comment by lutzroeder** [comment]
[optional_type.onnx.zip](https://github.com/lutzroeder/netron/files/8746170/optional_type.onnx.zip)

**Comment by fdwr** [comment]
Wow, fast.
