### ISSUE TITLE
TensorFlow: Unsupported attribute value type

### ISSUE THREAD

**Issue by goelbenj** [lutzroeder/netron#916]
When trying to load a .pb I am getting the following error:

![image](https://user-images.githubusercontent.com/59181809/170367669-c3be2b68-5f58-41f5-9458-13cd11e8fa8d.png)

I know that this model opens properly with release v.5.6.9 so maybe you can re-create that release? That would be great

**Comment by lutzroeder** [comment]
@goelbenj can you share a model file to reproduce the issue?

**Comment by goelbenj** [comment]
The change in behavior come from [this commit](https://github.com/lutzroeder/netron/commit/e4e4740e49db0acb7162810191b744470dc60996) (message get changed latter)
Where unknow case are no more ignored, but generate errors.

Can this be reverted?

**Comment by lutzroeder** [comment]
@goelbenj what is the root cause for the invalid attribute? Please share a repro file and how it was created.

**Comment by diviramon** [comment]
I am also seeing the same issue. I have attached a sample graph (I had to zip it since GitHub does not support the pb format).
[graph.pb.zip](https://github.com/lutzroeder/netron/files/8818946/graph.pb.zip)
