### ISSUE TITLE
Load very large language model with netron

### ISSUE THREAD

**Issue by hannan72** [lutzroeder/netron#919]
Hi all,

What I need is the ability to visualize the onnx file of large language models (specifically GPT like models) with netron. The only thing I need is to see the interconnections and also the input and output names of layers. Currently, my computer's RAM memory is less than the memory needed for loading this model and on the other hand, I do not need the much detail that existed in those models.
Is there any solution for this?

**Comment by lutzroeder** [comment]
Option 1: Find a computer with enough memory, load the model, strip the weights, save
Option 2: Write an incremental protobuf reader/writer that can do the same without requiring the file to be fully loaded
Option 3: Provide a pull request to support doing this on the fly in Netron
Option 4: ...
