### ISSUE TITLE
ONNX: support for files not using .onnx extension

### ISSUE THREAD

**Issue by yashnv** [lutzroeder/netron#921]
- Netron app and version: 5.8.5 Desktop app
- OS and browser version: Ubuntu 20.04.4, Firefox 101.0

I have a model named as `resnet.onnx.dla` and it can't be loaded by netron, but if I rename it as `resnet.dla.onnx` it works.

Does Netron need extensions to correctly infer what type of model it is?

**Comment by lutzroeder** [comment]
ONNX, TensorFlow and Caffe2 all use binary [Protocol Buffers](https://developers.google.com/protocol-buffers) which do not have way to definitively determine the format and schema from content. Is there a reason to use `.onnx.dla` instead of `.dla.onnx` if the format is ONNX?
