### ISSUE TITLE
Core ML: TypeError undefined is not an object

### ISSUE THREAD

**Issue by srjoglekar246** [lutzroeder/netron#927]
Using coremltools' latest `compression_utils` to post-training compress a model causes Netron to throw an error. The main property that's different about these models is the presence of `constexpr` ops (like `constexpr_affine_dequantize` in quantization example below) & compressed weights (like 8-bit ints in quantization)

- Netron app and version: 5.9.1 Web app
- OS and browser version: macOS 12 & Safari

Steps to Reproduce:

```
import torch  # 1.12.0
import torchvision  # 0.13.0
import coremltools as ct  # 6.0b1

print(ct.compression_utils.affine_quantize_weights)

model = torchvision.models.mobilenet_v2(pretrained=True)
model.eval()
example_input = torch.rand(1, 3, 256, 256)
traced_model = torch.jit.trace(model, example_input)
mlmodel_mil = ct.convert(traced_model, inputs=[ct.TensorType(shape=example_input.shape)], convert_to="mlprogram")

compressed_model = ct.compression_utils.affine_quantize_weights(mlmodel_mil, mode="linear_symmetric")

compressed_model.save("mobilenet_v2_quant.mlpackage")
```

Please attach our link model files to reproduce the issue if necessary.

[mobilenet_v2_quant.mlpackage.zip](https://github.com/lutzroeder/netron/files/9075372/mobilenet_v2_quant.mlpackage.zip)

CC @aseemw

**Comment by lutzroeder** [comment]
@[znation](https://github.com/znation)

**Comment by znation** [comment]
@lutzroeder Though the code change looks good to me, please note that I no longer work at Apple, so if you do want official eyes on it @aseemw might be a better reviewer. Thanks!

**Comment by srjoglekar246** [comment]
Verified that this works now. Thanks @lutzroeder !
