### ISSUE TITLE
PyTorch: torch.package support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#928]
This is tracking [torch.package](https://pytorch.org/docs/stable/package.html) support.

See #720 for PyTorch support.

Sample files:
[DCGAN2.pt.zip](https://github.com/lutzroeder/netron/files/9075628/DCGAN2.pt.zip)
[resnet34.pt.zip](https://github.com/lutzroeder/netron/files/9075629/resnet34.pt.zip)
[v3_1_ru.pt.zip](https://github.com/lutzroeder/netron/files/9075630/v3_1_ru.pt.zip)
[multi_return.pt.zip](https://github.com/lutzroeder/netron/files/12811973/multi_return.pt.zip)
[simple_leaf_fx.pt.zip](https://github.com/lutzroeder/netron/files/12839399/simple_leaf_fx.pt.zip)
[load_library.pt.zip](https://github.com/lutzroeder/netron/files/12839408/load_library.pt.zip)

**Comment by Klanly** [comment]
Can you take a look with this one?
[min-dalle-bart-dec_mini.pt.zip](https://github.com/lutzroeder/netron/files/9147239/min-dalle-bart-dec_mini.pt.zip)
(weights (data/xxx) are nulled, otherwise it's 890MB)
netron.app says exp_() not support.

**Comment by codingbutstillalive** [comment]
Hello. I wonder, what is the current status of Pytorch support?

Best regards!

**Comment by lutzroeder** [comment]
@codingbutstillalive see #720 for more information.

**Comment by lutzroeder** [comment]
Sample files:
[DCGAN2.pt.zip](https://github.com/lutzroeder/netron/files/9075628/DCGAN2.pt.zip)
[resnet34.pt.zip](https://github.com/lutzroeder/netron/files/9075629/resnet34.pt.zip)
[v3_1_ru.pt.zip](https://github.com/lutzroeder/netron/files/9075630/v3_1_ru.pt.zip)
