### ISSUE TITLE
TorchScript: Unsupported function `torch.as_strided`

### ISSUE THREAD

**Issue by SolomidHero** [lutzroeder/netron#931]
- Netron app and version: 5.9.2
- OS and browser version: MacOS 12.3.1 and Chrome Version 103.0.5060.114 (Official Build) (x86_64)

<img width="443" alt="Screenshot 2022-07-20 at 01 47 46" src="https://user-images.githubusercontent.com/28161779/179866698-7770c4ae-a36c-443f-bb30-002a860847e7.png">

Steps to Reproduce:

1. Create model (it uses torch.as_strided)

```py3
from fairseq.modules import LightweightConv

model = LightweightConv(
    256,
    9,
    padding_l=8,
    weight_softmax=True,
    num_heads=2,
    weight_dropout=0.2,
).eval()

traced_model = torch.jit.trace(model, example_args)
torch.jit.save(traced_model, traced_path)
```

2. run from cli:
```python3
netron /path/to/checkpoint
```

**Comment by lutzroeder** [comment]
@SolomidHero can you please provide a file to reproduce to issue. The script doesn't run.
