### ISSUE TITLE
Error loading Python module. Unsupported expression '-' in 'xxx.pt'.

### ISSUE THREAD

**Issue by Xinchengzelin** [lutzroeder/netron#936]
I like to use netron on (https://netron.app/) .  However, recently the error appear: " Error loading Python module. Unsupported expression '-' in 'xxx.pt'."  when I open the xxx.pt model.  I'm sure this model can be opened before.  What should I do to open  .pt model online?

- Netron app and version: 
- OS and browser version: 

Steps to Reproduce:

1.
2.

Please attach or link model files to reproduce the issue if necessary.

**Comment by lutzroeder** [comment]
@Xinchengzelin can you share a sample file to reproduce the issue.

**Comment by Xinchengzelin** [comment]
> @Xinchengzelin can you share a sample file to reproduce the issue.
I'm sure the model could be viewed before

[model.zip](https://github.com/lutzroeder/netron/files/9204522/model.zip)
