### ISSUE TITLE
TorchScript: serialization - update

### ISSUE THREAD

**Issue by zen-xingle** [lutzroeder/netron#938]
Thank you for building such great tool.

Refer to https://github.com/pytorch/pytorch/blob/master/caffe2/serialize/versions.h, version 8,9 is available now. Is there any plan to update the torchscript model version for netron?

**Comment by lutzroeder** [comment]
@zen-xingle can you share sample files to reproduce the issue.

**Comment by zen-xingle** [comment]
Yeah, I got a version 8 model. 
https://drive.google.com/file/d/1rCVV4uyILQfsVkO8T3GmBy7zrL_SiECM/view?usp=sharing
