### ISSUE TITLE
Visualize graph profiling report of onnx model

### ISSUE THREAD

**Issue by SolomidHero** [lutzroeder/netron#944]
Hi,
onnxruntime has built-in tool (`onnxruntime/transformers/profiler.py`) for profiling onnx models. But output reports can't be visualised, because of lack of graph structure. So such utilite must use both profiler report timings and graph structure. These are two different files.

I request as a minimum: information and color of each node time on the default netron graph.
Design can be derived from great open source project https://github.com/jrfonseca/gprof2dot

Profile report could be added by `--profile_report` flag or loaded through graph view ui.
There could be toggle for view of profile info and colors.

## Report semantic

onnx reports json which is a list of infodicts for each past node:
```json
[
...
{"cat" : "Node","pid" :23875,"tid" :3409660,"dur" :0,"ts" :9283811,"ph" : "X","name" :"Expand_1391_fence_before","args" : {"op_name" : "Expand"}},
{"cat" : "Node","pid" :23875,"tid" :3409660,"dur" :3,"ts" :9283812,"ph" : "X","name" :"Expand_1391_kernel_time","args" : {"input_type_shape" : [{"int64":[70,3]},{"int64":[3]}],"output_type_shape" : [{"int64":[2,70,3]}],"parameter_size" : "0","exec_plan_index" : "1016","thread_scheduling_stats" : "","output_size" : "3360","graph_index" : "1016","activation_size" : "1704","provider" : "CPUExecutionProvider","op_name" : "Expand"}},
{"cat" : "Node","pid" :23875,"tid" :3409660,"dur" :0,"ts" :9283820,"ph" : "X","name" :"Expand_1391_fence_after","args" : {"op_name" : "Expand"}},
{"cat" : "Node","pid" :23875,"tid" :3409660,"dur" :0,"ts" :9283821,"ph" : "X","name" :"Add_1357_fence_before","args" : {"op_name" : "Add"}},
{"cat" : "Node","pid" :23875,"tid" :3409660,"dur" :3,"ts" :9283821,"ph" : "X","name" :"Add_1357_kernel_time","args" : {"input_type_shape" : [{"int64":[]},{"int64":[]}],"output_type_shape" : [{"int64":[]}],"parameter_size" : "8","exec_plan_index" : "995","thread_scheduling_stats" : "","output_size" : "8","graph_index" : "995","activation_size" : "8","provider" : "CPUExecutionProvider","op_name" : "Add"}},
{"cat" : "Node","pid" :23875,"tid" :3409660,"dur" :0,"ts" :9283831,"ph" : "X","name" :"Add_1357_fence_after","args" : {"op_name" : "Add"}},
{"cat" : "Node","pid" :23875,"tid" :3409660,"dur" :0,"ts" :9283832,"ph" : "X","name" :"Sub_1359_fence_before","args" : {"op_name" : "Sub"}},
{"cat" : "Node","pid" :23875,"tid" :3409660,"dur" :3,"ts" :9283833,"ph" : "X","name" :"Sub_1359_kernel_time","args" : {"input_type_shape" : [{"int64":[]},{"int64":[]}],"output_type_shape" : [{"int64":[]}],"parameter_size" : "8","exec_plan_index" : "996","thread_scheduling_stats" : "","output_size" : "8","graph_index" : "996","activation_size" : "8","provider" : "CPUExecutionProvider","op_name" : "Sub"}},
{"cat" : "Node","pid" :23875,"tid" :3409660,"dur" :0,"ts" :9283839,"ph" : "X","name" :"Sub_1359_fence_after","args" : {"op_name" : "Sub"}}
]
```

## Additional request
Is it possible to make a profile even in netron package since it is simple to do and fast enough.

**Comment by lutzroeder** [comment]
@SolomidHero please add sample files and submit a pull request.

**Comment by SolomidHero** [comment]
@lutzroeder , I mean this is a feature request, not a PR :) Unfortunately, I don't have this feature implemented

Could you please
- point if there already was such request
- additional info if there are some recommendations or caveats on this profiling feature
- point to repo design, contributors readme (I don't know why all PRs are closed, but force-pushed)
- reopen this issue
?
