### ISSUE TITLE
NETRON as a foundation for AI Plugins

### ISSUE THREAD

**Issue by JohnnyOpcode** [lutzroeder/netron#945]
How difficult would it be to give NETRON a plugin capability?

The ability to write plugins could open the door for things like AI Ethics (bias inspection), network surgery, and a slew of unimagined capabilities. It would open the door for many people to expand the domain of AI (democratise).

NETRON is the defacto standard viewer/explorer. It's ubiquitous just like Tensorflow or Pytorch. Can it be taken to the next level?

**Comment by lutzroeder** [comment]
@JohnnyOpcode can you provide a specific scenario how this would work technically across desktop, browser and Python Server and submit a pull request.

**Comment by JohnnyOpcode** [comment]
> @JohnnyOpcode can you provide a specific scenario how this would work technically across desktop, browser and Python Server and submit a pull request.

I will have to think about and study the Python issue (I was not aware of it quite frankly). For Desktop/Browser I was thinking some form of JS event hooking maybe?

**Comment by pArtheum** [comment]
@JohnnyOpcode @lutzroeder 
I think if you want to start to modify the net structure, the Js itself is not sufficient. Most of the algo to do it, uses python librairies like onnx helpers or onnx surgeon.
