### ISSUE TITLE
Is there support for models like GFPGAN

### ISSUE THREAD

**Issue by magicse** [lutzroeder/netron#946]
Hi there. Is there support for models like GFPGAN ?
[GFPGANv1.3.pth](https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.3.pth)

**Comment by lutzroeder** [comment]
@magicse the file loads and shows the weights. Can you describe the issue.

**Comment by magicse** [comment]
Hi [lutzroeder](https://github.com/lutzroeder). Sorry I saw your post [PyTorch support](https://github.com/lutzroeder/netron/issues/720) that pytorch models are without graph connections.

**Comment by lutzroeder** [comment]
Duplicate of #720
