### ISSUE TITLE
[torchscript] How to visualize custom torchscript ops

### ISSUE THREAD

**Issue by shuokay** [lutzroeder/netron#947]
I have a model with custom ops, when viz it, netron report `Failed to resolve module 'ops.horizon' in 'yolox_quantized_rgb.pt'` error. `ops.horizon` is the custom op namespace.
After searching the Issues, I think it maybe caused by the way I define and register the custom op. Is there anyone can give me some advices?
### The way I defined the custom ops
I borrowed the idea from torchvision(An old version, they have changed the way to register ops in the latest version). A very short example code is followed:
**step 1: Implement the custom op:**
```cpp
at::Tensor custom_op(const at::Tensor & input){
out = balabala;
return out;
}
```
**step 2: register custom_op to torch:**
```cpp
static auto registry =
    torch::RegisterOperators()
        .op("horizon::custom_op", &custom_op);
```
**step3: call custom_op from python:**
```py
out = torch.ops.horizon.custom_op(input)
```

**Comment by lutzroeder** [comment]
@shuokay can you share a model file to reproduce the issue. TorchScript model files do not expose this information. Can you work towards getting this information added to the model format.

**Comment by shuokay** [comment]
@lutzroeder I will share a model later.
I agree with you, I have searched issues and also think the `custom_op` didn't expose the visualization essential information, so I attached an example code to illustrate the way I implemented the `custom_op`. 
Do you know a more `standard` or recommend way to implement custom op, so that it is more friendly to Netron?

**Comment by shuokay** [comment]
> @lutzroeder I will share a model later. I agree with you, I have searched issues and also think the `custom_op` didn't expose the visualization essential information, so I attached an example code to illustrate the way I implemented the `custom_op`. Do you know a more `standard` or recommend way to implement custom op, so that it is more friendly to Netron?

Hi @lutzroeder, the example model is followed, thanks for your great help:
[traced_scale_quant.pt.zip](https://github.com/lutzroeder/netron/files/9356840/traced_scale_quant.pt.zip)

**Comment by lutzroeder** [comment]
[traced_scale_quant.pt.zip](https://github.com/lutzroeder/netron/files/9387784/traced_scale_quant.pt.zip)

**Comment by lutzroeder** [comment]
> Do you know a more standard or recommend way to implement custom op

@shuokay please work with the PyTorch team to support operator extensibility in TorchScript files.
