### ISSUE TITLE
Update DEVELOPMENT.md

### ISSUE THREAD

**Issue by shuokay** [lutzroeder/netron#948]
Hi @lutzroeder,

I am trying to make Netron to support my custom defined op, and I find an old version of DEVELOPMENT.md: https://github.com/lutzroeder/netron/blob/41135278264ac9d9595594e7d2c89c104215fc8c/DEVELOPMENT.md
but it was removed in the latest code repo and the `Develop the Python server` section was outdated. Can you add DEVELOPMENT.md back and update the `Develop the Python server` section?

**Comment by lutzroeder** [comment]
[.github/DEVELOPMENT.md](https://github.com/lutzroeder/netron/blob/main/.github/DEVELOPMENT.md)
