### ISSUE TITLE
onnx node coloring code

### ISSUE THREAD

**Issue by parikshit14** [lutzroeder/netron#952]
Hi team,
(mainly talking about onnx graph visualization)
This is to ask about how the coloring of each node is working. What I can see is based on the categories of each node, if it's maxpooling the category is **pool**, for LeakyRelu the category is **activation** and most probably according to these categories you are coloring each node. (hope I'm right)
So can you point me where precisely is the coloring happening based on the categories (if happening that way) in the code base? I tried finding it but couldn't. 

P.S. sorry to open an issue for this query

**Comment by lutzroeder** [comment]
https://github.com/lutzroeder/netron/blob/87cbb2622f11fb6be9ee6ceba0d3b9e0d9263e56/source/view.js#L1006
https://github.com/lutzroeder/netron/blob/87cbb2622f11fb6be9ee6ceba0d3b9e0d9263e56/source/onnx.js#L572
https://github.com/lutzroeder/netron/blob/87cbb2622f11fb6be9ee6ceba0d3b9e0d9263e56/source/onnx.js#L1407
