### ISSUE TITLE
bug: cannot install netron through brew

### ISSUE THREAD

**Issue by popfido** [lutzroeder/netron#954]
- Netron app and version: 5.8.4
- OS and browser version: macOS 12.3.1

Steps to Reproduce:

1. `brew install netron`
2. `Error: Download failed on Cask 'netron' with message: Download failed: https://github.com/lutzroeder/netron/releases/download/v5.8.4/Netron-5.8.4-mac.zip`

**Comment by lutzroeder** [comment]
@popfido please investigate if this is an issue with the local brew instance. The current version is 6.0.0.
