### ISSUE TITLE
A format that can be used by other frameworks

### ISSUE THREAD

**Issue by yaoyaoding** [lutzroeder/netron#966]
Hi @lutzroeder,

Thanks for providing this lovely tool to visualize graphs. 

I am wondering if you could define a format (might name it as 'netron', and based on json) so that people can export the computation graph into your defined format and visualize it with netron. This is useful when people are developing new DNN optimizers and want to visualize their intermediate results of computation graphs, because it is always easy to export to an already existing format than hack netron to support a new format.

**Comment by lutzroeder** [comment]
Recommendation is to use one of the many existing formats like ONNX as a container. There is a [partial implementation](https://github.com/lutzroeder/netron/blob/main/source/message.js) of an intermediate format. However, it is not a priority to evolve this beyond the needs of client server experiments.
