### ISSUE TITLE
TensorFlow: stuck during loading model

### ISSUE THREAD

**Issue by Bigrock-dd** [lutzroeder/netron#967]
- Netron app and version: 
- OS and browser version: 

Steps to Reproduce:

1.i cant open my meta model
2.
[zinc_model.ckpt.zip](https://github.com/lutzroeder/netron/files/9547430/zinc_model.ckpt.zip)

Please attach or link model files to reproduce the issue if necessary.

**Comment by lutzroeder** [comment]
Duplicate of #68
