### ISSUE TITLE
TorchScript: AssertionError: Input image size

### ISSUE THREAD

**Issue by nahidalam** [lutzroeder/netron#970]
- Netron app and version: 6.0.5 in Mac
- OS and browser version: MacOS Catalina 10.15.7

Steps to Reproduce:
Open the `final_visual.pt` from [this](https://drive.google.com/file/d/194tnzP0_6pB5XAFrL6QO2dQ5mWvhSF0r/view?usp=sharing) 

When I try to open it, it shows below error

`AssertionError: Input image size doesn't match model (224x224) in final_visual.pt`

**Comment by lutzroeder** [comment]
See pytorch/pytorch#48525. The app is trying to guess the tensor size and pattern below is not recognized. Is it possible to use a code pattern resulting in basic if-condition-raise checks?

```
    if torch.eq(H, 224):
      _1 = torch.eq(W, 224)
    else:
      _1 = False
    if _1:
      pass
    else:
      _2 = torch.add("AssertionError: ", torch.format(_0, H, W, 224, 224))
      ops.prim.RaiseException(_2)
```
