### ISSUE TITLE
Confused about layer node names

### ISSUE THREAD

**Issue by Nuha1412** [lutzroeder/netron#988]
I want to understand. is the graph tree show names of layers nodes or what ?? I need the node names but too much information can you guide me

**Comment by lutzroeder** [comment]
@Nuha1412 please provide an example. The graph shows the node types (operators) by default. <kbd>Cmd</kbd>+<kbd>U</kbd> or <kbd>Ctrl</kbd>+<kbd>U</kbd> will show the node names if stored in the file.

**Comment by Nuha1412** [comment]
![image](https://user-images.githubusercontent.com/89157078/195047036-5aafd7eb-9c56-437f-a858-74f515feaf53.png)
