### ISSUE TITLE
MXNet model file not loading into Netron

### ISSUE THREAD

**Issue by anirudhacharya** [lutzroeder/Netron#99]
I tried loading the following MXNet model definition into Netron - http://data.dmlc.ml/models/imagenet/squeezenet/squeezenet_v1.1-symbol.json

I was able to load it when the saved filename was - ``squeezenet_v1.1-symbol.json``
but when the file was saved as  - ``squeezenet.json``, Netron was not able load the model definition. It gave the following error - 
```bash
Keras Error: class_name is not present.
```

I encounter the same error when I try to import a [sample ONNX model](https://drive.google.com/open?id=1gkBtObPxWoFpi54Y3XnEjw37OzqprfDY) into MXNet, and then try to load the [imported MXNet model](https://drive.google.com/open?id=1CjN_PE2qsujSA60IV78esWjrr51JLh-P) into Netron. 

```python
import mxnet as mx
from mxnet.contrib import onnx as onnx_mxnet

sym, arg, aux = onnx_mxnet.import_model("toy_model.onnx")
sym.save('toy_model.json')

import netron
netron.serve_file('toy_model.json')
```

While loading an MXNet model, should it be saved with a particular filename?

Information about my Netron installation is as follows - 
```
$ pip show Netron
Name: netron
Version: 1.7.0
Summary: Viewer for neural network models
Home-page: https://github.com/lutzroeder/Netron
Author: Lutz Roeder
Author-email: lutzroeder@users.noreply.github.com
License: MIT
Location: /Users/aanirud/anaconda2/envs/onnx/lib/python2.7/site-packages
Requires: 
```

**Comment by lutzroeder** [comment]
MXNet files need to end in `-symbol.json`. Files that are `.json` are detected as Keras or TensorFlow.js format. Feel free to bring this up with MXNet or Keras folks that better ways to disambiguate between different formats are needed.

**Comment by SirishaRella** [comment]
Hey, 
 I'm trying to use netron module in my python project. Whenever I'm trying to do netron.serve_file('model.onnx') it throws an error saying netron attribute doesn't contain serve_file. 

**Question-1:**
How to use netron in my python project. Is it just [https://github.com/SirishaRella/netron/blob/master/netron%20error.PNG](url)
import netron
netron.serve_file('model.h5')/netron.serve_file('model.onnx') or do I need to do add anything else to use it.
Please do have a look at screenshot
Note:
Netron is already installed using pip install netron.

**Question-2:**
Should I always run python on some web server when I'm using netron in my project? Does it not work in google colab?
