### ISSUE TITLE
NNEF support

### ISSUE THREAD

**Issue by kiritigowda** [lutzroeder/netron#992]
Khronos Neural Net Exchange Format ([NNEF](https://www.khronos.org/nnef)) is an open-source model format. It would be good to visualize these models using Netron.

[Tools](https://github.com/KhronosGroup/NNEF-Tools) are available for parsing the model file. Integrating the NNEF format natively with Netron would take the same process as other formats such as ONNX.

NNEF - https://www.khronos.org/nnef

NNEF Tools - https://github.com/KhronosGroup/NNEF-Tools

**Comment by lutzroeder** [comment]
@kiritigowda can you implement this, submit a pull request and sign up to support the feature.

**Comment by lutzroeder** [comment]
Duplicate of #1274
