### ISSUE TITLE
squashed and merged commits?

### ISSUE THREAD

**Issue by weimingzha0** [lutzroeder/netron#996]
Hey, want to bring to the attention about an issue I noticed in this project. 
It appears that all git commits are squashed, so the original author/committer info gets lost in git log.
This may not be a big deal, but if we want to motivate more new people to contribute, it might be important.

**Comment by lutzroeder** [comment]
Hi @weimingzha0, this is somewhat by design at the moment. None of the pull requests are squashed. Instead lot of the code is rewritten or manually ported, optimizing for shorter review cycles and maintainability.
