### ISSUE TITLE
TorchScript: Unknown function ops.prim.numel

### ISSUE THREAD

**Issue by mjack3** [lutzroeder/netron#997]
- Netron app and version: 6.1.1 Desktop app
- OS: Ubuntu 22.04 

https://pytorch.org/docs/stable/generated/torch.numel.html

**Comment by lutzroeder** [comment]
@mjack3 can you provide a model file to reproduce the issue.

**Comment by mjack3** [comment]
Hi! I cannot because it is a private project. Anyway the operation is straightforward to reproduce by just using it from torch.nn.numel().

Anyway, let me know if you have issues with that to help

Thanks

**Comment by mjack3** [comment]
No puedo porque el proyecto privado.

De todos modos la excepción es fácil de reproducir mediante el uso de torch.nn.numel.

De todos modos si tienes problemas para reproducirlo hazmelo saber

Gracias

**Comment by lutzroeder** [comment]
@mjack3 `torch.nn.numel` does not exist. Using `torch.numel` in a simple TorchScript module does not reproduce the issue as it compiles to `torch.numel` and not `ops.prim.numel`. It isn't clear from the description if this is TorchScript or a PyTorch Package. Can you create a simple repro model file and share it.

**Comment by mjack3** [comment]
I do not know why you think this issue should be closed...

It is a TorchScript file and that is why ops.prim.numel is complied intead torch.numel ....

Here there is a toy example for reproduce it, is not complicated....
```
class IDK(torch.nn.Module):
def__init__:
...
def forward(self, x):
return torch.numel(x)
```
You just need tot convert it to TorchScript. If you don't want to add support for this operation, of course this issue is correctly closed

Thanks

**Comment by lutzroeder** [comment]
> I do not know why the issue (with a unsolved problem) should be closed...

No repro. Can you please share a model file to reproduce the issue.

```python
import torch

class IDK(torch.nn.Module):
    def __init__(self):
        super(IDK, self).__init__()
    def forward(self, x):
        return torch.numel(x)

m = torch.jit.script(IDK())
torch.save(m, 'x.pt')

m = torch.jit.trace(IDK(), torch.rand(3,4))
torch.save(m, 'x.pt')
```
```
RuntimeError: Only tensors, lists, tuples of tensors, or dictionary of tensors can be output from traced functions
```
```
RuntimeError: Tried to serialize object __torch__.IDK which does not have a __getstate__ method defined!```
```
